### ISSUE TITLE
Remove Babun as the recommended option for Windows installation

### ISSUE THREAD

**Issue by himerus** [docksal/docksal#1004]
### Babun no longer maintained
According to [babun/babun/issues/868](https://github.com/babun/babun/issues/868), it is no longer maintained. 

This should likely be removed as the default option for Windows setup at https://docksal.io/installation#windows

I've just started a project where I need to test and verify support for Docksal on Windows, and am now switching over to Ubuntu + Docker for Windows (sadly) instead of the simpler Virtualbox experience that working with Babun allowed.

Otherwise, is there another option that would allow Ubuntu (or other linux subsystem) + Virutalbox?

**Comment by achekulaev** [comment]
@himerus yes thanks, it is happening in the upcoming 1.12 release. Ubuntu App (WSL) is going to be the main way to use Docksal on Windows. Babun will still work but will be a deprecated solution.

This ticket duplicates https://github.com/docksal/docksal/issues/946, so closing on favor of that one.

**Comment by himerus** [comment]
Apologies! I didn't see that ticket, I did attempt to look for duplicates.
