### ISSUE TITLE
DX improvements during the first boot

### ISSUE THREAD

**Issue by BR0kEN-** [docksal/docksal#1008]
**Description**

I already had `/Users/BR0kEN/projects` that resulted in the conflict:

```
Configuring NFS shares...

ERROR: Attempt to share /Users via NFS would create a conflict in /etc/exports.
       To solve the problem you can override the default Docksal projects folder.
       by setting DOCKSAL_NFS_PATH value in /Users/BR0kEN/.docksal/docksal.env.

Attempting auto-fix:
Do you want to use /Users/BR0kEN/Projects as Docksal projects path? [y/n]: n
```

I’ve added `DOCKSAL_NFS_PATH=/Users/BR0kEN/docksal-projects` to `/Users/BR0kEN/.docksal/docksal.env`, ran `fin vm restart` and stumbled upon:

```
Configuring NFS shares...
 ERROR:  exports:11: path contains non-directory or non-existent components: /Users/BR0kEN/docksal-projects
exports:11: no usable directories in export entry
exports:11: using fallback (marked offline): /
```

**Describe the results you expected:**

- As an automated resolution for the first item, I’d propose using a more unique path, like `/Users/BR0kEN/docksal-projects`.
- Also, probably would be good creating missing `DOCKSAL_NFS_PATH`.

**Comment by lmakarov** [comment]
@BR0kEN- to clarify - you set `DOCKSAL_NFS_PATH=/Users/BR0kEN/docksal-projects` but did not create that folder manually. When you ran `fin vm start` the exports configuration failed, complaining about the missing folder. Correct?

**Comment by lmakarov** [comment]
This should not happen, since there is a check for directory existence before the export is added:

https://github.com/docksal/docksal/blob/25aca808bb8dcef65fe330f743e47985c64206db/bin/fin#L2449-L2452

```
fin debug nfs_share_add '/Users/leonid/non-existing-folder'
 ERROR:  Invalid path: /Users/leonid/non-existing-folder
```

**Comment by BR0kEN-** [comment]
Yeah, that's how it was @lmakarov. The steps were:
- fin vm start
- error
- edit of /Users/BR0kEN/.docksal/docksal.env
- fin vm restart
- mkdir /Users/BR0kEN/docksal-projects
- fin vm restart

**Comment by lmakarov** [comment]
This was addressed in https://github.com/docksal/docksal/commit/00f4b1823ca5550608a4d58865916e7a3392bcdc and will be release in Docksal v1.12.0.

With the latest [RC](https://github.com/docksal/docksal/releases/tag/v1.12.0-rc1) released today:

```
$ cat /etc/exports

/Users/Guest 127.0.0.1
$ showmount -e
Exports list on localhost:
/Users/Guest                        127.0.0.1

$ fin vm mount
Configuring NFS shares...
Possible NFS conflict detected. Attempting auto-fix:
Suggested path for Docksal projects: /Users/leonid/Projects. Try it? [y/n]: n

$ fin config set --global DOCKSAL_NFS_PATH=/Users/leonid/non-existing-path
Added value for DOCKSAL_NFS_PATH into /Users/leonid/.docksal/docksal.env

$ fin vm mount
Configuring NFS shares...
 ERROR:  Invalid path: /Users/leonid/non-existing-path
 ERROR:  NFS sharing has failed
```

Note: I'm using `fin vm mount` instead of `fin vm start` to skip VM restarts.
