### ISSUE TITLE
Add Acquia BLT as a project creation option.

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#1011]
## Description

Add Acquia BLT as an option when creating a new Drupal 8 project. The following Drupal 8 options would exist when creating a new project:

* Drupal 8
* Drupal 8 (Composer Version)
* Drupal 8 (Acquia BLT Version)

This would setup blt.yml configuration to be compatible with Docksal OOTB. I pretty much work exclusively through BLT workflow at this point because of it's robust usage of configuration, creation of deployment artifacts, setup and configuration import strategies, and more.

Related issues https://github.com/docksal/docksal/issues/428 (Make Acquia BLT friends with Docksal). It seems like the near-consensus in that thread was that it would be "weird to initialize Docksal from BLT". In reality, folks have already chosen what their operating environment will be and will initialize a BLT project within that environment on their own. Docksal also knows how to set itself up for any given project better than that project will know how to set itself up for Docksal.

## Blocking Issues

- [ ] When running on MacOS (and I imagine Windows as well) and [following the instructions for creating a new BLT project](https://blt.readthedocs.io/en/latest/creating-new-project/), when run through either `fin rc` or `fin exec` after having created a Docksal project already we're seeing OOM errors when Composer tries to install/update packages. OOM persists even if passing `COMPOSER_MEMORY_LIMIT=-1` to the `create-project` command. `fin rc COMPOSER_MEMORY_LIMIT=-1 composer create-project --no-interaction acquia/blt-project my-project`. On Linux this is a non-issue.

    - Need to attempt with PHP and Composer memory limits completely disabled. Also test by increasing RAM allocated to VM (currently fails with 4GB of RAM allocated).

## Potential Issues

* When running Behat tests and leveraging headless Chrome, BLT expects the `google-chrome` binary to be available on the system running the `behat` command. (It will simply refuse to run `blt tests:behat`).
  * This is something that `docksal/cli` will likely never, nor should it, support. I think the onus is on BLT to support not forcing this. In Docker Compose projects it is trivial to include a headless Chrome service that lives on a host in the project network that you can reference in behat.yml. With the emergence and popularity of Docker Compose based projects (Docksal, Lando, DDev, etc.) BLT should really adapt. They may have changed this requirement in 10.x but I'm not sure.

Additional issues will be added to this list at this proposal is fleshed out.

**Comment by sean-e-dietrich** [comment]
@lpeabody I like the idea. I'm not familiar with it. Would you be willing to put together a starter repo with a very basic drupal 8 install that `fin init` will install everything needed? That would be a little easier for us to look at and make use of.

**Comment by lpeabody** [comment]
Fully intend to. I wanted to create the issue first as the center for discussion on the subject.

**Comment by sean-e-dietrich** [comment]
Thanks! 🎉

**Comment by shelane** [comment]
We had been planning on starting with a boilerplate version of it, but I kept running into memory issues with composer lately. We also want to make sure to get drupal console installed, which can be challenging as well.

**Comment by lpeabody** [comment]
What's the difficulty with getting Drupal console going?

If you are running into Composer issues with a D8 site you should make sure you're including [zaporylie/composer-drupal-optimizations](https://github.com/zaporylie/composer-drupal-optimizations). I, too, was having memory issues in some circumstances but including that package resolved that entirely. Also Composer runs muuuuch faster. The BLT 10.x line includes that package by default now.

**Comment by shelane** [comment]
I added that to my project, but I still get the same memory errors. I can't do any composer updates or requires without running `php -d memory_limit=-1` prior to the composer command.

**Comment by lpeabody** [comment]
Hmm... yeah this is fun. I haven't encountered this with new projects before. Like I can't even get a BLT project going, with memory_limit set to -1 and 4GB of memory allocated to the virtual machine.

**Comment by ey-** [comment]
For the behat issue:
I am setting the web-driver in my blt.yml to a value like "chrome-custom".
That way, blt does not try to start chrome before tests:

`behat:
  config: '${repo.root}/tests/behat/local.yml'
  profile: local
  chrome:
    port: 9222
    args: ''
  paths:
    - '${repo.root}/tests/behat'
  tags: '~ajax&&~experimental&&~lightningextension'
  extra: ''
  web-driver: chrome-custom`

In addition I have a custom command called blt-test, which is adding a headless chrome container to the current stack and running the given command:

`#!/bin/bash

is_windows()
{
	local res=$(uname | grep 'CYGWIN_NT')
	if [[ "$res" != "" ]]; then
		return 0
	else
		return 1
	fi
}

set -e

TESTS_YML="/.docksal/docksal-tests.yml"
SEPARATOR=':'; is_windows && SEPARATOR=';'
OLD_COMPOSE_FILE=${COMPOSE_FILE}
NEW_COMPOSE_FILE="${OLD_COMPOSE_FILE}${SEPARATOR}${PROJECT_ROOT}${TESTS_YML}"
COMPOSE_FILE=${NEW_COMPOSE_FILE} fin start
fin blt "$@"
COMPOSE_FILE=${OLD_COMPOSE_FILE} fin start
`

the docksal-test.yml contains:

`version: "2.1"

services:
 chrome:
   hostname: chrome
   image: zenika/alpine-chrome
   shm_size: 512M
   cap_add:
     - SYS_ADMIN
   command: --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0 http://localhost/
   dns:
     - ${DOCKSAL_DNS1}
     - ${DOCKSAL_DNS2}
`

So running behat tests is "simply":
`fin blt-test tests:behat:run`


BUT, this is probably a misuse of the COMPOSE_FILE variable :).

**Comment by lpeabody** [comment]
Thanks for your insight into the workaround, @ey-!

**Comment by lpeabody** [comment]
I updated the issue summary with the blocking detail pertaining to running out of memory when trying to setup a new BLT project.

**Comment by lmakarov** [comment]
@ey- regarding hacking the `COMPOSE_FILE` variable - try using the `DOCKSAL_ENVIRONMENT` variable instead:
https://docs.docksal.io/stack/configuration-variables/#docksal-environment

It allows you having different sets of yml and env files per environment, which can be set like this:

```
export DOCKSAL_ENVIRONMENT=test
```

With that set, fin will load `docksal-test.env` and `docksal-test.yml` **in addition to** the default ones.

**Comment by ey-** [comment]
@lmakarov
Unfortunately we are already using this variable for different instances. This hack is used to load the container during testing and remove it afterwards independent of the environment. So it is a third file loaded on top of the environment yml files.

**Comment by achekulaev** [comment]
@lpeabody @shelane could you test if everything works?

**Comment by achekulaev** [comment]
@lpeabody regarding out of memory. Increasing composer memory does not increase memory available to PHP. And this is exactly the culprit as I can tell from the discussion here https://github.com/acquia/blt/issues/2664#issuecomment-375064271

So you want to increase memory limit either in `cli` or in realtime with `ini_set('memory_limit', '2048M');`

**Comment by lpeabody** [comment]
@achekulaev testing in the past the PHP memory limit had not been the issue for me, but rather the memory limit of the VM running Docker. In some instances I have spun up a new project using `fin exec composer create-project ...` and Composer ran out of memory (with the PHP memory limit set to unlimited), but increasing the amount of RAM available to the VM (2048 -> 4096) did the trick.

I've pretty much always had to bump the VM to 4096M rather than the default of 2048M. I'd be curious as to what others experiences have been with VM memory limit problems.

Regarding testing this, I will be able to verify this work early next week!

**Comment by achekulaev** [comment]
> increasing the amount of RAM available to the VM (2048 -> 4096) did the trick.

As per that conversation, composer requires up to 2GB of RAM to install BLT. 

Naturally to get provide that amount to composer inside container VM itself needs 3Gb or more.

**Comment by achekulaev** [comment]
Maybe. Created a ticket, let's get more opinions on it.

**Comment by lmakarov** [comment]
`docksal/cli` starting with v2.7.0 should improve the composer memory issues substantially.
See https://github.com/docksal/service-cli/issues/99.
