### ISSUE TITLE
Drush no PHP configuration

### ISSUE THREAD

**Issue by nkoporec** [docksal/docksal#1012]
I know that you are not officially supporting Drupal 6, but I'm trying to spin up a local Drupal 6 project with docksal. I'm using default stack with docksal/cli:2.5-php5.6 CLI image.

Everything is working except Drush, by executing drush status command, I'm seeing that there is no PHP Configuration found (i'm executin drush in a container and in project root). What could I do to fix it?

If I use an older docksal image (docksal/cli 1.0) the drush is working but I can't use Xdebug because apache timeout when enabled.

**Comment by sean-e-dietrich** [comment]
@nkoporec download an older version of drush in the CLI. Then add it to the global path in `/usr/local/bin` I'd call it either drush6 or you could replace the existing drush binary that is there. and then you can run `fin drush`

**Comment by nkoporec** [comment]
Thanks for all the help, I was now able to load the php configuration, it was a permission issue so when I ran `sudo chown -R $(whoami) /usr/local` the PHP configuration started to show up in drush status.

But drush is still not working, it looks like it can't bootstrap Drupal, although the drush sql-cli command is working normally. Any ideas?

**Comment by nkoporec** [comment]
I have now managed to fix the issue, there was no permission issue but the error was indeed in the drush version, by upgrading drush to a newer version (8.20) it started to work. This drush PR helped me fixing this issue: https://github.com/drush-ops/drush/pull/2002.
