### ISSUE TITLE
WSL without VirtualBox

### ISSUE THREAD

**Issue by macmladen** [docksal/docksal#1029]
Excuse me for this **dumb** question, I am investigating Windows option with WSL.

As the WSL is hypervisored Linux kernel, it behaves almost as "true" Linux from the command line perspective.

I installed `git`, `node`, used `gulp` to start `browsersync` with `php` acting as server and that worked completely, including `localhost:3000` proxy.

Now I am wondering why is VirtualBox needed, doesn't WSL provides an viable environment for Docker and Docksal?

**Comment by lmakarov** [comment]
> WSL provides a Linux-compatible kernel interface developed by Microsoft (containing no Linux kernel code)

There is no hypervisor involved and no real Linux kernel in WSL. This means no kernel level support for Linux containers. For now, you still need a separate VM with a true Linux kernel to run Docker.
