### ISSUE TITLE
Create a doc on available image versions 

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#1038]
We need a docs for image versions available and their "meaning" in terms of software and compatibility.

We should start with `cli` image and then extend further.

Otherwise [issues like this](https://github.com/docksal/docksal/issues/1028) happen and even Docksal maintainers get confused, leave alone regular users.

**Comment by mikecrittenden** [comment]
To add some context, I did see https://docs.docksal.io/service/cli/settings/#php-versions but it doesn't mention that `2-` is a valid option, so the question of "how can I avoid having to change my docksal.env file when cli v2.7 is released" isn't answered there.

**Comment by achekulaev** [comment]
Right, basically that is the doc we need to update for CLI

**Comment by achekulaev** [comment]
https://develop.docs.docksal.io/stack/images-versions/
