### ISSUE TITLE
Update docs on apache config overrides

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#1042]
Docs should state that after changing files in `.docksal/etc/apache/httpd-vhost-overrides.conf` or `.docksal/etc/apache/httpd-vhosts.conf` then `fin project reset web` is required.

**Comment by lmakarov** [comment]
`fin project reset web` is fine, except it is going to kill any manual alterations to the web container,  which may or may not be desired. `fin project restart web` would suffice in this case.

**Comment by shelane** [comment]
Testing a change in my `.docksal/etc/apache/httpd-vhost-overrides.conf` with `fin project restart web` and it was sufficient.
