### ISSUE TITLE
DNS nameservers gets overridden by cloud-init networking config

### ISSUE THREAD

**Issue by ey-** [docksal/docksal#105]
## Problem
- The dns nameserver settings are not applied, so domains *.docksal are not resolved on ubuntu xenial.

### Steps to reproduce
I used the following Vagrantfile to provision a simple VM.
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
end
```
after vagrant up, logged in to the server via vagrant ssh and installed docksal as described in
[https://github.com/docksal/docksal/blob/develop/docs/env-setup.md#linux](here)

After that created a simple project in folder web with the following structure:
```folder
- .docksal
- docroot
| - index.html
```
after fin start, service spinned up, but wget web.docksal could not be resolved.

### Findings
The image I've used seems to have cloud-init installed which adds the following configuration file to
/etc/network/interfaces.d/50-cloud-init.cfg
```shell
# This file is generated from information provided by
# the datasource.  Changes to it will not persist across an instance.
# To disable cloud-init's network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
auto lo
iface lo inet loopback

auto enp0s3
iface enp0s3 inet dhcp
```

Docksal adds the configuration for his dns-nameserver to the file /etc/network/interfaces.
The dns-nameservers entry by docksal gets overridden by the configuration above.

**Comment by lmakarov** [comment]
On a pure Ubuntu 16.04 installed from an iso there is no `/etc/cloud` in it.

Have you tried this?

```
# To disable cloud-init's network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
```

**Comment by ey-** [comment]
This doesn't solve the issue.
But I can just remove the lines
´´´
auto lo
iface lo inet loopback
´´´
from that config. It doesn't get reapplied again.

**Comment by achekulaev** [comment]
Something to consider someday. Currently it's hard to account for some other software messing with network configs.
