### ISSUE TITLE
macOS firewall troubleshooting docs

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#1061]
![image](https://user-images.githubusercontent.com/402007/57896487-041f7300-781f-11e9-8257-2715c18c69a3.png)

**Comment by lmakarov** [comment]
@achekulaev will you take care of this or provide more details to @shelane ?

**Comment by achekulaev** [comment]
@lmakarov @shelane this ticket was supposed to be for adding documentation to `troubleshooting/common-issues.md` to add a case when on macOS things are not mounting properly during system start. 
And as a consequence when containers are run users see errors like
```
ERROR: for cli  Cannot create container for service cli: error while mounting vo
lume with options: type='none' device='/Users/alex/Projects/myproject' o='bind': no such file or directory
ERROR: Encountered errors while bringing up the project.
```
The item would describe that one of way to check if firewall is to blame would Go to System Preferences -> Security and Privacy -> Firewall and either turn the Firewall off or to configure it to allow all connections (like shown on the image). Then do `fin system restart` and check if it fixes the issue.
