### ISSUE TITLE
add Acquia API v2 options

### ISSUE THREAD

**Issue by shelane** [docksal/docksal#1062]
Acquia has created v2 of their API, which is active now and v1 will be EOL April 15, 2020. Some applications, such as BLT are already using v2. The authentication uses a `key` and a `secret` rather than `email` and `key`. They are then stored in `/home/docker/.acquia/cloud_api.conf` which looks something like:
`{"key":"123a123b-1111-1111-1111-111111111111111","secret":"somerandomsetofcharacters"}`.
When generated, this "key" is not the same key as a users v1 key.

At minimum, we need new SECRET variables for v2. It appears that v2 is only available via REST and not drush, so there should be no interference in use. We just need the other set of key/secret.

**Comment by sean-e-dietrich** [comment]
This makes me wonder also if we should be creating a Drush 9 plugin as right now the only one we have works with Drush 8

**Comment by shelane** [comment]
EOL for ACAPI v1 is April 15, 2020
https://docs.acquia.com/support/eol/

**Comment by typhonius** [comment]
Hi there, I'm in the process of updating typhonius/acquia_cli to connect to the 2.x version of typhonius/acquia-php-sdk-v2 - the overhaul for the cli tool is not as dramatic as that of the SDK (work now complete), however I will be pulling some functionality out and trying to make the tool as unopinionated as I can so it can be more versatile for all users.

Both of these tools are recommended by Acquia on their docs page: https://docs.acquia.com/acquia-cloud/develop/api/.

**Comment by lmakarov** [comment]
I'm surprised Acquia drops the ball like that on a cli tool for their own API v2 implementation.

From https://docs.acquia.com/acquia-cloud/develop/api/

> **How to call an endpoint**
> Build your own tooling, or use open source tooling to get started, such as the Typhonius PHP SDK or Typhonius CLI.

If https://github.com/typhonius/acquia_cli is the recommended tool to work with the new Acquia API v2, then is https://github.com/docksal/service-cli/issues/171 the only pending task to have support for it in Docksal?

I guess, we could go further and add support for secrets and automatic config generation similarly to how we do it with the current Acquia/Pantheon/Platform.sh integrations. Looks like the respective config file for `typhonius/acquia_cli` would be `~/.acquiacli/acquiacli.yml`.

**Comment by typhonius** [comment]
I’m currently working in [this PR](https://github.com/typhonius/acquia_cli/pull/28) to update the CLI tool to the latest version of the SDK. I’d be happy to make some additions to it to allow another location for the config file if it makes sense.

The majority of the rest of the changes involve restructuring the commands to be less opinionated and more broadly applicable as well as to add greater test oversight.

**Comment by typhonius** [comment]
The PR for the 2.0.0 branch has now been merged into master and I've tagged a couple of releases. We can either include the Acquia Cli package as-is or as a phar.

**Comment by shelane** [comment]
EOL on API v1 has been changed to July 1, 2020.

**Comment by lmakarov** [comment]
@shelane is `~/.acquia/cloud_api.conf` generated by BLT? If so, is that a BLT specific config file?

If I'm reading everything correctly, to automatically configure Acquia V2 API keys for BLT we would need to generate `~/.acquia/cloud_api.conf`:

```
{"key":"123a123b-1111-1111-1111-111111111111111","secret":"somerandomsetofcharacters"}.
```

Can BLT read these values from env variables?

---

Then, for acquiacli, we would either need to write config to `~/.acquiacli/acquiacli.yml`:

```
acquia:
  key: 'd0697bfc-7f56-4942-9205-b5686bf5b3f5'
  secret: 'D5UfO/4FfNBWn4+0cUwpLOoFzfP7Qqib4AoY+wYGsKE='
```

or use env variables:

```
export ACQUIACLI_KEY=15fd1cde-1e66-b113-8e98-5ff9d444d54f
export ACQUIACLI_SECRET=Sdtg0o83TrZm5gVckpaZynCxpikMqcht9u3fexWIHm7
```

Effectively, we are talking about supporting two different tools and configurations for Acquia API v2.

**Comment by shelane** [comment]
The generation of `cloud_api.conf` was removed from BLT last October, so I don't think there is an actionable item on that for us.

I think supporting the environment variables would be better as it may be possible to have a different key and secret for different projects. I'm not positive on that as I only have one project on Acquia cloud. Since these variables don't start with "SECRET" they will have to be masked as well.

We would not want those values included in code anywhere as they are per person and sensitive. I currently have my values stored in `~/.docksal/docksal.env` and set them up as `SECRET_` values that I use with a manual curl connection to the API v2.

**Comment by lmakarov** [comment]
ok, sounds like we would only then need config support added for acquiacli and that would happen via the env variables to keep things simple.
