### ISSUE TITLE
fin drush doesn't work for symlink

### ISSUE THREAD

**Issue by alunyovblink** [docksal/docksal#107]
1. setup the drupal site
2. create symlink 'default' and point some folder with configuration
3. run `drush cc all`
https://www.screencast.com/t/p7v8Quh9
after researching I found that in cli drush is run from folder where symlink is linked:
https://www.screencast.com/t/zEOSHONa

**Comment by lmakarov** [comment]
This has been resolved in fin v1.0.1 (https://github.com/docksal/docksal/commit/d45bc44e52fe726eac16dcc4dd841c44540e03a7)
