### ISSUE TITLE
Container cannot be found after updating to 1.86.0

### ISSUE THREAD

**Issue by nikolabintev** [docksal/docksal#1074]
**Description**
I'm no longer able to ssh to containers other than CLI after I updated to 1.86.0. `fin` says that the container that I'm trying to execute a command in, cannot be found. I'm running on MacOS Mojave 10.14.4.

**Steps to reproduce the issue:**
1. `fin system start`
2. `fin project start`
3. `fin exec --in=[container-name] bash`

I use the [container-name] provided by the `fin status` command.
**Docksal response**
`ERROR:  Container 'core_web_1' cannot be found`
`Cannot run fin exec command in that container`

**Expected behavior**
I expect ssh access to the web container.

**Comment by achekulaev** [comment]
@nikolabintev in your case use `fin exec --in=web ls`, but thanks I will fix it

**Comment by nikolabintev** [comment]
@achekulaev thanks, `web` works :)
