### ISSUE TITLE
"docker rm" requires at least 1 argument

### ISSUE THREAD

**Issue by acondura** [docksal/docksal#1076]
Whenever I run 'fin cleanup' I get the following warnings:

 fin cleanup
Checking for orphaned Docksal project stacks...
Removing dangling Docksal volumes...
Total reclaimed space: 0B
Removing dangling images...
Total reclaimed space: 0B
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers

Problem/feature description...

**Steps to reproduce the issue:**

I found it happens when running any of these commands:
1. fin cleanup
2. fin update

I'm using the latest code from Docksal

**Comment by lmakarov** [comment]
@acondura thanks for reporting this. I assume you are running Linux, since I was only able to reproduce it there. The problem is in the way (GNU) xargs works on Linux. Going to push a fix shortly.

**Comment by acondura** [comment]
Yep, exactly, I run Docksal only on Linux servers.
Great, thank you!
