### ISSUE TITLE
Add the ability to exclude directories or files when using unison mounts

### ISSUE THREAD

**Issue by opdavies** [docksal/docksal#1097]
Is there a way to specify files or directories to be excluded from syncing with unison? For example, the `.git` and `sites/default/files/php/twig` directories could be excluded to improve performance.

Likewise, any `vendor` or `node_modules` directories that are generated within the container don't need to be synced to the host machine.

**Comment by achekulaev** [comment]
Theoretically yes there is. There is a `SYNC_EXTRA_UNISON_PROFILE_OPTS` variable that you can pass to unison container (https://github.com/docksal/unison).

```
The value of this variable will be appended to the end of the Unison profile that's automatically generated when this container is started. Ensure that the syntax is valid. If you have more than one option that you want to add, simply make this a multiline string
```

So you can add ignore lines with it. I haven't tried it personally. Feel free to comment if you have additional questions or share working configuration if you succeed. I will close this ticket for now as it was hanging for long time and I don't even know if you are going to read this :)

**Comment by opdavies** [comment]
I read it. :)

I'll look into using `SYNC_EXTRA_UNISON_PROFILE_OPTS` and post back any findings.
