### ISSUE TITLE
Fix ngrok.yml config file documentation

### ISSUE THREAD

**Issue by robertromore** [docksal/docksal#1100]
**Description**

The ngrok.yml file at "examples/.docksal/etc/ngrok/ngrok.yml" currently has this documentation at the top:
```
# Ngrok example configuration file.
# To use, rename the items in CAPS to your docksal host, and rename this file to ngrok.yml or ngrok.local.yml.
```

However both the documentation (https://docs.docksal.io/tools/ngrok/) and bin (https://github.com/docksal/docksal/blob/develop/bin/fin#L5615) use the `ngrok-{ENV_NAME}.yml` naming convention.

**Comment by lmakarov** [comment]
Resolved via #1145
