### ISSUE TITLE
Do not expect exact version match for all the tools installed.

### ISSUE THREAD

**Issue by ndobromirov** [docksal/docksal#112]
I was having docker 13.x.x already installed on my machine.
The tool was giving me error that I need to upgrade to 12.... whatever.

As I checked the script it is expecting exact match for the version comparison. This is likely to never work for many users.

A much better approach would be to have a minimum version required, so anyone with that version and newer will be able to use the tool.

**Comment by lmakarov** [comment]
>A much better approach would be to have a minimum version required, so anyone with that version and newer will be able to use the tool.

That is what we've been using previously and it tended to break quite often.
The current approach (with version locking) is aimed towards stability of the setup, as Docker is moving pretty fast with the new versions and breaking changes/bugs in them.

We will add support for the latest version as soon as there is enough time to test the compatibility and make necessary adjustments. For anyone interested to try new Docker versions early on, we can add a switch, which will allow overriding the version requirements.

Thanks for raising the concern.

**Comment by achekulaev** [comment]
Docker 0.13.0 [has a bug](https://github.com/docker/docker/issues/30279) that makes it unusable with Docksal.
This bug is going to be fixed in 0.13.1 but it's not released yet.
That's why we do and we will expect exact version match.

**Comment by fuzzbomb** [comment]
Docker's  `yakkety/main` repo is available now, and a `fin update` can result in docker 1.13.0 being installed, and then you run into the version requirement issue here.

If running `fin update` watch out for a message like "Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script."

I'd press Crtl+C at this point.

**Comment by ndobromirov** [comment]
It's another option to have minimum version + a list of black-listed ones (with known issues).

**Comment by achekulaev** [comment]
@ndobromirov if you can advice how to blacklist versions so that apt-get did not install them it would help

**Comment by ndobromirov** [comment]
I was thinking more of a pre-install / pre-execute check, so install / init will terminate when your version is blacklisted or too old.
