### ISSUE TITLE
Using Docksal with VPNs

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#1124]
This is a landing page for those having issues with using Docksal alongside a "greedy" VPN connection (one that re-routes all traffic via itself). It will eventually turn into a troubleshooting doc. Please post your use case and successful/unsuccessful attempts in comments.

---

Some VPNs are configured to intercept and re-route all traffic (let's call them "greedy"), thus breaking access to the `192.168.64.100` IP that Docksal is using. Attempting to change network routing while connected to a greedy VPN will usually result in VPN dropping the connection. Enterprise security at work here 😬

The one thing VPNs cannot do, though, is mess with the hosts loopback interface (127.0.0.1). That's how your traditional web server is not affected by a greedy VPN connection - it just binds to `127.0.0.1:80` (or more likely to `0.0.0.0:80` - port 80 on all network interfaces).

Binding to `0.0.0.0:80` can be achieved with Docksal like this:

```
fin config set --global DOCKSAL_VHOST_PROXY_IP=0.0.0.0
fin system reset vhost-proxy
```

You can then access `http://localhost` (or `https://127.0.0.1`) and see the "Project missing" page from Docksal's vhost-proxy container.

![image](https://user-images.githubusercontent.com/1205005/63534326-cdaf5f00-c4c3-11e9-9c8c-23e04870bc54.png)

Now, how do you get `http://myproject.docksal` working in this setup? `<anything>.docksal` resolves to `192.168.64.100` by default, and that won't work while connected to a greedy VPN. 

For now, you will have to manually add an DNS override in your `hosts` file, e.g.:

```
127.0.0.1 myproject.docksal
```

Test it with a ping:

```
$ ping myproject.docksal
PING myproject.docksal (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.048 ms
```

## Important note

The approach mentioned above is only possible on Linux or Docker Desktop (Mac and Windows). It won't work when using Docksal with VirtualBox.

**Comment by sidddrupal** [comment]
@lmakarov  Thank you. ping command response received (64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.043 ms) however accessing from browser, it still shows error dns_unresolved_hostname. is proxy settings restrict it in browser ?

**Comment by sidddrupal** [comment]
@lmakarov  Thank you again. Yes I tried opening with ip https://127.0.0.1 it shows me the 
"Project missing This domain does not map to an existing project stack." as posted by you.

**Comment by lmakarov** [comment]
> ping command response received (64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.043 ms) however accessing from browser, it still shows error dns_unresolved_hostname

@sidddrupal what browser are you using? Try in a different one.

Also, what do you get from `curl -Iv http://<your-project>.docksal`

**Comment by sidddrupal** [comment]
@lmakarov Thank you. here is the output of curl -Iv http://<your-project>.docksal

* Rebuilt URL to: http://<project>.docksal/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to <project>.docksal (127.0.0.1) port 80 (#0)
> HEAD / HTTP/1.1
> Host: <project>.docksal
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Server: openresty/1.13.6.2
Server: openresty/1.13.6.2
< Date: Wed, 04 Sep 2019 10:42:03 GMT
Date: Wed, 04 Sep 2019 10:42:03 GMT
< Content-Type: text/html; charset=UTF-8
Content-Type: text/html; charset=UTF-8
< Connection: keep-alive
Connection: keep-alive
< X-Powered-By: PHP/7.2.14
X-Powered-By: PHP/7.2.14
< Cache-Control: must-revalidate, no-cache, private
Cache-Control: must-revalidate, no-cache, private
< X-Drupal-Dynamic-Cache: MISS
X-Drupal-Dynamic-Cache: MISS
< X-UA-Compatible: IE=edge
X-UA-Compatible: IE=edge
< Content-language: en
Content-language: en
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
< Expires: Sun, 19 Nov 1978 05:00:00 GMT
Expires: Sun, 19 Nov 1978 05:00:00 GMT
< Vary: 
Vary: 
< X-Generator: Drupal 8 (https://www.drupal.org)
X-Generator: Drupal 8 (https://www.drupal.org)
< X-Drupal-Cache: MISS
X-Drupal-Cache: MISS

< 
* Connection #0 to host <project>.docksal left intact

**Comment by lmakarov** [comment]
@sidddrupal 

The output from `curl` indicates that everything is working as expected - there is a Drupal 8 site at http://project.docksal (127.0.0.1)

> what browser are you using? Try in a different one.

IE/Edge may not honor records in the hosts file, but Chrome does.

**Comment by sidddrupal** [comment]
@lmakarov Thank you.
I am using latest Chrome and Safari browsers only.

**Comment by sidddrupal** [comment]
@lmakarov Thank you.
suddenly It started working.

**Comment by shelane** [comment]
@lmakarov Do you want this added to documentation? Troubleshooting?

**Comment by lmakarov** [comment]
@shelane yes. A dedicated page in the Troubleshooting section, please :)

**Comment by shakilahmad46** [comment]
> > ping command response received (64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.043 ms) however accessing from browser, it still shows error dns_unresolved_hostname
> 
> @sidddrupal what browser are you using? Try in a different one.
> 
> Also, what do you get from `curl -Iv http://<your-project>.docksal`

@lmakarov @sidddrupal after running this command I'm getting this output
Can you help me please.

curl -Iv http://<your-project>.docksal
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to <your-project>.docksal (127.0.0.1) port 80 (#0)
> HEAD / HTTP/1.1
> Host: <your-project>.docksal
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Server: openresty/1.19.3.2
Server: openresty/1.19.3.2
< Date: Wed, 03 Nov 2021 20:30:24 GMT
Date: Wed, 03 Nov 2021 20:30:24 GMT
< Content-Type: text/html
Content-Type: text/html
< Connection: keep-alive
Connection: keep-alive

<
* Connection #0 to host <your-project>.docksal left intact
* Closing connection 0
