### ISSUE TITLE
OS X DNS resolver w/o internet connection.

### ISSUE THREAD

**Issue by scythian** [docksal/docksal#113]
OS X has a bag or feature, when DNS resolver wont work without internet connection. In case of loosing Wi-Fi or LAN, local environment (for example "test.docksal") becomes unavailable.
Problem can be solved in case of manual updating "/etc/hosts" file (e.g. "192.168.64.100 test.docksal"), same way as MAMP stack doing.
As variant separate "init" command for OS X should be implemented or existing "init" script updated, with adding OS validation and updating "hosts" file.

**Comment by achekulaev** [comment]
In the commit referenced above I have added a `fin hosts` commands subset. 
It will allow adding lines to OS-dependent hosts file.
fin will not append lines there automatically but you can use it in your init scripts to do that if required.
e.g. `fin hosts add test.docksal`

**Comment by achekulaev** [comment]
Hosts command improved so that without parameters `fin hosts add` and `fin hosts remove` will use `VIRTUAL_HOST` of a current project.

Now people writing `init` script can do something like this

```bash
if is_windows; then
  cd "$PROJECT_ROOT"
  fin hosts add
fi
```

This command is the best I can do for using Docksal offline. As I don't want to force user to change his hosts file by default.

**Comment by achekulaev** [comment]
On macOS checking if user is offline can be done like this:

```bash
if ping -c 1 google.com >> /dev/null 2>&1; then
    echo "online"
else
    echo "offline"
fi
```

**Comment by loopy3025** [comment]
I see this issue was resolved but I'm having some reading comprehension issues with the post.  Is the a guide on how I get docksal running on a Mac that's offline?

**Comment by achekulaev** [comment]
Use `fin hosts` commands subset or edit hosts file manually. There is no other way
