### ISSUE TITLE
link to sample projects in documentation is a 404

### ISSUE THREAD

**Issue by joachim-n** [docksal/docksal#1139]
**Description**

See https://docs.docksal.io/troubleshooting/common-issues/

Link in the 'Warning' box to https://docs.docksal.io/stack/config/#sample-projects is a 404.

**Steps to reproduce the issue:**

1. Go to the documentation
2. Click the link

**Describe the results you received:**

404

**Describe the results you expected:**

Not a 404.

**Comment by shelane** [comment]
The docs will be updated. Here is a link to [sample projects](https://github.com/docksal?q=boilerplate).
