### ISSUE TITLE
Allow overriding VirtualBox version requirement

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#114]
We are currently requiring a particular version of VirtualBox, which matches the version of VirtualBox Additions packaged with a given boot2docker/docker version. These measures are aimed towards stability of the setup.
There are cases when users have to use other tools alongside Docksal and those tools may require a different version of VirtualBox. This leads to conflicts.

We should make it possible to disable/override the VirtualBox version requirement and give users a way to experiment with the versions not officially supported or recommended (at their own risk).

Version requirement override can be implemented as an environment variable. If the version requirement override is in place, users will be warned about it every time the Docksal VM is started or `fin update` is run.

**Comment by achekulaev** [comment]
Resolved in fin 1.1.0.

Setting `SKIP_VBOX_VERSION_CHECK` to `1` will force fin not to check for VIrtualBox requirements.

Can be used via command line
```bash
SKIP_VBOX_VERSION_CHECK=1 fin update
```

or via editing global env file `~/.docksal/docksal.env`

```ini
...
SKIP_VBOX_VERSION_CHECK=1
...
```
