### ISSUE TITLE
Zero-configuration example produces a 403

### ISSUE THREAD

**Issue by joachim-n** [docksal/docksal#1140]
**Description**

The 'Zero-configuration' example in the documentation produces a site that shows a 403.

**Steps to reproduce the issue:**

1. Follow the instructions at https://docs.docksal.io/stack/zero-configuration/
2. When `fin start` is complete, follow the link it gives to Project URL: http://docksal-test.docksal

**Describe the results you received:**

Page with a 403 error.

**Describe the results you expected:**

Some sort of web page. Possibly an HTML index of the empty folder?

**Comment by shelane** [comment]
There is zero configuration, but an index.html or index.php file must be created in `docroot` directory of your project.

**Comment by joachim-n** [comment]
I tried adding an index.html file and got the same result.

**Comment by lmakarov** [comment]
@joachim-n it should be `docroot/index.html`. Try this:

```
mkdir myproject
cd myproject
mkdir docroot
echo "Hello World" > docroot/index.html
fin start
```

Test:

```
$ curl http://myproject.docksal
Hello World
```

You can also just do a `fin init` in an empty (or an existing project) folder for a wizard experience:

```
$ mkdir myproject2
$ cd myproject2
$ fin init
Initialize a project in /Users/leonid/Work/Projects/myproject2? [y/n]: y
DOCROOT has been detected as docroot. Is that correct? [y/n]: y
Configuration was generated. You can start it with fin project start
Key 'id_ecdsa' already loaded in the agent. Skipping.
Key 'id_rsa' already loaded in the agent. Skipping.
Starting services...
Creating network "myproject2_default" with the default driver
Creating volume "myproject2_cli_home" with default driver
Creating volume "myproject2_project_root" with local driver
Creating volume "myproject2_db_data" with default driver
Creating myproject2_db_1  ... done
Creating myproject2_cli_1 ... done
Creating myproject2_web_1 ... done
Connected vhost-proxy to "myproject2_default" network.
Waiting for project stack to become ready...
Waiting for project stack to become ready...
Project URL: http://myproject2.docksal
```

The above will generate the directory structure for you if one does not exist, as well as create a dummy `docroot/index.php` file.

```
$ curl -I http://myproject2.docksal
HTTP/1.1 200 OK
Server: openresty/1.13.6.2
Date: Wed, 02 Oct 2019 16:29:09 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Powered-By: PHP/7.3.9
```

**Comment by joachim-n** [comment]
> it should be docroot/index.html 

It would be really helpful if the Zero-configuration example mentioned this. The reason I was trying that example in the first place was that my main project wasn't managing to start up docksal, and I was trying something as possible to see if the problem was my system or the project itself.

**Comment by lmakarov** [comment]
@joachim-n fair enough.

@shelane we should mention the default assumed `docroot` folder, the `index.html`/`index.php` default directory index document (link to https://docs.docksal.io/getting-started/project-setup/#project-directory-structure), as well as the ability to change the docroot using `fin config set DOCROOT=<folder>` (link to https://docs.docksal.io/stack/configuration-variables and add the `DOCROOT` variable description there).
