### ISSUE TITLE
Using Docker Engine REST API inside Docksal containers?

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#1143]
I'm attempting to build a dashboard site that lists, in real time, the existing sandbox sites on the sandbox server (amongst other things like connecting back to services like Mavenlink, Jira, and Bitbucket). To do so, I need access to the Engine REST API on the host from inside the cli container. I'm just not sure how to go about getting access to Docker Engine from inside a running container.

At the most basic level, I want to query all containers with label io.docksal.virtual-host and just create a page that lists the virtual hosts. Thoughts? I realize this is a pretty generic Docker question, but I'm not sure if there's anything specifically about Docksal I should be taking into account. Thank you!

**Comment by lpeabody** [comment]
Accomplished by adding to cli volumes:

- /var/run/docker.sock:/var/run/docker.sock

Add adding a startup.sh script to ensure that the docker user inside the container has read access to the socket.

**Comment by achekulaev** [comment]
Sounds like a nice thingy that could be added to vhost-proxy
