### ISSUE TITLE
docs don't where to put a custom addon

### ISSUE THREAD

**Issue by joachim-n** [docksal/docksal#1148]
I can't see on https://docs.docksal.io/fin/addons/ anywhere where it says where to put a custom addon that I'd write myself.

I can tell by looking at the downloaded addons in my project that they go in `.docksal/addons/adminer/conf`, but it's not clear from the docs.

There's this bit:

> Fin will first look for the addon in the ~/.docksal/addons directory. If it is not located there, then it will attempt to search the Docksal Addons Repository.

But that's in 'Installing to Project', not in 'Creating Addons'. It's also rather ambiguous, as that makes it sound like you put your custom addon there, and then have to run `fin install`, which does... something that's not clear? My project has addons from the repository placed there already, so does that mean that `fin install` downloads them there and puts them there? In which case, how does `fin install` handle a custom addon I place there?

**Comment by shelane** [comment]
An addon is a community written command that is installed via an install command `fin install <name>`. If you're creating a command for your own project, you're creating a [custom command](https://docs.docksal.io/fin/custom-commands/) and you only need the command file placed inside `.docksal/commands`.
