### ISSUE TITLE
docs page 'db: Access for External Tools' assumes a VM

### ISSUE THREAD

**Issue by joachim-n** [docksal/docksal#1150]
Docs page at https://docs.docksal.io/service/db/access/ says:

```
$ fin vm ip
192.168.64.100
$ fin ps
```

However, if running with Docker desktop (which IIRC is the recommended method), I get:

```
$ fin vm ip

 ERROR:  Docksal VM cannot be used in Docker Desktop mode
        You have DOCKER_NATIVE set to 1. VM functions should not be used in this mode.
        See https://docs.docksal.io/getting-started/docker-modes/ for details
```

**Comment by joachim-n** [comment]
127.0.0.1 as an IP in Sequel Pro works for me.

**Comment by lmakarov** [comment]
`192.168.64.100` is a canonical Docksal IP that works on all systems. We should just drop `fin vm ip` from docs and just say `192.168.64.100`.

> 127.0.0.1 as an IP in Sequel Pro works for me.

True. On Docker Desktop, the localhost IP also works.
