### ISSUE TITLE
How to install docksal on Oracle Linux Server 7.7

### ISSUE THREAD

**Issue by bhavanasisarath** [docksal/docksal#1171]
Followed below command to install docker on my oracle linux and installed **docker-engine.x86_64 0:18.09.8.ol-1.0.4.el7**
sudo yum install docker-engine

After that to install docksal used  **bash <(curl -fsSL https://get.docksal.io)** but it is throwing the below error.

**Docker version should be 18.09.2 or greater.
        Automated Docker installation is not supported on this platform.
        Install Docker 18.09.2 or greater manually and run Docksal installation again.**

When i tried for list of available docker engine verions, it listed like below.
**yum list docker-engine --showduplicates | sort -r**
Loaded plugins: langpacks, ulninfo
docker-engine.x86_64              1.9.1-1.0.1.el7                     ol7_addons
docker-engine.x86_64              1.8.3-1.0.2.el7                     ol7_addons
docker-engine.x86_64              1.8.3-1.0.1.el7                     ol7_addons
docker-engine.x86_64              1.8.2-1.0.2.el7                     ol7_addons
docker-engine.x86_64              18.09.8.ol-1.0.4.el7                ol7_addons
docker-engine.x86_64              18.09.1.ol-1.0.8.el7                ol7_addons
docker-engine.x86_64              18.09.1.ol-1.0.5.el7                ol7_addons
docker-engine.x86_64              18.03.1.ol-0.0.9.el7                ol7_addons
docker-engine.x86_64              18.03.1.ol-0.0.15.el7               ol7_addons
docker-engine.x86_64              18.03.1.ol-0.0.14.el7               ol7_addons
docker-engine.x86_64              18.03.1.ol-0.0.12.el7               ol7_addons
docker-engine.x86_64              17.06.2.ol-1.0.7.el7                ol7_addons
docker-engine.x86_64              17.06.2.ol-1.0.6.el7                ol7_addons
docker-engine.x86_64              17.06.2.ol-1.0.1.el7                ol7_addons
docker-engine.x86_64              17.03.1.ce-3.0.1.el7                ol7_addons
docker-engine.x86_64              1.12.6-1.0.3.el7                    ol7_addons
docker-engine.x86_64              1.12.6-1.0.1.el7                    ol7_addons
docker-engine.x86_64              1.12.2-1.0.1.el7                    ol7_addons
docker-engine.x86_64              1.12.0-1.0.2.el7                    ol7_addons
docker-engine.x86_64              1.10.3-1.0.3.el7                    ol7_addons
docker-engine.x86_64              1.10.3-1.0.2.el7                    ol7_addons
docker-engine.x86_64              1.10.3-1.0.1.el7                    ol7_addons
Available Packages

But the above error message shows as 18.09.2 to install, it is not listed here. Please help me how to install docksal on oracle linux.

**Comment by lmakarov** [comment]
Please post the output from `docker version`.

**Comment by bhavanasisarath** [comment]
Hi @lmakarov , Thank you for your response.

Here is the output of > docker version
Client:
 Version:           18.09.1-ol
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e32a1bd
 Built:             Thu Jun  6 14:55:42 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by lmakarov** [comment]
@bhavanasisarath how about `sudo docker version`?
