### ISSUE TITLE
Can't start docksal project after clean install

### ISSUE THREAD

**Issue by nicoschi** [docksal/docksal#118]
Hi, 
i clean installed docksal on a Mac 10.11.6 after downgrade of Virtualbox, uninstallation of Docker for Mac and Toolbox togeter with all vm's but, as after a previous installation, i have a problem during "fin create-site" ending with: 
Creating docksaltest_cli_1
Creating docksaltest_db_1

ERROR: for db  Cannot start service db: {"message":"no such file or directory"}

ERROR: for cli  Cannot create container for service cli: {"message":"no such file or directory"}
ERROR: Encountered errors while bringing up the project.

Can anyone help me?

The project is a Drupal 7 site, i'm starting with a test before migrate all my project from MAMP to Docksal

Thanks

**Comment by achekulaev** [comment]
Hi @nicoschi 

Your project should be somewhere inside your home folder on Mac (For example I have ~/Projects folder where I store all my projects). 
Looks like you're trying to run a project somewhere outside of it.

**Comment by nicoschi** [comment]
Great, it works, sorry, my project was outside home folder. 
Thank you very much

**Comment by achekulaev** [comment]
Great! We will describe that limitation somewhere in documentation.
