### ISSUE TITLE
How to update globally installed Drush 8?

### ISSUE THREAD

**Issue by alanmels** [docksal/docksal#1184]
The documentation page on https://docs.docksal.io/tools/drush states:

> For legacy setups and older Drupal versions, cli also ships with a globally installed Drush 8. 

without telling how to upgrade its version. Because of the error discussed on https://github.com/backdrop-contrib/drush/issues/200 I need to get the current CLI Drush version on my Docksal setup:

> docker@cli:/var/www/.docksal$ drush --version
> Drush Launcher Version: 0.6.0
>  Drush Version   :  8.1.16 
> 
> docker@cli:/var/www/.docksal$ 

from 8.1.16  to 8.2.3. Could you please explain how could I do it? Thanks a lot!

**Comment by alanmels** [comment]
Had to:

```
cd /usr/local/bin/
sudo mv drush8 drush8.bk
sudo wget https://github.com/drush-ops/drush/releases/download/8.2.3/drush.phar
sudo mv drush.phar drush8
sudo chmod 755 drush8
```

and running the `drush st` command in `var/www/docroot` shows the desired version. 

However, I still wonder what is the "official Docksal" way of updating drush CLI version?

**Comment by achekulaev** [comment]
@alanmels you don't update drush manually. Latest PHP 7.2 image contains drush 8.3.0. Just use them. 

If really needed 

```
sudo curl -fsSL "https://github.com/drush-ops/drush/releases/download/${DRUSH_VERSION}/drush.phar" -o /usr/local/bin/drush8
```

**Comment by shelane** [comment]
The docs also state:

> Drush Launcher is also installed globally in the cli container. It will automatically pickup project level drush version and pass execution to it.

This means that Drush should be installed as part of the project (for newer projects) with composer. So you can install whatever version you need if it’s different than what is provided and the Drush launcher will pass all Drush commands to that version.

**Comment by alanmels** [comment]
> The docs also state:
> 
> > Drush Launcher is also installed globally in the cli container. It will automatically pickup project level drush version and pass execution to it.
> 
> This means that Drush should be installed as part of the project (for newer projects) with composer. So you can install whatever version you need if it’s different than what is provided and the Drush launcher will pass all Drush commands to that version.

@shelane, thanks for the update, but I am workin with Backdrop, which does not have Composer. So I'll just follow @achekulaev's recommendation.

**Comment by alanmels** [comment]
@achekulaev, strangely enough, but the project was deployed with `CLI_IMAGE='docksal/cli:2.5-php7.2'` in docksal.env file, which is confirmed by the `php -v` command on CLI:

```
docker@cli:/var/www/docroot$ php -v
PHP 7.2.10 (cli) (built: Sep 15 2018 02:33:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.23.0~linux-x64-non_zts72, https://blackfire.io, by Blackfire
docker@cli:/var/www/docroot$ 
```

but it still had `Drush Version : 8.1.16`.

**Comment by achekulaev** [comment]
@alanmels so you pinned it to cli version 2.5. latest cli version available is 2.8. https://github.com/docksal/service-cli/releases

`CLI_IMAGE='docksal/cli:2.8-php7.2'` or use `CLI_IMAGE='docksal/cli:2-php7.2'` to always have the latest 2.x version, but beware that in latter case your project will automatically rebuild `cli` container after you update Docksal and it `fin` updates references to the latest images.

**Comment by alanmels** [comment]
Just have restarted with `docksal/cli:2.6-php7.2` and again after `fin bash` it shows the same unwanted version 8.1.18:

```
docker@cli:/var/www/docroot$ php -v
PHP 7.2.14 (cli) (built: Jan 11 2019 01:23:39) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.14, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.24.2~linux-x64-non_zts72, https://blackfire.io, by Blackfire
docker@cli:/var/www/docroot$ drush st
 Backdrop version         :  1.14.1                          
 Site URI                 :  http://docroot                  
 Database driver          :  mysql                           
 Database hostname        :  db                              
 Database username        :  user                            
 Database name            :  default                         
 Backdrop bootstrap       :  Successful                      
 Backdrop user            :                                  
 PHP configuration        :                                  
 PHP OS                   :  Linux                           
 Drush script             :  /usr/local/bin/drush8           
 Drush version            :  8.1.18                          
 Backdrop Drush           :  1.x-1.x                         
 Drush temp directory     :  /tmp                            
 Drush configuration      :  /home/docker/.drush/drushrc.php 
 Drush alias files        :                                  
 Install profile          :  standard                        
 Backdrop Settings File   :  ./settings.php                  

docker@cli:/var/www/docroot$ 
```

**Comment by achekulaev** [comment]
See above

**Comment by alanmels** [comment]
> @alanmels so you pinned it to cli version 2.5. latest cli version available is 2.8. https://github.com/docksal/service-cli/releases
> 
> `CLI_IMAGE='docksal/cli:2.8-php7.2'` or use `CLI_IMAGE='docksal/cli:2-php7.2'` to always have the latest 2.x version, but beware that in latter case your project will automatically rebuild `cli` container after you update Docksal and it `fin` updates references to the latest images.

Oh, I was looking at https://docs.docksal.io/stack/images-versions and was not aware of the existence of 2.8 branch. Please somebody update the documentation page.

**Comment by achekulaev** [comment]
It will update with the release

**Comment by alanmels** [comment]
> It will update with the release

but then according to https://github.com/docksal/service-cli/releases the last release was 27 days ago:

> v2.8.0
> @lmakarov lmakarov released this 27 days ago

yet the https://docs.docksal.io/stack/images-versions contains outdated information.

**Comment by achekulaev** [comment]
Let know if you have any additional questions.

**Comment by alanmels** [comment]
> Let know if you have any additional questions.

Thanks for your help. If you could take a look why `drush dl devel` is failing on https://github.com/backdrop-contrib/drush/issues/200 would be wonderful.

**Comment by achekulaev** [comment]
That is rather a question to backdrop team

**Comment by alanmels** [comment]
Indeed [it was about](https://github.com/backdrop-contrib/drush/issues/200#issuecomment-542896271) Backdrop drush integration. Still it would be very nice to get https://docs.docksal.io/stack/images-versions updated not to confuse Docksal users. If updating that documentation page is too tiresome for your team with every new cli release, then please consider at least just referencing the https://github.com/docksal/service-cli/releases page on it.

**Comment by achekulaev** [comment]
Yes it is too cumbersome to update that page after every release of cli. They are a bit out of sync as 2 different components. Sometimes new images are not supported by old fin, so they should not just appear there.

> then please consider at least just referencing the https://github.com/docksal/service-cli/releases page on it

It is already referenced there, "Release notes" button above the table. If you have

**Comment by alanmels** [comment]
Fair enough, @achekulaev . Thanks!
