### ISSUE TITLE
Add documentation on creating BLT project using wizard

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#1187]
Based on #1011

**Comment by shelane** [comment]
@achekulaev Looking through the documentation that we have, I don't see documentation for any of our boilerplate projects. Is there something specific you're looking to have in the docs? We may need a place about the memory requirements, but I see this for the Drupal composer project as well. So maybe we make note of the memory requirement for the VM/Docker for using composer.

**Comment by achekulaev** [comment]
@shelane it's more of documentation about BLT rather than a boilerplate. Should go under "Toola and integrations. Boilerplate here is just a tool.

**Comment by achekulaev** [comment]
@shelane I don't think we need to repeat the docs. It's just a landing for those who will open docs.docksal.io and search for BLT. Right now they find exactly nothing.

We need a page where they will land "Using BLT with Docksal"
The page should say:

1. Ezpz way: use boilerplate so and so
2. Here is official docs: link
3. Here is a lengthy and descriptive blogs post: link
