### ISSUE TITLE
Increase default DEFAULT_MACHINE_VBOX_RAM

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#1188]
Some composer tasks (like [installing BLT]()https://github.com/docksal/docksal/issues/1011#issuecomment-543201414) require up to 2GB of RAM. Having default VM to have 2GB ram in total sets up such tasks for failure. 

It is probably time to increase it. 3GB or 4GB sound like reasonable options.

cc @lmakarov @sean-e-dietrich @lpeabody

**Comment by lpeabody** [comment]
We've standardized all of our Docksal installs to require a VM RAM total of 4096M. It's possible 3072M is sufficient, but I can say for certain that when running Composer commands day-to-day the 2048M has never been enough to guarantee we won't see OOM errors. I for one would be in favor of bumping up the default to _at least_ 3072M.

**Comment by lmakarov** [comment]
`docksal/cli` starting with v2.7.0 should improve the composer memory issues substantially.
See https://github.com/docksal/service-cli/issues/99.

**Comment by achekulaev** [comment]
@lpeabody which `cli` version were you running when experienced RAM issues?

**Comment by lmakarov** [comment]
Another thing to consider is how many project stacks you are running in parallel. Each stack consumes at least a few hundred MB of RAM even when idle (MySQL buffers/caches, etc.).

I ran into the `Killed` situation during `composer install` today:

```
$ fin exec COMPOSER_PROCESS_TIMEOUT=600 COMPOSER_MEMORY_LIMIT=-1 composer
...
Updating dependencies (including require-dev)
Killed
fin exec COMPOSER_PROCESS_TIMEOUT=600 COMPOSER_MEMORY_LIMIT=-1 composer   0.95s user 0.45s system 1% cpu 2:15.54 total
```

`composer install` was running in `docksal/cli:2.9.-php7.3`. I had one more D8 project stack running at the same time. After stopping that other stack (restarting Docker Desktop to be precise, but the result would be more or less the same) I was able to run `composer install` without it running out of physical memory.

In my case, peak `cli` RAM usage reached 1.177 GB:

![](https://i.imgur.com/h7xYUuD.gif)

**Comment by achekulaev** [comment]
I think it is reasonable to suppose at least 2, but maybe 3 projects running in parallel as a default situation. From what I see composer will not be able to run when more than 1 project runs. Increasing to 3GB should fix this.

**Comment by achekulaev** [comment]
Should we do it now? I don't think it hurts.

**Comment by lmakarov** [comment]
We can increase `DEFAULT_MACHINE_VBOX_RAM`, but Docker Desktop defaults to 2GB. We will need to mention that switching to 3GB RAM or more is recommended somewhere in docs.

**Comment by shelane** [comment]
#1189 does mention this. Should it be included elsewhere too?

**Comment by lmakarov** [comment]
VirtualBox and Docker Desktop should have matching settings (as close as possible). While we create the VirtualBox VM and can set its configuration, we do not control Docker Desktop defaults. Any additional settings in Docker Desktop have to be handled manually. Adding more manual steps to the default setup flow makes the UX worse.

2GB should be enough to install a D8 composer based project. As such, this default is reasonable.
If there was a way to set Docker Desktop defaults automatically, then I'd say YES to going with 3GB as a failsafe standard.

I think we should add a page for Docker Desktop configuration in the docs and cover the RAM and other settings there (similar to how we have a page for VirtualBox settings - https://docs.docksal.io/core/vm/#set-docksal-s-virtualbox-vm-memory-ram). We can then link to this page from other places that call for configuration changes, like the Composer docs @shelane mentioned (#1189 )

**Comment by achekulaev** [comment]
I don't see a reason why 2 completely different apps with completely different ways of doing things should have similar settings, but since there is a workaround I don't care enough to argue.
