### ISSUE TITLE
Docksal breaks after updating to Docker Desktop 2.1.0.x (Docker 19.03.x)

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#1197]
**Symptoms**

```
$ fin system reset
...
Resetting Docksal system services...
 * proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (841b2b966f296e1b54f20077bc505ecaf644c3203dd8383d1cb232d8efebf885): Error starting userland proxy: /forwards/expose/port returned unexpected status: 500.
 ERROR:  Failed starting the proxy service.
```

![image](https://user-images.githubusercontent.com/1205005/67428488-10a8b400-f593-11e9-85a2-1ca01fb73009.png)

**Upstream issue**

https://github.com/docker/for-mac/issues/3970

**Workaround**

```
fin config set --global DOCKSAL_VHOST_PROXY_IP=0.0.0.0
fin system reset
```

**Comment by achekulaev** [comment]
Can it be closed? This issue seems to be resolved by restarting Docker

**Comment by lmakarov** [comment]
Restarting Docker will indeed fix this but only for the first container launched with an exposed `IP:port`. Restarting that container or starting new containers will fail. To fix this, we will need to have `DOCKSAL_VHOST_PROXY_IP=0.0.0.0` set by default for the time being.

**Comment by lmakarov** [comment]
After updating to macOS Catalina 10.15.1 I'm no longer able to reproduce this issue on my Mac.

**Comment by lmakarov** [comment]
Closing for now as there have been now other reports of this issue. It's still not clear what was causing it.
