### ISSUE TITLE
Trouble with install

### ISSUE THREAD

**Issue by davekopecek** [docksal/docksal#12]
Hi -

Just blew my drude / vagrant install away and am testing docsal with the drupal8 project on Windows 10 with Babun and Virtualbox 5.1.6

After `fin init` I can `fin drush status` and get the usual drush results, but I can't hit the site in my browser. It looks like my docksal virtualbox vm network adapter 2 is bound to the wrong IP address.  Instead of 192.168.10.10 it's 192.168.64.1.  From `fin sysinfo`:

````
NETWORK INTERFACES
Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            54a76287-b485-4745-8176-7d490464826a
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:fc70:e8f3:9931:7d00
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:1a
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2
````

I've blown the adapter away, recreated the project services and finally recreated docsal vm docker-machine.  Suggestions?

**Comment by davekopecek** [comment]
The DHCP server for *Virtualbox Host-Only Ethernet Adapter #2*  is defaulting to:

````
Server Address: 192.168.64.6
Server Mask: 255.255.255.0
Lower Address Bound: 192.168.64.100
Upper Address Bound: 192.168.64.254
````

These settings appear to survive the adapter being deleted.  There was an error message the first time I installed the fin prerequisites about a network adapter and a 'known bug in virtualbox' but I no longer have access to the message.

**Comment by lmakarov** [comment]
@davekopecek we switch to a new default IP for Docksal: `192.168.64.100`.
So what you are seeing is correct. Please update you host file records accordingly (necessary on Windows only).

**Comment by lmakarov** [comment]
`192.168.64.1` is the host IP address (your Widows box) within the host-only network that VirtualBox creates.

**Comment by davekopecek** [comment]
Working !! Thanks. 

Do you want me to do a pull request to update the drupal8 Readme.md?

````
3. On Windows add 192.168.10.10 drupal8.docksal to your hosts file
````

**Comment by lmakarov** [comment]
I've just update this in all sample projects.
We still have a lot of work to be done with the documentation overhaul. You are definitely welcome to contribute :)
