### ISSUE TITLE
Document Drupal multisite use case

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#1208]
This has been brought up a few times recently, so it will be good to have it documented on [docs.docksal.io](https://docs.docksal.io/)

Example of a D7 multisite setup:
https://github.com/docksal/boilerplate-drupal7-advanced

Relevant docs:

- https://docs.docksal.io/fin/fin-help/#db
- https://docs.docksal.io/tools/drupal/
- https://docs.docksal.io/core/system-vhost-proxy/#using-arbitrary-custom-domains

**Comment by shelane** [comment]
https://deploy-preview-1209--docs-docksal-io.netlify.com/use-cases/drupal-multisite/
