### ISSUE TITLE
Update Behat docs

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#121]
Update Behat docs to explain that behat is custom command and where to get it (link to drupal7-advanced)

**Comment by achekulaev** [comment]
Daria (Dasha) Vashchylenko [2:58 PM] 
http://docksal.readthedocs.io/en/master/behat/ - this page contains wrong instruction now, when `fin behat` has been removed from main fin
[2:59]  
it should be linked to examples from the https://github.com/docksal/drupal7-advanced instead, including custom comand

**Comment by dashav** [comment]
I have found that behat doc has been updated in develop branch: http://docksal.readthedocs.io/en/develop/behat/

Could you please publish it to master?
