### ISSUE TITLE
aliases for 'fin system foo' commands don't show up in command list or help

### ISSUE THREAD

**Issue by joachim-n** [docksal/docksal#1211]
**Description**

There are commands `fin start`, `fin stop`, `fin restart` (I think?)

But when you do `fin list`, these are not shown. Nor can you get help on then with `fin help start`.

It looks like these are subcommands of `fin system` which are somehow aliased. But if you don't know this, these omissions are confusing.

**Comment by lmakarov** [comment]
These are legacy commands which are now grouped under `fin project`. `fin help project` lists them as aliases.
