### ISSUE TITLE
Update release scripts in all image repos

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#1228]
Replace the old `release.sh` script with the `docker-push.sh` script used in [docksal/cli](https://github.com/docksal/service-cli/blob/develop/scripts/docker-push.sh). The new script ensures stable, major and minor image tags point to the same image ID.

List of repos to update:

- [x] service-vhost-proxy
- [x] service-ssh-agent
- [x] service-dns
- [x] service-cli
- [x] service-apache
- [x] service-nginx
- [x] service-mysql
- [x] service-mariadb
- [x] service-varnish
- [x] service-solr
- [x] service-ssh-proxy

**Comment by sergey-zabolotny** [comment]
all listed repos updated
