### ISSUE TITLE
ERROR: 2 matches found based on name: network backdrop_default is ambiguous

### ISSUE THREAD

**Issue by alanmels** [docksal/docksal#1236]
**Description**

Problem/feature description...

**Steps to reproduce the issue:**

I am not sure how exactly this error came up, but I have a wild guess it happened because I tried to open the http://backdrop.docksal on my browser and at the same time fired up the `fin p start` command on CLI.

**Describe the results you received:**

It's not coming up on browser. CLI is giving:

```
alan@Bohemian:~/Projects/backdrop/docroot$ fin p restart
Key 'id_rsa' already loaded in the agent. Skipping.
Disconnecting project network...
Stopping services...
Stopping backdrop_web_1  ... done
Stopping backdrop_pma_1  ... done
Stopping backdrop_db_1   ... done
Stopping backdrop_cli_1  ... done
Stopping backdrop_mail_1 ... done
Starting services...
Creating network "backdrop_default" with the default driver
Starting backdrop_db_1 ... 
Starting backdrop_mail_1 ... error
Starting backdrop_db_1   ... error
Starting backdrop_cli_1  ... 

ERROR: for backdrop_mail_1  Cannot start service mail: network backdrop_default is ambiguous (2 matches found on name)

Starting backdrop_cli_1  ... error
Starting backdrop_pma_1  ... error
ERROR: for backdrop_cli_1  Cannot start service cli: network backdrop_default is ambiguous (2 matches found on name)

ERROR: for backdrop_pma_1  Cannot start service pma: network backdrop_default is ambiguous (2 matches found on name)

ERROR: for mail  Cannot start service mail: network backdrop_default is ambiguous (2 matches found on name)

ERROR: for db  Cannot start service db: network backdrop_default is ambiguous (2 matches found on name)

ERROR: for cli  Cannot start service cli: network backdrop_default is ambiguous (2 matches found on name)

ERROR: for pma  Cannot start service pma: network backdrop_default is ambiguous (2 matches found on name)
ERROR: Encountered errors while bringing up the project.
alan@Bohemian:~/Projects/backdrop/docroot$ fin p restart
Key 'id_rsa' already loaded in the agent. Skipping.
Disconnecting project network...
Stopping services...
ERROR: 2 matches found based on name: network backdrop_default is ambiguous

**Comment by achekulaev** [comment]
Not sure if anything can be done about it. Looks like a fundamental issue of running `docker-compose up` twice in parallel for a same project. `finp remove` `fin p start`.

**Comment by alanmels** [comment]
So what's your best recommendation in this case?

**Comment by achekulaev** [comment]
Do not run `fin p start` when project is being waked up in the browser :) As well as do not start project in 2 separate terminal tabs simultaneously.

I mean it really is a fundamental concurrency issue. Like trying to create 2 files with the same name in the same folder and getting an error. The error in this case is not avertible and totally fine and the only advice there could be is do not create 2 files with the same name in the same folder.

p.s. Theoretically I could implement a lock, like creating a PID file, but that would open another can of worms with project being "locked" in case `docker-compose up` did not end properly or such.

**Comment by alanmels** [comment]
Well, I don't do any of the counted things. Also I've hard-removed the `backdrop` directory, run `fin cleanup`, `fin update` and restarted Docker, but still when trying to create a project with the same name it gives:

```
ERROR: 2 matches found based on name: network backdrop_default is ambiguous
```

So there is something else in the system.

**Comment by achekulaev** [comment]
Run `fin project remove` in the project directory. If you still have the issue, you will have to use docker commands to [list all networks](https://docs.docker.com/engine/reference/commandline/network_ls/), find the one named `backdrop_default` and [remove it](https://docs.docker.com/engine/reference/commandline/network_rm/). You might have to preliminary [disconnect any containers](https://docs.docker.com/engine/reference/commandline/network_disconnect/) that might have been bound to it.

**Comment by alanmels** [comment]
Thank you for pointing me to `docker network prune` which helped to resolve the issue.

**Comment by benjifisher** [comment]
I had the same problem. For the sake of the next person who comes across this issue, this is what I did:

```
fin system stop
docker network prune
```

Maybe just the second line is enough. That is pretty much what the previous comment said, but I want to be explicit that this works without any additional steps or arguments.
