### ISSUE TITLE
Create documentation for SSH auth proxy over TCP

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#1239]
Implemented here https://github.com/docksal/docksal/pull/1088
It only describes variable. 
There is a need for somewhat more detailed explanation on this feature, any why it was implemented on the page: https://docs.docksal.io/core/system-ssh-agent/

@GMTA does it sound like something you could handle?

**Comment by GMTA** [comment]
@achekulaev Sure, I could write up a page about this feature!

**Comment by achekulaev** [comment]
Thanks! I guess it mostly will be your comment from that PR that describes the whole thing in details.
