### ISSUE TITLE
Commit cli image

### ISSUE THREAD

**Issue by nicoschi** [docksal/docksal#124]
Hi there, 
i'm trying to modify cli image (adding for example grunt, browsersync and others node packages). 

I tried: 
`fin docker run -it -u root:root docksal/cli:1.0-php5 /bin/sh`
then from inside the container: 
`npm install -g browser-sync && npm install -g grunt-cli && exit`
then a commit: 
`fin docker commit -m "added grunt" [CONTAINER ID] docksal/cli:1.0-php5`
but when i "fin start" a previous project which uses php5 i have this message:
`Starting services...`
`Recreating myproject_cli_1`
`Starting myproject_db_1`
`Recreating myproject_web_1`
`Changing user id in cli to 501 to match host user id...`
`Resetting permissions on /var/www...`
`Restarting php daemon...`
`Error response from daemon: Container [CONTAINER ID] is not running`

Probably i am wrong using "-u root:root" in docker run. I tried without it having this problem when "fin start" a previous project: 
`Error getting uid from cli container`
`You might need to recreate containers with fin reset`

Can someone help to solve this?

Thanks

**Comment by achekulaev** [comment]
First you need to use unique name and tag for your modified image.
`fin docker commit -m "added grunt" [CONTAINER ID] nicoschi/cli:1.0-php5`

After you created your own image you need to update the web container definition in your project to point to the newly built image - add the following to `docksal-local.yml`

```
version: "2.1"

services:
  cli:
    image: nicoschi/cli:1.0-php5
```

**Comment by nicoschi** [comment]
Great, it works like a charm
Many thanks
