### ISSUE TITLE
Coder IDE with password

### ISSUE THREAD

**Issue by acondura** [docksal/docksal#1240]
I was finally able to upgrade Docksal on my Ubuntu dev servers and while the Coder IDE loads fine and is fully working, I was not able to use the IDE with a password since all my Dev environments are using a public domain. I tried both IDE_PASSWORD and PASSWORD variable and still ide-project.domain is freely accessible without a password. I tracked down the code in cli and I saw that IDE_PASSWORD is actually PASSWORD but still no go (hope I looked in the right place). 
Am I missing something?

**Comment by acondura** [comment]
I see PASSWORD is set with the value from IDE_PASSWORD in service-cli/7.2/startup.sh but it just doesn't work. I reset every container, restart the project, connect to ide-project.domain through a logged out window and every possible browser and still the connection is passwordless.

**Comment by achekulaev** [comment]
`fin config`

**Comment by acondura** [comment]
---------------------
COMPOSE_PROJECT_NAME_SAFE: grav
COMPOSE_FILE:
/home/grav/.docksal/stacks/volumes-bind.yml
/home/grav/.docksal/stacks/stack-default-nodb.yml
/home/grav/project/grav/.docksal/docksal.yml
/home/grav/.docksal/stacks/overrides-ide.yml
ENV_FILE:
/home/grav/project/grav/.docksal/docksal.env

PROJECT_ROOT: /home/grav/project/grav
DOCROOT: docroot
VIRTUAL_HOST: grav.opncld.com
VIRTUAL_HOST_ALIASES: *.grav.opncld.com
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: grav.opncld.com
      GIT_USER_EMAIL: ''
      GIT_USER_NAME: ''
      HOST_GID: '1009'
      HOST_UID: '1009'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: serverName=grav.opncld.com
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: grav.opncld.com
      XDEBUG_CONFIG: remote_host=ide remote_port=9000
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.10-php7.3
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  ide:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: grav.opncld.com
      GIT_USER_EMAIL: ''
      GIT_USER_NAME: ''
      HOST_GID: '1009'
      HOST_UID: '1009'
      IDE_ENABLED: '1'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: serverName=grav.opncld.com
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: grav.opncld.com
      XDEBUG_CONFIG: remote_host=ide remote_port=9000
      XDEBUG_ENABLED: '0'
    expose:
    - '8080'
    - '9000'
    hostname: ide
    image: docksal/cli:2.10-php7.3
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: ide-grav.opncld.com,ide-grav.opncld.com.*
      io.docksal.virtual-port: '8080'
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish-grav
    image: docksal/varnish:6.1-2.0
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: varnish-grav.opncld.com
    volumes:
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /home/grav/project/grav
      io.docksal.virtual-host: grav.opncld.com,*.grav.opncld.com,grav.opncld.com.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/grav/project/grav
      o: bind
      type: none

---------------------

**Comment by achekulaev** [comment]
I don't see `IDE_PASSWORD` environment variable set...

**Comment by acondura** [comment]
I was surprised, too. I tried several times and it is just not being "read" from docksal.env file.

**Comment by achekulaev** [comment]
@acondura ok I see. Looks like passthrough of this variable was forgotten to be added to the default stack for IDE. Just add it yourself in your yaml and and (re-)start the project.

**docksal.yml:**
```yaml
version: "2.1"
services:
  ide:
    environment:
      - IDE_PASSWORD
```

**Comment by acondura** [comment]
Oh I see, great, thank you!
