### ISSUE TITLE
Support Preloading in PHP 7.4

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#1245]
**Description**

PHP 7.4 introduced [preloading](https://stitcher.io/blog/preloading-in-php-74). This can result in a noticeable increase in performance when leveraged optimally. Some folks have done some investigation into what is the optimal way to preload, and it turns out it isn't so straightforward.

It looks like preloading "hot" classes rather than everything is the way to go. See [this comment](https://github.com/composer/composer/issues/7777#issuecomment-440268416) in the Composer thread on the topic.

Essentially what needs to be done is:

1. Restart cli.
2. Hit a decent "sample" of pages in your application.
3. Run the "hot loading" script (similar to what's in the comment, though that appears to be a little janky).
4. Have some place in Docksal that you can place this script (.docksal/services/cli/preload.php maybe?)
5. Restart cli, have the container detect and read in the preload script if it's available.

**Comment by lmakarov** [comment]
This is getting too much into the application area. We can preinstall extensions and fine tune PHP settings, but suggesting workflows/scripts that will warm up your application feels out of scope for Docksal.

**Comment by lpeabody** [comment]
Maybe we just add support for having a conventional place to put preload.php, but leave the "hot loader" script to Docksal addons? Feels like a core/contrib-ish relationship.

**Comment by lmakarov** [comment]
It feels very nuanced, something a very small amount of users will comprehend and use as it does require an extra script developed by the end user.

I wonder what hosting providers are doing/planning around this feature.

We can probably have it documented in the advanced use cases section on docs.docksal.io.

**Comment by lpeabody** [comment]
I think if documentation is the way we want to handle it that's fine, but I think we just need to make sure there are no technical barriers preventing Docksal users from leveraging preloading if they want to.

**Comment by achekulaev** [comment]
@lmakarov I see it as another quirk in PHP configuration similar to `php.ini` and `php-fpm.ini`. We just need to define the common place for `preload.php` in `.docksal/etc/php` and pre-load it when it exists. There is nothing else we need to do.

**Comment by lmakarov** [comment]
> We just need to define the common place for `preload.php` in `.docksal/etc/php` and have PHP pre-load it when it exists.

This can be done without additional modifications to the image. Just add in `.docksal/etc/php/php.ini`:

```
opcache.preload = /var/www/.docksal/etc/php/preload.php
```

@lpeabody what happens if `opcache.preload = /var/www/.docksal/etc/php/preload.php` is set but the file does not exist? If PHP will just ignore the directive and this does not cause any performance hits, then we can add this line in the default config and document the use case.

Also, from https://symfony.com/blog/new-in-symfony-4-4-preloading-symfony-applications-in-php-7-4

> Keep in mind that preloaded files remain cached in OPCache memory forever. If you change the source code of any preloaded file, you'll need to restart the web server or changes won't have any effect.

This really looks to be more useful for the hosting use case and not so much for local development.

**Comment by lmakarov** [comment]
> what happens if opcache.preload = /var/www/.docksal/etc/php/preload.php is set but the file does not exist?

The answer: https://github.com/docksal/service-cli/pull/163/commits/c5c125902e3f6254680cb07c5d74ad286ec2ad64. This build failed, which means a more sophisticated logic is necessary to check whether the `preload.php` file is in place or not.

IMO if someone wants preloading, they can add that one line in the project's `php.ini` overrides.

**Comment by lpeabody** [comment]
Yeah, you make several excellent points 😊 I was overthinking this one. Just always looking for ways to make things more convenient, but this would probably just end up being a pain for maintenance.

Is it worth documenting?

**Comment by achekulaev** [comment]
@lmakarov I would add it for marketing purposes. "More sophisticated logic" is basically a check for file exists.

**Comment by lmakarov** [comment]
> @achekulaev: I would add it for marketing purposes.
> @lpeabody: Is it worth documenting?

Preloading in PHP 7.4 is not a feature of Docksal.
If it required a challenging setup for the user, that we took care of in Docksal, then we could market it as a benefit. But for a single line in config + a custom `preload.php` (which we won't be handling anyway)... IMO a blog post about it with examples and results would be the best medium.

**Comment by achekulaev** [comment]
xdebug is not a feature of Docksal as well

**Comment by lmakarov** [comment]
> xdebug is not a feature of Docksal as well

xdebug falls into the "challenging setup for the user, that we take care of in Docksal" category.
As already figure out above, nothing in enabling preloading is challenging except the actual `preload.php` script, which is out of scope for Docksal anyway.

**Comment by achekulaev** [comment]
I see 0 reasons for you to be this conservative in this question

**Comment by lmakarov** [comment]
Since @sean-e-dietrich already implemented this check in https://github.com/docksal/service-cli/pull/163/commits/b8b9bfe928960ba42d47107e5cfcf37cd23a604d, there is no reason to continue this debate.
