### ISSUE TITLE
Xdebug not working after updating to 1.92.2 

### ISSUE THREAD

**Issue by awm086** [docksal/docksal#1249]
**Description**

Xdebug not working after updating to 1.92.2 

**Steps to reproduce the issue:**

1. Enable xdebug;  in docksal-local.env by setting `XDEBUG_ENABLED=1`
2. Setup a breakpoint a php file in phpstorm
3. Send a request in the browser

**Describe the results you received:**

no debugging session was started

**Comment by achekulaev** [comment]
Will be fixed in a hotfix release. Meanwhile use the workaround from this ticket https://github.com/docksal/docksal/issues/1238

**Comment by awm086** [comment]
`XDEBUG_CONFIG:remote_connect_back=0 remote_host=${DOCKSAL_HOST_IP} ` worked

**Comment by lmakarov** [comment]
@awm086 I'd recommend you update your project's config to use the latest docksal/cli image for the cli service: `image: docksal/cli:2.10-php7.1`. Alternatively, switch to using the default stack to receive automatic updates for image versions. See the conversation starting from this comment https://github.com/docksal/docksal/issues/1238#issuecomment-562670327

> `XDEBUG_CONFIG:remote_connect_back=0 remote_host=${DOCKSAL_HOST_IP}` worked

You won't need to override this with the latest docksal/cli image version.

**Comment by awm086** [comment]
Thanks, just curious, do you get notifications whenever an issue is posted? you guys reply before I finish editing the issue :)

**Comment by lmakarov** [comment]
Yep. Email and Slack =)

**Comment by lmakarov** [comment]
Fixed in 86c9ccd
