### ISSUE TITLE
fin project create ignores the http proxy env variables

### ISSUE THREAD

**Issue by weh** [docksal/docksal#1251]
**Description**
If you work behind a http/https proxy, and can not directly connect to the internet, you will not be able to use `fin project create`. It will fail to clone e.g. the Drupal 8 boilerplate repo on github.

If you have a existing Docksal project, or run `fin config generate` first, you can add your `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` variables to the `docksal-local.env`, or use it in `docksal-local.env`. But this does not work with `fin project create`.

**Steps to reproduce the issue:**

1. Setup a proxy and deny direct access to the internet
2. Set your system env variables (HTTP_PROXY,...)
3. run `fin project create`
4. select Drupal 8 to install

**Describe the results you received:**

```
Project software: Drupal 8
Source repo:      https://github.com/docksal/boilerplate-drupal8.git
Project URL:      http://not-gonna-happen.docksal

Do you wish to proceed? [y/n]: y
Cloning repository...
Cloning into 'not-gonna-happen'...
fatal: unable to access 'https://github.com/docksal/boilerplate-drupal8.git/': Failed to connect to github.com port 443: Connection refused
```

**Describe the results you expected:**

```
Project software: Drupal 8
Source repo:      https://github.com/docksal/boilerplate-drupal8.git
Project URL:      http://this-is-fine.docksal

Do you wish to proceed? [y/n]: y
Cloning repository...
Cloning into 'this-is-fine'...
remote: Enumerating objects: 22538, done.
remote: Counting objects: 100% (22538/22538), done.
remote: Compressing objects: 100% (18177/18177), done.
remote: Total 22538 (delta 4386), reused 11615 (delta 2826), pack-reused 0
Receiving objects: 100% (22538/22538), 22.67 MiB | 3.48 MiB/s, done.
Resolving deltas: 100% (4386/4386), done.
...
```

**Comment by achekulaev** [comment]
Thanks for contribution!
