### ISSUE TITLE
CODER IDE doesn't allow syntax highlighting or allow debugger breakpoints in files without .php extension

### ISSUE THREAD

**Issue by davekopecek** [docksal/docksal#1254]
CODER IDE does not do syntax highlighting or allow for X-DEBUG breakpoint selection for files that do not have *.php extension.  Saving codet/vscode settings.json results in permission error.
 
**Steps to reproduce the issue:**

1 Install Drupal8 compose site with `fin project create`
2. fin config set --env=local IDE_ENABLED=1
2. fin config set --env=local XDEBUG_ENABLED=1
3. Navigate to IDE, open index.php and any *.module file.
4. Notice no syntax highlighting in *.module. Breakpoints set in index.php, not other files
5. Try adding file associations to settings.json:
````
      "files.associations": {
        "*.inc": "php",
        "*.module": "php",
        "*.install": "php",
        "*.theme": "php",
        "*.tpl.php": "php",
        "*.test": "php",
        "*.php": "php"
      },  
````
6. Error message:
````
Failed to save 'settngs.json': Insufficient permissions. Select 'Retry as Sudo' to retry as superuser
````
7. Retry save fails.

**Comment by acondura** [comment]
I got the same issues. For now, I solved the permissions issue by:
- fin bash ide
- go to coder User dir to edit settings.json file, which is actually a
symlink.
- go to that symlink dir and chown to docker user.

Exit the ide container and you can now save the highlighting settings.
