### ISSUE TITLE
Docker for mac and xdebug

### ISSUE THREAD

**Issue by bladeaweb** [docksal/docksal#1256]
When I try to use docker for mac for my projects, I face of problem working with xdebug. When xdebug enabled. I have got too slow docker.
time fin drush cr
total: 1:57 m

With disabled xdebug the same command returns total: 0:22.5 m

Does anybody have solution how to fix this issue?

**Comment by lmakarov** [comment]
You can try NFS volumes with Docker for Mac:

```
fin config set DOCKSAL_VOLUMES=nfs
fin project reset
```

Note: switching volumes mode requires a full project reset, so make sure you backup your project's database (if applicable) before proceeded.

See [Shared Volumes](https://docs.docksal.io/core/volumes/) docs for more information.

Also, next time please include the diagnostic information when submitting a new issue:

- Output of `fin config`
- Output of `fin sysinfo`
