### ISSUE TITLE
Database connection issues (no route to host)

### ISSUE THREAD

**Issue by stenvdb** [docksal/docksal#1257]
I've got a question about the database connection. I just installed Docksal on pop!_os 19.10 (ubuntu based) and everything works. But I got some database issues I can't figure out.

On mysql workbench I can connect fine at 192.168.64.100 on port 33061
I have set the following in my docksal.env
`MYSQL_PORT_MAPPING='33061:3306'`

However the following doesn't work:
```
fin exec mysql -uroot -proot -P33061 -h192.168.64.100 -e "show variables like 'version'"
ERROR 2003 (HY000): Can't connect to MySQL server on '192.168.64.100' (113 "No route to host")
```

After a lot of trying I found out this does work:
```
fin exec mysql -uroot -proot -P3306 -hdb -e "show variables like 'version'"
+---------------+--------+
| Variable_name | Value  |
+---------------+--------+
| version       | 5.6.43 |
+---------------+--------+
```
My application also only works when setting the host and port to 'db' and '3306' , which I can't figure out because that's not what it should be.

the output of `fin ps` is:
```
            Name                         Command                State                        Ports                  
--------------------------------------------------------------------------------------------------------------------
gent-zuid-chilli-craft_cli_1   /opt/startup.sh supervisord   Up (healthy)   22/tcp, 0.0.0.0:3000->3000/tcp, 9000/tcp
gent-zuid-chilli-craft_db_1    docker-entrypoint.sh mysqld   Up (healthy)   0.0.0.0:33061->3306/tcp                 
gent-zuid-chilli-craft_web_1   httpd-foreground              Up (healthy)   443/tcp, 80/tcp      
```
This seems right to me, the port is set to 33061, yet I can only connect on this port using mysql workbench. It does not work in the cli or in the live application (via the browser).

Fyi: I have the project with identical docksal.env & docksal.yml files on a macbook pro running, with docker for mac, where it does work as expected.

**Comment by achekulaev** [comment]
`192.168.64.100` is your host computer localhost alias.
It is not visible form within `cli` container
`fin exec` executes commands inside `cli` container.
From inside the container it should talk directly to the `db` container by the hostname `db`.

Everything works as expected.
