### ISSUE TITLE
nodemon not reloading when file changes

### ISSUE THREAD

**Issue by ovangmbh** [docksal/docksal#1277]
I saw the possibility to use nodemon with docksal: https://docs.docksal.io/service/cli/override-command/

So I've created a yaml file like this: https://github.com/docksal/boilerplate-nodejs/blob/master/.docksal/docksal.yml

In the yaml file I had to remove the "cli_home:/home/docker" from the "volumes", else nodemon does not work.

nodemon is now running, but if I save the index.js file, nothing happens. If I go directly in the docker container and change the index.js file, nodemon reloads as expected.

There seems to be an issue with the mount?

Thanks for your help

**Comment by ovangmbh** [comment]
After hours I think I've solved it: with the parameter "--legacy-watch", see https://github.com/remy/nodemon#nodemon

**Comment by lmakarov** [comment]
File system watchers only work Linux or Docker Desktop for Mac. See https://docs.docksal.io/core/volumes/

In all other configuration you would have to use a file system polling mechanism/mode (which is what legacyWatch in nodemon does).
