### ISSUE TITLE
Remove adapters by IP 192.168.64.* and DHCP server before Machine creation

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#129]
We need to search for and remove adapters by IP 192.168.64.* DHCP server responsible for that network before machine creation to ensure that VM will get proper IP. Otherwise if adapter exists VM will get IP higher than *.64.100 and issues like #117 may happen.

**Comment by lmakarov** [comment]
@achekulaev is this still relevant?

**Comment by achekulaev** [comment]
Looks like this is a super edge case. Adapters are being removed during `fin vm remove`.
