### ISSUE TITLE
Using `multipass` instead of VirtualBox

### ISSUE THREAD

**Issue by macmladen** [docksal/docksal#1301]
Ubuntu released **MultiPass** https://multipass.run/ which they market as an **Instant Ubuntu VMs** _A mini-cloud on your Mac or Windows workstation._

They seem to use native Hypervisor for Windows and Mac.

I've installed it and launched a server with

```
$ multipass launch --name new --disk 10G --cpus 2 --mem 4G
$ multipass list
Name                    State             IPv4             Image
new                     Running           192.168.65.4     Ubuntu 18.04 LTS
```
(we have to specify larger disk and more memory than default 5GB disk and 1GB memory)

Installation of **docksal** is finished successfully, started and it is working:
```
$ fin system status
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
0c59c17fd443        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   28 minutes ago      Up 28 minutes (healthy)                                                            docksal-ssh-agent
6ad686678d13        docksal/dns:1.1           "docker-entrypoint.s…"   28 minutes ago      Up 28 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
d41869e52d2a        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   28 minutes ago      Up 28 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

$ sudo lsof -i -P -n | grep LISTEN
systemd-r  782 systemd-resolve   13u  IPv4  15588      0t0  TCP 127.0.0.53:53 (LISTEN)
sshd      1081            root    3u  IPv4  18728      0t0  TCP *:22 (LISTEN)
sshd      1081            root    4u  IPv6  18734      0t0  TCP *:22 (LISTEN)
docker-pr 2412            root    4u  IPv4  24168      0t0  TCP 192.168.64.100:443 (LISTEN)
docker-pr 2439            root    4u  IPv4  24772      0t0  TCP 192.168.64.100:80 (LISTEN)

$ cd Sites/wp/
$ fin start
Starting services...
Creating network "wp_default" with the default driver
Starting wp_db_1  ... done
Starting wp_cli_1 ... done
Starting wp_web_1 ... done
Connected vhost-proxy to "wp_default" network.
Waiting for project stack to become ready...
Project URL: http://wp.docksal
```
So far everything works inside VM as expected. But the name inside VM is not resolving:
```
$ curl wp.docksal
curl: (6) Could not resolve host: wp.docksal
$ ping 192.168.64.100
PING 192.168.64.100 (192.168.64.100) 56(84) bytes of data.
64 bytes from 192.168.64.100: icmp_seq=1 ttl=64 time=0.076 ms
64 bytes from 192.168.64.100: icmp_seq=2 ttl=64 time=0.055 ms
c64 bytes from 192.168.64.100: icmp_seq=3 ttl=64 time=0.089 ms
64 bytes from 192.168.64.100: icmp_seq=4 ttl=64 time=0.101 ms
^C
--- 192.168.64.100 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3187ms
rtt min/avg/max/mdev = 0.055/0.080/0.101/0.018 ms
```
Once I added the IP to `hosts` file, `curl` showed it works
```
$ curl wp.docksal
<!DOCTYPE html>

<html class="no-js" lang="en-US">
```
But I had no idea how to make the browser see that site, adding IP of the VM did not help just as it didn't work inside VM.

I can assume that there is something I am missing (and not knowing) to make this option work but it seems to me like a better virtualization technology than VirtualBox or Native Docker (or I may be wrong).

**Comment by achekulaev** [comment]
I have investigated multipass option already. On Mac it's hard to tell if using xhyve is better than Vbox, different tests are needed and results are far from obvious. But in any case on Windows multipass uses Hyper-V, just like Docker Desktop. If we used multipass instead of VBox, then Windows users would not be able to use Vagrant alongside with Docksal, which seems to be quite an often setup.

Regarding your case. When you set up Docksal with VirtualBox you install `fin` on your host machine, and `fin` sets up certain IP for VM (for network routing purposes), and configures name resolution on your host FOR the `.docksal` domain, binding it to that VM.

Here you set up VM yourself, so your host has no idea about it. 

The easiest way would be to treat it like a remote server that you installed somewhere, in which case you can follow this guide:
https://blog.docksal.io/installing-docksal-on-a-remote-server-digital-ocean-scaleway-etc-ed0c230ddb82

**Comment by macmladen** [comment]
You are doing such amazing work and I admire you for that.

This would be also a useful hint to use it for staging (I am not daring to say even live server) so I would suggest adding this to Docksal documentation, just the section **Expose Docksal to the outer world**, maybe with that name.

The other thing, **resolving**, is dependent on an actual situation:

1. For some kind of a local VM name resolution, **dnsmasq** can be used which can provide wildcard extension resolution to some IP for that machine
2. For some local LAN resolution, some smart router or `avahi` based solution would be needed,
3. For remote server, some real wildcard DNS solution is needed e.g. **my-stage.com** and then use a particular project name like `VIRTUAL_HOST="demo.my-stage.com"`. IP and xip.io service would work only if there is just one site if I'm correct.
