### ISSUE TITLE
Docker can't find/write in a folder /opt on OS X Catalina

### ISSUE THREAD

**Issue by khalld** [docksal/docksal#1315]
Hello, i need to create my maria-db container when i try to force with
docker service scale mariadb=1

I have this message
`invalid mount config for type "bind": bind source path does not exist: /op…`
but the path exist.
I declared on my db-compose
` - /opt/mariadb-data:/var/lib/mysql `

if i do ls -la inside /opt folder i see that have the permission of writing:

`drwxrwxrwx   2 777     wheel   64 23 Apr 20:10 mariadb-data`

if i use on my db-compose another folder it works but i need to put it under /opt.

Some help?

**Comment by lmakarov** [comment]
Disclaimer: what you are trying to do is have your databases reside on a VERY slow (considering DB engine filesystem demands) medium. Volumes from the host machine are mounted via either osxfs (Docker for Mac) or NFS (VirtualBox / Docker for Mac).

---

`/opt/mariadb-data:/var/lib/mysql` = mount `/opt/mariadb-data` on **the Linux VM** (which runs the Docker engine) into `/var/lib/mysql` in the container.

`/opt/mariadb-data` is not automatically mapped from the your Mac into the VM.

With VirtualBox, only `/Users` is mapped fro Mac to VM.

With Docker for Mac, you can map more host directories. Open **File Sharing** options in the Docker for Mac application preferences and add `/opt` to the list.

![image](https://user-images.githubusercontent.com/1205005/80872855-7aec9080-8c69-11ea-9a2f-18e668e1b83d.png)


Take a look at the volumes docs to get a better understanding of how file sharing and volumes work: https://docs.docksal.io/core/volumes/
