### ISSUE TITLE
Detecting which processes use ports on the host

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#1348]
# Symptoms 

```
docker: Error response from daemon: Ports are not available: listen udp 0.0.0.0:53: bind: address already in use.
 ERROR:  Failed starting the DNS service.
```

```
docker: Error response from daemon: Ports are not available: listen tcp 0.0.0.0:80: bind: address already in use.
 ERROR:  Failed starting the Failed starting the proxy service.
```

```
docker: Error response from daemon: Ports are not available: listen tcp 0.0.0.0:443: bind: address already in use.
 ERROR:  Failed starting the Failed starting the proxy service.
```

# Diagnostics and fixing

### UDP/53

Port **53** will likely be used by a local dnsmasq instance. You may not even remember installing it.

Check which process uses UDP port 53:

```
$ netstat -vanp udp | awk '$4 ~ /\.53$/' | awk '{print $8}' | xargs ps -p
  PID TTY           TIME CMD
  140 ??         0:00.01 /usr/local/opt/dnsmasq/sbin/dnsmasq --keep-in-foreground -C /usr/local/etc/dnsmasq.conf
```

Use the following instructions to install/uninstall dnsmasq:
https://gist.github.com/valentinocossar/c92abb39ffa0ba1eaf08466e35b85d11

### TCP/80 and TCP/443

Ports **80/443** are web server ports and will likely be used by a local Apache/etc. instance:

Check which process uses TCP ports 80/443

```
$ netstat -vanp tcp | awk '$4 ~ /\.80$/' | awk '{print $9}' | xargs ps -p
$ netstat -vanp tcp | awk '$4 ~ /\.443$/' | awk '{print $9}' | xargs ps -p
```

## Windows

TDB

---

Please post details in comments if you ran into this issue and how use resolved it.

**Comment by icasimpan** [comment]
Hi,

I'm on MacOS Catalina (10.15.5) and I don't have dnsmasq installed:
```
~$ netstat -vanp udp | awk '$4 ~ /\.53$/' | awk '{print $8}' | xargs ps -p
  PID TTY           TIME CMD
 6652 ??         3:23.14 /usr/sbin/mDNSResponder
```
Attempting to unload mDNSResponder is prohibited by System Integrity Protection:
```
~$ sudo launchctl unload -w  /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist
Password:
/System/Library/LaunchDaemons/com.apple.mDNSResponder.plist: Operation not permitted while System Integrity Protection is engaged
```

It's possible to disable SIP from https://www.howtogeek.com/230424/how-to-disable-system-integrity-protection-on-a-mac-and-why-you-shouldnt/ but I didn't attempt it yet. Maybe the project should think about using non-standard ports instead.

**Comment by icasimpan** [comment]
Adding this reference https://www.ddev.com/ddev-local/open-source-collaboration-signing-tools-for-macos-catalina/ as that might help fix the problem.

**Comment by achekulaev** [comment]
@lmakarov close?
