### ISSUE TITLE
image operating system "linux" cannot be used on this platform

### ISSUE THREAD

**Issue by jack1590** [docksal/docksal#1358]
Hi, 
I'm trying to follow the windows intallation guide but. when I execute 
DOCKER_NATIVE=1 bash <(curl -fsSL https://get.docksal.io) I'm getting 
docker: Error response from daemon: invalid mount config for type "volume": invalid mount path: '/projects'.
See 'docker run --help'.
 ERROR:  Failed starting the proxy service.

![image](https://user-images.githubusercontent.com/4235324/83364816-9da5be00-a369-11ea-8ba7-3ddcef74e1bb.png)

Any clue on this?

**Comment by lmakarov** [comment]
```
image operating system "linux" cannot be used on this platform
```

You are running Docker Desktop in "Windows container" mode. You will have to switch to Linux containers to use Docksal.
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

**Comment by jack1590** [comment]
Thanks, solved
