### ISSUE TITLE
Fix README.md links

### ISSUE THREAD

**Issue by vstanchev** [docksal/docksal#136]
Going to https://github.com/docksal/docksal and clicking on the first link "Docksal environment setup" shows a page not found at http://docksal.readthedocs.io/en/master/getting-started/env-setup
Same for the "Setup instructions" link

**Comment by lmakarov** [comment]
We use the `develop` branch by default on github, however documentation links point to the master on readthedocs. In the new release there were changes to the docs outline, thus there was a period when links were not matching. The new release has been rolled-out today and the URLs should be all good now.
