### ISSUE TITLE
Is it possible to use Parallels Desktop instead of VirtualBox?

### ISSUE THREAD

**Issue by josefglatz** [docksal/docksal#1360]
I wonder if it is possible to use Parallels Desktop Pro/Business instead of VirtualBox.

I know Docker Desktop for Mac is recommended, but I always had more performant apps running with Parallels (e.g. a ubuntu Docker host provisioned with Vagrant, Ansible).

Would really love know if that is possible anyhow with Docksal.

Thanks in advance,
Josef

**Comment by lmakarov** [comment]
There are currently no plans to support Parallels. This is unlikely to happen in the future either. There is just too much overhead involved in supporting various hypervisors across multiple operating systems.

Additionally, [boot2docker is EOL](https://github.com/boot2docker/boot2docker/releases/tag/v19.03.5), which means anything but Docker Desktop will be [supported longterm](https://github.com/docksal/docksal/issues/1361).

That said, you can always install a Linux distribution manually in Parallels and then install Docksal there, use the [Coder integration](https://docs.docksal.io/tools/ide/) to work with code inside the Linux/dockerized environment. This does change your workflow and how you interact with your codebase and may not be a suitable solution. At the same time, this would be the most performant solution you can get on a non-Linux environment.

**Comment by achekulaev** [comment]
You can definitely install Ubuntu VM in Parallelrs and use Docksal inside the VM.

**Comment by josefglatz** [comment]
Thank you folks for your answers!
