### ISSUE TITLE
macOS Catalina (10.15.5) has port conflict with httpd

### ISSUE THREAD

**Issue by jacobsaw** [docksal/docksal#1364]
**Description**

After upgrading to 10.15.5, received `docker: Error response from daemon: Ports are not available: listen tcp 0.0.0.0:80: bind: address already in use.`.

Inspected and noticed that the `httpd` process was using 80 after the upgrade, disabled to resolve the issue.

**Steps to reproduce the issue:**

1. Upgrade to macOS 10.15.5
2. Attempt to run `fin project start`

**Describe the results you received:**

`docker: Error response from daemon: Ports are not available: listen tcp 0.0.0.0:80: bind: address already in use.`

**Describe the results you expected:**

Project would start without conflict

**Comment by jacobsaw** [comment]
Command for disabling httpd `sudo launchctl unload -w /System/Library/LaunchDaemons/org.apache.httpd.plist`

**Comment by achekulaev** [comment]
That's [expected](https://github.com/docksal/docksal/releases/tag/1.13.3).
