### ISSUE TITLE
TTY requirement

### ISSUE THREAD

**Issue by vstanchev** [docksal/docksal#137]
When installing Docksal in an Ubuntu 14.04 LXC container the install_tools_ubuntu() function silently returns, because the is_tty() function returns non-zero. This is because when running ```$ lxc exec docksal -- bash``` to attach to the container named docksal, we're not on a tty.
As a workaround run ```$ lxc exec docksal -- sh -c "exec >/dev/tty 2>/dev/tty </dev/tty && bash"```
Another workaround is to connect to the container via ssh.

I think it's good to add an LXC section somewhere in the docs or just echo a warning in install_tools_ubuntu()

**Comment by achekulaev** [comment]
Thanks doing the full investigation cycle. I'll append a warning.
