### ISSUE TITLE
Docs: Local trusted HTTPS certs using mkcert

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#1370]
Document mkcert addon - https://github.com/docksal/addons/tree/master/mkcert

Demo: https://asciinema.org/a/344708

Scope:

- [x] https://docs.docksal.io/fin/addons (update - include mkcert in the list, add a section for global addons)
- [x] https://docs.docksal.io/tools/mkcert (add new)
- [ ] Write a blog post for https://blog.docksal.io/

Related:

- https://github.com/docksal/docksal/issues/498
- https://github.com/docksal/service-vhost-proxy#default-and-custom-certs-for-https

**Comment by shelane** [comment]
@lmakarov You would like a new page created in tools for an addon? All of the other tools listed are tools that are included in the cli or have a boilerplate project.

**Comment by shelane** [comment]
BTW, I installed it and got this message:
```
Created a new local CA at "/Users/french/Library/Application Support/mkcert" 💥
The local CA is now installed in the system trust store! ⚡️
Warning: "certutil" is not available, so the CA can't be automatically installed in Firefox! ⚠️
Install "certutil" with "brew install nss" and re-run "mkcert -install" 👈
```

Not sure why a non-OS standard package is required.

**Comment by lmakarov** [comment]
> You would like a new page created in tools for an addon? All of the other tools listed are tools that are included in the cli or have a boilerplate project.

That's a good observation. We do have an integration for which have both a community addon and a page in docs for manual setup - https://docs.docksal.io/tools/phpmyadmin/

I guess, we could approach mkcert in a similar fashion, since addon maintenance and updates are not guaranteed.

> BTW, I installed it and got this message...

mkcert docs mention [this for macOS installation](https://github.com/FiloSottile/mkcert#macos):

```
brew install mkcert
brew install nss # if you use Firefox
```

In the docs, we can ask the user to manually install mkcert on their platform and then provide instructions on how to generate and install certs for a project

This is the meat of it:

```bash
# generate cert for a project
$ fin debug -c 'mkdir -p ${CONFIG_CERTS}; mkcert -key-file ${CONFIG_CERTS}/${VIRTUAL_HOST}.key -cert-file ${CONFIG_CERTS}/${VIRTUAL_HOST}.crt *.${VIRTUAL_HOST} ${VIRTUAL_HOST}'
# reset vhost-proxy to pick-up the new cert
$ fin system reset vhost-proxy
```
