### ISSUE TITLE
Mac Os virtual box

### ISSUE THREAD

**Issue by MohamedMamdouh98** [docksal/docksal#1372]
I followed some instructions on how to set a Mac os virtual machine, and everything went as expected until the apple icon showed up and the os started installing. Right after the installation, a black screen showed that error.
- reference screenshot to the error: https://1drv.ms/u/s!Ak0GKWJEKPFxieAZSDmlLMl-3ma8lg?e=hNgH17

- that's the link to the instructions I followed: https://www.makeuseof.com/tag/macos-windows-10-virtual-machine/

**Comment by lmakarov** [comment]
This does not seem to be related to [Docksal](https://github.com/docksal/docksal).
