### ISSUE TITLE
Privileged system containers

### ISSUE THREAD

**Issue by vstanchev** [docksal/docksal#138]
When running ```$ fin reset system``` inside an Ubuntu 14.04 LXC container I got the following error 
```
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_l
inux.go:291: setting cgroup config for ready process caused \\\"failed to write a *:* rwm to devices.allow: write /sys/fs/cgroup/devices/docker/261311e7
33ab80251b011c645128e908599a95d806c0660c84fb8c93d9ac990e/devices.allow: operation not permitted\\\"\"\n".
```

However when I removed the ```--privileged``` flag from ```/usr/local/bin/fin``` on [line 1992](https://github.com/docksal/docksal/blob/develop/bin/fin#L1992), [line 2014](https://github.com/docksal/docksal/blob/develop/bin/fin#L2014) and [line 2064](https://github.com/docksal/docksal/blob/develop/bin/fin#L2064) and then ```fin reset system``` everything worked fine.

Is there any particular reason why docksal-ssh-agent, docksal-dns, docksal-vhost-proxy are created with the --privileged option?

**Comment by lmakarov** [comment]
@vstanchev the change originated a while back [here](https://github.com/blinkreaction/dde/issues/105) to give the vhost-proxy access to the `docker.sock`. The two other system services do not need access to `docker.sock`, so those can be updated to not run as privileged.

In fact, I've just run [tests](https://travis-ci.org/docksal/service-vhost-proxy/builds/208639080) and it looks like the vhost-proxy does not need those either for all of it's use cases :)

Thanks for bringing this up. I'm going to remove `--privileged --userns=host` from all3 system services.
