### ISSUE TITLE
Docker Compose configuration file not found at the expected location

### ISSUE THREAD

**Issue by davekopecek** [docksal/docksal#14]
Hi -

I can make the drupal7 and drupal8 test projects run, but am getting `Docker Compose configuration file not found at the expected location` for other projects.  Here's a transcript with a simple site with a hello-world html file:

```
{ projects }  » mkdir hello                                                           /c/projects
{ projects }  » mkdir hello/docroot                                                   /c/projects
{ projects }  » cp ~/hello.html ./hello/docroot/index.html                            /c/projects
{ projects }  » cd hello                                                              /c/projects
{ hello }  » git init                                                           /c/projects/hello
Initialized empty Git repository in /cygdrive/c/projects/hello/.git/
{ hello } HEAD » git add -A                                                     /c/projects/hello
{ hello } HEAD » git commit -m "Initial Commit"                                 /c/projects/hello
[master (root-commit) 88e04dc] Initial Commit
 1 file changed, 13 insertions(+)
 create mode 100644 docroot/index.html
{ hello } master » fin install docksal-config                                   /c/projects/hello
[!] Using Docksal develop branch
Latest version of docker-compose.yml was downloaded.
{ hello } master » fin up                                                       /c/projects/hello
Docker Compose configuration file not found at the expected location:
/docker-compose.yml
{ hello } master » cd docroot                                                 /c/projects/hello 1
{ docroot } master » fin up                                             /c/projects/hello/docroot
Docker Compose configuration file not found at the expected location:
/docker-compose.yml
```

I'm also getting the same error when docroot has a full drupal site copied from a working drude install.  I can confirm that `fin install docsal-config` did pull down docker-compose.yml:

```
{ hello } master » ls                                                           /c/projects/hello
docker-compose.yml  docroot
{ hello } master »  
```

**Comment by lmakarov** [comment]
Quick fix - run `mkdir .docksal` in the project directory.

We are shifting towards storing everything Docksal related (including the compose files(s)) in the `.docksal` directory. This directory is then used to search for and identify the project root.

We still figuring out the necessary messaging and process for setting up new projects or migrating from the existing Drude projects.

**Comment by davekopecek** [comment]
Works. Thank you

You might want to add `mkdir .docsal` to 
https://github.com/docksal/docksal/blob/develop/docs/project-setup.md

>>We still figuring out the necessary messaging and process for setting up new projects or migrating from the existing Drude projects.

I've got several projects to convert. Happy to test anything you've got in the works.

**Comment by achekulaev** [comment]
I need to actually add `mkdir .docksal` to `config-install`

**Comment by achekulaev** [comment]
Resolved by two things
1. zero configuration setup. just create `.docksal` directory and you're done
2. `fin config generate` for more sophisticated setup
