### ISSUE TITLE
When creating a new project Drupal 9 is using Drupal 9 blt

### ISSUE THREAD

**Issue by gheydon** [docksal/docksal#1408]
**Description**

When create a fresh project if you select option 3 for a basic version of Drupal 9 

**Steps to reproduce the issue:**

1. create fresh directory
2. run `fin project create`
3. choose option 3

**Describe the results you received:**

```
Enter your choice (0-18): 3

Project folder:   /Users/gordon/Source/drupal/head/head
Project software: Drupal 9 (BLT Version)
Source repo:      https://github.com/docksal/boilerplate-drupal9-blt.git
Project URL:      http://head.docksal
```

**Describe the results you expected:**

Enter your choice (0-18): 3

Project folder:   /Users/gordon/Source/drupal/head/head
Project software: Drupal 9
Source repo:      https://github.com/docksal/boilerplate-drupal9.git
Project URL:      http://head.docksal

The problem is in the target repo select on about line 3253 the cases for Drupal 9 BLT and Drupal 9 are setting the wrong values.

**Comment by shelane** [comment]
Yep. I see that. Thanks.
