### ISSUE TITLE
Docksal drush updb error: Bootstrap failed

### ISSUE THREAD

**Issue by hollyhw15** [docksal/docksal#1416]
**Description**

Hi, I have a current druple project(using mysql) which always fail at "drush updb" step.  I have tried different approaches with my local druple project which were all failed. 

I created a sample druple 7 project and failed at the same step.  I expect sample druple 7 comes with docksal can pass the "drush updb" smoothly. Not sure what should I do to pass this step. seems like sample druple 7 project doesn't use mysql database. 

**Steps to reproduce the issue:**

1. in Ubuntu shell, "fin project create" and select 7 to create a druple 7 project
2. project was created fin project create and I can curl/ping my test project to get response 
$  curl http://testdruple.docksal 
$ ping testdruple.docksal
PING testdruple.docksal (192.168.64.100) 56(84) bytes of data.

3. run into error while do "drush updb" in both project path and docroot path. 
same error with "drush updb" and "drush updb --root=project root --uri=http://myproject" 

$/mnt/c/projects/testdruple$ drush updb
$/mnt/c/projects/testdruple/docroot$ drush updb
$/mnt/c/projects/testdruple/docroot$ drush updb --uri=http://testdruple.docksal --root=/mnt/c/projects/testdruple/ -vvv
[Exception]
Bootstrap failed. Run your command 

**Describe the results you received:**
run into error while do "drush updb"
Drush status provided in detail

<details>

/mnt/c/projects/testdruple$ drush status
 PHP binary    : /usr/bin/php7.4
 PHP config    : /etc/php/7.4/cli/php.ini
 PHP OS        : Linux
 Drush script  : /usr/local/src/drush/drush
 Drush version : 10.2.2
 Drush temp    : /tmp
 Drush configs : /usr/local/src/drush/drush.yml

hollyw@ITS-HWANG-LT:/mnt/c/projects/testdruple/docroot$ drush --version
Drush Commandline Tool 10.2.2

hollyw@ITS-HWANG-LT:/mnt/c/projects/testdruple/docroot$ drush updb --uri=http://testdruple.docksal --root=/mnt/c/projects/testdruple/ -vvv
 [preflight] Config paths: /usr/local/src/drush/drush.yml
 [preflight] Alias paths:
 [preflight] Commandfile search paths: /usr/local/src/drush/src
 [debug] Starting bootstrap to full [0.05 sec, 9.66 MB]

In BootstrapHook.php line 32:

  [Exception]
  Bootstrap failed. Run your command with -vvv for more information.

Exception trace:
  at /usr/local/src/drush/src/Boot/BootstrapHook.php:32

</details>

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

/mnt/c/projects/testdruple/docroot$ fin config
---------------------
COMPOSE_PROJECT_NAME_SAFE: testdruple
COMPOSE_FILE:
/home/hollyw/.docksal/stacks/volumes-bind.yml
/home/hollyw/.docksal/stacks/stack-default.yml
/mnt/c/projects/testdruple/.docksal/docksal.yml
ENV_FILE:
/mnt/c/projects/testdruple/.docksal/docksal.env

PROJECT_ROOT: /mnt/c/projects/testdruple
DOCROOT: docroot
VIRTUAL_HOST: testdruple.docksal
VIRTUAL_HOST_ALIASES: *.testdruple.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: testdruple.docksal
      GIT_USER_EMAIL: ''
      GIT_USER_NAME: ''
      HOST_GID: '1000'
      HOST_UID: '1000'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_ACQUIACLI_KEY: null
      SECRET_ACQUIACLI_SECRET: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: testdruple.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.11-php7.3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /home/hollyw/.docksal/tmp/testdruple:/home/hollyw/.docksal/tmp/testdruple:ro
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.5
    logging:
      options:
        max-file: '10'
        max-size: 1m
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /mnt/c/projects/testdruple
      io.docksal.virtual-host: testdruple.docksal,*.testdruple.docksal,testdruple.docksal.*
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /mnt/c/projects/testdruple
      o: bind
      type: none

---------------------

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  fin sysinfo
███  OS
Linux Ubuntu 20.04
Linux ITS-HWANG-LT 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel
DOCKER_HOST :

███  FIN
fin version: 1.99.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.26.0
docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

███  DOCKER
EXPECTED CLIENT VERSION: 19.03.9
EXPECTED SERVER VERSION: 19.03.9

Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
project             STATUS                    virtual host                                                   project root
testdruple          Up 18 minutes (healthy)   testdruple.docksal,*.testdruple.docksal,testdruple.docksal.*   /mnt/c/projects/testdruple

███  DOCKSAL: VIRTUAL HOSTS
*.testdruple.docksal
testdruple.docksal.*
testdruple.docksal

███  DOCKSAL: NETWORKING

DOCKSAL_IP: 192.168.64.100
DOCKSAL_VHOST_PROXY_IP:
DOCKSAL_DNS_IP:
DOCKSAL_DNS_DISABLED: 0
DOCKSAL_NO_DNS_RESOLVER: 0
DOCKSAL_DNS_UPSTREAM:
DOCKSAL_DNS_DOMAIN: docksal

Checking connectivity to http://dns-test.docksal...
Host: PASS
Containers: PASS

</details>

**Comment by achekulaev** [comment]
You did not include what error you have exactly. Will reopen once added

**Comment by hollyhw15** [comment]
Hi, I added error in the content and also in the title. Please reopen it. Thank you

**Comment by achekulaev** [comment]
You need to specify what folder you run the command in. Bootstrap failed is vary vague error.

**Comment by hollyhw15** [comment]
Thank you, folder information and drush status information provided.

**Comment by achekulaev** [comment]
I see that as per your log `drush updb` runs perfectly in docroot my friend. 

```
$/mnt/c/projects/testdruple/docroot$ drush updb
```

You just have no updates to run. 

But It does not run properly when you run in the incorrect folder or manually specify incorrect root of course. It has nothing to do with Docksal. You're using the tool wrong.
