### ISSUE TITLE
documentation question: is there a documented way to do wordpress multisite with docksal?

### ISSUE THREAD

**Issue by icasimpan** [docksal/docksal#1428]
Hi,

I searched and so far didn't find any for wordpress multi-site installation. Any hints on how to do it with docksal?

Thanks.

**Comment by lmakarov** [comment]
There are no official docs or boilerplates for Wordpress multi-site with Docksal.

There are [docs](https://docs.docksal.io/use-cases/drupal-multisite/) and a [sample repo](https://github.com/docksal/boilerplate-drupal7-advanced) for Drupal multisite, which may give some hints.

Apart from the application logic in Wordpress (or anything else), the most important consideration for a multisite setup at the Docksal stack configuration level would be support for multiple/custom domains per project. Docs for that are [here](https://docs.docksal.io/core/system-vhost-proxy/#using-arbitrary-custom-domains).

**Comment by sean-e-dietrich** [comment]
The biggest issue when doing the multisite is having redirect loops happen. The fix to this is to adjust the .htaccess file. This can be done by following the directions on WordPress.org

https://wordpress.org/support/article/htaccess/#multisite
