### ISSUE TITLE
Any plans to support Podman allowing for rootless docker containers in multi-user environments?

### ISSUE THREAD

**Issue by hillier1** [docksal/docksal#1429]
**Description**
We have several multi-user linux environments (RHEL 7/8 mostly) where we leverage Podman to allow for users to run docker containers without granting root access. Are there any plans for docksal to support running with Podman (https://podman.io/) or something like it to enable this?

Thanks in advance.
-Jeff

**Comment by lmakarov** [comment]
@hillier1 no plans at the moment, though thanks for bringing this up.

For now, Docker and Docker Compose are still the golden standards for simple container orchestration on a single node (local environment). We'll see how the container ecosystem evolves in the next year or so before looking into massive changes in the architecture for Docksal.

**Comment by kamal2222ahmed** [comment]
now that we have:
here is a snippet from Docker:
It remains free for small businesses (fewer than 250 employees AND less than $10 million in annual revenue), personal use, education, and non-commercial open source projects.
It requires a paid subscription (Pro, Team or Business), for as little as $5 per user per month, for professional use in larger businesses.
The effective date of these terms is August 31, 2021. There is a grace period until January 31, 2022 for those that will require a paid subscription to use Docker Desktop.
Are you taking a second look at this?

**Comment by lmakarov** [comment]
See #1570 and #1567.
