### ISSUE TITLE
Use head branch or add option for branch when using a custom git url for "project create"

### ISSUE THREAD

**Issue by acouch** [docksal/docksal#1435]
**Description**

Currently docksal defaults to and requires [master](https://github.com/docksal/docksal/blob/develop/bin/fin#L3398) when using a custom git url for ``project create``.

Using the HEAD branch for the custom git url or adding an option for the remote branch would allow users to start a project with a remote URL that does not contain or does not use ``master``. Github has deprecated use of the word ``master``. 

**Steps to reproduce the issue:**

1. ``fin project create``
2. Select "  Custom
    0. Custom git repository"
3. Enter project that does not contain a ``master`` branch

**Describe the results you received:**

```
Cloning into 'test-project'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
```

I'd be willing to create a PR if the maintainers would like to move on this.

**Comment by lpeabody** [comment]
I think its a reasonable addition. What would the UX look like here? I imagine, in addition to specifying the repository, it would also prompt for the branch (with a default of `master`).
