### ISSUE TITLE
Document vhost-proxy routing to an arbitrary service port

### ISSUE THREAD

**Issue by miroslav-lee** [docksal/docksal#1440]
> Had similar need recently and this is how to add entries to hosts file via `docksal.yml`:
> 
> ```
> version: "2.1"
> 
> services:
>   # CLI
>   cli:
>     extends:
>       file: ${HOME}/.docksal/stacks/services.yml
>       service: cli
>     extra_hosts:
>       - "www.example.com:127.0.0.1"
>       - "example.com:127.0.0.1"
> ```

But if I have a port in the host?
```
       - "www.example.com:9200:127.0.0.1"
```
It doesn't work

_Originally posted by @miroslav-lee in https://github.com/docksal/docksal/issues/1102#issuecomment-731961505_

**Comment by lmakarov** [comment]
@miroslav-lee `extra_hosts` is a docker-compose parameter that injects records into container's `/etc/hosts` file for custom DNS resolution. DNS has no concerns over service ports.

In Docksal, you can have a virtual-host (`my-service.my-project.docksal`, `HTTP` (port `80`) and `HTTPS` (port `443`)) routed to a service running on an arbitrary port in a container using the `io.docksal.virtual-host` and `io.docksal.virtual-port` labels on the service container.

Here's an example from the MailHog service definition in `services.yml`:

https://github.com/docksal/docksal/blob/9ab42e612fa6d21b03f9595b0c061ac1867761e3/stacks/services.yml#L272-L288

You host machine as well as containers will be able to access that virtual-host endpoint.

Is that what you are looking for?

**Comment by lmakarov** [comment]
I realized that we don't have this documented well. We only have dry explanations for [io.docksal.virtual-host](https://docs.docksal.io/stack/configuration-labels/#io-docksal-virtual-host) and [io.docksal.virtual-port](https://docs.docksal.io/stack/configuration-labels/#io-docksal-virtual-port) in the docs. Will need a documentation update effort to clarify this use case.

**Comment by lmakarov** [comment]
ping @shelane
