### ISSUE TITLE
Random documentation issues

### ISSUE THREAD

**Issue by paulsheldrake** [docksal/docksal#1447]
### Is read the docs no longer available?
http://docksal.readthedocs.io/en/master/getting-started/env-setup/  is now 404'ing

If yes, is it possible to set a redirect?  I had notes in project READMEs that reference readthedocs.io that are now broken

### Version specific documentation showing in search results
<img width="583" alt="Screen Shot 2020-12-18 at 6 12 19 AM" src="https://user-images.githubusercontent.com/1062456/102624015-46462000-40f8-11eb-8780-7c6fc6313dbf.png">

Is that planned?   Would be nice to have a consistent subdomain and then a version switching dropdown within the docs themselves

### Spelling
Docksal is spelled wrong on the main site on the installation page https://docksal.io/installation#macos-virtualbox
`Start Dosksal`

**Comment by shelane** [comment]
There is a consistent domain for the master. https://docs.docksal.io/ The link to the different doc versions is available in the menu on the left. https://docs.docksal.io/versions/

**Comment by lmakarov** [comment]
> Is read the docs no longer available?

http://docksal.readthedocs.io has long been gone.
We had a redirect in place for a year or two before deleting the repo on RTD.

I've restored it and added a page redirect from 

- http://docksal.readthedocs.io/en/master/getting-started/setup/ 
- http://docksal.readthedocs.io/en/master/getting-started/env-setup/ 

to https://docs.docksal.io/getting-started/setup/.

I realize these URLs are likely mentioned in a bunch of early adopter repos.

> Version specific documentation showing in search results

I'll see what can be done at the build/hosting side.

Thanks for bringing these up @paulsheldrake.
