### ISSUE TITLE
Unable to share VPN connection inside a container

### ISSUE THREAD

**Issue by mikecrittenden** [docksal/docksal#1451]
My company hosts some NPM packages at a private hostname that's VPN protected. I can access this fine from the host:

```
❯ curl -I https://PRIVATEDOMAINHERE/
HTTP/1.1 200 OK
ETag: W/"878-1555837839000"
Date: Tue, 22 Dec 2020 16:59:34 GMT
Last-Modified: Sun, 21 Apr 2019 09:10:39 GMT
Content-Type: text/html
Content-Length: 878
X-Varnish: 1040679107 1040515943
Age: 393
Via: 1.1 varnish (Varnish/6.0)
X-Cache: HIT
X-Varnish-Node: PRIVATEDOMAINHERE
Accept-Ranges: bytes
```

But within the cli container it fails:

```
❯ fin run curl -I https://PRIVATEDOMAINHERE/
curl: (6) Could not resolve host: PRIVATEDOMAINHERE
```

Note that it works fine from a throwaway non-Docksal-managed container:

```
❯ docker run --rm -it node curl -I https://PRIVATEDOMAINHERE
HTTP/1.1 200 OK
ETag: W/"878-1555837839000"
Last-Modified: Sun, 21 Apr 2019 09:10:39 GMT
Content-Type: text/html
Content-Length: 878
Date: Tue, 22 Dec 2020 17:06:33 GMT
X-Varnish: 348238010 348532080
Age: 83
Via: 1.1 varnish (Varnish/6.0)
X-Cache: HIT
X-Varnish-Node: PRIVATEDOMAINHERE
Accept-Ranges: bytes
```

Note that I did follow the instructions here: https://docs.docksal.io/troubleshooting/vpn/

Any thoughts on what the issue could be here?

**Comment by lpeabody** [comment]
@mikecrittenden I think we'll be able to get some eyes on this early after the holidays.

**Comment by mikecrittenden** [comment]
No rush! Thanks for the update!

**Comment by lmakarov** [comment]
@mikecrittenden you have to run `fin system reset dns` every time you connect/disconnect from VPN.

**Comment by mikecrittenden** [comment]
Ah, gotcha. Thanks!
