### ISSUE TITLE
Reduce idle load by increasing container healthcheck interval

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#1453]
We use container healthchecks in Docksal system and project containers.
The interval between healthchecks is configured in Dockerfile of each container image. The default value we use is **5s**.

Unfortunately, as the number of running containers on a host grows, so grows the load from all of the individual 
 heathchecks in each container. This becomes noticeable on host machines running multiple projects and containers concurrently. Even when projects sit idle, Docker constantly runs those healthchecks.

Healthcheck options can be overridden at runtime (`docker run ...` or `docker-compose.yml`). So we don't have to push updates to all container images in the Docksal library, but set the interval globally instead.

Increasing the interval from 5s to 10s can help save some CPU cycles. Laptops users on batteries will especially appreciated this change.

**Comment by alexander-danilenko** [comment]
For me, setting `DOCKSAL_CONTAINER_HEALTHCHECK_INTERVAL=1m` in `$HOME/.docksal/docksal.env` reduced the count of system log messages about container file system mounting like here: https://github.com/docker/for-linux/issues/679
