### ISSUE TITLE
DOCKSAL_VOLUMES incorrect documentation

### ISSUE THREAD

**Issue by nicoschi** [docksal/docksal#1461]
**Description**

Incorrect documentation in [Shared Volumes / DOCKSAL_VOLUMES](https://docs.docksal.io/core/volumes/#docksal-volumes). It reports in case of DOCKSAL_VOLUMES switch: 

_Once you set a new DOCKSAL_VOLUMES option, you must recreate the cli container. The easiest way is fin project reset, but it will also remove all data from the db volume. If you want to retain it, remove only the cli container, and start the project again: fin project remove cli; fin project start_

but `fin project remove cli && fin project start` won't work because project_root volume is used in all containers (for all cases except cli as read-only) so it will produce for a test project: 

`ERROR: Configuration for volume project_root specifies "o" driver_opt None, but a volume with the same name uses a different "o" driver_opt (addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,actimeo=1). If you wish to use the new configuration, please remove the existing volume "test_project_root" first:
$ docker volume rm test_project_root`

I add a question, is project_root volume needed in read-only mode for all containers except for cli? Maybe can it be used in cli and web only? In this way with `fin project remove cli && fin project remove web && docker volume rm myproj_project_root && fin restart` we can achieve the result without a `fin project reset` which will remove db data too.

**Comment by lmakarov** [comment]
Yeah, switching volumes is a destructive operation for the whole project stack.

`project_root` is mounted in all containers to support (possible) configuration overrides stored in `.docksal/etc/<service>`.

Unless we refactor how config overrides get injected into containers, there is no way to switch volumes mode (`DOCKSAL_VOLUMES `) without resetting the whole project stack. We could run `docker cp` for each service folder in `.docksal/etc/`, but that need to happen in-between container creation and startup. I feel like the amount of work and added complexity is not worth the hassle here.

For now, we should update the docs and mention that to preserve the current state of the database, it has to be exported before the switch, then imported back.
