### ISSUE TITLE
Document Connecting to DB Directly (via Sequel Pro, for example)

### ISSUE THREAD

**Issue by charginghawk** [docksal/docksal#147]
This wasn't documented anywhere, but I imagine it's pretty important, given the popularity of Sequel Pro. To wit:

```
$ docker-machine ip docksal
192.168.64.100
$ fin ps
        Name                      Command               State            Ports
---------------------------------------------------------------------------------------
sitename_cli_1   /opt/startup.sh gosu root  ...   Up      22/tcp, 9000/tcp
sitename_db_1    /entrypoint.sh mysqld            Up      0.0.0.0:34567->3306/tcp
sitename_web_1   /opt/startup.sh apache2 -D ...   Up      443/tcp, 80/tcp
```

Use the IP for host and the sitename_db_1 port (in this case, 34567, but it's unique for every site) for port, and then the username and password you've configured (user/user by default).

It should look like this:

<img width="468" alt="screen shot 2017-03-14 at 1 35 30 pm" src="https://cloud.githubusercontent.com/assets/7936651/23914065/363d477a-08bb-11e7-9ec8-2e8955b31b23.png">

**Comment by lmakarov** [comment]
Hi @charginghawk, we have it documented on the docs site here http://docksal.readthedocs.io/en/master/advanced/db-access/#mysql-db-access-for-external-tools

It may not be on the surface, but you can always use Search on readthedocs to find what you are looking for.

**Comment by achekulaev** [comment]
I guess we can improve that doc with commands and screenshot from the first comment.

**Comment by undersound** [comment]
> Hi @charginghawk, we have it documented on the docs site here http://docksal.readthedocs.io/en/master/advanced/db-access/#mysql-db-access-for-external-tools
> 
> It may not be on the surface, but you can always use Search on readthedocs to find what you are looking for.

New link https://docs.docksal.io/service/db/access/
