### ISSUE TITLE
How to autostart docksal services?

### ISSUE THREAD

**Issue by ivnish** [docksal/docksal#1488]
Hi!

How to autostart docksal services without sudo?

**fin system start** requires **sudo** (why?) 

I tried use /etc/sudoers and start without password for **fin** but without success

**Comment by lpeabody** [comment]
**Why does `fin` use sudo?**

You can look at the various usages of `sudo` within the `fin` script by running `less $(which fin)`. In short, `fin` needs to run `sudo` in a handful of situations:

- Creating Docksal's IP networking.
- Working with `nfsd` service.
- Configuring local DNS to be able to resolve `.docksal` domains on the host.
- Adding domains to `/etc/hosts` when asked.
- Starting/stopping Docker service.

There are more usages, but they're all visible in the `fin` script.

**How to auto-start Docksal system services?**

There is no current Docksal feature for this. You could probably add a startup task that runs as your user that starts system services, somehow. Not sure how that would be done off the top of my head.

**Comment by lmakarov** [comment]
> How to auto-start Docksal system services?

We use the `unless-stopped` [restart policy](https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy) when setting up Docksal [system services](https://docs.docksal.io/core/overview/#docksal-system-services).

> unless-stopped 
>
> Similar to&nbsp;always, except that when the container is stopped (manually or otherwise), it is not restarted even after Docker daemon restarts.

Closing. Feel free to follow up if you have more questions around this.
