### ISSUE TITLE
Install error on new machine with Ubuntu 20.04

### ISSUE THREAD

**Issue by broeker** [docksal/docksal#1498]
**Description**

I've been running Docksal for several years on both Mac OS and Ubuntu 18.04 -- the motherboard died on my Ubuntu machine so I'm now running a new Dell XPS with Ubuntu 20.04. I'm trying to do a fresh install of Docksal but when I run the install command in a root terminal I get this error:

```
 root@Kermit:~# bash <(curl -fsSL https://get.docksal.io)
curl: (23) Failure writing output to destination
```
if I try to run directly as sudo I get this error:

```
root@Kermit:~# sudo bash <(curl -fsSL https://get.docksal.io)
bash: /dev/fd/63: No such file or directory
root@Kermit:~# curl: (23) Failed writing body
```

**Steps to reproduce the issue:**

1. Install a fresh copy of Ubuntu 20.04 -- install `curl` and make sure other documented prereqs are met
2. Run the install command
3. Can't install due to above errors :(

Any idea on what I'm missing? Again this is a brand new out-of-box machine with a fresh Ubuntu 20.04 install. Thank you. 

ETA: Is there any documented way to install manually without the script? I tried replacing the $DOCSKAL_VERSION and $RANDOM vars in the curl script but received this error:

```
broeker@Kermit:~$ sudo curl -fsSL "https://raw.githubusercontent.com/docksal/docksal/1.15.1/bin/fin?r=xxxx" /usr/local/bin/fin
curl: (22) The requested URL returned error: 404
curl: (3) URL using bad/illegal format or missing URL
```

**Comment by broeker** [comment]
This was caused by the most recent release of curl that I installed via Snap released in April 2021. I removed thits version and installed via `sudo apt install curl` and all is good to go. Beware dragons on a fresh install of Ubuntu!

**Comment by lpeabody** [comment]
Thank you for the troubleshooting @broeker! Glad to hear things are working for you now.
