### ISSUE TITLE
ExpressVPN + Docksal + /etc/hosts

### ISSUE THREAD

**Issue by danshumaker** [docksal/docksal#1511]
On a Mac ( 11.4 ) I normally don't have to edit the /etc/hosts file to correctly resolve my docksal sites in the browser. However when I use ExpressVPN, the only way I can see my docksal local sites is by adding them to /etc/hosts.   While this workflow is not too bad it seems like there should be a simple fix to some other low level network file on the mac that doesn't require editing the /etc/hosts file.

In reading https://github.com/docksal/docksal/issues/384 , it looks like I could edit my /etc/resolve.conf file or something, but those are Debian and not Darwin related.   And from what I can glean from posts, I probably shouldn't be editing /etc/resolve.conf anyway as settings might get removed on the next mac update.

Current Setup
macOS 11.4
Docker Desktop 3.5.1
Docksal 1.103.0

Is there a way to use ExpressVPN and Docksal without having to edit the /etc/hosts file?

Many thanks!

**Comment by shelane** [comment]
Yes, we had the same issue with our VPN with macOS 10.15 or higher. The solution is to switch to using the docksal.site domain.

Run:
```
fin config set DOCKSAL_DNS_DOMAIN=docksal.site
fin up
```

And then your sites will be available via `projectname.docksal.site`

**Comment by danshumaker** [comment]
Thank you @shelane .   That did the trick!!

**Comment by danshumaker** [comment]
Cross referencing: 
https://github.com/docksal/docksal/issues/1124
and
https://docs.docksal.io/troubleshooting/vpn/

I'm also having difficulty connecting to solr and initially thought it was due to the VPN. But that difficulty remains regardless of whether the VPN is connected or not.

I have tried specifying the solr host as

1. solr (as documentation suggests)
2. solr.mysite.docksal.site  (as browser is able to connect to it)
3. solr.site (wild guessing)

Still can't get solr to connect.

**Comment by lpeabody** [comment]
@danshumaker can you open a new issue re: solr and post your `fin config` and `fin sysinfo`, along with the above info as well as any additional information you might think is relevant? Thanks :)

**Comment by VladBo** [comment]
@danshumaker did you find a solution for that issue? I have the same problem with solr after changing DOCKSAL_DNS_DOMAIN to docksal.site on Mac OS with VPN enabled

**Comment by dshumakerUT** [comment]
Unfortunately I did not find a solution.  ExpressVPN ALSO ended up gobbling up all kinds of outgoing http requests. Some times a `composer install` (inside the docksal cli)  would completely halt if my VPN was on.  I messed with my changing my default dns server ( from google 8.8.8.8 to a different one , and then back) but that was fruitless.  So as much as I hate to turn off my vpn, sometimes I just half to.  However I have not re-addressed the solr issue directly yet (but will have to soon).  Good luck to everyone!

**Comment by danshumaker** [comment]
Here is the error I get with composer timeouts and the vpn being on:

`The following exception probably indicates you have misconfigured DNS resolver(s)


  [Composer\Downloader\TransportException]
  curl error 28 while downloading https://packages.drupal.org/lenient/packages.json: Resolving timed out after 10000 milliseconds


Exception trace:
 () at phar:///usr/local/bin/composer2/src/Composer/Util/Http/CurlDownloader.php:305
 `
