### ISSUE TITLE
Unable to access mailhog

### ISSUE THREAD

**Issue by MKorostoff** [docksal/docksal#152]
I followed the [steps here](https://github.com/docksal/docksal/blob/015a9c08c28c19ad228e7d4f1b03097ddbe9150a/docs/tools/mailhog.md), but when I attempt to navigate to http://webmail.example.docksal/  I just see this forever:

![waking up the daemons 2017-03-22 16-23-26](https://cloud.githubusercontent.com/assets/1197335/24219058/e71adf38-0f1b-11e7-95d8-ae1533664a02.png)

Also, when I run `fin ps` I see this result:

```
 $ fin ps
     Name                   Command               State             Ports          
----------------------------------------------------------------------------------
example_cli_1    /opt/startup.sh gosu root  ...   Up       22/tcp, 9000/tcp        
example_db_1     /entrypoint.sh mysqld            Up       0.0.0.0:33066->3306/tcp 
example_mail_1   MailHog                          Exit 1                           
example_web_1    /opt/startup.sh apache2 -D ...   Up       443/tcp, 80/tcp     
```

Using docker version 1.1.0 on Mac OS

**Comment by achekulaev** [comment]
This is a Docker regression. See https://github.com/docksal/docksal/issues/142

For a workaround run that container as root.

```yml
  mail:
    # ...lines from mailhog instructions...
    user: root
```

**Comment by achekulaev** [comment]
@lmakarov we probably need to update manual until that regression is resolved

**Comment by MKorostoff** [comment]
@achekulaev it works!  Thanks!

![mailhog](https://cloud.githubusercontent.com/assets/1197335/24252150/02f401c0-0fb3-11e7-9973-c3bcec05e0f6.png)
