### ISSUE TITLE
How to find what the latest client version is 

### ISSUE THREAD

**Issue by darrenwh** [docksal/docksal#1520]
I have just spent quite a few hours trying to upgrade composer to version 2.0

The docs say that the current stock versions only go up to docksal/cli:2.11-php7.4 https://docs.docksal.io/stack/images-versions/#cli  but to have Composer 2.0 I need at least 2.12 of the cli

Eventually I just changed the 2.11 to 2.12 and it worked but this is not that obvious 

my Docksal .env is set to :

DB_IMAGE='docksal/db:1.2-mysql-5.7'
CLI_IMAGE="docksal/cli:2.12-php7.4"  (previously 2.11)

Could someone tell me what the current list of versions is and how to list them on the console and I can then update the documentation.

Would also be worth updating https://docs.docksal.io/tools/composer/#usage to say that if you will need to update the cli in the env file.

Sorry if I'm being a complete numpty but this has been quite a frustration over the last few days and if the documents had been more informative it would have saved me a lot of time.

Thanks

**Comment by lpeabody** [comment]
The upcoming release does update the stock images documentation, https://github.com/docksal/docksal/pull/1515/files#diff-dccfbf4a183ff253b27bbb5c9d37f4b65b29728f77f126bc4bc08df10e97ca21. There isn't really a way to list all available versions on the console, to my knowledge.

**Comment by shelane** [comment]
I will add some wording in the documentation about where to look for the latest image versions.

**Comment by lmakarov** [comment]
> Could someone tell me what the current list of versions is and how to list them on the console

[fin image registry](https://docs.docksal.io/fin/fin-help/#image), specifically for `docksal/cli`:

```
fin image registry docksal/cli
```

We also list image tags in the [docs](https://docs.docksal.io/stack/images-versions#cli). However, the [latest Docksal release docs](https://docs.docksal.io/) may not have all of the latest images listed (images have to be released first). The [upcoming release docs](https://develop.docs.docksal.io/stack/images-versions) would cover the most recent yet to be officially released image versions. It is also possible to look up the most recent image releases on Github ([docksal/service-cli](https://github.com/docksal/service-cli/releases)) and available image tags on Dockerhub ([docksal/cli](https://hub.docker.com/r/docksal/cli/tags?page=1&ordering=-name)).
