### ISSUE TITLE
Cannot use xdebug without manual configuration

### ISSUE THREAD

**Issue by MKorostoff** [docksal/docksal#153]
I followed the steps for [setting up xdebug here](https://github.com/docksal/docksal/blob/015a9c08c28c19ad228e7d4f1b03097ddbe9150a/docs/tools/xdebug.md#debugging-with-phpstorm).  However, when I put a breakpoint in index.php, code execution did not pause on my breakpoint.  I could reload the page repeatedly as though there was no breakpoint.

## Workaround 1

On the advice of Miki Stojkovic, I ssh'ed into the CLI container with `fin bash`.  Then did the following:

```
cd /etc/php5/fpm/conf.d/
sudo ln -s /etc/php5/mods-available/xdebug.ini 80-xdebug.ini
sudo service php5-fpm restart
```

It worked!  PHP now stopped at my breakpoint.

## Workaround 2

I undid all the changes from workaround 1.  This again caused my breakpoints to be ignored.  Then, I added the following lines to `.docksal/etc/php/php.ini`:

```
zend_extension=xdebug.so
xdebug.remote_enable=1
xdebug.remote_connect_back=1
xdebug.remote_port=9000
xdebug.max_nesting_level=256
```

This also worked.  PHP now stops at my breakpoint.

OS Version: Mac OSX Sierra
Docksal Version: 1.1.0
Drupal Version: 7

**Comment by MKorostoff** [comment]
At the request of @achekulaev I have documented myself reproducing the issue here https://www.youtube.com/watch?v=z0Fn2GCvC5s

**Comment by MKorostoff** [comment]
@lmakarov asked me to add the following information to this issue:

During our skype call this afternoon, we conducted the following test.  First, created a new docksal project.  Then ran `fin exec php -v`.  The result was as follows:

```
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with blackfire v1.15.0~linux-x64-non_zts56, https://blackfire.io, by Blackfireio Inc.
```

Then, we did the following:

```
fin vm ssh
sudo /etc/init.d/docker restart
exit
fin up
fin exec php -v
```

The result of this was the following:

```
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
    with blackfire v1.15.0~linux-x64-non_zts56, https://blackfire.io, by Blackfireio Inc.
```

Note the addition of "with Xdebug..." in the second to last line.  We were also able to produce the same result by running `fin vm restart` from the host OS.  Which brings us to...

## Workaround 3
After enabling xdebug, restart the VM with `fin vm restart`

**Comment by lmakarov** [comment]
It's worth noting that `fin reset` did not help either, same as creating a new project with `XDEBUG_ENABLED=1` set right away (before running `fin up`).

It is also not an NFS mount related issue, as restarting the docker daemon in the VM fixes the issue and does not involve NFS share mounting/re-mounting from the host.

I experienced similar issues previously when working on a container image locally.
I would rebuild a container image and reset the container using it. After some number of iterations I would not see the container updating (using the newly built image) as expected. Restarting the docker daemon or the VM always resolved the problem.

This looks to be an upstream regression in docker itself. Unfortunately it is the one that can be reliably reproduced everywhere.

**Comment by achekulaev** [comment]
`fin cleanup` seems to have helped. Moreover I believe it has deleted outdated images docker had been erroneously picking up and now things just work as intended on Matt's workstation. Just adding XDEBUG_ENABLED=1 and running `fin up` is enough now. 

I guess we need to include cleanup into different update functions.

## Workaround 4 and the proper one
Run `fin cleanup`
