### ISSUE TITLE
Unable to install Docksal with Virtualbox Windows 10 

### ISSUE THREAD

**Issue by chadmandoo** [docksal/docksal#1550]
Docksal simply refuses to install using Virtualbox or the documentation is outdated.

1.) The website recommends using Virtualbox
2.) Using the command bash <(curl -fsSL https://get.docksal.io) it recommends using docker for windows 10 and then fails after the docker installation fails.

**Steps to reproduce the issue:**

1.  Install a new Ubuntu machine on windows
2. bash <(curl -fsSL https://get.docksal.io)
3. Watch it error out immediately

[STEP 3/4] Updating tools...
Installing Docker...
# Executing docker install script, commit: 28bc4d09b3938ea30c69407d198ee8ece52c3e12

WSL DETECTED: We recommend using Docker Desktop for Windows.
Please get Docker Desktop from https://www.docker.com/products/docker-desktop

^^^^ Why is the script installing docker when its suppose to be using Virtualbox?

 * Starting Docker: docker                                                                                       [ OK ]
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:40 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Docker installation/upgrade has failed.
ERROR:  Updates failed. fin was not updated.

The website claims "Install Docksal (VirtualBox will be installed automatically if necessary)"

I have tried to install Virtualbox on windows manually and letting docksal install this.

Why is it expecting docker when docker is not installed? Also why is it recommending on the website to use Virtualbox and then recommending Docker during the installation?

I attempted to also use docker for this and had a whole of myriad of issues that is out of the scope of this issue.

**Comment by lmakarov** [comment]
> WSL DETECTED: We recommend using Docker Desktop for Windows.
Please get Docker Desktop from https://www.docker.com/products/docker-desktop

This output comes from the upstream https://get.docker.com script that Docksal uses for automated Docker installation.
This message would only be triggered in a true Linux environment, which would mean you are running WSL2 on Windows. WSL2 is not yet supported in Docksal (#1055)

Please run this in powershell and post the output:

```
wsl --list --verbose
```

**Comment by chadmandoo** [comment]
This makes sense. I am on WSL2. Maybe I missed this or it is not in the documentation that you need WSL1. The link provided on the documentation page is to Microsoft which includes enabling WSL2 and installing it.

**Comment by lmakarov** [comment]
Yeah, externally linked instructions change over time and WSL2 is the default now in the Microsoft docs. We'll have to mention this in the Docksal docs.

While trying this myself, I found a few more problems with Docksal installation on WSL1 (which also behaves differently over time...). I'm looking into how we can address them in Docksal. Thanks for reporting BTW.

**Comment by chadmandoo** [comment]
Understandable. I would considered this issue closed then and attempt to downsize to wsl 1
