### ISSUE TITLE
docksal - Problem to run CLI and DB?

### ISSUE THREAD

**Issue by MiloshN** [docksal/docksal#1555]
Hi,

I want to run docksal container but as a result, I get this error:

`
Cannot start Docker Compose application. Reason: Error invoking remote method 'compose-action': Error: Command failed: docker-compose --file "docksal.yml" --file "volumes-nfs.yml" --file "stack-default.yml" --file "docksal.yml" --project-name "culinarius" --project-directory "/Users/milosn/Documents/work/vegait/culinarius/.docksal" up -d .FileNotFoundError: [Errno 2] No such file or directory: './volumes-nfs.yml'`

But when I want to run CLI first particularly:

`
Error invoking remote method 'docker-start-container': Error: (HTTP code 500) server error - OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/var/lib/docker/volumes/_project_root/_data" to rootfs at "/var/www" caused: stat /var/lib/docker/volumes/_project_root/_data: stale file handle: unknown
`

DB:

`
Error invoking remote method 'docker-start-container': Error: (HTTP code 500) server error - OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/var/lib/docker/volumes/_project_root/_data" to rootfs at "/var/www" caused: stat /var/lib/docker/volumes/_project_root/_data: stale file handle: unknown
`
My PC:

`
Model Name: MacBook Pro
  Model Identifier: MacBookPro17,1
  Chip: Apple M1
  Total Number of Cores:    8 (4 performance and 4 efficiency)
  Memory:   8 GB
`
Please help!

ps. Why do I get a 403 Forbidden error when I want to run the site on docksal domain?

**Comment by lmakarov** [comment]
ARM/Apple M1 architecture is not yet fully supported in Docksal.
You can track the progress (and community contributed workarounds) in https://github.com/docksal/docksal/issues/1421.
