### ISSUE TITLE
Suggestion: publish docksal on common package managers (brew, apt-get)

### ISSUE THREAD

**Issue by MKorostoff** [docksal/docksal#157]
It'd be pretty cool to be able to install docksal with `apt-get install docksal`

**Comment by lmakarov** [comment]
I was thinking about that for a while. We have to figure out which would be the best ones to target and what's the overhead involved.
Currently installing docksal is a two step process:

- install fin
- run `fin update`

I guess the package manager would only handle the first one.

@MKorostoff do you have experience publishing with package managers?

**Comment by MKorostoff** [comment]
@lmakarov I do not.  Admittedly, this would probably be a large investment for not much reward.

**Comment by achekulaev** [comment]
Creating DEB packages is not a too hard task. I did it before. I think we can nail it.

**Comment by achekulaev** [comment]
We could also do it Docker-way with something like `curl http://get.docksal.io | sh`

**Comment by achekulaev** [comment]
One-liner was implemented `curl -L get.docksal.io | sh`

https://github.com/docksal/get.docksal.io

**Comment by lmakarov** [comment]
With the new one-line installer we don't really need this anymore. Closing.
