### ISSUE TITLE
Would docksal support alternates to Docker Desktop?

### ISSUE THREAD

**Issue by kamal2222ahmed** [docksal/docksal#1572]
Now that we have a clear statement from docker:

It remains free for small businesses (fewer than 250 employees AND less than $10 million in annual revenue), personal use, education, and non-commercial open source projects.
It requires a paid subscription (Pro, Team or Business), for as little as $5 per user per month, for professional use in larger businesses.
The effective date of these terms is August 31, 2021. There is a grace period until January 31, 2022 for those that will require a paid subscription to use Docker Desktop.

Would there be an effort to supporting alternates to Docker like Podman ( https://podman.io/ )

**Comment by lmakarov** [comment]
See https://github.com/docksal/docksal/discussions/1570 and https://github.com/docksal/docksal/discussions/1567
