### ISSUE TITLE
Can't make requests from VM guest to internet - Windows 10

### ISSUE THREAD

**Issue by RoloDMonkey** [docksal/docksal#158]
I recently created a Docksal project. From the very beginning, the virtual machine hasn't been able to get "out" to the internet to do things like checking for Drupal updates, or download new modules.

I was able to work around this, but now I need to initialize a theme that uses Compass and I can't do that without this functionality.

**Comment by lmakarov** [comment]
Try changing your Windows network settings - set DNS to `8.8.8.8` and `8.8.4.4`, restart the VM.

If that does not help, please post the output from `fin sysinfo`

**Comment by RoloDMonkey** [comment]
That seemed to do the trick. Thank you.
