### ISSUE TITLE
Exit code 129 from fin exec with php

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#16]
When running any php based tool with fin exec in the cli container the exit code returned by docker is 129 regardless of the real exit code.

```
$ fin drush --version
 Drush Version   :  8.0.5
$ echo $?
129

$ fin drupal --version
Drupal Console version 1.0.0-alpha1
$ echo $?
129

$ fin exec php -r "echo('hi');"
hi%
$ echo $?
129
```

The same commands run inside the cli container exit as expected (with 0).

```
$ fin bash
docker@cli:/var/www$ drush --version && echo $?
 Drush Version   :  8.0.5

0
docker@cli:/var/www$ drupal --version && echo $?
Drupal Console version 1.0.0-alpha1
0
docker@cli:/var/www$ php -r "echo('hi');" && echo $?
hi0
```

**Comment by lmakarov** [comment]
There is an issue reported for Docker Compose: https://github.com/docker/compose/issues/3379 (open as of today).
Also and old similar one reported for Docker: https://github.com/docker/docker/issues/18948 (closed in favor of https://github.com/docker/docker/issues/19699)

**Comment by achekulaev** [comment]
The issue does not seem to be reproducible anymore, so I have removed the hack with `exit $?` from `exec`.
