### ISSUE TITLE
Add support for Docker Community Edition (CE)

### ISSUE THREAD

**Issue by kwiechmann** [docksal/docksal#1617]
**Description**

Per https://docs.docksal.io/use-cases/docker-modes/, Docksal only supports two operation modes on Mac and Windows:
* VirtualBox VM (default)
* Docker Desktop for Mac/Windows

**Describe the results you expected:**

Docksal supports _three_ operation modes on Mac and Windows:
* VirtualBox VM (default)
* Docker Desktop for Mac/Windows
* Docker Community Edition

With the recent changes in the license, many need to move away from DD4M/W. This leaves just Virtual Box as the only documented option for Docksal. Unfortunately, Virtual Box is not really an option due to VPN (e.g., Cisco AnyConnect) conflicts.

**Comment by kwiechmann** [comment]
Either Colima or DD4W/M support would be equally fine.

**Comment by Flower7C3** [comment]
I have just checked [colima](https://github.com/abiosoft/colima) and it works. Just set `DOCKER_NATIVE=1`, to tell Docksal to work Docker Desktop mode.

So far for me the only one problem is that Docksal DNS is not working, so I need to use `fin hosts add` command.

**Comment by lmakarov** [comment]
What is "Docker Community Edition" and how is it different from Docker Desktop for Mac/Win? I cannot find any meaningful references to this.

lima/colima look promising.

> So far for me the only one problem is that Docksal DNS is not working, so I need to use fin hosts add command.

@Flower7C3 you can disable the Docksal DNS resolver and switch over to the `docksal.site` base domain. It has a public `*.docksal.site` DNS record pointing to your local Docksal instance IP (`192.168.64.100`).

```
fin config set --global DOCKSAL_DNS_DISABLED=1
```

Also see https://docs.docksal.io/stack/configuration-variables/#docksal-dns-disabled

Your projects can then be accessed at http://projectname.docksal.site. 2nd order wildcard subdomains are also supported (e.g., http://mail.projectname.docksal.site).

Anyway, this belongs in Discussions over here: https://github.com/docksal/docksal/discussions/1567

@Flower7C3 if you have Docksal fully working with colima, it will be great if you could shared the details in that discussion thread.
