### ISSUE TITLE
Updating babun breaks grep behavior on Windows

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#162]
After updating Babun (run %USERPROFILE%\.babun\update.bat) to the latest version cygwin's grep stops stripping "\r" out of piped input.
This causes the issue when grep is no longer properly handling `^` and `$` in regular expressions affecting many aspects of `fin`.

<img width="1067" alt="windows 7 2017-04-06 09-06-07" src="https://cloud.githubusercontent.com/assets/402007/24755466/53bc972a-1aa8-11e7-8a75-a1306e433816.png">

**Comment by achekulaev** [comment]
We should probably alter `~/.babunrc` and put `export DISABLE_CHECK_ON_STARTUP="true"`

**Comment by achekulaev** [comment]
Created a Babun issue for reference https://github.com/babun/babun/issues/765

**Comment by achekulaev** [comment]
Babun update checks are disabled in https://github.com/docksal/docksal/commit/703f0dd841f9929f993015772e00ca0aa68ccf46

**Comment by lmakarov** [comment]
As reinstalling Babun fixes this and we added a flag to disable Babun updates for users, this can be considered as done for now.
