### ISSUE TITLE
fin will not create a share if share already exists. Can lead to issues

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#165]
Sometimes users have a share already existing for a drive. And that share can be created as read-only or don't have proper permissions. However fin will not try to re-create shares that already exist.

There is a need to know when to re-create share and do it. fin could possibly check share description to see if share was created by Docksal.

**Comment by achekulaev** [comment]
@lmakarov I guess this issue is addressed with latest changes.

**Comment by achekulaev** [comment]
@lmakarov if it's addressed could you check and close this issue?

**Comment by lmakarov** [comment]
Resolved via #205
