### ISSUE TITLE
DNS resolver doesn't work in Fedora 35

### ISSUE THREAD

**Issue by igorlakic** [docksal/docksal#1652]
So, when I'm using Docksal in Fedora 35, I cannot access the project via browser by using the `name-of-project.docksal` without adding it manually with `fin hosts add name-of-project.docksal`. I guess DNS resolver doesn't work in Fedora for some reason.

If I can give you more info about this issue, just ask, I'm willing to cooperate and help. :)

**Comment by lmakarov** [comment]
We are deprecating the internal DNS resolver and the use of `.docksal` base domain in favor of `.docksal.site` base domain, which is publicly resolvable. Please see https://github.com/docksal/docksal/pull/1646 and try it out.

Docs here (dev version): https://develop--docs-docksal-io.netlify.app/stack/configuration-variables/#docksal-dns-disabled
