### ISSUE TITLE
DOCKSAL_ENVIRONMENT variable is not available on latest release

### ISSUE THREAD

**Issue by matias-miranda** [docksal/docksal#1668]
**Description**

We have a set of custom scripts that depends on `DOCKSAL_ENVIRONMENT` env var, but after `fin update`, it's not available.
We found that the variable is not exported anymore, it was removed here https://github.com/docksal/docksal/commit/fcb051c6c3e86b53328d426d0c67816c6ab06e0c#diff-94510d6e95042be47b77563f572ca571fac6640d3a20e019fc84e3c7d1abbbacL6471

@lmakarov was that intentional?, if so, it should be removed from documentation as well: https://docs.docksal.io/stack/configuration-variables/#docksal-environment

**Steps to reproduce the issue:**

1. we created a `.docksal/commands/testme` file to check the existence of the env var:
```
#/bin/bash
echo "DOCKSAL_ENVIRONMENT = ${DOCKSAL_ENVIRONMENT}"

```

2. execute `DOCKSAL_VERSION=v1.16.2 fin update && fin version && fin testme`
**_Output:_**
```
fin version: 1.107.1
DOCKSAL_ENVIRONMENT = local
```
3. execute `fin update && fin version && fin testme`
**_Output:_**
```
Docksal version: v1.17.0
fin version:     1.110.1
DOCKSAL_ENVIRONMENT =

```

**Comment by lmakarov** [comment]
The primary use case for this variable is to be set globally, e.g., `fin config set --global DOCKSAL_ENVIRONMENT=ci` in a CI environment, which does get propagated into custom commands and addons.

`DOCKSAL_ENVIRONMENT` was indeed exported to be available to custom commands and addons **by default** - https://github.com/docksal/docksal/commit/fce8f506992cd8127a9f5ad519e5b130e987b10a. So, confirming that this is an unintentional regression.

As a temporary workaround, you can do this:

```
fin config set --global DOCKSAL_ENVIRONMENT=local
```
