### ISSUE TITLE
Broken link docs.docksal.io/fin/fin-pull

### ISSUE THREAD

**Issue by CFin86** [docksal/docksal#1677]
**Description**

The hyperlinked [URL](https://github.com/docksal/addons/master/pull) on `/fin/fin-pull` returns a 404

**Steps to reproduce the issue:**

1. Visit https://docs.docksal.io/fin/fin-pull
2. Click the link
3. View 404 page

**Describe the results you received:**

It's github's 404 page https://docs.docksal.io/fin/fin-pull

**Describe the results you expected:**

I believe the appropriate URL is https://github.com/docksal/addons/tree/master/pull

**Output of `fin config`:**

<details>
N/A

</details>

<br>

**Output of `fin sysinfo`:**

N/A

<details>
  <summary>fin sysinfo output</summary>

  ```
N/A
  ```

</details>

**Comment by leeomara** [comment]
I believe this was fixed in commit b4595db50c04af14 (currently in the `develop` branch)

**Comment by shelane** [comment]
Closed via #1663
