### ISSUE TITLE
More Windows installation errors

### ISSUE THREAD

**Issue by ComboPrime** [docksal/docksal#168]
Two issues, might be related. One has to do with the "System certificate pool" and the other claims there are invalid characters in container paths:

fin vm start
Starting "docksal"...
(docksal) Check network to re-create if needed...
(docksal) Waiting for an IP...
Machine "docksal" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-m
achine env` command.
Configuring SMB shares...
Enter your Windows account password:
Importing ssh keys...
time="2017-04-07T16:44:49-04:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
time="2017-04-07T16:44:49-04:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
fin up
time="2017-04-07T16:45:04-04:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
time="2017-04-07T16:45:04-04:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Starting services...
Starting project_mail_1
Creating project_db_1
Creating project_cli_1

ERROR: for db  Cannot create container for service db: create \c\Users\username\Sites\project\.docksal\etc\mysql\my.cnf: "\\c\\Users\\username\\Sites\\project\\
.docksal\\etc\\mysql\\my.cnf" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intented to pass a host directory, use absolute path

ERROR: for cli  Cannot create container for service cli: invalid bind mount spec
"C:\\Users\\username\\.babun\\cygwin\\home\\username:/.home:ro": invalid volume specification: 'C:\Users\username\.babun\cygwin\home\sindjui_a:/.home:ro'
ERROR: Encountered errors while bringing up the project.

Thanks for help!

**Comment by achekulaev** [comment]
We need to see your real paths. With real username and real path. Not being replaced with `username` and `project`.

**Comment by ComboPrime** [comment]
Thanks, Alexei! After some offline discussion, the issue was because I had copied the YML config file from an older Docksal installation to kickstart a new project. In the meantime, however, the config syntax had changed to accommodate both Windows and Unix paths.

The solution was to move docksal.yml out of .docksal, run "fin config generate" to create a new config file, and then copy over any custom settings from the old YML file. Problem solved.
