### ISSUE TITLE
Default is Deprecated?

### ISSUE THREAD

**Issue by danshumaker** [docksal/docksal#1687]
By Looking at 
https://github.com/docksal/docksal/blob/develop/bin/fin#L286
and
https://github.com/docksal/docksal/blob/develop/bin/fin#L6536-L6541

We can gather/conclude that the default is deprecated...  

Shouldn't the default not throw a warning?   Is the new default *.local?

Several developers are complaining of a warning that they didn't cause...  So we just set our `DOCKSAL_DNS_DOMAIN=local` and move on right?

**Comment by helioha** [comment]
https://github.com/docksal/docksal/issues/1215
