### ISSUE TITLE
fin update gives "1-ce: invalid number"

### ISSUE THREAD

**Issue by rfay** [docksal/docksal#169]
Running `fin update` gives a complaint on MacOS (without failure) of:

```
/usr/local/bin/fin: line 491: printf: 1-ce: invalid number
```

I imagine this has to do with docker current being installed, version `17.03.1-ce-mac5`

**Comment by achekulaev** [comment]
We are aware about an issue and it was addressed in newer versions of fin. It is not known to cause any issues though.
If it causes any issues for you please feel free to re-open the ticket.

**Comment by rfay** [comment]
Just FYI, this was with your current version of fin, downloaded and updated yesterday. So I assume you mean you've fixed it in an unreleased version.

**Comment by achekulaev** [comment]
That is exactly correct @rfay
