### ISSUE TITLE
fin update self gets stuck on Ubuntu 16.04

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#17]
When running fin update self on Ubuntu 16.04 it would get stuck after saying "Downloading...".
On Mac it prompts for user password there. For some reason this prompt is not showing up on Ubuntu. If user enters the password and hits Enter the update process proceeds as expected.

**Comment by achekulaev** [comment]
I'm pretty sure there's some problem with your Ubuntu setup
https://monosnap.com/file/Oi0e5m3bvFvwcqrukevbwvcYIxsy0Z
