### ISSUE TITLE
A way to extend official Docksal containers

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#171]
Document the recommended way to extend official Docksal images per project using the `build` docker compose directive in `docksal.yml`

**Comment by lmakarov** [comment]
This was implemented in [v1.4.0](https://github.com/docksal/docksal/releases/tag/v1.4.0) and is documented [here](http://docs.docksal.io/en/v1.4.0/advanced/extend-images/)

**Comment by berliner** [comment]
The link to the docs is broken, I suppose that https://docs.docksal.io/stack/extend-images/ is covering this topic.
