### ISSUE TITLE
PHP8 CLI - 403 After User Login

### ISSUE THREAD

**Issue by mnavsa-openbox** [docksal/docksal#1710]
**Description**

After upgrading my Docksal container to use the php8.0-3.2 image user logins always return a 403.

**Steps to reproduce the issue:**

1. Using Docker 3.4.0
2. Using `CLI_IMAGE='docksal/cli:php8.0-3.2'`
3. Using Drush 10.6.2.
4. Login with valid credentials or generate a one-time login with `drush uli` using both existing accounts and the user ID 1 account.

**Results:**

User receives an HTTP 403 and receives error message: "You are not authorized to access this page."

**Example request path after login:**

`/user/50516?check_logged_in=1`

**Comment by ivnish** [comment]
Can you try another PHP cli image?

**Comment by lmakarov** [comment]
This sounds like an application level issue (possibly, related to PHP version changes?). There would be no way for maintainers to reproduce this. Closing.
