### ISSUE TITLE
Upgrade PHP 8.1 image to 8.1.6+

### ISSUE THREAD

**Issue by ivnish** [docksal/docksal#1713]
Because PHP versions < 8.1.6 have [an opcache bug](https://github.com/php/php-src/issues/8164)

**Comment by devkinetic** [comment]
For now, you can use 'docksal/cli:php8.1' which at present is 8.1.8. Check out https://hub.docker.com/r/docksal/cli/tags?page=1&name=8.1 to see what is available.

It would be great if these images had the various node versions as well, the php8.1 image above is only node 16. Why do these these not get built already with the two supported node versions through the pipelines?

**Comment by ivnish** [comment]
Yes, thank you. I run `docker pull docksal/cli:php8.1-3.2` and php was updated to 8.1.8

**Comment by ianwesty** [comment]
Strange, I can't get 8.1.6 to install. 
Both versions mentioned above and 8.1-3.3 install PHP 8.1.14 for me 😕

**Comment by shelane** [comment]
Is there a reason to specifically want php 8.1.6?

**Comment by ianwesty** [comment]
Basically the same reason as the OP. 
Drupal recommends PHP 8.1.6 https://www.drupal.org/node/3295061

**Comment by ianwesty** [comment]
> Is there a reason to specifically want php 8.1.6?

Basically the same reason as the OP.
Drupal recommends PHP 8.1.6 https://www.drupal.org/node/3295061

**Comment by ivnish** [comment]
@ianwesty this is a MINIMUM recommended version. 8.1.14 is the best than 8.1.6 :)

**Comment by ianwesty** [comment]
> @ianwesty this is a MINIMUM recommended version. 8.1.14 is the best than 8.1.6 :)

Not quite sure what you mean?

PHP versions 8.1.0-8.1.5 have [a bug with the PHP OPcache](https://github.com/php/php-src/issues/8164) that may cause intermittent fatal errors at runtime for class autoloading.

8.1.14 falls inbetween 8.1.0-8.1.5.

**Comment by ianwesty** [comment]
> @ianwesty this is a MINIMUM recommended version. 8.1.14 is the best than 8.1.6 :)

I'm not quite sure what you mean?

"PHP versions 8.1.0-8.1.5 have [a bug with the PHP OPcache](https://github.com/php/php-src/issues/8164) that may cause intermittent fatal errors at runtime for class autoloading.
Therefore, the minimum recommended PHP version for Drupal 9.5 and above has been increased to 8.1.6"

8.1.14 falls in between 8.1.0-8.1.5.

**Comment by ivnish** [comment]
> 8.1.14 falls inbetween 8.1.0-8.1.5.

No :) 

8.1.0-8.1.5 then 8.1.6, then 8.1.7 then 8.1.8, then 8.1.9, then 8.1.10, then 8.1.11, then 8.1.12, then 8.1.13 and TA-DA , then 8.1.14

**Comment by ivnish** [comment]
Versions before 8.1.5 have that bug, versions after 8.1.5 doesn't have

**Comment by ianwesty** [comment]
> > 8.1.14 falls inbetween 8.1.0-8.1.5.
> 
> No :)
> 
> 8.1.0-8.1.5 then 8.1.6, then 8.1.7 then 8.1.8, then 8.1.9, then 8.1.10, then 8.1.11, then 8.1.12, then 8.1.13 and TA-DA 8.1.14

Ahh of course. Thanks!
