### ISSUE TITLE
linux: /etc/resolv.conf is updated even if DOCKSAL_DNS_DISABLED is set 

### ISSUE THREAD

**Issue by obriat** [docksal/docksal#1777]
**Description**

With Linux, if `DOCKSAL_DNS_DISABLED=1` (This automatically sets `DOCKSAL_DNS_DOMAIN=docksal.site` and `DOCKSAL_NO_DNS_RESOLVER=1`.) `fin` function `check_docksal_environment()` will append `nameserver ${DOCKSAL_IP} ` into  `/etc/resolv.conf`. 

**Steps to reproduce the issue:**

1. Set `DOCKSAL_DNS_DISABLED=1`  into `docksal.env`
2. Reset docksal: `fin system reset` 
3. check that the dns container is no longer running: `docker ps | grep docksal-dns` 
4. Restart a projet (to trigger `check_docksal_environment`): `fin p restart` 

**Describe the results you received:**

`nameserver ${DOCKSAL_IP} `  has been append to the first line of `/etc/resolv.conf`.

**Describe the results you expected:**
No `/etc/resolv.conf` modification

**Proposed solution:**
I propose to add a condition into `fin`  `check_docksal_environment ()`:
```bash
        local mode="${1:-on}"
        [[ "$DOCKSAL_NO_DNS_RESOLVER" != "0" ]] && mode='off'
        if is_linux && ! is_gitpod; then
			configure_resolver_alpine $mode
```

**Comment by obriat** [comment]
Nobody's reviewing the PR?

**Comment by lmakarov** [comment]
Thanks for reporting this. I incorporated your proposed fix and also set `DOCKSAL_DNS_DISABLED=1` by default in preparation for a complete removal of this deprecated functionality.
