### ISSUE TITLE
"16. Static HTML site" is not available on project create

### ISSUE THREAD

**Issue by vitaly-malashevsky** [docksal/docksal#1824]
**Description**

Unable to install a project using static site template
![image](https://github.com/docksal/docksal/assets/8169225/9a264710-ac59-4f36-9413-8a8c0a35577e)

**Steps to reproduce the issue:**

1. Run `fin project create`
2. Provide a project name
3. Pick the option "16. Static HTML site"

**Describe the results you received:**

ERROR:  Enter a number between 0 and 15.

**Describe the results you expected:**

The command runs successfully

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
 ERROR:  Cannot detect project root.
         Please make sure you have .docksal directory in the root of your project.
         To setup a basic Docksal stack in the current directory run fin config generate
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```

███  DOCKSAL
Docksal version: v1.18.2
fin version:     v1.113.2

███  OS
Linux Linux Mint 21.3
...
  ```

</details>

**Comment by shelane** [comment]
This issue has been fixed in develop with #1810.

To test this, you can run `DOCKSAL_VERSION=develop fin update` and then run `fin project create`. The HTML version in develop is now 14 after Drupal 9 was dropped from the list.
