### ISSUE TITLE
fin used in an continuous integration environment

### ISSUE THREAD

**Issue by christianwiedemann** [docksal/docksal#189]
Hi all,

has someone used fin as a part of his ci workflow to create feature based environments? 
Would recommend to use fin for that and if so maybe there is a sample for that

Thanks!
Christian

**Comment by lmakarov** [comment]
Yep, we are using it internally in CI to provision sandboxes for feature branches.
Once you have `fin init` working locally for a project, you can take it to any host Docksal is installed on, run `fin init` there and expect the result to be identical.

There are no docs on that yet. We plan to eventually formalize everything we learn from our own experience into an offering ("Docksal CI").

Several folks/organizations have figured it out on their own already.
You need a server to host the sandboxes on, a CI server to react to git commits and kick off the build process. From there, it's the same flow as with local. `docksal-vhost-proxy` service will handle the http/https routing between multiple sandboxes the same way it does it on you local.

**Comment by achekulaev** [comment]
@lmakarov please close if you think this is not something we will be providing as a service.

**Comment by achekulaev** [comment]
Closing in favor of https://github.com/docksal/docksal/issues/435
