### ISSUE TITLE
fin mysql-import fails with Syntax error: end of file unexpected

### ISSUE THREAD

**Issue by davekopecek** [docksal/docksal#19]
`fin mysql-import` fails, but command executable from inside `fin bash`. This happens with all my existing projects.  Backups were created with `drush sql-dump`

```
{ docroot } master » fin mysql-import /c/projects/project/data/production.sql      
[!] This will drop the existing database. Continue? [y/n]: y
stdout is not a tty
Importing production.sql into the database...
sh: 1: Syntax error: end of file unexpected
mysql-import failed
```

Here's the result from inside `fin bash`:

```
docker@cli:/var/www/docroot$ drush sql-drop
Do you really want to drop all tables in the database drupal? (y/n): y
docker@cli:/var/www/docroot$ drush sql-cli < /var/www/data/production.sql
docker@cli:/var/www/docroot$
```

**Comment by davekopecek** [comment]
Issue persists after updating from 0.2.8 to 0.4.1

**Comment by lmakarov** [comment]
We should probably just turn both `fin mysql-dump` and `fin mysql-import` into aliases to drush commands:
- `fin exec 'drush sql-dump > db.sql'`
- `fin exec 'drush sql-cli < db.sql'`

While we have some fancy stuff in the current commands, they are too fragile and also cause pain on Windows (or vice versa), while working perfectly fine on Mac/Linux.

**Comment by achekulaev** [comment]
mysql related functions were dramatically rewritten in 0.11.0
This ticket should not be relevant anymore

**fin 0.11.0** in develop branch Introduces fixes and non-backward compatible changes for some functions:
 * **mysql-import (sqli)** now requires a database name
 * **mysql-dump (sqld)** now requires a database name
 * **IMPORTANT:** `mysql-import ... -y` that was used in scripts is not supported anymore, use `mysql-import ... --force` to suppress any confirmations (there's only confirmation now if database truncation fails)
