### ISSUE TITLE
Add ability to customize apache conf

### ISSUE THREAD

**Issue by tjb328** [docksal/docksal#192]
The need to do this is so that we can do things in apache conf such as:
`SetEnv APP_ENV dev`

This can be done in .htaccess temporarily, but ideally the long term solution would be to allow users to have custom values in a separate file similar to how php.ini is copied over. The solution may be something like having a file such as /etc/apache2/apache.conf.

**Comment by lmakarov** [comment]
Support for this has been added in https://github.com/docksal/service-web/releases/tag/v2.1.0

Image versions:

- `docksal/web:2.1-apache2.2`
- `docksal/web:2.1-apache2.4`

Docs: http://docs.docksal.io/en/develop/advanced/web-configuration-overrides/

This will be included in the default stacks in the upcoming release of Docksal.

**Comment by tjb328** [comment]
Just letting you know that this works as stated and works for my use case.
