### ISSUE TITLE
cli (Node.js server host) IP address is changing

### ISSUE THREAD

**Issue by ArtuGit** [docksal/docksal#195]
Now it is 172.19.0.3.

![image](https://cloud.githubusercontent.com/assets/10816446/25653055/e2324148-2ff3-11e7-87ec-d2ad8a366715.png)

Yesterday it was 172.19.0.4.

Despite `cli` as a synonym for IP works in node app.js configuration code, I can not set `cli` as a Node.js server host in the Node.js module Dashboard (this configuration is stored in a DB).

![image](https://cloud.githubusercontent.com/assets/10816446/25653129/33b4be38-2ff4-11e7-96d1-0be4d8571af5.png)

Possible solutions:
1. Set a static digital synonym for `cli`.
2. Somehow get or parse the dynamic `cli` IP. We can set an received IP using `drush vset --exact nodejs_server_host '172.19.0.3'`

Could you advise?

> You can just use cli as Node.js server host value.
I use it.

But I can not use `cli' in the Node.js module DashBoard.

![image](https://cloud.githubusercontent.com/assets/10816446/25653129/33b4be38-2ff4-11e7-96d1-0be4d8571af5.png)

**Comment by achekulaev** [comment]
Container IP addresses are assigned dynamically by Docker.  You can use `cli` as Node.js server host value.

**Comment by ArtuGit** [comment]
Again, I can not.
When I set `cli` in this form it does not work. It works only with an digital IP.

![image](https://cloud.githubusercontent.com/assets/10816446/25653129/33b4be38-2ff4-11e7-96d1-0be4d8571af5.png)

**Comment by achekulaev** [comment]
This is pretty weird, especially in the light of the description of the field on your screenshot, that says 'The **hostname** of the Node.js server'. 

What module is that?

**Comment by ArtuGit** [comment]
It is https://www.drupal.org/project/nodejs .

**Comment by achekulaev** [comment]
I see. Unfortunately it's not possible to easily set a static IP to a container. You [could try](https://fordodone.com/2016/03/30/docker-compose-static-ip-address-in-docker-compose-yml/) but that's a hardcore customization which might not work best, if at all.

**Comment by lmakarov** [comment]
@ArtuGit try publishing the `8080` port in `cli` and then point Drupal to the Docksal VM IP.

```
# docksal.yml
...
cli:
  ports:
    - "8080:8080"
...
```

Node.js server host: `192.168.64.100`

**Comment by lmakarov** [comment]
Please note that two project will not be able to publish the same port. So if you plan on using this with multiple projects, you'll have to make sure they are using unique ports.

We used to have DNS service discovery a while back. It allowed to refer to containers using DNS names like `<service>.<project>.docker`. After Docker introduced their own internal DNS service there was no need in it and we removed it. So that's no longer an option.

**Comment by ArtuGit** [comment]
@lmakarov 
It does not work.
`Error: listen EADDRNOTAVAIL 192.168.64.100:8080` says app.js if I did the things that you proposed.

**Comment by achekulaev** [comment]
You need to expose the port in config. *Restart* containers. Check that port is exposed. And only then try using it. 
http://docksal.readthedocs.io/en/master/advanced/networking/#exposing-container-ports

**Comment by ArtuGit** [comment]
> Check that port is exposed.
Where? On my host machine? How to check?

**Comment by lmakarov** [comment]
@ArtuGit once you edit the `docksal.yml` file, do `fin up` to update the stack.

Then run `fin ps` to review the containers and ports published.
You should see something like `0.0.0.0:8080 -> 8080/tcp` for `cli`.
This means that port `8080` on the Docker host (the VM, IP `192.168.64.100`) is mapped to ports `8080` of the `cli` container.

**Comment by achekulaev** [comment]
> Where? On my host machine? How to check?
Have you read the instruction? I guides you step by step.

**Comment by ArtuGit** [comment]
@lmakarov 
@achekulaev 
Thank you.

My mistake was changing host in `nodejs.config.docksal.js` too. There should be `cli`.

**Comment by lmakarov** [comment]
@ArtuGit to be clear - which is the option that eventually worked for you?

`cli` or `192.168.64.100:8080` for the "Node.js server host" setting?

**Comment by ArtuGit** [comment]
The both:
`cli:8080` in the node app config file.
`192.168.64.100:8080` in the node.js module settings (which is in the DB).
