### ISSUE TITLE
Failure to install fin tools

### ISSUE THREAD

**Issue by kyleskrinak** [docksal/docksal#20]
I've installed and set fin permissions correctly. Not sure what to try next? Drude conflict?

```
fin install tools
Installing tools...
 ERROR:  Docker Machine 'docksal' exists but not running
         Start it with fin vm start first or destroy it with fin vm rm if you want it re-created.

fin vm start
    docker-machine executable was not found in /Users/kds38/.docksal/bin. (Try running 'fin install tools')

fin vm rm
    docker-machine executable was not found in /Users/kds38/.docksal/bin. (Try running 'fin install tools')
```

**Comment by achekulaev** [comment]
@kyleskrinak Could you show output of `docker-machine ls` and `docker-machine status "docksal"` please

**Comment by kyleskrinak** [comment]
docker-machine ls
        ERRO[0000] error getting state for host dev: machine does not exist
        ERRO[0000] error getting URL for host dev: machine does not exist
        NAME   ACTIVE   DRIVER       STATE   URL   SWARM
        dev    *        virtualbox   Error    

    docker-machine status "docksal"
        FATA[0000] docker-machine: 'status' is not a docker-machine command. See 'docker-machine --help'.

    docker-machine --version
        docker-machine version 0.2.0 (8b9eaf2)

Hrm, version 0.2 lacks the status command. However, version 0.8.2, available via brew, has the status command. 

    /usr/local/Cellar/docker-machine/0.8.2/bin/docker-machine status "docksal"
        Host does not exist: "docksal"

**Comment by achekulaev** [comment]
This is a very interesting case of old docker-machine in the $PATH. Anyways since you updated to 0.8.2 `fin install tools` should work fine now.

**Comment by kyleskrinak** [comment]
So that works, thank you. Now, however I'm stuck here:

On [this page](https://github.com/docksal/docksal/blob/develop/docs/project-setup.md) you say that "Presence of the .docksal folder in the repo is [a good indication]" However, `fin install docksal-config` doesn't install this directory. I'm presuming wrongly this is a templatized installation?

    fin up
     ERROR:  Cannot detect project root.
             Please make sure you have a .docksal directory in the root of your project.

**Comment by achekulaev** [comment]
@kyleskrinak you're right. We are pushing really hard implementing new features. We made changes to how configuration files are organized literally days ago and config examples are not there yet. However old configuration files are still supported. 
Basically you need only 1 thing to make folder a valid docksal project at the moment: a `.docksal` folder and `docksal.yml` file with containers descriptions inside it.
Stay with us we'll update .examples in repo shortly. `install config` will be updated later this or next week.

**Comment by achekulaev** [comment]
So now you don't need any install configs now. The .docksal folder is the only requirement for directory to be a valid Docksal project.

**Comment by achekulaev** [comment]
And also there is `fin config generate` but I would recommend zero-configuration with empty `.docksal` dir for regular use.

**Comment by kyleskrinak** [comment]
`fin start` works great, thank you.
