### ISSUE TITLE
Tests should be updated

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#210]
* `fin project ...`
* `fin db ...` (remove `fin sql...`)
* `fin hosts`
* `fin addon install/remove example`
* `fin system`
* `fin image`
* listing of custom commands and addons in `fin help`
* parse_params

**Comment by achekulaev** [comment]
* `fin system`
* `fin config get`
* `fin config set`
* `fin config remove`

**Comment by lmakarov** [comment]
@achekulaev please review and split as discussed.

**Comment by lmakarov** [comment]
RIP

**Comment by achekulaev** [comment]
Did you split it?

**Comment by lmakarov** [comment]
> Did you split it?

No. We've been pushing this out for so long, that it does not make sense to keep it around.
Smaller tickets would make sense so long as we plan on tackling them soon and have particular assignees (e.g., based on who created/maintains a particular feature in fin).
