### ISSUE TITLE
Automatic D4M/D4W vs VirtualBox switching

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#216]
We now have a set of steps, which should be performed to switch between "native" (Docker for Mac/Win) vs VirtualBox modes. This is a proposal to make this switch automatic based on the status of the Docksal VM.

- assume `DOCKER_NATIVE=1` by default
- `fin vm start` should:
  - set `DOCKER_NATIVE=0` in `~/.docksal/.docksal.env`
  - reset system services
  - configure and mount nfs/smb shares (if applicable)
- `fin vm stop` should do the reverse:
  - set `DOCKER_NATIVE=1` in `~/.docksal/.docksal.env`
  - reset system services
  - remove nfs/smb share exports (if applicable)

This way users can switch to the "native" mode by just running `fin vm stop`.
If the VM is started, then it takes precedence.

**Comment by achekulaev** [comment]
If host restarts DOCKER_NATIVE will remain 0 but vm will be stopped. Users might be puzzled and ask weird questions. I wonder if we could address that case somehow.

**Comment by lmakarov** [comment]
@achekulaev unfortunately, no. I think we won't be able to make it as easy as a single command, especially for Windows users.

I've updated the native mode docs instead (^^). Closing this issue.
