### ISSUE TITLE
Provide an uninstall script and document uninstall process

### ISSUE THREAD

**Issue by mccrodp** [docksal/docksal#22]
These docs only show how to Setup & Install: https://github.com/docksal/docksal/blob/develop/docs/env-setup.md

It would be great to know how to cleanly uninstall everything relating to `fin` and this repo.

Thank you.

**EDIT:** So far I did:
- `rm -rf ~/.docker`
- `rm -rf ~/.docksal`
- `rm -rf /usr/local/bin/fin`

**Comment by lmakarov** [comment]
Good suggestion, thanks.

The uninstall process would be:

```
fin vm rm
rm -rf ~/.docksal
rm -f /usr/local/bin/fin
```

`~/.docker` is a shared location for all docker tools, so that should be kept intact in most cases.

**Comment by mccrodp** [comment]
Great, many thanks, good to know, especially the `.docker`, didn't know that 😄
