### ISSUE TITLE
Multiple cases of Docker Machine 'docksal' needing to be run when using Docker for Mac.

### ISSUE THREAD

**Issue by Decipher** [docksal/docksal#220]
**Description**

When using Docksal on Mac via Docker for Mac (`DOCKER_NATIVE=1`) there are multiple cases where Docksal still requires you to be running the Docksal Docker Machine:

* `fin update`
* `fin cleanup`
* etc

**Steps to reproduce the issue:**

1. Install Docker for Mac
2. Install Docksal
3. Create a project and set `DOCKER_NATIVE=1`
4. Run `fin up`
5. Run `fin update`

**Describe the results you received:**

```
 ERROR:  Docker Machine 'docksal' should be running to perform update
         Start it with fin vm start or destroy it with fin vm remove if you want it re-created.
```

**Describe the results you expected:**

If I'm using Docker for Mac I shouldn't need to run the VM at all.

**Comment by achekulaev** [comment]
Hi thanks for reporting issues!

Please follow the issue template and provide the information that was requested.

Additionally to that:
> set DOCKER_NATIVE=1
How exactly did you set docker native? Can you show output of two consequent commands launched in a single terminal window.

```
echo "$DOCKER_NATIVE"
fin update
```

**Comment by Decipher** [comment]
I excluded the two additional items in the template as they didn't appear to contain any information pertinent to this issue, nor did I wish to share some of the values that they did contain.

`DOCKER_NATIVE` is set in the projects `.docksal/docksal.env` file. I take it from your implication that I should set this value machine wide? I'll give this a try shortly.

**Comment by lmakarov** [comment]
@Decipher yes, `DOCKER_NATIVE=1` should be set system-wide, not per project.

http://docs.docksal.io/en/master/getting-started/env-setup-native/
