### ISSUE TITLE
Shared volume(s) to persist package manager cache

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#231]
**Description**

When the `cli` container is reset all changes in it are lost, including cached packages for package managers like composer and npm.

This is a proposal to create a shared volume(s) in Docksal that will be used to persist data between project rebuilds (`fin init/reset`). This should reduce the rebuild/download time substantially.

The storage can be per project or globally shared will all projects, assuming this is safe and project are still isolated (changes in one project won't affect another one).

The volume(s) would be mounted in `cli` at `/home/docker/.composer/cache` for composer and `/home/docker/.npm` for npm.

**Comment by achekulaev** [comment]
This should be non-default behavior so that `cli` remained standardized environment users can rely on.

**Comment by vaza18** [comment]
I'm installing clamav antivirus and downloading db with viruses every time during fin init and that takes much time. Cache can spped up local environment setup, e.g. if cached version of image will be stored somewhere locally. I need something similar to bitbucket-pipelines caching.

**Comment by lmakarov** [comment]
I'm starting to think, that this would be more a documentation effort. It is already possible to define volumes in `docksal.yml` for anything that should persist when container configuration is updated.

```
  cli:
    ...
    volumes:
      - /home/docker/.composer/cache
      - /home/docker/.npm
    ...
```

`fin reset`, though, is doing a complete reset and killing all of the associated volumes. If that is not desired, then is should be used carefully inside a custom command (e.g. in `init`). It is possible to only reset individual services (e.g. `fin reset cli`), so you can avoid resetting the `db` service, when necessary.

@vaza18 to your point, the solution can be to better understand why and when you would be doing `fin init` for a project and maybe split it into several custom commands and use `init` only when a full reset is necessary. You could also make the `init` more flexible and accept an argument to do a partial vs full reset.

**Comment by achekulaev** [comment]
Side note:
> It is possible to only reset individual services
It's not possible yet with stable fin version. It's in 1.4.0 that was not released yet.

**Comment by vaza18** [comment]
Thank you, @lmakarov. Your suggestions are very helpful.

**Comment by lmakarov** [comment]
From https://gitter.im/docksal/community-support?at=59a4f6cd614889d47599b622 regarding implementing a shared cache (for multiple projects):

> As for the shared composer cache, something like this should work:
> 
> ```
> # Create a named volume
> fin docker volume create composer-cache
> ```
> 
> **docksal.yml**:
> 
> ```
> services:
>   cli:
>     volumes:
>       - composer-cache:/home/docker/.composer/cache
> 
> volumes:
>   composer-cache:
>     external: true
> ```
> 
> (similar to how the global docksal_ssh_agent volume is mounted in cli)
