### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by larruda** [docksal/docksal#234]
I can't seem to find some instructions to uninstall Docksal completely...
I mean, a real cleanup of everything it created and configured. Please advise.

**Comment by achekulaev** [comment]
http://docksal.readthedocs.io/en/master/getting-started/setup/#uninstallation

**Comment by kyletaylored** [comment]
Documenting since this is the first issue in search results. The uninstall docs have moved to [https://docs.docksal.io/getting-started/setup/#uninstall](https://docs.docksal.io/getting-started/setup/#uninstall)
