### ISSUE TITLE
Drupal console as a service

### ISSUE THREAD

**Issue by loganyott** [docksal/docksal#235]
I've run into issues before with the Drupal console version that Docksal installs conflicting with some local packages I have for a specific project. Drupal console's recommendation is to run console via its vendor binary (`.vendor/bin/drupal`). While we could try to do some PATH manipulations to make that easier, I would like to put forth the suggestion that we create a separate service for Drupal console.

These are roughly the steps I'm aware of that we would need to take
- [ ] Fork `docksal/service-cli` into a `docksal/service-drupal` repo for a `docksal/drupal` image
- [ ] Add `docksal/drupal` to default stacks
- [ ] Update the `fin` binary to use the new `drupal` service, similar to the way `_bash` specifically passes `cli` to the `_exec` command

I'm willing to put in the effort to start making this happen, but I wanted to get confirmation that this is a good direction to move in.

Thanks!

**Comment by lmakarov** [comment]
The official recommendation from the Drupal Console team is to install the [Drupal Console Launcher](https://github.com/hechoendrupal/drupal-console-launcher) globally. 

That's exactly what we are doing in `docksal/cli`. Unfortunately the launcher has been having compatibility issues with different console versions.

This has been presumably addressed [here]() and the edge versions of `cli` (`docksal/cli:edge` and `docksal/cli:edge-php7`) are using the latest release of the launcher ([rc20](https://github.com/hechoendrupal/drupal-console-launcher/releases/tag/1.0.0-rc20)), which should no longer be affected by the compatibility issues with the console version in a project.

@loganyott, try the edge cli version and see if you are still running into any issues.

**Comment by achekulaev** [comment]
It makes more sense to just install console on demand into cli container.

**Comment by lmakarov** [comment]
Closing as this does not seem to be a viable option.
