### ISSUE TITLE
Support for automatic cron jobs

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#238]
**Description**

There is currently no way to easily configure cron jobs out of the box in Docksal.
This is a proposal to add cron as a standalone service or as part of the `cli` service.

**Note:** It is possible to manually install and enable cron like this with a project's init script:

```
fin exec sudo apt-get update
fin exec sudo apt-get install -y --force-yes --no-install-recommends cron
fin exec sudo /etc/init.d/cron start
```

Example of adding a crontab:

```
fin exec '(crontab -l; echo "* * * * */1 echo \"hello world\" >> /tmp/hello.txt") | crontab -'
```

Also note, that whenever the `cli` container (or the whole stack) is restarted, cron won't start automatically and need a `fin exec sudo /etc/init.d/cron start` kick to get it running.

**Comment by lmakarov** [comment]
`cron` package added in https://github.com/docksal/service-cli/commit/bda7e4e895ed343f03babe1cd7c2eb7a8581057f.

Still need to decide on the way to configure crontab and autostart `crond`. Might just go with a supervisord approach and expecting settings in the codebase (`.docksal/etc/crontab`).

**Comment by achekulaev** [comment]
We might autostart in in our container manually if we detect a valid `.docksal/etc/crontab`
