### ISSUE TITLE
Compass watch does not work, update documentation

### ISSUE THREAD

**Issue by david-hernandez** [docksal/docksal#24]
In the Sass docs we need to remove the part about using compass watch since it does not work. If a local agent is needed, I'm willing to test it and update the docs.

**Comment by achekulaev** [comment]
@david-hernandez `compass watch --poll` should solve your problem. Please update to the latest fin, restarm vm and try out.

**Comment by achekulaev** [comment]
Updated https://github.com/docksal/docksal/blob/develop/docs/sass.md
