### ISSUE TITLE
"HTTP request status fails" 

### ISSUE THREAD

**Issue by ilakic** [docksal/docksal#240]
**Description**

"_**HTTP request status fails**_" when iptables are enabled

 <a href="http://tinypic.com?ref=2iut10g" target="_blank"><img src="http://i65.tinypic.com/2iut10g.png" border="0" alt="Image and video hosting by TinyPic"></a><a href="http://tinypic.com?ref=200ecup" target="_blank"><img src="http://i65.tinypic.com/200ecup.png" border="0" alt="Image and video hosting by TinyPic"></a> 

I tried a couple of solutions (urls below) but after machine reboots, everything is again the same. Only temporary fix that works for sure is to turn off/disable firewall completely (which certainly isn't a good option).

Also, I tried to add **noiptables.conf** under the **/etc/systemd/system/docker.service.d**/ (if I'm correct it stops Docker manipulation of iptables - a way to stop Docker to aggressively change iptables settings, more about that [here](https://blog.daknob.net/debian-firewall-docker/) ), and these solutions: [possible solution 1](https://stackoverflow.com/questions/17394241/my-firewall-is-blocking-network-connections-from-the-docker-container-to-outside) & [possible solution 2](https://stackoverflow.com/questions/30769829/docker-ignores-iptable-rules-when-using-p-portport)

Usually I use Gufw with preconfigured profile "Home" (on Ubuntu 16.04) - configured to allow outgoing traffic and deny incoming.

It would be nice if you could recommend me a ready-to-use working solution?

**Comment by ilakic** [comment]
More info about this issue:
```
$ fin bash
$ ping -c 10 updates.drupal.org
PING j.shared.global.fastly.net (151.101.113.175): 56 data bytes
--- j.shared.global.fastly.net ping statistics ---
10 packets transmitted, 0 packets received, 100% packet loss
```

**Comment by ilakic** [comment]
Ok, **noiptables.conf** hack blocked connections to updates.drupal.org... After removal noiptables.conf the output of `$ ping -c 10 updates.drupal.org` is:
```
PING j.shared.global.fastly.net (151.101.1.175): 56 data bytes
64 bytes from 151.101.1.175: icmp_seq=0 ttl=58 time=32.636 ms
64 bytes from 151.101.1.175: icmp_seq=1 ttl=58 time=32.153 ms
64 bytes from 151.101.1.175: icmp_seq=2 ttl=58 time=32.951 ms
64 bytes from 151.101.1.175: icmp_seq=3 ttl=58 time=32.885 ms
64 bytes from 151.101.1.175: icmp_seq=4 ttl=58 time=34.581 ms
64 bytes from 151.101.1.175: icmp_seq=5 ttl=58 time=33.150 ms
64 bytes from 151.101.1.175: icmp_seq=6 ttl=58 time=32.862 ms
64 bytes from 151.101.1.175: icmp_seq=7 ttl=58 time=34.065 ms
64 bytes from 151.101.1.175: icmp_seq=8 ttl=58 time=33.133 ms
64 bytes from 151.101.1.175: icmp_seq=9 ttl=58 time=33.305 ms
--- j.shared.global.fastly.net ping statistics ---
10 packets transmitted, 10 packets received, 0% packet loss
round-trip min/avg/max/stddev = 32.153/33.172/34.581/0.660 ms
```
And what is most important, drupal can now check for available updates...

Still, I have to see how it's going to work with my firewall enabled again...

**Comment by ilakic** [comment]
...should disable firewall when I saw for the first time this error message ("HTTP request status - Fails") and then **restart Docker** and/or these containers around Drupal example site so it can take effect.

I put all docker connections to the whitelist and it seems that everything is working ok now... I'll close this issue (at least for now).

**Comment by achekulaev** [comment]
Could you maybe include iptables commands you used to whitelist Docker connections @ilakic ?

**Comment by ilakic** [comment]
I whitelisted all docker connections through Gufw... Have to see if there is some better, more secure way of doing this but for now it will serve purpose. Hope this helps!

<a href="https://imgbb.com/"><img src="https://image.ibb.co/fvq1Na/f.png" alt="f" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>cdn images</a><br />
