### ISSUE TITLE
Duplicate VMs created on Windows 10

### ISSUE THREAD

**Issue by Martins15** [docksal/docksal#241]
**Description**

Duplicate VMs created. Had to remove them manually and restart http://take.ms/AB3l3

**Steps to reproduce the issue:**

1. 
2. 
3. 

**Describe the results you received:**

Results...

**Describe the results you expected:**

Expected behavior...

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
(paste your output here)
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  (paste your output here)
  ```

</details>

**Comment by Martins15** [comment]
@apotashov can you add more details?

**Comment by achekulaev** [comment]
We need more details here

**Comment by apotashov** [comment]
Now not avaible to reproduce there is issue (reinstalled).

**Comment by lmakarov** [comment]
Closing. Please open a new ticket with all requested diagnostics information if you run into this again.
