### ISSUE TITLE
Windows fin commands result in error

### ISSUE THREAD

**Issue by pdxkirkw** [docksal/docksal#256]
**Description**

After computer reboot, a new error pops up when executing 'fin up', 'fin ps', etc. 'fin vm start' ran normally (I believe).

**Steps to reproduce the issue:**

1. cd /c/projects/tek.com
2. run  fin vm start  - seemed to start ok
3. run fin up - resulted in a message like below

**Describe the results you received:**

error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.28/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.28/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
 ERROR:  Looks like your Docker client and Docker server are incompatible.
         Run fin update to update.

**Describe the results you expected:**

Expected behavior...

**Output of `fin config`:**

same error as above

```
(paste your output here)
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
{ tek.com } features/TEK-1690 » fin sysinfo                                   /c/projects/tek.com
███  OS & BASICS
CYGWIN_NT-10.0-WOW PC-BEAV-4EF4 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
 Microsoft Windows [Version 10.0.10586]
fin version: 1.10.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   -        virtualbox   Running   tcp://192.168.64.100:2376           v17.04.0-ce
███  DOCKER
DOCKER_HOST:

error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.28/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      windows/amd64
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build ee0f34e1
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine.exe version 0.10.0, build 76ed2a6
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.28/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
███  VIRTUALBOX
5.1.18r114002
███  NETWORK INTERFACES
Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            506cbbf9-9894-49ef-a8d8-6b12c38c3d87
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:61f8:9277:dc7a:ef75
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:0c
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2

Name:            VirtualBox Host-Only Ethernet Adapter #3
GUID:            60c042b9-67c9-460f-b374-cd1c6e5b8b5e
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:8556:bc0e:e0e3:87d4
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:0f
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #3

███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/cb7218ef9c8010e13c2082d5280107b1ebdac86e14b9caa8db7ffb2d5c53b4ad type aufs (rw,relatime,si=5a3d439a81131ba1,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/53cc2dbb256d9f598cb834c57b853264547ae7a662ec7223d5500ecd1f569f11/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/e5525abb81d9a379a4d562c80642c6e0a28d1800eec3f8747e1d053ad7d95a4b type aufs (rw,relatime,si=5a3d439a8048bba1,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/49dbc382d974c84460e408725a664809cdf3a85530bf5d0834e441851e0de151/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/df6114c109f4e21fa0034f1c3ff112be978624cd8c1ed0346deb46b61cca381a type aufs (rw,relatime,si=5a3d439a97b9bba1,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/2e096b2ce83aae45e1f063d042976774bc1ce71b9f70b042574a8d7511f95b4e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/45b8d23db28e type nsfs (rw)
nsfs on /var/run/docker/netns/4fe69d1becf3 type nsfs (rw)
nsfs on /var/run/docker/netns/bb76d22f8102 type nsfs (rw)
//192.168.64.1/docksal-c on /c type cifs (rw,relatime,vers=1.0,sec=ntlmssp,cache=strict,username=kirkw,domain=GLOBAL,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=61440,wsize=65536,actimeo=1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/15c172d347eaa3156cc55878afc3da2868cde12ed780b6a088fc59f36ab94efb type aufs (rw,relatime,si=5a3d439a80da1ba1,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/1c9e659805cedd50cd8c5f7f30b19614be21d1f83a97172bd8d399b6f2f7102e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
//192.168.64.1/docksal-c on /mnt/sda1/var/lib/docker/volumes/tekcom_project_root/_data type cifs (rw,relatime,vers=1.0,sec=ntlmssp,cache=strict,username=kirkw,domain=GLOBAL,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=61440,wsize=65536,actimeo=1)
nsfs on /var/run/docker/netns/b89e9d714ad9 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/4836b66a27d6f66a8ed640b35ba9c4ca5a07db7e62b71294f87a1aaacc6d53be type aufs (rw,relatime,si=5a3d439a81c44ba1,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/f81761fa7e4935261d3839f2dd0523146f6bdd245233774d59dd7821da364a51/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
nsfs on /var/run/docker/netns/391608c6ba8b type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/7ad94074e411907ba5cf1f3bb31ef1114c39df144af02e3f3bd425d72c91259d type aufs (rw,relatime,si=5a3d439a82accba1,dio,dirperm1)
shm on /mnt/sda1/var/lib/docker/containers/84c0a1867d8bcc73ae12c871536a421b630276abea6e7d18f8e44aa73cce9a70/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
//192.168.64.1/docksal-c on /mnt/sda1/var/lib/docker/volumes/tekcom_host_home/_data type cifs (rw,relatime,vers=1.0,sec=ntlmssp,cache=strict,username=kirkw,domain=GLOBAL,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=61440,wsize=65536,actimeo=1)
nsfs on /var/run/docker/netns/6d756cd118fe type nsfs (rw)
{ tek.com } features/TEK-1690 » 
  ```

</details>

**Comment by achekulaev** [comment]
Hi @pdxkirkw 

Could you show output of
1. `which docker`
2. `ls ~/.docksal/bin`
3. `fin vm ssh ps aux | grep -i docker`

**Comment by pdxkirkw** [comment]
Hi Alexei,  Here are the outputs you requested.  Kirk

{ tek.com } features/TEK-1690 » which docker                                  /c/projects/tek.com
docker not found


{ tek.com } features/TEK-1690 » ls ~/.docksal/bin                           /c/projects/tek.com 1
docker.exe          docker-machine.exe  winpty.exe        winpty-debugserver.exe
docker-compose.exe  winpty.dll


{ tek.com } features/TEK-1690 » fin vm ssh ps aux | grep -i docker          /c/projects/tek.com 1
1355 root     /usr/local/bin/dockerd -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 --label provider=virtualbox --tlsverify --tlscacert=/var/lib/boot2docker/ca.pem --tlscert=/var/lib/boot2docker/server.pem --tlskey=/var/lib/boot2docker/server-key.pem -s aufs
1373 root     docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc --debug
1586 root     /usr/local/bin/docker-proxy -proto udp -host-ip 192.168.64.100 -host-port 53 -container-ip 172.17.0.2 -container-port 53
1597 root     /usr/local/bin/docker-proxy -proto tcp -host-ip 192.168.64.100 -host-port 443 -container-ip 172.17.0.4 -container-port 443
1608 root     /usr/local/bin/docker-proxy -proto tcp -host-ip 192.168.64.100 -host-port 80 -container-ip 172.17.0.4 -container-port 80
1620 root     docker-containerd-shim 53cc2dbb256d9f598cb834c57b853264547ae7a662ec7223d5500ecd1f569f11 /var/run/docker/libcontainerd/53cc2dbb256d9f598cb834c57b853264547ae7a662ec7223d5500ecd1f569f11 docker-runc
1624 root     docker-containerd-shim 49dbc382d974c84460e408725a664809cdf3a85530bf5d0834e441851e0de151 /var/run/docker/libcontainerd/49dbc382d974c84460e408725a664809cdf3a85530bf5d0834e441851e0de151 docker-runc
1625 root     docker-containerd-shim 2e096b2ce83aae45e1f063d042976774bc1ce71b9f70b042574a8d7511f95b4e /var/run/docker/libcontainerd/2e096b2ce83aae45e1f063d042976774bc1ce71b9f70b042574a8d7511f95b4e docker-runc
1776 root     docker-gen -watch -notify supervisorctl restart dnsmasq /etc/dnsmasq.d/dockergen.tmpl /etc/dnsmasq.d/dockergen.conf
1818 root     ntpd -d -n -p 0.boot2docker.pool.ntp.org -p 1.boot2docker.pool.ntp.org -p 2.boot2docker.pool.ntp.org -p 3.boot2docker.pool.ntp.org
1975 root     docker-containerd-shim 1c9e659805cedd50cd8c5f7f30b19614be21d1f83a97172bd8d399b6f2f7102e /var/run/docker/libcontainerd/1c9e659805cedd50cd8c5f7f30b19614be21d1f83a97172bd8d399b6f2f7102e docker-runc
2041 root     /usr/local/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 32768 -container-ip 172.19.0.4 -container-port 3306
2047 root     docker-containerd-shim f81761fa7e4935261d3839f2dd0523146f6bdd245233774d59dd7821da364a51 /var/run/docker/libcontainerd/f81761fa7e4935261d3839f2dd0523146f6bdd245233774d59dd7821da364a51 docker-runc
2102 root     docker-containerd-shim 84c0a1867d8bcc73ae12c871536a421b630276abea6e7d18f8e44aa73cce9a70 /var/run/docker/libcontainerd/84c0a1867d8bcc73ae12c871536a421b630276abea6e7d18f8e44aa73cce9a70 docker-runc
2163 docker   apache2 -DFOREGROUND
2164 docker   {apache2} fcgi-pm -DFOREGROUND
2165 docker   apache2 -DFOREGROUND
2166 docker   apache2 -DFOREGROUND
2387 root     docker-gen -watch -notify proxyctl notify -notify-output /etc/nginx/default.conf.tmpl /etc/nginx/conf.d/default.conf
5795 docker   {php-fpm7.0} php-fpm: pool www
5802 docker   {php-fpm7.0} php-fpm: pool www
6022 docker   {php-fpm7.0} php-fpm: pool www
6159 root     sshd: docker [priv]
6161 docker   sshd: docker@notty
6162 docker   sh -c ps aux
6163 docker   ps aux

**Comment by achekulaev** [comment]
These outputs look fine. 
Please provide outputs of:

1. `echo $DOCKER_HOST`
2. `fin docker ps`

**Comment by pdxkirkw** [comment]
1.  echo $DOCKER_HOST
(returns a blank line)

{ tek.com } features/TEK-1690 » fin docker ps                                 /c/projects/tek.com
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.28/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.28/containers/json: open //./pipe
/docker_engine: The system cannot find the file specified. In the default daemon configuration on Wi
ndows, the docker client must be run elevated to connect. This error may also indicate that the dock
er daemon is not running.

(returns the same error).

**Comment by achekulaev** [comment]
Getting weirder and weirder :) Your docker is working, you even have some containers running. 

Ok let's try couple more:

1. `fin debug 'echo $DOCKER_HOST'`
2. `fin vm env`
3. `fin vm ssh docker ps`

**Comment by pdxkirkw** [comment]
1.  fin debug 'echo $DOCKER_HOST'  returns a blank line followed by prompt


  1.  fin vm env

{ tek.com } features/TEK-1690 » fin vm env                                    /c/projects/tek.com

export DOCKER_TLS_VERIFY="1"

export DOCKER_HOST="tcp://192.168.64.100:2376"

export DOCKER_CERT_PATH="C:\Users\kirkw\.docker\machine\machines\docksal"

export DOCKER_MACHINE_NAME="docksal"

export COMPOSE_CONVERT_WINDOWS_PATHS="true"

# Run this command to configure your shell:

# eval $("C:\Users\kirkw\.babun\cygwin\home\kirkw\.docksal\bin\docker-machine.exe" env docksal)


  1.  fin vm ssh docker ps
{ tek.com } features/TEK-1690 » fin vm ssh docker ps                          /c/projects/tek.com
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
1c9e659805ce        docksal/web:1.0-apache2.2   "/opt/startup.sh a..."   11 days ago         Up 3 hours          80/tcp, 443/tcp                                          tekcom_web_1
f81761fa7e49        docksal/db:1.0-mysql-5.5    "/entrypoint.sh my..."   11 days ago         Up 3 hours          0.0.0.0:32768->3306/tcp                                  tekcom_db_1
84c0a1867d8b        docksal/cli:1.2-php7        "/opt/startup.sh s..."   11 days ago         Up 3 hours          22/tcp, 9000/tcp                                         tekcom_cli_1
49dbc382d974        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      11 days ago         Up 3 hours                                                                   docksal-ssh-agent
53cc2dbb256d        docksal/dns:1.0             "/opt/entrypoint.s..."   11 days ago         Up 3 hours          192.168.64.100:53->53/udp                                docksal-dns
2e096b2ce83a        docksal/vhost-proxy:1.0     "/usr/local/bin/st..."   11 days ago         Up 3 hours          192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

**Comment by achekulaev** [comment]
> fin debug 'echo $DOCKER_HOST'  returns a blank line followed by prompt

Ok, that's the root cause. Let's try to find out why it happened.

1. `cat ~/.docksal/machines/.env` (to check if there's an empty cached value for some reason)
2. `echo "--${DOCKER_HOST}--"` (to double check that your DOCKER_HOST does not contain spaces which make it a non-empty value)

**Comment by pdxkirkw** [comment]
1.  cat ~/.docksal/machines/.env (to check if there's an empty cached value for some reason)
returns a blank line then the prompt


2    echo "--${DOCKER_HOST}--" (to double check that your DOCKER_HOST does not contain spaces which make it a non-empty value)
returns four hyphens, like this  ----

**Comment by achekulaev** [comment]
`fin vm restart` should solve your issue

**Comment by pdxkirkw** [comment]
Ok, I will try that and let you know the results.  Thanks

**Comment by pdxkirkw** [comment]
You were right.  Fin vm restart worked, after that fin up worked normally. Here are results of fin ps

{ tek.com } features/TEK-1690 » fin ps                                        /c/projects/tek.com
    Name                  Command               State            Ports
-------------------------------------------------------------------------------
tekcom_cli_1   /opt/startup.sh supervisord      Up      22/tcp, 9000/tcp
tekcom_db_1    /entrypoint.sh mysqld            Up      0.0.0.0:32768->3306/tcp
tekcom_web_1   /opt/startup.sh apache2 -D ...   Up      443/tcp, 80/tcp

I am wondering if I should have this many instances of Virtual Box running?
[cid:image001.png@01D2DF85.8FD326B0]

**Comment by achekulaev** [comment]
Cool. Usually `fin vm restart` is the first thing to try out when experiencing "weird issues".

"Have you tried turning off and on again?" ©

**Comment by pdxkirkw** [comment]
I have another issue regarding rebooting that I need to resolve, but I do not think it is docker related. Reboots require 15 – 45 minutes, which is crazy. Our IT people are going to look into that later today.

Thanks you very much for your expert help!!  If I have additional issues, I will follow the steps to log an issue in github, and perhaps work with you again.

Kirk
