### ISSUE TITLE
Feed of updates

### ISSUE THREAD

**Issue by samgaard** [docksal/docksal#263]
Is there a feed we could subscribe to for when we should update? Maybe a slack channel or rss?

**Comment by lmakarov** [comment]
`fin` does weekly update checks an will notify you of there is a newer version of Docksal available.

We also post updates in the community support room on Gitter:    
https://gitter.im/docksal/community-support

Additionally, you should be able to subscribe to Github's built-in feed for releases: https://github.com/docksal/docksal/releases.atom

**Comment by samgaard** [comment]
Thank you so much!
