### ISSUE TITLE
How can I get php-soap install on docksal/cli:1.2-php7

### ISSUE THREAD

**Issue by leoman730** [docksal/docksal#275]
**Description**
My drupal project requires to call external service via SOAP; however, the docksal/cli:1.2-php7 doesn't come with the soap.so extension. I try to install it via `apt-get install php7-soap`, but it could not locate the package.

The docksal/cli:1.2-php5 comes with the extension and it works fine; however, I am wondering would it be possible to allow custom php extension in the docksal/cli:1.2-php7. How could we do that? 

Thanks.

**Comment by lmakarov** [comment]
PHP7 extensions are prefixed with `php7.0-`, so the SOAP extension would be [php7.0-soap](https://packages.debian.org/sid/php7.0-soap). I added it to the php7 cli image. It will be released in v1.3 of the images. For now you can switch to the edge version to get it right away: `docksal/cli:edge-php7` (the build will finish within 0.5h on Docker Hub).
