### ISSUE TITLE
docksal.io being blocked

### ISSUE THREAD

**Issue by RoloDMonkey** [docksal/docksal#281]
**Description**

The docksal.io domain is being blocked by Comcast/XFINITY based on this report:

http://dnsviz.net/d/docksal.io/WV5uCw/dnssec/

This prevents me from installing Docksal on a new computer because I cannot curl get.docksal.io.

**Comment by RoloDMonkey** [comment]
From Comcast DNS Support:

> The key terms are not Errors or Warnings, but Bogus, Insecure, and Secure in the upper left under RRset status.  Bogus is the issue. 
> 
> To be clear, we're not blocking anything.  We're validating the domain responses per the domain owner's request and the validations are failing.  The domain owner can fix the DNSSEC configuration or not ask us to validate by removing the DS records.   Many domains are DNSSEC-signed in order to provide protection against man-in-the-middle and cache poisoning attacks and it is up to the owner to maintain proper signatures/configurations. 
> 
> Note that Google's public DNS (8.8.8.8 et al) also performs DNSSEC validation and also fails the zone (SERVFAIL below):
> 
> $ dig docksal.io. @8.8.8.8
> 
> ; <<>> DiG 9.9.9-S6 <<>> docksal.io. @8.8.8.8
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 59689
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 512
> ;; QUESTION SECTION:
> ;docksal.io.
> IN A
> 
> ;; Query time: 119 msec
> ;; SERVER: 8.8.8.8#53(8.8.8.8)
> ;; WHEN: Thu Jul 06 17:45:46 UTC 2017
> ;; MSG SIZE  rcvd: 39

**Comment by achekulaev** [comment]
Thanks @RoloDMonkey 
As a workaround you can use the direct link to the script https://raw.githubusercontent.com/docksal/get.docksal.io/master/index.html

**Comment by RoloDMonkey** [comment]
Thank you for the workaround. At least I am no longer blocked.

I hope you will be able to resolve this easily.

**Comment by achekulaev** [comment]
It's some weird DNS magic :) Not all providers are actually blocking it. And even with xfinity it's not everywhere.

**Comment by lmakarov** [comment]
Thanks for reporting this. Should be resolved now.

http://dnsviz.net/d/docksal.io/WWOxYw/dnssec/

```
$ dig docksal.io 8.8.8.8

; <<>> DiG 9.8.3-P1 <<>> docksal.io 8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53131
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;docksal.io.			IN	A

;; ANSWER SECTION:
docksal.io.		300	IN	A	104.198.14.52

;; Query time: 29 msec
;; SERVER: 10.128.128.128#53(10.128.128.128)
;; WHEN: Mon Jul 10 09:56:42 2017
;; MSG SIZE  rcvd: 44

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55963
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;8.8.8.8.			IN	A

;; ANSWER SECTION:
8.8.8.8.		0	IN	A	8.8.8.8

;; Query time: 3 msec
;; SERVER: 10.128.128.128#53(10.128.128.128)
;; WHEN: Mon Jul 10 09:56:42 2017
;; MSG SIZE  rcvd: 41
```
