### ISSUE TITLE
Provide user-specific configuration at container creation time?

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#288]
Do you have any recommendations for providing user-specific configuration to files in the docker file system at the time of creation of the container(s)?

For example, we have a need to modify ~docker/.ssh/config for every user of the project. Specifically, we're setting the `User` configuration value in the SSH config file.

How do you recommend automating this process as much as possible? Is there a way to prompt for information when containers are being created from an image? Maybe it's best to have a custom project command that copies a templated version of the file to where it should live (wrapped into `fin init`)? Just curious if you've had to do anything similar in the past and how you solved the problem.

**Comment by lmakarov** [comment]
You can pass host environment variables in `docksal.yml` (or `docksal-local.yml`) to any service. In the `init` script do whatever alterations are necessary via `fin exec` (for cli) and use those environment variables.
For other services use `fin docker-compose exec <service> <command>`.

**docksal.yml**

```yaml
services:
  cli:
    ...
    environment:
      ...
      - HOST_USER=$USER
      ...
    ...
```

**.docksal/commands/init**

```bash
...
fin exec 'echo $HOST_USER'
...
```

Replace `echo $HOST_USER` above with a necessary sed/etc. operation.

Another (even less involved option) would be to just pass host variables on the command line like this`fin exec "echo $USER"` (not double quotes in this case - variable are interpreted by the host shell before they are passed to the container) in the `init` script. This approach is much simpler, but also less transparent. I'd personally go with the first option.

**Comment by achekulaev** [comment]
If not doint that in `init` script then this might be an answer http://docs.docksal.io/en/v1.4.0/advanced/extend-images/
