### ISSUE TITLE
SSH keys with custom names

### ISSUE THREAD

**Issue by botanic** [docksal/docksal#290]
**Description**

When starting docksal, ssh-agent imports only keys that satisfy certain naming convention (`id_dsa`, `id_rsa`, `id_esca`).
If there is a key with custom name, e.g. `key_acquia` it will not be imported to vm.

This can be solved by manually adding the key, but it would be great if we can somehow state which keys/patterns should be imported on vm start.

**Comment by sean-e-dietrich** [comment]
@achekulaev I believe this is solved as a result of https://github.com/docksal/docksal/pull/549 right?

**Comment by achekulaev** [comment]
Yes, thanks.
