### ISSUE TITLE
fin mysql-dump doesn't work by default

### ISSUE THREAD

**Issue by rootical** [docksal/docksal#30]
I am getting this error when trying to create a dump using `fin mysql-dump some_name.sql`:

`mysqldump: Got error: 1045: Access denied for user 'drupal'@'localhost' (using password: YES) when trying to connect`

**Comment by lmakarov** [comment]
What does `fin drush sql-connect` output (has to be run within `docroot`)?

See my comment here and test the alternative approach
https://github.com/docksal/docksal/issues/19#issuecomment-255645203

**Comment by DigitalFrontiersMedia** [comment]
On Mac, `fin mysql-import` works as advertised, i.e. connects to the database correctly to do the import.  `fin mysql-dump` however seems to try to connect using the defaults drupal:123 instead of reading the values set in docksal.env.

**Comment by DigitalFrontiersMedia** [comment]
I should note that if you use the `--db-user` and `--db-pass` override parameters, `fin mysql-dump` seems to work fine (as does the drush workaround).

**Comment by achekulaev** [comment]
I'm in the process of updating all mysql related commands to make them non-Drupal dependent. I will update this ticket when it's done

**Comment by achekulaev** [comment]
This was updated in 0.11.0.
mysql related functions were dramatically changed internally.

**fin 0.11.0** in develop branch Introduces fixes and non-backward compatible changes for some functions:
 * **mysql-import (sqli)** now requires a database name
 * **mysql-dump (sqld)** now requires a database name
 * **IMPORTANT:** `mysql-import ... -y` that was used in scripts is not supported anymore, use `mysql-import ... --force` to suppress any confirmations (there's only confirmation now if database truncation fails)
