### ISSUE TITLE
Possible to get return value from fin exec?

### ISSUE THREAD

**Issue by regenrek** [docksal/docksal#303]
Hi

currently I'm writing a custom init script with wp cli. I need to reproduce something like this:

```shell
# shell commands ...

# get cf7 meta ID (dynamic)
cf7_id=$(wp post list --post_type='wpcf7_contact_form' --field=ID)
# update meta fields with dynamic id
wp post meta update $cf7_id _form < ~/config/c7meta/_form.txt
wp post meta update $cf7_id _mail < ~/config/c7meta/_mail.txt
wp post meta update $cf7_id _mail2 < ~/config/c7meta/_mail2.txt
```

Since I want to use ``fin exec`` it is impossible to solve this case in any form.
Any hints maybe?

```
fin exec "wp post meta update <DYNAMIC VAR HERE> _form < ${PROJECT_ROOT}/.docksal/config/contact-form-7/_form.txt"
```

Regards

**Comment by achekulaev** [comment]
I don't understand which problem you have @regenrek 
Could you re-phrase or explain why is it "impossible to solve this case in any form"?

**Comment by achekulaev** [comment]
Ah I see what you mean. 
You do it like this:

```bash
# get cf7 meta ID (dynamic)
cf7_id=$(fin exec  -T wp post list --post_type='wpcf7_contact_form' --field=ID)
# update meta fields with dynamic id
fin exec "wp post meta update $cf7_id _form < ~/config/c7meta/_form.txt"
```

Just don't use `~` in your file paths, because it refers to your home folder outside of Docksal, not to home folder inside the Docksal container. Put this file somewhere in your project and refer from there:

```bash
# update meta fields with dynamic id
fin exec "wp post meta update $cf7_id _form < $PROJECT_ROOT/config/c7meta/_form.txt"
```

Feel free to re-open if you still have questions.
