### ISSUE TITLE
Wordpress example project gets 403: Access Forbidden

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#306]
While installing a [Wordpress example](https://github.com/docksal/wordpress) site via `fin project create` finishes successfully, the project is inaccessible after install. 

<img width="429" alt="403" src="https://user-images.githubusercontent.com/402007/29042037-4e4c8c3c-7b83-11e7-900f-ff148ae4850a.png">

As described [here](https://gitter.im/docksal/community-support?at=59848797c101bc4e3aeb04f4) the issue is that Docksal's Apache lacks setting:

```
DirectoryIndex index.php
```

Indeed, providing this setting via `.htaccess` resolves the issue:

```bash
echo "DirectoryIndex index.php" > docroot/.htaccess
``` 

There's either a need to include this directive in Apache config inside `service-web` or a need to update `init` script for Wordpress example site.

**Comment by lmakarov** [comment]
Yeah, this is a regression/change from docksal/web:1.0 to docksal/web:2.0 images - there is no more a `DirectoryIndex index.php` statement in the Apache configs.

While I'd expect WP to ship with it's own `.htaccess` files, I also think that serving a broader use case of any LAMP app out of the box is something we want to handle in Docksal. That would include serving `index.php` by default and thus should be part of the `docksal/web` images.

**Comment by lmakarov** [comment]
There is a new hotfix release for `docksal/web:2.0` images, which addresses this issues with WP.
To pull the new image versions do `fin update --project-images` inside the WP project folder.
