### ISSUE TITLE
Feature Request: Docksal Slack

### ISSUE THREAD

**Issue by aczietlow** [docksal/docksal#308]
## Problem/feature description: 
As a developer working at a firm relying on docksal
I want a tool to facilitate open conversations about docksal
So that as a community we can solve common challenges without always requiring the maintainers to find time in their busy days.

 e.g. The Pantheon [power-user](https://pantheon.io/docs/power-users/) slack.

As a note, this is something I am willing to help get set up.

**Comment by lmakarov** [comment]
We do have a community-support room in Gitter: https://gitter.im/docksal/community-support
Are you asking for a power-users room specifically or Slack specifically vs Gitter? :)

**Comment by aczietlow** [comment]
Gitter sounds great. I just hadn't seen it posted anywhere so I didn't know it existed.

**Comment by achekulaev** [comment]
We have it mentioned twice here https://github.com/docksal/docksal but yeah nowhere on the Readthedocs @lmakarov

**Comment by lmakarov** [comment]
I added the Gitter chat room link on docksal.io

**Comment by tdhouibi** [comment]
Hi aczieltlow ,
do you know how can i add Torifier http://www.torifier.com/  this Browser Tor to the phpCode:
// start Firefox with 5 second timeout
$host = 'http://localhost:4444/wd/hub'; // this is the default
$capabilities = DesiredCapabilities::firefox();
$driver = RemoteWebDriver::create($host, $capabilities, 5000);
$driver->get('https://www.example.com')

thankyou
Tarek
