### ISSUE TITLE
Missing page http://docs.docksal.io/en/v1.4.0/advanced/folder-aliases

### ISSUE THREAD

**Issue by fjmk** [docksal/docksal#309]
**Description**

The page http://docs.docksal.io/en/v1.4.0/advanced/folder-aliases, linked from Release page https://github.com/docksal/docksal/releases/tag/v1.4.0 gives the error: ```This page does not exist yet.```

**Comment by lmakarov** [comment]
Updated the [link](http://docs.docksal.io/en/v1.4.0/fin/aliases/). Thanks for reporting!
