### ISSUE TITLE
Automate updates for Docksal's portable installer script

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#316]
Whenever there is a new release of Docksal, the portable installer script (https://get.docksal.io/portable) should be updated automatically.

Alternatively it may make sense to bundle that into fin directly or into an addon.

**Comment by achekulaev** [comment]
Way stale ticket. Close?

**Comment by lmakarov** [comment]
Yeah... Portable has not been a wildly (if at all) used feature. R.I.P.
