### ISSUE TITLE
fin init issue

### ISSUE THREAD

**Issue by sivaarigela** [docksal/docksal#318]
I'm getting this same issue:
i was using windows10

**ERROR: for drupal8_cli_1 Cannot start service cli: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/drupal8_project_root/_data': error while mounting voluCreating drupal8_db_1 ... error

ERROR: for drupal8_db_1 Cannot start service db: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/drupal8_project_root/_data': error while mounting volume with options: type='none' device='/c/Users/VSCADMIN/.babun/cygwin/home/VSCADMIN/drupal8' o='bind': no such file or directory

ERROR: for db Cannot start service db: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/drupal8_project_root/_data': error while mounting volume with options: type='none' device='/c/Users/VSCADMIN/.babun/cygwin/home/VSCADMIN/drupal8' o='bind': no such file or directory

ERROR: for cli Cannot start service cli: error while mounting volume '/mnt/sda1/var/lib/docker/volumes/drupal8_project_root/_data': error while mounting volume with options: type='none' device='/c/Users/VSCADMIN/.babun/cygwin/home/VSCADMIN/drupal8' o='bind': no such file or directory
Encountered errors while bringing up the project.**

Can You Please help me on that isuue

**Comment by lmakarov** [comment]
When creating new issues, please follow the issue submission template. The information requested there helps the maintainers better understand the issue and will usually expedite a response and resolution.

The problem you are having is a non-working SMB mount, which is, unfortunately, very common on Windows. We have a troubleshooting guide for Windows users -
 http://docs.docksal.io/en/develop/troubleshooting-smb

If you are still having issues after following through the guide, then #117 would be the appropriate place to followup.
