### ISSUE TITLE
How to setup a phpstorm project?

### ISSUE THREAD

**Issue by MKorostoff** [docksal/docksal#32]
In [`xdebug.md`](https://github.com/docksal/docksal/blob/develop/docs/xdebug.md), step three is "Open your project in PHPStorm" but how do I create the project.  Here's what I did so far:

1. Clicked File > New Project From Existing Files
![1](https://cloud.githubusercontent.com/assets/1197335/20147276/72bc2e94-a675-11e6-8d94-ea565cd04b72.png)

2. Selected "webserver on remote host, files are accessible via network
![2](https://cloud.githubusercontent.com/assets/1197335/20147322/9d4b9f5a-a675-11e6-8457-fa94ca40938b.png)

3. Filled out the next screen as follows:
![3](https://cloud.githubusercontent.com/assets/1197335/20147385/db5a22e4-a675-11e6-8213-a0c2eac50481.png)

4. Chose "add a new server"
![4](https://cloud.githubusercontent.com/assets/1197335/20147454/20ce997c-a676-11e6-9e61-4ea9350cf828.png)

5. What goes here?
![5](https://cloud.githubusercontent.com/assets/1197335/20147504/5b71312a-a676-11e6-978e-683fcaeeb8e0.png)

6. My files are all in one directory, but if I choose the project root, I get this error:

![6](https://cloud.githubusercontent.com/assets/1197335/20147566/a0d239da-a676-11e6-80df-168c79a14ba1.png)

**Comment by lmakarov** [comment]
I have not used the Wizard to configure a project in PHPStorm in quite a while.
I use `File > Open Directory` and call it done :)

**Comment by MKorostoff** [comment]
Thanks!  That worked 👍
