### ISSUE TITLE
Add an ability to manage multiple databases

### ISSUE THREAD

**Issue by dealancer** [docksal/docksal#323]
Right now I run following if I want to add a new DB programmatically:

```
echo "DROP DATABASE IF EXISTS mvp; CREATE DATABASE mvp; GRANT ALL PRIVILEGES ON mvp.* TO 'user'@'%' WITH GRANT OPTION;" | fin db import
```

There are a couple of problems:

1. By default, DB import uses default DB to execute commands.
2. Not very convenient to run all these lines of code.

**Comment by achekulaev** [comment]
I don't completely get the inquiry. You need `fin db create`?

**Comment by dealancer** [comment]
@achekulaev I am actually thinking about two options:

1. Using `docksal.env` or `docksal.yml` for defining multiple databases.

or 

2. Using `fin db create`, `fin db drop` commands.

**Comment by dealancer** [comment]
Also is there a way to import SQL dump into a specific database?

e.g. `fin db import --db=[name] ~/dump.sql`?

**Comment by dealancer** [comment]
I have found couple of example in https://github.com/docksal/drupal7-advanced/blob/master/.docksal/commands/init#L147

**Comment by lmakarov** [comment]
@dealancer `fin db import --db=[name] ~/dump.sql` will work. See `fin help db` or docs [here](http://docs.docksal.io/en/master/fin/fin/)

**Comment by achekulaev** [comment]
There is now an improved way to manage databases https://medium.com/docksal/better-database-management-with-docksal-1-5-0-cae7cbf12438
