### ISSUE TITLE
Docsal is not working in windows10

### ISSUE THREAD

**Issue by sivaarigela** [docksal/docksal#324]
Hi Team,
 
I am trying to install docsal in my windows10. I am trouble with the below issue, can you please help me on that.
 
“error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.”

![docsal error](https://user-images.githubusercontent.com/20301034/29549275-e0cacd38-8724-11e7-8dff-00c7457442fa.jpg)

**Comment by lmakarov** [comment]
@sivaarigela please follow the New issue template, when creating an issue. Specifically, we need:

- steps to reproduce the issue
- output from `fin sysinfo`
- output from `fin config`

At a high level, it looks like you are having the same issues as before (https://github.com/docksal/docksal/issues/217#issuecomment-323270814)

Have you already followed the troubleshooting guide for Windows users?
http://docs.docksal.io/en/develop/troubleshooting-smb/

**Comment by achekulaev** [comment]
Closing for 7 days of inactivity
