### ISSUE TITLE
CLI healthcheck fails on project create

### ISSUE THREAD

**Issue by mf-lit** [docksal/docksal#325]
**Description**

(Possibly related to [#311](https://github.com/docksal/docksal/issues/311) but this is on Ubuntu 17.04)
My first time trying docksal, no problems with installation, but fails on project creation due to (bogus?) healthcheck failure.

**Steps to reproduce the issue:**

```
$  mkdir test
$  cd test
$  fin -v
WARNING: No swap limit support
1.22.0
$  docker -v
Docker version 17.06.0-ce, build 02c1d87
$  docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED              STATUS              PORTS                                                    NAMES
8b7c131f269d        docksal/ssh-agent:1.0     "/run.sh ssh-agent"      About a minute ago   Up About a minute                                                            docksal-ssh-agent
22c647ea9559        docksal/dns:1.0           "/opt/entrypoint.s..."   About a minute ago   Up About a minute   192.168.64.100:53->53/udp                                docksal-dns
6c97d04f0e51        docksal/vhost-proxy:1.1   "docker-entrypoint..."   About a minute ago   Up About a minute   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
~/temp/sal_sbl/test  $  fin project create
WARNING: No swap limit support
Please enter the name of your project (all one word, no spaces or slashes): mytest

What would you like to install?
[1] Drupal 7
[2] Drupal 8
[3] Wordpress
[4] Magento
[5] Static HTML site

: 1

Your site will be created at /home/marc/temp/sal_sbl/test/mytest
Your site will run Drupal 7
The URL of your site will be http://mytest.docksal

Do you wish to proceed? [y/n]: y
Cloning repository...
Cloning into 'mytest'...
remote: Counting objects: 2501, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 2501 (delta 2), reused 8 (delta 2), pack-reused 2492
Receiving objects: 100% (2501/2501), 3.87 MiB | 4.42 MiB/s, done.
Resolving deltas: 100% (1023/1023), done.
WARNING: No swap limit support
Step 1  Initializing local project configuration...
Making site directory writable...
Copying /home/marc/temp/sal_sbl/test/mytest/docroot/sites/default/settings.local.php...
Step 2  Recreating services...
WARNING: No swap limit support
Removing containers...
Removing network mytest_default
WARNING: Network mytest_default not found.
Removing volume mytest_project_root
WARNING: Volume mytest_project_root not found.
Volume docksal_ssh_agent is external, skipping
Enter passphrase for /root/.ssh/id_rsa: 
Identity added: id_rsa (id_rsa)
Starting services...
Creating network "mytest_default" with the default driver
Creating volume "mytest_project_root" with local driver
Creating mytest_db_1 ... 
Creating mytest_cli_1 ... 
Creating mytest_db_1
Creating mytest_cli_1 ... done
Creating mytest_web_1 ... 
Creating mytest_web_1 ... done
Waiting for mytest_cli_1 to become ready...
Waiting for mytest_cli_1 to become ready...
Waiting for mytest_cli_1 to become ready...
Waiting for mytest_cli_1 to become ready...
Waiting for mytest_cli_1 to become ready...
Waiting for mytest_cli_1 to become ready...
Waiting for mytest_cli_1 to become ready...
ERROR:  mytest_cli_1 heathcheck failed
        Container did not enter a healthy state within the expected amount of time.
        Try fin restart
~/temp/sal_sbl/test  $  docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
c1497ba51a9f        docksal/web:2.0-apache2.4   "httpd-foreground"       47 seconds ago      Up 46 seconds             80/tcp, 443/tcp                                          mytest_web_1
8f5b16cdb62b        docksal/cli:1.3-php5        "/opt/startup.sh s..."   48 seconds ago      Up 47 seconds (healthy)   22/tcp, 9000/tcp                                         mytest_cli_1
9b9ee92b38b6        docksal/db:1.1-mysql-5.6    "/entrypoint.sh my..."   48 seconds ago      Up 48 seconds             0.0.0.0:32773->3306/tcp                                  mytest_db_1
8b7c131f269d        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      3 minutes ago       Up 3 minutes                                                                       docksal-ssh-agent
22c647ea9559        docksal/dns:1.0             "/opt/entrypoint.s..."   3 minutes ago       Up 3 minutes              192.168.64.100:53->53/udp                                docksal-dns
6c97d04f0e51        docksal/vhost-proxy:1.1     "docker-entrypoint..."   3 minutes ago       Up 3 minutes              192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
~/temp/sal_sbl/test  $  docker exec -it mytest_cli_1 /bin/bash
root@cli:/var/www# /opt/healthcheck.sh ; echo $?
0
root@cli:/var/www# exit
```

**Describe the results you received:**

New docksal project fails to create

**Describe the results you expected:**

Expected behavior...

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
$  fin config
WARNING: No swap limit support
---------------------
COMPOSE_PROJECT_NAME_SAFE: salsbl
COMPOSE_FILE:
/home/marc/.docksal/stacks/volumes-bind.yml
/home/marc/temp/sal_sbl/.docksal/docksal.yml
ENV_FILE:
/home/marc/temp/sal_sbl/.docksal/docksal.env

PROJECT_ROOT: /home/marc/temp/sal_sbl
DOCROOT: docroot
VIRTUAL_HOST: salsbl.docksal
VIRTUAL_HOST_ALIASES: *.salsbl.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      HOST_GID: '1000'
      HOST_UID: '1000'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php7
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 3306/tcp
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.0-apache2.4
    labels:
      io.docksal.project-root: /home/marc/temp/sal_sbl
      io.docksal.virtual-host: salsbl.docksal,*.salsbl.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  project_root:
    driver: local
    driver_opts:
      device: /home/marc/temp/sal_sbl
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
$  fin sysinfo
WARNING: No swap limit support
███  OS & BASICS
Linux 9360 4.12.6-041206-generic #201708111232 SMP Fri Aug 11 16:34:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 17.04
fin version: 1.22.0
Mode:  Native / Docker for Mac/Windows
███  DOCKER
DOCKER_HOST:	

Docker: Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
WARNING: No swap limit support
███  DOCKER: IMAGES
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
docksal/web                   2.0-apache2.4       7f75db9a6aa7        2 weeks ago         87.5MB
docksal/vhost-proxy           1.1                 898fb21e7f2d        2 weeks ago         158MB
docksal/cli                   1.3-php7            1442dc481915        3 weeks ago         752MB
docksal/cli                   1.3-php5            77f9a2e141fa        3 weeks ago         808MB
docksal/db                    1.1-mysql-5.6       6feb79af9597        4 weeks ago         298MB
docksal/dns                   1.0                 20c7a535479d        7 months ago        61.6MB
docksal/ssh-agent             1.0                 148220cc033d        7 months ago        12.2MB
<<<RETRACTED>>>
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                   PORTS                                                    NAMES
c1497ba51a9f        docksal/web:2.0-apache2.4   "httpd-foreground"       8 minutes ago       Up 8 minutes             80/tcp, 443/tcp                                          mytest_web_1
8f5b16cdb62b        docksal/cli:1.3-php5        "/opt/startup.sh s..."   8 minutes ago       Up 8 minutes (healthy)   22/tcp, 9000/tcp                                         mytest_cli_1
9b9ee92b38b6        docksal/db:1.1-mysql-5.6    "/entrypoint.sh my..."   8 minutes ago       Up 8 minutes             0.0.0.0:32773->3306/tcp                                  mytest_db_1
8b7c131f269d        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      10 minutes ago      Up 10 minutes                                                                     docksal-ssh-agent
22c647ea9559        docksal/dns:1.0             "/opt/entrypoint.s..."   10 minutes ago      Up 10 minutes            192.168.64.100:53->53/udp                                docksal-dns
6c97d04f0e51        docksal/vhost-proxy:1.1     "docker-entrypoint..."   11 minutes ago      Up 10 minutes            192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.23r116680
███  NETWORK INTERFACES

  ```

</details>

**Comment by mf-lit** [comment]
A bit more investigation shows that the healthcheck doesn't go "healthy" for quite a long time (longer than `fin init` will wait for it). It appears that /var/run/cli takes a long time to be created when the cli container comes up. I'm just having a look into why....

**Comment by mf-lit** [comment]
This `chown` is taking over 35 seconds to complete! Hence the timeout:
https://github.com/docksal/service-cli/blob/1234a4b6b7917493a9e626788d50a08ac7d79fff/startup.sh#L40

**Comment by lmakarov** [comment]
@mf-lit thanks for investigating this all the way to the root cause!

That `chown` operation should not be taking this long at all. Can you try the steps below and compare the results with mine? I ran this on my Mac and in a Ubuntu VM, with similar results.

```
leonid@ubuntu-vm:~/projects$ fin docker run -it --rm docksal/cli:1.3-php7 bash
WARNING: No swap limit support
WARNING: No swap limit support
docker@00160ae69ef8:/var/www$ time sudo chown 1000:1000 -R /home/docker

real	0m0.929s
user	0m0.020s
sys	0m0.368s
docker@00160ae69ef8:/var/www$ 
```

**Comment by achekulaev** [comment]
@mf-lit maybe you just have a lot of files in the project?
Could you run `find . -type f | wc -l` and tell the result?

**Comment by lmakarov** [comment]
@achekulaev docksal/drupal7 is used here, so it's as slim as it gets.

I tested on Ubuntu using the php5 version of cli (used in docksal/drupal7) - similar results:

```
fin docker run -it --rm docksal/cli:1.3-php5 bash
WARNING: No swap limit support
WARNING: No swap limit support
docker@3a6b174fc10a:/var/www$ time sudo chown 1000:1000 -R /home/docker

real	0m0.464s
user	0m0.012s
sys	0m0.248s
docker@3a6b174fc10a:/var/www$ 
```

**Comment by achekulaev** [comment]
Maybe there's some anti-virus installed on the system?

**Comment by mf-lit** [comment]
Interestingly, the time for the chown once the container is up is minimal:

```
$  fin docker run -it --rm docksal/cli:1.3-php5 bash
WARNING: No swap limit support
WARNING: No swap limit support
docker@ab40c4737c7d:/var/www$ time sudo chown 1000:1000 -R /home/docker

real	0m0.139s
user	0m0.018s
sys	0m0.113s

```
However, it's still taking over 35 seconds to actually reach the bash prompt in order to run that `time` command.

This led me to test a bit further, modifying startup.sh to add `time` to the chown command:

```
$  fin docker run -it --entrypoint /bin/bash clitest -x /opt/startup.sh supervisord
WARNING: No swap limit support
WARNING: No swap limit support
+ HOME_DIR=/home/docker
+ DEBUG=0
+ [[ supervisord == \s\u\p\e\r\v\i\s\o\r\d ]]
+ DEBUG=1
+ [[ '' != '' ]]
+ [[ 0 != '' ]]
+ [[ 0 != \0 ]]
+ echo-debug 'Resetting permissions on /home/docker and /var/www...'
+ [[ 1 != 0 ]]
+ echo 'Resetting permissions on /home/docker and /var/www...'
Resetting permissions on /home/docker and /var/www...
+ chown : -R /home/docker
+ chown : /var/www

real	0m0.002s
user	0m0.002s
sys	0m0.000s
+ echo-debug 'Preliminary initialization completed'
+ [[ 1 != 0 ]]
+ echo 'Preliminary initialization completed'
Preliminary initialization completed
+ touch /var/run/cli
+ echo-debug 'Executing the requested command...'
+ [[ 1 != 0 ]]
+ echo 'Executing the requested command...'
Executing the requested command...
+ [[ supervisord == \s\u\p\e\r\v\i\s\o\r\d ]]
+ gosu root supervisord -c /etc/supervisor/conf.d/supervisord.conf
2017-08-23 10:23:10,611 CRIT Supervisor running as root (no user in config file)
2017-08-23 10:23:10,621 INFO RPC interface 'supervisor' initialized
2017-08-23 10:23:10,621 INFO supervisord started with pid 50
2017-08-23 10:23:11,623 INFO spawned: 'sshd' with pid 57
2017-08-23 10:23:11,625 INFO spawned: 'php-fpm' with pid 58
2017-08-23 10:23:11,769 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140096210094992 for <Subprocess at 140096210324368 with name php-fpm in state STARTING> (stdout)>
2017-08-23 10:23:11,782 DEBG fd 15 closed, stopped monitoring <POutputDispatcher at 140096210095280 for <Subprocess at 140096210324368 with name php-fpm in state STARTING> (stderr)>
2017-08-23 10:23:12,783 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-08-23 10:23:12,783 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

```
So, it's not actually chown that's taking 35 seconds, however it's clearly observable that the container is effectively hung for ~35 seconds while the chown is taking place.

I don't really know how to debug this further now. Any suggestions?

**Comment by mf-lit** [comment]
Interestingly, the time for the chown once the container is up is minimal:

```
$  fin docker run -it --rm docksal/cli:1.3-php5 bash
WARNING: No swap limit support
WARNING: No swap limit support
docker@ab40c4737c7d:/var/www$ time sudo chown 1000:1000 -R /home/docker

real	0m0.139s
user	0m0.018s
sys	0m0.113s

```
However, it's still taking over 35 seconds to actually reach the bash prompt in order to run that `time` command.

This led me to test a bit further, modifying startup.sh to add `time` to the chown command:

```
$  fin docker run -it --entrypoint /bin/bash clitest -x /opt/startup.sh supervisord
WARNING: No swap limit support
WARNING: No swap limit support
+ HOME_DIR=/home/docker
+ DEBUG=0
+ [[ supervisord == \s\u\p\e\r\v\i\s\o\r\d ]]
+ DEBUG=1
+ [[ '' != '' ]]
+ [[ 0 != '' ]]
+ [[ 0 != \0 ]]
+ echo-debug 'Resetting permissions on /home/docker and /var/www...'
+ [[ 1 != 0 ]]
+ echo 'Resetting permissions on /home/docker and /var/www...'
Resetting permissions on /home/docker and /var/www...
+ chown : -R /home/docker

real	0m37.844s
user	0m0.052s
sys	0m3.053s
+ chown : /var/www
+ echo-debug 'Preliminary initialization completed'
+ [[ 1 != 0 ]]
+ echo 'Preliminary initialization completed'
Preliminary initialization completed
+ touch /var/run/cli
+ echo-debug 'Executing the requested command...'
+ [[ 1 != 0 ]]
+ echo 'Executing the requested command...'
Executing the requested command...
+ [[ supervisord == \s\u\p\e\r\v\i\s\o\r\d ]]
+ gosu root supervisord -c /etc/supervisor/conf.d/supervisord.conf
2017-08-23 10:29:58,222 CRIT Supervisor running as root (no user in config file)
2017-08-23 10:29:58,233 INFO RPC interface 'supervisor' initialized
2017-08-23 10:29:58,233 INFO supervisord started with pid 51
2017-08-23 10:29:59,235 INFO spawned: 'sshd' with pid 58
2017-08-23 10:29:59,237 INFO spawned: 'php-fpm' with pid 59
2017-08-23 10:29:59,371 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 139819236666256 for <Subprocess at 139819236895632 with name php-fpm in state STARTING> (stdout)>
2017-08-23 10:29:59,380 DEBG fd 15 closed, stopped monitoring <POutputDispatcher at 139819236666544 for <Subproc
```

**Comment by mf-lit** [comment]
Also, for the record:
```# find /home/docker | wc -l
8171
```

**Comment by achekulaev** [comment]
Ha! So it's /home/docker not /var/www that takes long. Very interesting.

**Comment by lmakarov** [comment]
@mf-lit `fin docker info`

**Comment by mf-lit** [comment]
@lmakarov 

```
$  fin docker info
WARNING: No swap limit support
WARNING: No swap limit support
Containers: 196
 Running: 0
 Paused: 0
 Stopped: 196
Images: 184
Server Version: 17.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.12.6-041206-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.681GiB
Name: 9360
ID: 4WR7:LDTE:665X:E7R7:7UCI:GBS6:HGBY:EVSL:4SGQ:IXEG:WP3U:ZEFV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: xxxxx
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by lmakarov** [comment]
@mf-lit with an Ubuntu 17.04 64bit instance on DigitalOcean:

```
root@ubuntu-2gb-nyc3-01:~# fin docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:18:10 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:17:03 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
root@ubuntu-2gb-nyc3-01:~# fin docker info
WARNING: No swap limit support
WARNING: No swap limit support
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-28-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951GiB
Name: ubuntu-2gb-nyc3-01
ID: N34C:OMP6:DZDG:UYTE:F6OH:J6J2:OLZW:SPTG:DQGF:X6EP:7L4L:6UIJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

```
root@ubuntu-2gb-nyc3-01:~# fin docker run -it --rm docksal/cli:1.3-php5 bash
WARNING: No swap limit support
WARNING: No swap limit support
docker@0a063dd55f88:/var/www$ time sudo chown 1000:1000 -R /home/docker

real	0m0.160s
user	0m0.012s
sys	0m0.140s
```

Some key differences: 

- you have `Storage Driver: overlay2` vs `Storage Driver: aufs` on DO.
- you have `Server Version: 17.06.1-ce` vs `Server Version: 17.06.0-ce` - have you manually updated docker just now? You previous output from `fin sysinfo` showed `17.06.0-ce`. Either way this should not contribute to the issue, I just wanted to know what's happening.
- `Containers: 196` and `Images: 184` :scream:

I'd recommend doing `docker system prune` to clean up all those stopped containers and unused images. Then try the `chown` test again.

Switching the storage driver may be a more involved task.

**Comment by achekulaev** [comment]
Interesting. From what I read overlay2 is supposed to be faster that AUFS. I wonder if cached images quantity can indeed impact the performance.

**Comment by mf-lit** [comment]
Sorry it's taken a while to follow up on this.

So, a `docker system prune` made no difference. However, switching storage driver did, bringing the time to chown /home/docker down to less than a second!

Unfortunately this doesn't really help my use-case, my target users are nearly all running Ubuntu 16.04 for which overlay2 is the default driver. Getting them all to change isn't really practical.

It seems unlikely this is an issue with dockersal now, rather it's an issue with docker and/or overlay2. I'd like to open an issue there, but it's proving difficult to create an simple image that I can demonstrate the issue with.

I've tried creating a jessie-based image with several thousand files in it and setting the ENTRYPOINT to be a recursive chown of those file but performance is fine, with both overlay2 and aufs.

I really can't figure out what the root-cause is here.

**Comment by lmakarov** [comment]
My current Ubuntu VM is a 16.04 and uses `aufs`, however, it was upgrades from 14.04, so maybe that's why it does not have `overlayfs2`. However, Ubuntu 17.04 I spun up on DigitalOcean also uses `aufs` out of the box.

According to Docker docs [here](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#docker-ce), Docker will pick `aufs` by default if it is available.

They also list the following storage driver priority order for Docker CE on Ubuntu:

> aufs, devicemapper, overlay2 (Ubuntu 14.04.4 or later, 16.04 or later), overlay, zfs, vfs

However, the docs they say:

> When in doubt, the best all-around configuration is to use a modern Linux distribution with a kernel that supports the overlay2 storage driver, and to use Docker volumes for write-heavy workloads instead of relying on writing data to the container’s writable layer.

It looks like you would get `overlay2` on Ubuntu only via an override.

I'm going to test this on a clean ubuntu-16.04.3-desktop-amd64 install.

**Comment by lmakarov** [comment]
BTW, notice this

> ... use Docker volumes for write-heavy workloads instead of relying on writing data to the container’s writable layer ...

Sounds like `overlay2` is not great at handling write operations and your issues confirm this.

@mf-lit let's try the recommendation to use a volume for write-heavy destinations.

Add/update the `cli` service in `docksal.yml` like this:

```
version: "2.1"

services:
  cli:
    volumes:
      - /home/docker
```

**Comment by lmakarov** [comment]
@mf-lit 

> Unfortunately this doesn't really help my use-case, my target users are nearly all running Ubuntu 16.04 for which overlay2 is the default driver. Getting them all to change isn't really practical.

On a clean ubuntu-16.04.3-desktop-amd64 install (confirmed by several folks):

```
$ fin docker info | grep 'Operating System\|Storage Driver'
Storage Driver: aufs
Operating System: Ubuntu 16.04.3 LTS
```

Ask you users do run this commend and gather some sample data.

I have a strong feeling that the volume workaround will fix your issues with `chown`.
It would be also good to know how you ended up with `overlay2` on your Ubuntu.

**Comment by mf-lit** [comment]
Hmmm... I am able to corroborate your findings.

I've just done clean installs of Ubuntu 16.04 and 17.10 and found in both cases that aufs is the default.

Yet on my desktop (17.04) I don't have aufs at all and I don't seem to be able to enable it either. (I have messed about with the kernel on this machine however so that may be related).

I also have another 17.04 VM that I installed a few week backs and that also defaults to overlay2. Weird weird weird.

Anyway, clearly the majority of our tests have found that aufs is in fact the default for Ubuntu 16/17 (despite a message saying overlay2 [here](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#recommended-extra-packages-for-trusty-1404)) so I don't think this is worth pursuing further.

**Comment by mf-lit** [comment]
> Add/update the cli service in docksal.yml like this:
>
```
version: "2.1"

services:
  cli:
    volumes:
      - /home/docker
```
> 

Yep, that works perfectly! Great suggestion, that will keep me working on my desktop.

Thanks lmakarov

**Comment by lmakarov** [comment]
We are going to write a blog post about `aufs` vs `overlay2` differences. By default we are sticking with and supporting the default storage driver, which is currently `aufs` for Ubuntu.

**Comment by achekulaev** [comment]
So apparently not all Ubuntu installations are equal. I hit exactly the same issue on Scaleway with Ubuntu 1604. 
They have Kernel 4.4 but apparently they do not have `linux-image-extra` modules for this Kernel included in their Ubuntu image so there is no `aufs` driver by default. Hence Docker falls back to `overlay2` leading to the issue described.

```bash
root@scw-6542fb:~/Projects/demo# fin up
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Starting services...
Starting demo_db_1 ... 
Recreating demo_cli_1 ... 
Starting demo_db_1
Recreating demo_cli_1 ... done
Recreating demo_web_1 ... 
Recreating demo_web_1 ... done
Waiting for demo_cli_1 to become ready...
Waiting for demo_cli_1 to become ready...
Waiting for demo_cli_1 to become ready...
Waiting for demo_cli_1 to become ready...
Waiting for demo_cli_1 to become ready...
Waiting for demo_cli_1 to become ready...
Waiting for demo_cli_1 to become ready...
 ERROR:  demo_cli_1 heathcheck failed
         Container did not enter a healthy state within the expected amount of time.
         Try fin restart
```

Workaround with home volume does not seem to work for me.

<details>
  <summary>fin config output</summary>

```
root@scw-6542fb:~/Projects/demo# fin config
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
---------------------
COMPOSE_PROJECT_NAME_SAFE: demo
COMPOSE_FILE:
/root/.docksal/stacks/volumes-bind.yml
/root/.docksal/stacks/stack-default.yml
/root/Projects/demo/.docksal/docksal.yml
ENV_FILE:
/root/Projects/demo/.docksal/docksal.env

PROJECT_ROOT: /root/Projects/demo
DOCROOT: docroot
VIRTUAL_HOST: demo.docksal
VIRTUAL_HOST_ALIASES: *.demo.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '0'
      HOST_UID: '0'
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php7
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /root/Projects/demo
      io.docksal.virtual-host: demo.docksal,*.demo.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
  project_root:
    driver: local
    driver_opts:
      device: /root/Projects/demo
      o: bind
      type: none

---------------------
```
</details>

<br/>

Even with the configuration above that has `/home/docker` as volume I'm still getting the output at the top of this comment (with failure to start the container). 

However it doesn't fail in fact (sic!), it's just Docker **thinks** it has failed. 

```bash
root@scw-6542fb:~/Projects/demo# fin ps
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
   Name                Command             State            Ports          
--------------------------------------------------------------------------
demo_cli_1   /opt/startup.sh supervisord   Up      22/tcp, 9000/tcp        
demo_db_1    /entrypoint.sh mysqld         Up      0.0.0.0:32768->3306/tcp 
demo_web_1   httpd-foreground              Up      443/tcp, 80/tcp         

root@scw-6542fb:~/Projects/demo# fin exec ls
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
docroot
```

As you see containers are fully functional but Docker thinks that cli has never started! So if I will try to access the hostname `vhost-proxy` will try to re-start containers (which will fail of course). 

So it looks more like a bug with setting/getting healthy status with `overlay2` as storage driver, rather than issue with `overlay2` driver per se.

**Comment by frederickjh** [comment]
> We are going to write a blog post about aufs vs overlay2 differences. By default we are sticking with and supporting the default storage driver, which is currently aufs for Ubuntu.

# From [Get Docker CE for Ubuntu](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/)

## If you need to use aufs
**Docker CE now uses the overlay2 storage driver by default, and it is recommended that you use it instead of aufs.** If you need to use aufs, you will need to do additional preparation.

# XENIAL 16.04 AND NEWER

For Ubuntu 16.04 and higher, the Linux kernel includes support for OverlayFS, and Docker CE will use the overlay2 storage driver by default. If you need to use aufs instead, you need to configure it manually. See [aufs
](https://docs.docker.com/engine/userguide/storagedriver/aufs-driver/)
# TRUSTY 14.04

Unless you have a strong reason not to, install the linux-image-extra-* packages, which allow Docker to use the aufs storage drivers.

**Comment by frederickjh** [comment]
> Add/update the cli service in docksal.yml like this:

```
version: "2.1"

services:
  cli:
    volumes:
      - /home/docker
```
Is there a way to globally modify all cli containers with this configuration? I looked through the stack configuration but did not find mention of a ~/.docksal/docksal.yml which is what I thought the global override might be called.

**Comment by lmakarov** [comment]
Looks like the default has changed now for Ubuntu from `aufs` to `overlay2` (this still needs to be confirmed with a real life test on a clean Ubuntu 16.04 LTS and 17.10).

https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#docker-ce
> When possible, overlay2 is the recommended storage driver. When installing Docker for the first time, overlay2 is used by default. Previously, aufs was used by default when available, but this is no longer the case. 

@frederickjh 
> Is there a way to globally modify all cli containers with this configuration?

The default stack configuration is defined in the following two yamls:

https://github.com/docksal/docksal/blob/master/stacks/stack-default.yml
https://github.com/docksal/docksal/blob/master/stacks/services.yml

`fin config generate` uses this static yaml:
https://github.com/docksal/docksal/blob/master/stacks/stack-default-static.yml

Anyone with custom stack definitions (including those starting with `fin config generate`) will have to adjust the home directory volume manually in their site level `docksal.yml` files.

We _could_ include a patch yaml file for this and enforce it on everyone regardless of whether they are using default or custom stacks ([example](https://github.com/docksal/docksal/pull/397)), but I don't think we _should_ do this just yet. This change may come with unclear and unexpected consequences. It should be tested thoroughly before we decide to propagate it across the board.

**Comment by frederickjh** [comment]
OK, Not sure I understand what the consequences could be.
For myself I have created a ~/.docksal/docksal-local.yml file (with the suggested override above) then in a custom fin command that sets up a new site it symlinks to this file into the new project. This is working for me. I suppose I could have had the custom command copy it into the new project instead. I will see if this was the best decision as time pases.

**Comment by alexandar87** [comment]
I can confirm that adding `docksal-local.yml` file, in `.docksal` folder, with following content fixed my init to pass without `heathcheck failed` error:

```
version: "2.1"
services:
  cli:
    volumes:
      - /home/docker
```

**Comment by lmakarov** [comment]
I added the `/home/docker` volume in `stacks/services.yml` so this will be handled automatically with the next release.
