### ISSUE TITLE
MySQL in memory

### ISSUE THREAD

**Issue by ygerasimov** [docksal/docksal#326]
In Drupal development, I reinstall the site all the time (OpenY distro). It takes up to 7 minutes to install (can't do much about it). Is there a way to have MySQL in memory so installation could take shorter. Maybe if it is not feasible to have an alternative database (like SQLite) to make builds faster?

**Comment by lmakarov** [comment]
@ygerasimov it may be possible to put the `/var/lib/mysql` volume on a tmpfs file system (which would be in memory) or use the Memory database engine.

I don't believe SQLite can be faster than MySQL.

If you were dealing with a huge DB import, I'd recommend taking a look at out [Database sandbox mode](http://docs.docksal.io/en/master/advanced/db-sandbox/) docs. However, with full reinstalls that may not be as useful.

**Comment by ygerasimov** [comment]
moving mysql to memory doesn't give much boost on my ssd drives laptop. I think we can safely close this ticket.
