### ISSUE TITLE
Sometimes removing docker machine does not remove reference to the disk file in the VirtualBox media registry

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#339]
In some rare cases (ex. #337 ) removing docker machine via `docker-machine rm` glitches and does not remove files completely. 

We need to ensure it's deletion by deleting `~/.docker/machines/machine/docksal` forcibely if it was not removed by `docker-machine` itself.

**Comment by lmakarov** [comment]
The force flag in `docker-machine rm -f` should handle that and that's what we are already using.
Are you saying that that still leaves some leftovers?

```
$ docker-machine rm --help
...
   --force, -f	Remove local configuration even if machine cannot be removed, also implies an automatic yes (`-y`)
...
```

**Comment by achekulaev** [comment]
So the issue was that the reference to the disk file had still lingered in VirtualBox media registry.
https://github.com/docksal/docksal/issues/337#issuecomment-326570225

**Comment by lmakarov** [comment]
Closing as won't fix, as this was an edge case.
