### ISSUE TITLE
Warning each time `fin drupal` is executed

### ISSUE THREAD

**Issue by MKorostoff** [docksal/docksal#34]
In #33 I reported a work around needed to make drupal console run.  Once that is complete, however, there is still a warning which displays every time you invoke `fin drupal`:

```
The configuration "date.timezone" was missing and overwritten with "America/Tijuana".
```

![warning](https://cloud.githubusercontent.com/assets/1197335/20224418/679e664c-a80c-11e6-804d-8f1900fb51a8.png)

I'm currently just ignoring it.

**Comment by david-hernandez** [comment]
This happens all the time with console. https://hechoendrupal.gitbooks.io/drupal-console/content/en/drupal_console_faq/installation-problems.html

I'm not sure the long-term fix. It is a setting in php.ini, so I suppose one could argue it should be added in the default when Docksal uses, but I imagine we resist setting time zone specific stuff.

**Comment by lmakarov** [comment]
We can probably set `date.timezone = "UTC"` in the default php-fpm and php-cli settings.
Users can then override those if desired.

**Comment by lmakarov** [comment]
docksal/cli images have been updated. `date.timezone = "UTC"`is now set by default.
