### ISSUE TITLE
Drush version compatible with Drupal 7?

### ISSUE THREAD

**Issue by welly** [docksal/docksal#341]
I'm doing some work on a legacy project, the Drush version installed (8.1.11) isn't compatible with Drupal 7. Is there some config that lets me specify an earlier version?

Thanks

**Comment by achekulaev** [comment]
You can run Drush 7 in this way:

```
fin exec drush7 status
```

I'm not sure though what you mean by "incompatible" because I have Drupal 7 projects and running  drush 8.1 works fine for them.  E.g.

```
$ fin drush st
The following module has moved within the file system: <em class="placeholder">file_entity</em>. In order to fix this, clear caches or put the module back in its original location. For more    [warning]
information, see <a href="https://www.drupal.org/node/2487215">the documentation page</a>. bootstrap.inc:1143
The following module is missing from the file system: <em class="placeholder">views_php</em>. For information about how to fix this, see <a href="https://www.drupal.org/node/2487215">the       [warning]
documentation page</a>. bootstrap.inc:1143
 Drupal version                  :  7.56                                                                                             
 Site URI                        :  http://default                                                                                   
 Database driver                 :  mysql                                                                                            
 Database hostname               :  db                                                                                               
 Database username               :  user                                                                                             
 Database name                   :  default                                                                                          
 Database                        :  Connected                                                                                        
 Drupal bootstrap                :  Successful                                                                                       
 Drupal user                     :                                                                                                   
 Default theme                   :  clientname                                                                                        
 Administration theme            :  seven                                                                                            
 PHP configuration               :  /etc/php5/cli/php.ini                                                                            
 PHP OS                          :  Linux                                                                                            
 Drush script                    :  /usr/local/bin/drush                                                                             
 Drush version                   :  8.1.10                                                                                           
 Drush temp directory            :  /tmp                                                                                             
 Drush configuration             :  /home/docker/.drush/drushrc.php                                                                  
 Drush alias files               :  /var/www/drush/aliases/aliases.drushrc.php /var/www/docroot/../drush/aliases/aliases.drushrc.php 
 Install profile                 :  acquia                                                                                           
 Drupal root                     :  /var/www/docroot                                                                                 
 Drupal Settings File            :  sites/default/settings.php                                                                       
 Site path                       :  sites/default                                                                                    
 File directory path             :  files                                                                                            
 Private file directory path     :  files/private                                                                                    
 Temporary file directory path   :  /tmp              
```

**Comment by welly** [comment]
Running **fin drush en -y nodequeue**, for instance, results in the following:

> [31-Aug-2017 17:20:15 Europe/London] PHP Fatal error:  Declaration of Drush\Command\DrushInputAdapter::hasParameterOption() must be compatible with Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false) in phar:///usr/local/bin/drush/lib/Drush/Command/DrushInputAdapter.php on line 27
> 
> Fatal error: Declaration of Drush\Command\DrushInputAdapter::hasParameterOption() must be compatible with Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false) in phar:///usr/local/bin/drush/lib/Drush/Command/DrushInputAdapter.php on line 27
> Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                                                                                 [error]
> Error: Declaration of Drush\Command\DrushInputAdapter::hasParameterOption() must be compatible with Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false) in
> phar:///usr/local/bin/drush/lib/Drush/Command/DrushInputAdapter.php, line 27

On further investigation, I found this: https://github.com/wodby/drupal-nginx/issues/21 although a bit further investigation reports other version of Drush 8 are:

https://github.com/drush-ops/drush/issues/2415

**Comment by achekulaev** [comment]
Are you sure your site is running Drupal 7? Could you share `fin drush status` output? 

The error I see looks like if you were running Drupal 8 with a core version that is higher, than the one compatible with Drush 8.1.10. I had projects like that and in that case I had to install latest drush version into the project with `composer`.

**Comment by welly** [comment]
Where's the emoji for shooting oneself in the head? I hadn't run composer install.

Apologies.
