### ISSUE TITLE
Auto-fix of NFS conflicts edge cases

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#343]
There are some edge cases that need to be processed

1) if Projects folder already exists but it's case is different from `Projects` e.g. it's `projects`
2) if Projects folder already exists and contains Vagrant projects. Auto-fixing will fail. Looks like it happened once already.

<img width="690" alt="edgecase" src="https://user-images.githubusercontent.com/402007/29986889-6bac0b40-8f33-11e7-8ce6-def6727179dc.png">

**Comment by achekulaev** [comment]
In 1.7 we might want to move to Docker for Mac as a default option. This makes this ticket less likely to be addressed.

**Comment by achekulaev** [comment]
I'm inclined to close this ticket because VirtualBox is likely going to be phased out. @lmakarov

**Comment by lmakarov** [comment]
@achekulaev agreed, we don't want to spend time on edge cases for something that will be deprecated soon. Closing.
