### ISSUE TITLE
fin update doesn't install dependencies, only self-updates, on Windows 10 64-bit by default

### ISSUE THREAD

**Issue by mradcliffe** [docksal/docksal#346]
**Description**

I cannot use docksal on a Windows 64-bit system because

1. babun does not have a stable 64-bit release / process.
2. cygwin64 does have a stable 64-bit release that babun's documentation recommends to use instead of babun, but docksal is having issues detecting custom commands or running update.

**Steps to reproduce the issue:**

**With babun**

1. Try to install babun
2. Get Unexpected error message. Give up. Do not use docksal?

**With cywgin64**

1. Install cygwin64 via 64-bit installer. Make sure to include php and curl packages that are required for Drupal 8.4 core development.
2. Downloaded fin shell script to `C:\cygwin64\usr\local\bin\`.
3. Tried running `fin vm start` per instructions. Failed beacuse docker not available.
4. Tried running `fin update` per failed command above's recommendation. Fails to run fin update because the update command uses `sudo` instead of trying the winsudo function that fin defines.
5. Tried just running `fin init`:
   - `git clone https://github.com/BrianGilbert/docksal-core-sprint`
   - `cd docksal-core-sprint`
   - `fin init`
6. Try hacking fin shell script and keep running into hard errors. Give up.

**Describe the results you received:**

Tried to run `fin vm start` per docksal instructions...
```
$ fin vm start
docker-machine executable was not found. (Try running 'fin update')
```

Okay, now I tried `fin update`...
```
$ fin update
Updating fin...
/usr/local/bin/fin: line 3222: sudo: command not found
 ERROR:  Could not write /usr/local/bin/fin.updated
```

Okay, let's hack the update function to use winsudo instead...
```
$ fin update
Updating fin...
/usr/local/bin/fin: line 3231: /usr/local/bin/fin.updated: No such file or directory
fin  downloaded...
/usr/local/bin/fin: line 3235: /usr/local/bin/fin.updated: No such file or directory
```

**Describe the results you expected:**

I expect that I can use docksal on a Windows 10 64-bit system because the System Requirements for docksal do not mention needing to use 32-bit binaries.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
$ fin config output
 ERROR:  No configuration files found.
         Expected in C:/cygwin64/c/dev/docksal-core-sprint/.docksal/docksal.yml
```

But the file does in fact exist at `/cygdrive/c/dev/docksal-core-sprint/.docksal/docksal.yml` so for some reason fin config is using the Windows path and not the cygdrive path.
</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
$ fin sysinfo
███  OS & BASICS
CYGWIN_NT-10.0 MACHINENAME 2.8.2(0.313/5/3) 2017-07-12 10:58 x86_64 Cygwin
 Microsoft Windows [Version 10.0.14393]
fin version: 1.26.2
Mode:  VirtualBox VM
███  DOCKER
DOCKER_HOST:

/usr/local/bin/fin: line 3952: docker: command not found
Docker:
███  DOCKER COMPOSE
/usr/local/bin/fin: line 3955: docker-compose: command not found
Docker Compose:
███  VIRTUALBOX
5.1.26r117224
███  NETWORK INTERFACES
Name:            VirtualBox Host-Only Ethernet Adapter #4
GUID:            b9fa8fae-681d-43c6-a9e0-a6a7bf345a3c
DHCP:            Disabled
IPAddress:       192.168.253.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:8c39:7422:7a53:ad4b
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:0a
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #4

Name:            VirtualBox Host-Only Ethernet Adapter #3
GUID:            fe6eed92-3843-477c-aec9-5b3d5de3869b
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:59d7:c791:196f:97b1
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:0c
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #3
  ```

</details>

**Comment by mradcliffe** [comment]
This seems to be different than #337 because of the errors involved in that issue are completely different than my expected output.

**Comment by lmakarov** [comment]
32bit application work just fine on a 64bit Windows host, so that's not the issue here.

> Get Unexpected error message. Give up. Do not use docksal?

Can you share more details on this?

We have plenty of Windows 10 x64 users. I'm also personally testing Docksal on Windows using Windows 10 Pro 64bit (in a VMware VM).

**Comment by mradcliffe** [comment]
> Can you share more details on this?

Not really. babun installer's output is literally 
```
[babun] Installing babun
Error: was unexpected at this time.
```

There doesn't seem to be any relevant solutions in babun's issue queue. Though I just noticed that turning echo on might reveal the actual error.

Ah, IZArc extractor isn't keeping the directories the same. Ugh, I hate Windows...

**Comment by mradcliffe** [comment]
It's still disappointing that docksal is restricted to 32-bit on Windows. I'm not sure why it can't be run using cygwin64 rather than babun following babun's own recommendation?

**Comment by mradcliffe** [comment]
With babun 32-bit installed I run into similar issues that I ran into using cygwin directly.

```
{ USER }  » fin vm start                                     /cygdrive/c/Users/USER
docker-machine executable was not found. (Try running 'fin update')
{ USER }  » fin update                                     /cygdrive/c/Users/USER 1
Updating fin...
/usr/local/bin/fin: line 3231: /usr/local/bin/fin.updated: No such file or directory
fin  downloaded...
/usr/local/bin/fin: line 3235: /usr/local/bin/fin.updated: No such file or directory
```

**Comment by mradcliffe** [comment]
If I manually rename fin to fin.updated then it doesn't try a full update and starts to go.

**Comment by achekulaev** [comment]
Docksal requires 64-bit system.

**Comment by achekulaev** [comment]
I don't see where you run `curl -L get.docksal.io | sh`. Looks like you installed things manually. That's your choice but I don't think we can do much here.

**Comment by mradcliffe** [comment]
Yes, I absolutely did not run that command because it is a security risk and absolutely poor practice. It does not matter how trustworthy the source encouraging this behavior is poor practice. I'll probably be packaging fin / fin.updated separately in order to make it work to not encourage this behavior.

I do not see how that shell script runs fin.updated. [It runs a full update](https://github.com/docksal/docksal/blob/develop/bin/fin#L3190), which creates fin.updated (and  may or may not succeed because permissions on some systems), but then it would not get the dependencies because fin.updated isn't the calling script and would only try to update itself again. At least that's the behavior on Windows. It seems that the undocumented options for update might have a different behavior, but I don't see the curl'd shell script using those.

I think there are two follow-up issues here:

1. Improve the documentation to remove use of security risks:
   * Rewrite the native docker documentation. The first part of script is already part of the instructions anyway so it's not necessary.
   * Remove any mention of using curl.
   * Add documentation to install a _proper_ release of fin for the operating system rather than running an arbitrary shell script from a web site.
      * MacOS/Linux/Babun: `install -m 0755 fin /usr/local/bin/`
      * Run `fin install` to update dependencies (see below).
      * Or add to update's help to list the possible options and encourage to use those.
2. Improve fin so that update is split into its respective parts: 
   * An update command of its dependencies (update?).
   * An install command of its dependencies (install?).
   * Remove the self-update as that is also a security risk in my opinion despite numerous software packages offering it. It's also prone to fail on systems that restrict permissions.

**Comment by mradcliffe** [comment]
Improved the issue title.

**Comment by achekulaev** [comment]
Thanks for your feedback but I don't see how installation via curl from a **proven** source it is less secure that downloading setup.exe and mindlessly clicking next-next-next-finish, which I bet everyone did at least once.

**Comment by lmakarov** [comment]
@mradcliffe I'd suggest you removing Babun, reboot (we did have a user having issues with Babun, which were gone after the host machine was rebooted), then follow the official [Docksal installation instructions for Windows](http://docs.docksal.io/en/master/getting-started/env-setup/#installing-docksal-on-windows).

You can replace the `curl -fsSL get.docksal.io | sh` step with the commands below (that is the code behind get.docksal.io) if that looks safer:

```
sudo mkdir -p /usr/local/bin &&
sudo curl -fsSL https://raw.githubusercontent.com/docksal/docksal/master/bin/fin -o /usr/local/bin/fin &&
sudo chmod +x /usr/local/bin/fin &&
fin update
```

Report back if you run into issues.

**Comment by mradcliffe** [comment]
> Thanks for your feedback but I don't see how installation via curl from a proven source it is less secure than downloading setup.exe and mindlessly clicking next-next-next-finish, which I bet everyone did at least once.

@achekulaev, as I mentioned earlier it is not about how trustworthy the site is. It is about encouraging poor behavior, and that is precisely why it is poor practice. We should empower and spread knowledge in users instead of a simple shortcut that does not provide feedback as to what it's doing to your system. And what are we sacrificing for this poor behavior? 4 commands. That's it. And furthermore it bypasses the users' choice.

I think it is important that we are stewards of knowledge rather than gatekeepers of knowledge. 

In another argument against curl|bash scripts from an ops perspective, I would not install software this way. I would definitely want to track software with a package management or some other manner of hash checking.

> You can replace the curl -fsSL get.docksal.io | sh step with the commands below (that is the code behind get.docksal.io) if that looks safer:

Thank you, @lmakarov, I have already done this when I tested native docker on linux and my current Windows 10 testing. I concluded with a successful implementation of a docksal environment on Windows 10 and in linux, but not without having to hack fin/fin.updated per my comments above. I think the next step is to break out the update into several commands (or document the update command options) so that it doesn't need to do this weird fin.updated check to install dependencies as I noted above.

**Comment by lmakarov** [comment]
> I concluded with a successful implementation of a docksal environment on Windows 10 and in linux, but not without having to hack fin/fin.updated per my comments above

@mradcliffe, glad you got it working in both Linux and Windows.

It is still not clear why you had to hack anything. Docksal's install/update process works just fine on a clean Mac, Linux (including [automated tests in Travis CI](https://travis-ci.org/docksal/docksal)) or Windows system, assuming you follow the instructions as written.

Being not able to reproduce the issues you reported, I can only assume, that you have some kind of custom setup/permissions/etc. (which we know nothing about), which is causing those difficulties in your case.

**Comment by achekulaev** [comment]
> encouraging poor behavior

You do not provide any solid arguments to back your opinion about "poor behavior".
Arguments like this:
> does not provide feedback as to what it's doing to your system

are applicable to **any** binary installer whether it's EXE, MSI, PKG or even apt-get. Exception is only DMG files on macOS where user just copies a file. 

Furthermore, a ton of popular software uses this way of installation. To name a few: [Brew](https://brew.sh/), [Composer](https://getcomposer.org/download/), Docker itself used to use it for a long time and get.docker.com still provides a robust way to install Docker on Linux.

One line installer helps novice users to get software installed. And we have seen **tremendous** positive feedback from that group of users after we moved from 4 commands to 1, because for them those 4 lines make no more sense than 1 line.

To conclude: 
- Popular software used by thousands use this way of installation
- Novice users love this way of installation
- Advanced users are able to see what is going on. It is not hard. It's 4 lines of bash.

With all said above I fin this way of installation not only not poor, but purely great for command line utilities.

**Comment by mradcliffe** [comment]
> are applicable to any installer whether it's EXE, MSI, PKG or even apt-get. Exception is only DMG files on macOS where user just copies a file.

This is not a true for open source software. curl|shell scripts (most likely) lack

1. A configurable install routine 
2. An uninstall routine
3. Are not as reliable as packages with checksum
4. Makes it more difficult to debug because it is obfuscated, which leads to a more frustrating experience

Installers _can_ be less verbose, but for the most part there is suitable documentation around packages that describe its dependency chain, where it installs to, etc...

> Furthermore, a ton of popular software uses this way of installation. To name a few: Brew, Composer, Docker itself used to use it for a long time and get.docker.com still provides a robust way to install Docker on Linux.

And no one should use this method of installation. Composer for instance it is recommended not to install from curl, but use an actual release. Docker can be compiled and installed via packages (this is what I do). Brew, while I'm not as familiar with, also provides a lot of verbosity and is built around the package mentality (I hope you find this ironic to your argument). So your point here is completely false?

> One line installer helps novice users to get software installed

I have not disputed this? I dispute that it is in the best interest of everyone to obfuscate and hide installation routines and configurability from users.

Furthermore obfuscation makes it harder to troubleshoot, and it took a long time to figure out where errors were actually occurring (albeit much of this was with babun which has the same problem).

> With all said above I find this way of installation not only not poor, but purely great for command line utilities.

So in essence because it is popular it is good? That is not a good argument based on false assumptions, and does not address the points that I have made . We should provide not the software, but teach those about software as well.

However I think more important than trying to argue about curl|bash I would like some feedback on my proposed solutions for more documenation and improving fin update by splitting out the commands. At this point I am unsure whether I should continue to collaborate and contribute back to this project.

**Comment by achekulaev** [comment]
Looks like you are trying to compose suitable installation of Docksal. If you need help with doing that, we can definitely advice how to mitigate certain issues. However we have limited resources and this is an enthusiastic project, so we do not have ability to work through every possible scenario of customization. 

One-liner is an _easy_ way to install Docksal, even with certain drawbacks it provides an ability for users to easily get Docker based local web-development environment. The whole purpose of Docksal is to make achieving that goal as easy as possible. 

To the matter of the ticket. Most likely your issues running `fin update` are related to the permissions issue with `/usr/local/bin` that should be writable for current user or the fact that this dir is missing.

In relation to the documentation:

- If you have any specific requests related to Docker Native documentation that you could outline in a separate ticket, we can append that activity to the backlog.
- `fin update` installs proper (latest) version of Docksal. I would not recommend installing non-latest version unless there is a breaking bug, but there is a way to install certain Docksal version with `DOCKSAL_VERSION=v1.5.1 fin update` where `DOCKER_VERSION` specifies a tag in the repo.
- dependencies are inseparable from features, that's why update process is universal and updates all parts. Arbitrary version of fin can not work with arbitrary version of docker, docker-compose or boot2docker, as well as arbitrary version of docker-compose can not work with arbitrary version of docker etc. That's why we test them as a solution and update as a solution.

We are always glad to see contributions to the project, but not every contributions will get accepted as-is. Despite it might feel discouraging for those who propose contributions, it protects the core of the software that current users liked.
