### ISSUE TITLE
Feature: env and stack files on DOCKSAL_ENVIRONMENT variable

### ISSUE THREAD

**Issue by b-connect** [docksal/docksal#352]
It would be nice to declare stack and env files depending on a enviroment variable. 

Like ```DOCKSAL_ENVIRONMENT=prod```

Load order
- docksal.env
- docksal.prod.env
- docksal-local.env

**Comment by b-connect** [comment]
For now we add this code in our docksal.env

```
if [ "$DOCKSAL_ENVIRONMENT" != "" ]; then
  DOCKSAL_ENVIRONMENT=local
fi
DOCKSLA_ENV_FILE="$(get_project_path_dc)/.docksal/docksal.${DOCKSAL_ENVIRONMENT}.env"
if [ -f $DOCKSLA_ENV_FILE ]; then
  source $DOCKSLA_ENV_FILE
fi
```

**Comment by achekulaev** [comment]
Fixed in the referenced PR
