### ISSUE TITLE
`init` is gone?

### ISSUE THREAD

**Issue by RoloDMonkey** [docksal/docksal#355]
**Steps to reproduce the issue:**

1. On the command line: `fin init`

**Describe the results you received:**

> Unknown command init. See 'fin help' for list of available commands.

**Describe the results you expected:**

I expected Docksal to build a new environment based on the folder I set up.

**Comment by lmakarov** [comment]
`init` is a custom, per project command. Custom commands are stored in `.docksal/commands` in the project repo. E.g. https://github.com/docksal/drupal8/tree/master/.docksal/commands

Docs on custom commands: http://docs.docksal.io/en/master/fin/custom-commands/

**Comment by RoloDMonkey** [comment]
Doh!

I was looking at the "Setup instructions" help page, instead of the "Project setup" page; which are both different from the "Docksal setup" page.

You have to admit, those titles can be a little confusing :)
