### ISSUE TITLE
Docksal for Windows -  driver failed programming external connectivity on endpoint docksal-vhost-proxy

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#358]
**Description**

I switched to using native docker support on Windows. It seems like it's almost working after running `fin reset system` but I run into a permission denied issue that I'm not sure how to handle. Any thoughts? I followed the Docksal on Windows setup instructions to a T http://docksal.readthedocs.io/en/master/getting-started/env-setup/#windows. I can confirm the containers do get downloaded.

```
{ ~ }  » docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/vhost-proxy   1.1                 898fb21e7f2d        6 weeks ago         158MB
docksal/dns           1.0                 20c7a535479d        8 months ago        61.6MB
docksal/ssh-agent     1.0                 148220cc033d        8 months ago        12.2MB
```

**Steps to reproduce the issue:**

1. Switch to Native Docker in Docksal for Windows.
2. `fin reset system`

**Describe the results you received:**

```
{ ~ }  » fin reset system
Resetting network settings...
Resetting Docksal services...
 * proxy
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (c42d83088a9116d1127c26f81405d35a8d9c3718ba9888fa57716dfc7f2ab49d): Error starting userland proxy: Bind for 192.168.64.100:80: unexpected error Permission denied.
 * dns and resolver for .docksal domain
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
 * ssh-agent
Identity added: id_rsa (id_rsa)

```

**Describe the results you expected:**

I expected the system to be successfully reset and Docksal services to start running without error.

**Comment by lpeabody** [comment]
Maybe related https://github.com/moby/moby/issues/20486

**Comment by lpeabody** [comment]
Running the commands indicated in this comment allowed me to bind to port 80. https://stackoverflow.com/questions/1430141/port-80-is-being-used-by-system-pid-4-what-is-that#comment71116139_1430165

**Comment by lmakarov** [comment]
We have separate instructions for Docker for Mac/Windows - http://docksal.readthedocs.io/en/master/getting-started/env-setup-native/
This is the so called "native mode". Support for it is experimental, but it should be usable.

Regarding port 80 - this would be true for any environment. If another app is binding to the wildcard `0.0.0.0:80` endpoint on the machine, then `docksal-vhost-proxy` won't be able to bind to its `192.168.64.100:80` endpoint. You do have to stop or configure the other server to not use the wildcard endpoint and use a specific `IP:Port` instead.

**Comment by lpeabody** [comment]
@lmakarov Yes, the permission denied issue was a little vague though compared to other error messages I saw out there specifically saying the port was already in use. By shutting down W3SVC I was able to bind to 80. Would be nice to have that in documentation since, well, Windows isn't the best at administrative interfaces...

**Comment by lpeabody** [comment]
PS - I have Docksal working in native mode on Windows now and am happily doing Drupal dev. Thanks again for a great product.

**Comment by lmakarov** [comment]
This is covered in the troubleshooting section in docs :)
http://docs.docksal.io/en/master/troubleshooting/#conflicting-ports

We also have an issue in the queue to improve the way port conflicts for vhost-proxy are handled:
https://github.com/docksal/docksal/issues/176

**Comment by lpeabody** [comment]
@lmakarov It is kind of covered, in the cases of Linux for the most part. Windows is a different beast altogether though. In the case of Windows 10, I had to scour the interwebz for what in the heck could be binding to port 80 even though I had nothing like Apache installed on my system.

What I'm trying to get at is, anybody setting up Docksal on Windows 10 using the onboarding instructions you've provided in the setup section are going to run into port conflicts with W3SVC.

I'll call out the specific commands I used to disable W3SVC here:

```
sc stop w3svc
sc config w3svc start= disabled
```

After that, I was able to run `fin reset system` successfully. I think this will be the case whether you're running Docker Native through Hyper-V or regular ol' Docker Machine through VirtualBox.

**Comment by lmakarov** [comment]
Agreed. I added that to the todo list in the scope of https://github.com/docksal/docksal/issues/176

**Comment by fuzzbomb** [comment]
I also ran into these bind errors, for ports 53 and 443, but can safely say it wasn't due to having a copy of Apache running locally.  I was running a fresh install of Kubuntu 17.10 and followed the intructions for the initial Docksal setup.

I don't fully understand what was stopping the bind working, but running these commands fixed things for me.  They are based on the READMEs from [docksal/service-dns](https://github.com/docksal/service-dns) and [docksal/service-vhost-proxy](https://github.com/docksal/service-vhost-proxy) respectively:

`docker rm docksal-vhost-proxy`

`docker run -d --name docksal-vhost-proxy --label "io.docksal.group=system" --restart=always --privileged --userns=host  -p "${DOCKSAL_VHOST_PROXY_PORT_HTTP:-80}":80 -p "${DOCKSAL_VHOST_PROXY_PORT_HTTPS:-443}":443  -e PROJECT_INACTIVITY_TIMEOUT="${PROJECT_INACTIVITY_TIMEOUT:-0}"  -v /var/run/docker.sock:/var/run/docker.sock  docksal/vhost-proxy`

`docker rm docksal-dns`

`docker run -d  --name docksal-dns --label "io.docksal.group=system" --restart=always -e DNS_DOMAIN=docksal -e DNS_IP=192.168.64.100 docksal/dns`

**Comment by lmakarov** [comment]
> I was running a fresh install of Kubuntu 17.10 and followed the intructions for the initial Docksal setup.

@fuzzbomb do you happen to have the installation logs?
Also, it's great that you figured out how to manually launch individual Docksal system services, but we have a handy shortcut for that :)

```
fin reset system
```

And please post the logs if you run into this again!

**Comment by tdowgielewicz** [comment]
in my case it was docker-compose up command executed from cmd.exe instead from powershell

**Comment by achekulaev** [comment]
``` anybody setting up Docksal on Windows 10 using the onboarding instructions you've provided in the setup section are going to run into port conflicts with W3SVC.```

Thanks for clearing up that it was the IIS. At the same time I was setting up Docksal on a clean Windows 10 Pro recently and frankly speaking I did not run into port collusion issues.

**Comment by davekopecek** [comment]
While w3svc is the most likely culprit for this issue, it's worth noting that "SQL Server Reporting Services (MSSQLSERVER)" is sneaky and binds to port 80 by default and will also show up as 0.0.0.0:80 PID 4.  This can be changed with these instructions: `https://seankilleen.com/2012/11/how-to-stop-sql-server-reporting-services-from-using-port-80-on-your-server-field-notes/`.  Or just shut it off in services.

**Comment by ronakganatra9** [comment]
I have just changed my port number in yaml file and it worked for me
