### ISSUE TITLE
Docksal with Docker for Windows - Volume directory not created?

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#359]
**Description**

After running `fin init` for a project, I expect the project's services to be spun up and started. 

**Steps to reproduce the issue:**

1. Clone project using Docksal.
2. Run `fin init`. It either runs `fin start` or `fin reset -f` depending on if the services exist already.

**Describe the results you received:**

```
{ baxter-corvette } master » fin init
 Step 1  Creating services...
One second! Checking for updates...
Starting services...
Creating network "baxtercorvette_default" with the default driver
Creating volume "baxtercorvette_project_root" with local driver
Pulling cli (lpeabody/blt-cli:latest)...
latest: Pulling from lpeabody/blt-cli
Digest: sha256:40b6e6bc504b67ddd6cb76a7e6d18fbc73e20fa37f308a4022b7456a6a467b3f
Status: Downloaded newer image for lpeabody/blt-cli:latest
Pulling web (docksal/web:2.1-apache2.4)...
2.1-apache2.4: Pulling from docksal/web
Digest: sha256:37982a727ea90117c8655bea7849a9fe2838e303e0eaed44c50952ac9798517a
Status: Downloaded newer image for docksal/web:2.1-apache2.4
Pulling varnish (docksal/varnish:1.0-varnish4)...
1.0-varnish4: Pulling from docksal/varnish
Digest: sha256:71c3c17f0ae51c05e2b9692a5ab601b1840447b759db7738d7744d6bc8c3ec97
Status: Downloaded newer image for docksal/varnish:1.0-varnish4
Pulling memcached (memcached:1.4-alpine)...
1.4-alpine: Pulling from library/memcached
Digest: sha256:3741668c175a68f9fb2ba453461105534d639e9a772ef09120ce63de7f4da8c6
Status: Downloaded newer image for memcached:1.4-alpine
Pulling db (docksal/db:1.1-mysql-5.6)...
1.1-mysql-5.6: Pulling from docksal/db
Digest: sha256:621af7593a933b98f417734c1500db51df43c8900624cb33be098142b1856753
Status: Downloaded newer image for docksal/db:1.1-mysql-5.6
Pulling solr (docksal/solr:1.0-solr4)...
1.0-solr4: Pulling from docksal/solr
Digest: sha256:f32c32a8e5dd2fc563b631f6b0ac4bd9b2753148b882ea1364cf97eb156272c6
Status: Downloaded newer image for docksal/solr:1.0-solr4
Creating baxtercorvette_solr_1 ...
Creating baxtercorvette_memcached_1 ...
Creating baxtercorvette_cli_1 ...
Creating baxtercorvette_db_1 ...
Creating baxtercorvette_solr_1
Creating baxtercorvette_memcached_1
Creating baxtercorvette_db_1
Creating baxtercorvette_cli_1 ... error

ERROR: for baxtercorvette_cli_1  Cannot start service cli: error while mounting volume '/var/lib/docker/volumes/baxtercorvette_project_root/_data': error while mounting volume with options: type='none' device='/c/Users/lpeabody/.babun/cygwin/home/lpeabody/Sites/baxter-corvette' o='bind': no such filCreating baxtercorvette_db_1 ... error

ERROR: for baxtercorvette_db_1  Cannot start service db: error while mounting volume '/var/lib/docker/volumes/baxtercorvette_project_root/_data': error while mounting volume with options: type='none' device='/c/Users/lpeabody/.babun/cygwin/home/lpeabody/Sites/baxter-corvette' o='bind': no such file or directory

ERROR: for db  Cannot start service db: error while mounting volume '/var/lib/docker/volumes/baxtercorvette_project_root/_data': error while mounting volume with options: type='none' device='/c/Users/lpeabody/.babun/cygwin/home/lpeabody/Sites/baxter-corvette' o='bind': no such file or directory

ERROR: for cli  Cannot start service cli: error while mounting volume '/var/lib/docker/volumes/baxtercorvette_project_root/_data': error while mounting volume with options: type='none' device='/c/Users/lpeabody/.babun/cygwin/home/lpeabody/Sites/baxter-corvette' o='bind': no such file or directory
Encountered errors while bringing up the project.
```

**Describe the results you expected:**

I expected the project to have it's services successfully start without error. I can confirm that the directory C:\Users\lpeabody\.babun\cygwin\home\lpeabody\Sites\baxter-corvette does in fact exist. Or is this error referring to the mount directory /var/lib/docker/volumes/baxtercorvette_project_root? Because that directory definitely does NOT exist. What creates it?

I have to wonder if issue #358 is related.

**Comment by lmakarov** [comment]
@lpeabody these errors indicate that the SMB share was either not created or not mounted in the VM. Please post the output from `fin sysinfo` and `fin config`

Try `fin vm mount` and post the output here.

Also, I'd recommend using `/c/projects` (`C:\projects`) as the root directory for your projects, but this is not a hard requirement.

**Comment by lpeabody** [comment]
@lmakarov Thanks for the recommendation, it is nicer keeping a shorter project path for usre.

I'm using Docker for Windows (I may yet try to get Docker Machine working instead, though Docker for Windows is performing very well), and I have this solved.

I had to open up Docker for Windows settings (right click in tray and select Settings...), click Shared Drives, and check off whichever drive is going to be storing your volume data. In my case I just have C checked for now.

Restart Docker and then try spinning up your Docksal project again with `fin start`, it should work fine.

**Comment by lmakarov** [comment]
I think that is something we should add to the native mode docs. That definitely won't be obvious to anyone new to Docker for Windows. Going to keep this open as a documentation update request.

**Comment by achekulaev** [comment]
Added to docs ^

**Comment by lmakarov** [comment]
Actually already added via df019a92eddae011945e71cdedc914e77bd6eff1
