### ISSUE TITLE
Error when pulling images: "read: connection reset by peer"

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#36]
```
Pulling cli (docksal/cli:php7)...
ERROR: Get https://registry-1.docker.io/v2/docksal/cli/manifests/php7: read tcp 10.0.2.15:48440->52.206.180.136:443: read: connection reset by peer
```

Looks like there is an issue with the latest VirtualBox version (5.1.8).
It is being discussed here https://github.com/docker/docker/issues/27734

Downgrading to 5.1.6 (on Mac) solves the problem for now.

**Comment by geerlingguy** [comment]
5.1.10 should also fix the issue; was just released a couple days ago.

**Comment by lmakarov** [comment]
@geerlingguy thanks for pointing that out.

We now have to wait until docker/boot2docker 1.13.0 is released. It will include the matching version of VirtualBox Guest Additions 

https://github.com/boot2docker/boot2docker/releases/tag/v1.13.0-rc2

**Comment by lmakarov** [comment]
We've switched to boot2docker [1.12.6](https://github.com/boot2docker/boot2docker/releases/tag/v1.12.6), which comes with the VirtualBox Guest Additions v5.1.12.

Docksal 1.0.0-RC2 now requires VirtualBox v5.1.12
