### ISSUE TITLE
Docksal update notifications misleading - pressing enter doesn't install update

### ISSUE THREAD

**Issue by charginghawk** [docksal/docksal#360]
**Description**

First, let me say I really like Docksal.

For a long time now, I've thought that when I get a Docksal update notification ("UPDATE AVAILABLE, fin x.x --> x.y, Press Enter to continue"), pressing enter would install the update.

I just realized this isn't the case. I mentioned it to my team and they were also surprised that pressing enter doesn't update. But this explained why we had been having issues where people weren't using the latest version like they thought they were.

**Steps to reproduce the issue:**

1. Get update notification
2. Misunderstand
3. Think you've updated Docksal but not actually

**Describe the results you received:**

"I'm still on x.x? What? I thought I updated to x.y?"

**Describe the results you expected:**

"Oh, this update notification makes it clear that installing the update is an additional step."

**Comment by lpeabody** [comment]
Maybe something like instead of "Press Enter to continue." we got "Would you like to update now? [y/N]" with a default to no. It's implicitly defaulting to no currently because forcing an update after notifying you the first time is not really a user friendly experience.

I do think providing the option is a good idea though.

**Comment by charginghawk** [comment]
I think giving the user an option to update right then and there is a good idea. I just don't know what the repercussions might be of starting an update in the middle of whatever process they could be running. Updates can probably be pretty disruptive, but then you can probably restrict update notifications to processes where updates wouldn't be as disruptive (say, only show them on fin up).

My current PR is a one line fix that just adds "You can update after this process by running fin update" to the notification, so it's a simple bug fix that clears up the confusion. Adding an option to update in the notification strikes me as more of a feature request.
