### ISSUE TITLE
VM corrupts after the computer sleeps for an extended period.

### ISSUE THREAD

**Issue by david-hernandez** [docksal/docksal#373]
**Description**

When my computer is a sleep for an extended period of time, like over the weekend, when I come back Docksal no longer works. The VM powers off but will not work after turning back on.

When I run any command I get this:

```
It looks like 'docksal' docker machine is not running.
Run 'fin vm start' to start it now? [y/n]: y
Starting "docksal"...
(docksal) Check network to re-create if needed...
listen tcp4 127.0.0.1:49852: bind: address already in use
Could not start Docksal docker machine properly
```
If I run `fin status` I get this:

```
$ fin status
Cannot connect to the Docker daemon at tcp://192.168.64.100:2376. Is the docker daemon running?
Cannot connect to the Docker daemon at tcp://192.168.64.100:2376. Is the docker daemon running?
 ERROR:  Looks like your Docker client and Docker server are incompatible.
         Run fin update to update.
```
Fin update doesn't appear to be relevant. It doesn't update anything.

When it gets in this state the only thing that seems to work is to manually destroy the VM and let Docksal make a new one.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

fin config does not work. Same result as above.

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
Darwin Davids-MBP-3.home 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
Mac OS X 10.12.6
fin version: 1.27.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
docksal   -        virtualbox   Stopped                 Unknown   
███  DOCKER
DOCKER_HOST:	

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Docker: Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.12.2, build 9371605
███  VIRTUALBOX
5.1.22r115126
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS
# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
  ```

</details>

**Comment by david-hernandez** [comment]
This doesn't appear to happen when my computer sleeps over night. Only when I go an extended time without using Docksal. Like multiple days. I'm not sure if it is from the computer sleeping or just not using Docksal.

**Comment by david-hernandez** [comment]
I removed the VM and let docksal recreate it. The above errors went away, but it still did not work. Docksal would go through the steps to setup sites, whatever `fin init` required, but they dont actually work. The sites do not respond.

I rebooted and this is what I see in Virtual Box.

![screen shot 2017-10-16 at 4 22 17 pm](https://user-images.githubusercontent.com/1504038/31633452-728fd2e2-b28e-11e7-8f32-372a1bef6417.png)

**Comment by david-hernandez** [comment]
Confirming that after rebooting, and removing the VM again after the error above, it works again.

**Comment by achekulaev** [comment]
So it happens regularly for you? Every time after an extended sleep you have issues with the VM? Did you try to restart your macBook? I suspect there might be issues with VBox drivers and maybe time synchronization.

**Comment by david-hernandez** [comment]
@achekulaev When it happens it is after not using docksal or the computer for a while. Overnight does not do it, but the weekend does. I don't know if the issue is not using docksal or not using the computer. A regular sleep does not cause it.

When it does happen, I have to reboot the computer to fix it. What I described above is after rebooting. (the NS_ERROR_FAILURE) so a reboot doesn't fix it without going through the steps to remove the VM and add a new one. Removing the VM before rebooting does not fix it.

**Comment by david-hernandez** [comment]
It has happened again. I used my computer on Saturday, but not Sunday, and now Monday morning it is giving me that problem.

```$ fin status
One second! Checking for updates...
It looks like 'docksal' docker machine is not running.
Run 'fin vm start' to start it now? [y/n]:```

**Comment by david-hernandez** [comment]
Ive upgraded virtualbox to 5.1.30. I was on 5.1.22. I'll see if that helps.

**Comment by Kerby70** [comment]
I am seeing this same `bind: address already in use` error.

**Comment by lmakarov** [comment]
@Kerby70 do you have to manually stop the vm from the VirtualBox UI or would `fin vm restart` also work?

**Comment by Kerby70** [comment]
I had to use the UI, `fin vm restart` returns:
`Stopping "docksal"...
Machine "docksal" is already stopped.
Starting "docksal"...
(docksal) Check network to re-create if needed...
listen tcp4 127.0.0.1:50606: bind: address already in use`

**Comment by david-hernandez** [comment]
Another weird thing that both John and I were seeing, the vm would show as stopped and fin would not run commands, but the websites still worked. Even when I told virtual box to stop the vm, I think the websites continued working. Weird.

**Comment by lmakarov** [comment]
@david-hernandez this can only happen if you have two instances of VirtualBox running at the same time - one under your user and another one under root. Have you or @Kerby70 been using `sudo` with any fin command?

**Comment by lmakarov** [comment]
I've finally figured out where those port bind errors are coming from

![image](https://user-images.githubusercontent.com/1205005/32129112-c894904e-bb38-11e7-8989-28d5a2071a22.png)

That's the ssh port mapping on the NAT interphase of the VM. docker machine uses the port mapping to talk to the VM and do provisioning over SSH. This does not explain why the issues are happening, but at least drops more light on where they are coming from.

**Comment by david-hernandez** [comment]
I updated virtualbox last week to 5.1.30. Today I have the problem again after going the weekend without using Docksal. I did use my laptop, but did not run any fin commands.

I see the port mappings in the vm config, but is there anything to do about it? The fact that the vm completely corrupts is troubling.

**Comment by david-hernandez** [comment]
I don't recall running fin commands with sudo so I don't think that is it.

**Comment by Kerby70** [comment]
Mine on vbox 5.1.22 has also failed again. My technique of turning the box off from the UI and starting failed.
```
fin vm start
Starting "docksal"...
/usr/local/bin/VBoxManage showvminfo docksal --machinereadable failed:
VBoxManage: error: Failed to create the VirtualBox object!
VBoxManage: error: Code NS_ERROR_SOCKET_FAIL (0xC1F30200) - IPC daemon socket error (extended info not available)
VBoxManage: error: Most likely, the VirtualBox COM server is not running or failed to start.
```

**Comment by david-hernandez** [comment]
After rebooting, I get a different error this time. When I logged back into the laptop and checked virtualbox, the vm doesn't show up as corrupt, but docksal can't seem to use it.

```
$ fin start
It looks like 'docksal' docker machine is not running.
Run 'fin vm start' to start it now? [y/n]: y
Starting "docksal"...
(docksal) Check network to re-create if needed...
(docksal) Waiting for an IP...
Machine "docksal" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded
Could not start Docksal docker machine properly
```

**Comment by david-hernandez** [comment]
Here is my fin sysinfo
```
Cannot connect to the Docker daemon at tcp://192.168.64.100:2376. Is the docker daemon running?
███  OS & BASICS
Darwin Davids-MBP-3.home 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
Mac OS X 10.12.6
fin version: 1.27.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           Unknown   Unable to query docker version: Cannot connect to the docker engine endpoint
███  DOCKER
DOCKER_HOST:	tcp://192.168.64.100:2376

Cannot connect to the Docker daemon at tcp://192.168.64.100:2376. Is the docker daemon running?
Docker: Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine version 0.12.2, build 9371605
Cannot connect to the Docker daemon at tcp://192.168.64.100:2376. Is the docker daemon running?
███  VIRTUALBOX
5.1.30r118389
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=1845260k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
```

**Comment by lmakarov** [comment]
@david-hernandez 

Try creating a test docker VM next time you know you will not be using your laptop for a while:

```
$ fin docker-machine create test
```

This will not interfere with the existing Docksal VM. You can see the list of docker-machine managed VMs like this:

```
$ fin docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.06.0-ce   
test      -        virtualbox   Running   tcp://192.168.99.100:2376           v17.10.0-ce   
```

Run that command when you have the issue again and post here the output. Also, ping me in chat so  I can take a closer look at what's going on. I wonder if both VMs will be down or just the Docksal one.

**Comment by Kerby70** [comment]
Closing the VirtualBox App and trying `fin vm start` worked. Could the App act like another VirtualBox vs the CLI?

**Comment by lmakarov** [comment]
@Kerby70

> Closing the VirtualBox App and trying fin vm start worked.

That's interesting. Do you usually keep the VBox UI open? Maybe try keeping it closed and see if the issue reoccurs within a week.

**Comment by achekulaev** [comment]
VirtualBox UI is a headache you don't want to keep it open. VBoxManage (cli utility that manages Vboxes) will sometimes fail to work properly if VirtualBox UI is open.

**Comment by Kerby70** [comment]
Got-it, I had gotten in a habit of leaving it open when working with some other VMs. I will update if I do/don't see the error again.

**Comment by david-hernandez** [comment]
Just to add, I do not usually have the virtualbox app open so I don't think that is related for me.

**Comment by achekulaev** [comment]
@david-hernandez next time you see the error could you reply "no" to that "Do you want to start it now?" question, run `fin docker-machine ls` and post here the output?

And the run `fin vm restart`.

**Comment by david-hernandez** [comment]
Update: after the virtualbox update to 5.1.30 and my last reboot I haven't experienced the problem again. The past two weekends have been ok. If I don't have it again I'll close the issue. John, feel free to keep it open if you are still having problems.

**Comment by lmakarov** [comment]
Interesting. We plan to include VirtualBox 5.1.28 in the next release, which will be using boot2docker 17.09.0, which in turn bundles VirtualBox Guest Additions v5.1.28. Maybe we should bump that up all the way to the most recent VirtualBox version.

**Comment by david-hernandez** [comment]
Just went through this with Leonid. The VM becomes detached somehow. We don't know the cause.  VirtualBox sees it as off, and Docksal sees at as off, but if you open Activity Monitor, there is a process there still running. Something like VirtualBoxHeadless. Killing that process allowed be to restart the VM, but no indication yet why it gets detached. Even using VirtualBox's own cli commands it does not see the VM as running or accessible.

**Comment by lmakarov** [comment]
Adding some more details from the debugging session with @david-hernandez 

```
$ sudo lsof -i tcp:50798
COMMAND     PID           USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
VBoxHeadl 23962 davidhernandez   16u  IPv4 0x2c31bb188bf64231      0t0  TCP localhost:50798 (LISTEN)
```

![image](https://user-images.githubusercontent.com/1205005/33093460-da297a68-ceb1-11e7-9abd-f9d66fbc46c1.png)


Possibly related VirtualBox issues:

- [A running VM is listed as Powered Off](https://www.virtualbox.org/ticket/9223)
- [vboxmanage list runningvms does not list anything](https://www.virtualbox.org/ticket/6808)

In @david-hernandez's case, the detached VBoxHeadless process is running as the his user (not root or another user). Both these commands displayed nothing:

```
$ VBoxManage list runningvm
$ sudo VBoxManage list runningvm
```

**Comment by david-hernandez** [comment]
With the updated virtualbox and perhaps some Docksal updates, I have not experienced this again. Maybe we can close this. @Kerby70 have you experienced this lately?

**Comment by lmakarov** [comment]
> With the updated virtualbox

@david-hernandez Can you please confirm the VirtualBox version you are currently using?

**Comment by Kerby70** [comment]
I have not seen this issue in a while.
I am on:
VirtualBox Version 5.1.22 r115126 (Qt5.6.2)
Docksal Version 1.27.0
Mac OS Version 10.12.6 (16G1114)

I had removed & reinstalling VirtualBox, cleared /etc/exports info & Host-only Networks, and a regular Mac OS security update.

**Comment by david-hernandez** [comment]
5.1.30 r118389

**Comment by lmakarov** [comment]
ok, I'm closing this issue, since there were no recent incidents reported.
