### ISSUE TITLE
How do I execute phantomjs inside cli container?

### ISSUE THREAD

**Issue by ApacheEx** [docksal/docksal#378]
### This is not a bug. It's a question.
Let's imagine:

1) Project has basic LAMP stack (stack-default.yml)
2) I want to have possibility to execute phantomjs insite [cli](https://github.com/docksal/service-cli) container like this
`fin exec "phantomjs --version"`
3) How can I do it? I'm not the docker user, that's why I'm asking 😅 

I thought about add `depends_on` (with [backstopjs](https://github.com/docksal/backstopjs) or [phantomjs](https://hub.docker.com/r/wernight/phantomjs/ ) container) into the cli container inside docksal.yml but it wasn't succeed. It would be cool to have an example.

Thanks in advance. You're making a great project.

**Comment by achekulaev** [comment]
@ApacheEx you want to take a look here https://docksal.readthedocs.io/en/master/tools/behat/

Comment here if you have more questions.
