### ISSUE TITLE
'fin share' does not expose ngrok web UI

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#379]
**Description**

`fin share` command does not expose the ngrok web UI port

**Steps to reproduce the issue:**

1. `fin share`
2. Open http://192.168.64.100:4040

**Describe the results you received:**

```
Session Status                online                                                                                                                                                     
Version                       2.2.8                                                                                                                                                      
Region                        United States (us)                                                                                                                                         
Web Interface                 http://0.0.0.0:4040                                                                                                                                        
Forwarding                    http://6e88f351.ngrok.io -> ymcacw_web_1.ymcacw_default:80                                                                                                 
Forwarding                    https://6e88f351.ngrok.io -> ymcacw_web_1.ymcacw_default:80
```

```
This site can’t be reached

192.168.64.100 refused to connect.
```

**Describe the results you expected:**

Be able to access ngrok web UI.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
N/A
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  N/A
  ```

</details>

**Comment by achekulaev** [comment]
@lmakarov I guess it creates a minor problem that if port 4040 is busy on your localhost there is no way to tell not to expose UI.

**Comment by lmakarov** [comment]
@achekulaev that's the reason we did not do this in the first place. What I did this time instead, is publish 4040 as a random port. You will have to them figure out what the port is. I covered this ins the docs. See the related commit.
