### ISSUE TITLE
Change VHOST Name and reset Container without resetting DB?

### ISSUE THREAD

**Issue by regenrek** [docksal/docksal#380]
Hi,

i want to change the VHOST Name (in docksal.env) for a certain project. Is it possible to recreate the container and don't trash the db ?

fin reset resets everything 

Regards

**Comment by 3mkay** [comment]
Hi there,
fin reset web
Should be enough.
Thanks Mike

On Fri, Nov 10, 2017 at 11:30, kevin regenrek <notifications@github.com> wrote:
Hi,

i want to change the VHOST Name (in docksal.env) for a certain project. Is it possible to recreate the container and don't trash the db ?

fin reset resets everything

Regards

**Comment by achekulaev** [comment]
Hi @regenrek 

`fin up` is enough. `web` container will be re-created. It will not affect your DB container.
