### ISSUE TITLE
fin config set/get <variable>

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#381]
Implement command to manage project level and global Docksal variables.

**Comment by achekulaev** [comment]
Done in https://github.com/docksal/docksal/commit/024ddc1d6ffb1aa56e1dfe534d28031e40c36a55

**Comment by shelane** [comment]
This is a nice usability feature. I don’t see updates in the docs to show usage there. https://github.com/docksal/docksal/blob/develop/docs/fin/fin.md
