### ISSUE TITLE
Document DOCKSAL_ENVIRONMENT variable usage

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#383]
Initially proposed in #354. Implemented in ba61259

**Comment by achekulaev** [comment]
I don't know why we only added ability to control ENV files with DOCKSAL_ENVIRONMENT, probably just forgot about YML. But today I needed to control yml files too so I made a commit above.

**Comment by frederickjh** [comment]
Adding list of variables found in the containers to be added to the documentation:

#### DB
- $MYSQL_ROOT_PASSWORD
- $MYSQL_ALLOW_EMPTY_PASSWORD
- $MYSQL_RANDOM_ROOT_PASSWORD
- $MYSQL_INITDB_SKIP_TZINFO
- $MYSQL_DATABASE
- $MYSQL_USER
- $MYSQL_PASSWORD
- $MYSQL_ONETIME_PASSWORD

#### Web
- $APACHE_BASIC_AUTH_USER
- $APACHE_BASIC_AUTH_PASS
- $APACHE_SERVERNAME

#### Cli
- $DEBUG
- $HOST_UID
- $HOST_GID
- $XDEBUG_ENABLED

Some of these are in the current documentation, but it would be good to have them all in one place.

**Comment by frederickjh** [comment]
It should also be noted in the documentation that changing the following variables (and possibly others listed above) for the DB container will not change these setting by only doing `fin stop` then `fin up`.  

Running `fin reset db` is required to use these settings. This **will destroy the database** and re-import it if this has been setup in the configuration using the new settings.
1. $MYSQL_ROOT_PASSWORD
2. $MYSQL_DATABASE
3. $MYSQL_USER
4. $MYSQL_PASSWORD

**Comment by frederickjh** [comment]
14fee1c09a8cbd45cde6865263c0b553b89fa9e6
Added ability to lock Docksal updates

Set **DOCKSAL_LOCK_UPDATES** to anything in $HOME/.docksal/docksal.env to lock updates. Useful on CI/sandbox servers.

**Comment by frederickjh** [comment]
#### New environmental variables in 1.8.0 release:
Secrets - a way to pass keys/tokens to `cli`
Currently supported: `SECRET_SSH_PRIVATE_KEY`,  `SECRET_ACAPI_EMAIL`, `SECRET_ACAPI_KEY`, `SECRET_TERMINUS_TOKEN`
All secrets should be prefixed with `SECRET_`

**Comment by frederickjh** [comment]
#### From 1.7.0 release notes:
When `CI=true` is set in in `$HOME/.docksal/docksal.env`, vhost-proxy will be open to the world (bind to `0.0.0.0`). This should be used in CI/Sandbox environments.

Does this do the same thing as setting `DOCKSAL_VHOST_PROXY_IP=0.0.0.0` ?

**Comment by frederickjh** [comment]
### from 1.6.0 release notes:

Added backup upstream DNS server for docksal-dns. This addresses cases when **`DOCKSAL_DNS_UPSTREAM`** is set to an internal IP (VPN/LAN) and becomes inaccessible when user disconnects from that network. `8.8.4.4` will now be used as a backup when `DOCKSAL_DNS_UPSTREAM` is not reachable.

**Comment by frederickjh** [comment]
#### from 1.40 release notes:
Prevent NFS conflicts on macOS. (#133)
**`DOCKSAL_NFS_PATH`** can be used to override Docksal projects folder which effectively serves as NFS mount point.

**Comment by frederickjh** [comment]
@achekulaev would it help if I would start an editable pull request with as much information as I know about the Docksal environmental variables?
Where would you see it ending up in the documentation(one of the current pages, a new page)?

**Comment by achekulaev** [comment]
@frederickjh yes, it would! Thanks! A new page `docs/advanced/environment-variables.md`

**Comment by achekulaev** [comment]
Thanks for keeping the list @frederickjh 
It will get done, I promise. This is an obvious documentation gap not to have it documented.

**Comment by frederickjh** [comment]
@achekulaev Now you just making me feel bad. :wink: I did start a new feature branch for this but have not completed it to the point where I am ready to submit a pull request. I need to revisit the work I did on this and finish it the best I can.

**Comment by achekulaev** [comment]
I think this issue ticket be considered by @sean-e-dietrich
