### ISSUE TITLE
Allow overriding DOCKSAL_DNS_DOMAIN to be used when loading configuration

### ISSUE THREAD

**Issue by frederickjh** [docksal/docksal#390]
**Description**
In commit 5566a1ad76846f3a49f8e57741f3478b2f35f30a "Allow overriding DOCKSAL_DNS_DOMAIN", a new Docksal variable was added DOCKSAL_DNS_DOMAIN. This is currently being used in the `install_dns_service ()` function.

I suggest that it should also be used in the `load_configuration ()` function to use the same DNS domain for containers that are started without `VIRTUAL_HOST` being set.

Currently the lines in `load_configuration ()` function read:
```
# Set defaults
export VIRTUAL_HOST=${VIRTUAL_HOST:-$COMPOSE_PROJECT_NAME_SAFE.docksal}
export DOCROOT=${DOCROOT:-docroot}
# Make project root globally available
```
To make this possible the line setting VIRTUAL_HOST could be change to: 
```
# Set defaults
export VIRTUAL_HOST=${VIRTUAL_HOST:-$COMPOSE_PROJECT_NAME_SAFE.$DOCKSAL_DNS_DOMAIN}
```
This will cause project containers to use the DNS domain name in `DOCKSAL_DNS_DOMAIN` and fallback to the default **.docksal** DNS domain if it is empty.

This provides a more complete solution for overidingthe default docksal DNS domain. Currently even after setting the `DOCKSAL_DNS_DOMAIN` variable in `~/.docksal.docksal.env`, one must set the `VIRTUAL_HOST` variable for each and every project to use the new DNS domain.

**Comment by lmakarov** [comment]
Makes sense. Thanks for the suggestion!
