### ISSUE TITLE
Refactor volume mounts from -v to --mount

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#391]
According to the official Docker docs on volumes and binf mounts (https://docs.docker.com/engine/admin/volumes/bind-mounts):

> Tip: New users should use the `--mount` syntax. Experienced users may be more familiar with the `-v` or `--volume` syntax, but are encouraged to use `--mount`, because research has shown it to be easier to use.

> Differences between `-v` and `--mount` behavior
> Because the `-v` and `--volume` flags have been a part of Docker for a long time, their behavior cannot be changed. This means that there is one behavior that is different between `-v` and `--mount`.
> 
> If you use `-v` or `--volume` to bind-mount a file or directory that does not yet exist on the Docker host, `-v` will create the endpoint for you. It is always created as a directory.
> 
> If you use `--mount` to bind-mount a file or directory that does not yet exist on the Docker host, Docker does not automatically create it for you, but generates an error.

**Comment by achekulaev** [comment]
@lmakarov can this one be closed?
