### ISSUE TITLE
Docker for Mac: default ssh keys are not automatically added to docksal-ssh-agent

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#395]
After Docker for Mac is restarted, the default ssh keys from the host are not available in `docksal-ssh-agent`. Running `fin ssh-add` addresses this.

Short term, we should handle this case the same we handle it on Linux - trigger `ssh_add` on up/start/reset.

Long term, we may handle this via `fin docksal start` (See #387).

**Comment by achekulaev** [comment]
https://github.com/docksal/docksal/pull/396
