### ISSUE TITLE
Plea for a heads-up on versions that modify containers or break existing configs

### ISSUE THREAD

**Issue by davekopecek** [docksal/docksal#40]
I get and truly appreciated that you are cranking out versions at a breakneck pace and I've read the `Breaking changes and outdated docs are very possible` warning in README.md , but please, please, please could there be a breaking change heads-up somewhere?  Something as simple as  `BREAKING CHANGE WARNING` in the commit message would be a huge help.

**Comment by lmakarov** [comment]
@davekopecek RC1 is expected to come out tomorrow. With that we will start maintaining the change log and release notes. Thanks for your feedback.

**Comment by david-hernandez** [comment]
For everyone reading, we will also try to post announcements in the Gitter that was setup for Docksal. https://gitter.im/docksal/community-support

**Comment by achekulaev** [comment]
Can we consider this closed? I already started announcing breaking changes in the Gitter's channel.

**Comment by lmakarov** [comment]
Yes, from now on we are going to maintain the change log in [CHANGELOG.md](https://github.com/docksal/docksal/blob/develop/CHANGELOG.md) and on the [releases](https://github.com/docksal/docksal/releases) page as well as make announcements in the Gitter support room.
