### ISSUE TITLE
PHP 5.4 support?

### ISSUE THREAD

**Issue by drubage** [docksal/docksal#409]
Is there a way to spin up Docksal with PHP 5.4 instead of 5.6? I only see 5.6 as the "5" option.

**Comment by lmakarov** [comment]
`docksal/cli` are custom PHP 5.6 and PHP 7.0 images built from Debian.
We are [shifting](https://github.com/docksal/service-cli/pull/13) to building from the [official PHP images](https://hub.docker.com/_/php/) on Docker Hub. All minor PHP versions available on Docker Hub will be supported when that's ready.

There are no plans to support the end of line [PHP versions](http://php.net/supported-versions.php). That is anything below PHP 5.6 at the moment.

**Comment by drubage** [comment]
Aw man! We love Docker so much and would love to be able to use it for legacy projects as well.

**Comment by lmakarov** [comment]
You can always build your own Docker image with a legacy PHP version and use it with Docksal. Self-service to the rescue! ;) 

Unless you have tons of code, that cannot be easily upgraded to run on PHP 5.6, I don't think there is an reason not to upgrade.

**Comment by drubage** [comment]
Have you any documentation on setting up a container like that? Is there a cli template container that is ready for PHP to be installed into it or anything like that? Thanks!!

**Comment by lmakarov** [comment]
@drubage I would wait until https://github.com/docksal/service-cli/pull/13 is merged and then use that setup as a base to add an older PHP version (official images build PHP from source, so adding an older version should not be a huge shift from that).

**Comment by achekulaev** [comment]
@drubage any reason why you need 5.4 specifically?

**Comment by drubage** [comment]
We've got some old projects (mostly I am thinking about non Drupal stuff) that are on really old legacy technology and the clients are unwilling to upgrade (and are willing to accept the security risks). Some clients also host projects themselves and we have no control over their hosting and they cannot upgrade and we want our development environments to match their production environments as much as possible.

**Comment by achekulaev** [comment]
I see. Just saying that I've been there (legacy project) and used 5.6 image with almost no issues apart from some additional warnings/notices I've seen in 5.6 as compared to 5.4. They don't differ that much 5.4 and 5.6. It was not perfect but good enough.

**Comment by drubage** [comment]
I am with you. Again, we want our development environments to match production as best as possible and I guess the biggest reason is that we don't have control over those hosting environments that are stuck on legacy PHP versions.

In this particular case the client is using a really old version of Cake and their server is really old and running PHP 5.4 and their code won't work in 5.6 it seems.

**Comment by achekulaev** [comment]
Gotcha. Yeah... unfortunately compiling 5.4 image is pretty hard because it is legacy version for Linux. So to install php 5.4 to debian (which is a base image for CLI) one would need to use older Debian version or connect legacy distros, which is another can of worms.

As Leonid mentioned above the ongoing work to use official php-fpm images as a base for CLI may allow compiling 5.4 image easier, once that work is done.

**Comment by drubage** [comment]
Awesome! Thanks for all that you do!

**Comment by achekulaev** [comment]
That work is ongoing here you might want to "Watch" ithttps://github.com/docksal/service-cli/pull/13
