### ISSUE TITLE
Cannot get clean install to work on Mac

### ISSUE THREAD

**Issue by DigitalFrontiersMedia** [docksal/docksal#41]
Previously couldn't get Drude to install due to insufficient RAM.  Now I can't get Docksal to install/run correctly.  In the end, the Drupal7 demo fails to run and stops at Step 3 with 
" Step 3  Installing site...
bash: cd: docroot: No such file or directory"

Even though docroot is there and permissioned correctly AFAIK.
http://drupal7.docksal = 404

One apparent error during install.  Though it doesn't really explain the problem in a way that helps me to understand what is so offensive about the finding (old drude issue?):
"Configuring NFS shares...
 ERROR:  exports:2: path contains non-directory or non-existent components: /Users/stephen/Projects
exports:2: no usable directories in export entry
exports:2: using fallback (marked offline): /
exports:5: /Users conflicts with existing export /Users/stephen/Projects"

Installation Session below...

```
MotherPhoenix-3:drupal7 stephen$ sudo curl -L https://raw.githubusercontent.com/docksal/docksal/develop/bin/fin -o /usr/local/bin/fin && \
> sudo chmod +x /usr/local/bin/fin
Password:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 94198  100 94198    0     0   123k      0 --:--:-- --:--:-- --:--:--  292k
MotherPhoenix-3:drupal7 stephen$ sudo nano -c +46 /usr/local/bin/fin
#>>>Re: above-^  - Needed to edit vboxmanage due to case-sensitivity.  Will file separate issue.<<<
MotherPhoenix-3:drupal7 stephen$ fin update
[!] Using Docksal develop branch
Updating fin... 0.10.0 [OK]
Updating default configs...
  services.yml...		[OK]
  stack-acquia.yml...		[OK]
  stack-default.yml...		[OK]
  volumes-bind.yml...		[OK]
  volumes-nfs.yml...		[OK]
  volumes-unison.yml...		[OK]
Installing docker client v1.12.3...
Installing docker-compose v1.8.0...
Installing docker-machine v0.8.2...
MotherPhoenix-3:drupal7 stephen$ fin init
One second! Checking for updates...
 Step 1  Initializing local project configuration...
/Users/stephen/Sites/drupal7/docroot/sites/default/settings.local.php already in place
tests/behat/behat.yml already in place
 Step 2  Creating services...
It looks like 'docksal' docker machine is not running.
Run 'fin vm start' to start it now? [y/n]: y
Creating docker machine 'docksal' (virtualbox)...
Running pre-create checks...
Creating machine...
(docksal) Copying /Users/stephen/.docker/machine/cache/boot2docker.iso to /Users/stephen/.docker/machine/machines/docksal/boot2docker.iso...
(docksal) Creating VirtualBox VM...
(docksal) Creating SSH key...
(docksal) Starting the VM...
(docksal) Check network to re-create if needed...
(docksal) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env docksal
docksal is already active
Exporting env variables for 'docksal'...
Pulling system images...
1.0: Pulling from docksal/vhost-proxy
3690ec4760f9: Pull complete
43ee8fcb29fc: Pull complete
93c2d6979a3a: Pull complete
4846e7b558d8: Pull complete
5747549a3f69: Pull complete
925ee096adf8: Pull complete
7570b017f234: Pull complete
e53eb617aa2c: Pull complete
Digest: sha256:4520e3d9d14bcd461bc4a5c7b2e79506852352f5acdf9b2a2926240d038ce984
Status: Downloaded newer image for docksal/vhost-proxy:1.0
1.0: Pulling from docksal/dns
3690ec4760f9: Already exists
11a23a520de3: Pull complete
1d0004b0c15f: Pull complete
36d47ce4dea5: Pull complete
54542e6ef1bb: Pull complete
7c3d75b9bc15: Pull complete
815740f35694: Pull complete
Digest: sha256:cf9a12c4dcb96779bd101630c61cfbab07d691065370a7f514f7a13ffa8d998b
Status: Downloaded newer image for docksal/dns:1.0
1.0: Pulling from docksal/ssh-agent
3690ec4760f9: Already exists
98dee06d369d: Pull complete
0ddd46a26df8: Pull complete
Digest: sha256:ee4ece8c560a0c20890c709a6a5d1e1f164c283d0a5188b9167ca86b773beceb
Status: Downloaded newer image for docksal/ssh-agent:1.0
Resetting Docksal services...
 * proxy
 * dns and resolver for .docksal domain
 * ssh-agent
Configuring NFS shares...
 ERROR:  exports:2: path contains non-directory or non-existent components: /Users/stephen/Projects
exports:2: no usable directories in export entry
exports:2: using fallback (marked offline): /
exports:5: /Users conflicts with existing export /Users/stephen/Projects
-----------------
# VAGRANT-BEGIN: 502 2f3e57c5-cace-406c-8178-cab3118a05c2
"/Users/stephen/Projects" 192.168.10.10 -alldirs -mapall=502:20
# VAGRANT-END: 502 2f3e57c5-cace-406c-8178-cab3118a05c2
# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
-----------------
Starting services...
Creating network "drupal7_default" with the default driver
Pulling db (docksal/db:1.0-mysql-5.5)...
1.0-mysql-5.5: Pulling from docksal/db
386a066cd84a: Pull complete
827c8d62b332: Pull complete
de135f87677c: Pull complete
05822f26ca6e: Pull complete
581edb358f3e: Pull complete
df4ad3824469: Pull complete
de3fccb307ff: Pull complete
98bc471865b4: Pull complete
0d19ce23241a: Pull complete
cbcfa8a8ca0c: Pull complete
fc80053c4cc5: Pull complete
c798d1495234: Pull complete
04ccd4d8a6f9: Pull complete
3ea0af8c7a98: Pull complete
Digest: sha256:b62889615b41a57698eee7cc346360e1e606705fc1d9b404e186461fd5f10610
Status: Downloaded newer image for docksal/db:1.0-mysql-5.5
Pulling cli (docksal/cli:1.0-php5)...
1.0-php5: Pulling from docksal/cli
386a066cd84a: Already exists
ef06075d90ca: Pull complete
ef3141243c2e: Pull complete
7770f28c06f3: Pull complete
df75342c3d10: Pull complete
a42c7df9fe0d: Pull complete
a821f2bd0281: Pull complete
28e9a08cb143: Pull complete
e52862923f3e: Pull complete
fd3139cb2eb1: Pull complete
58c90744c86c: Pull complete
4b62f4ef920b: Pull complete
03496846829b: Pull complete
2aa52dbb6484: Pull complete
941552e6fa50: Pull complete
950316f08dc6: Pull complete
71f57a8a3c52: Pull complete
e644058d7241: Pull complete
494346ada6bd: Pull complete
596ec6482920: Pull complete
c1b962d767fe: Pull complete
5965b2b14341: Pull complete
49cbcc0458bd: Pull complete
Digest: sha256:1da483a88052e44882ca61d307a8d59b9c5ef67ded2bd044a9d60586f19d1ec9
Status: Downloaded newer image for docksal/cli:1.0-php5
Pulling web (docksal/web:1.0-apache2.2)...
1.0-apache2.2: Pulling from docksal/web
c952bb7239f0: Pull complete
4b3a0a7558e7: Pull complete
ab1944938d88: Pull complete
73efc7e7e1e2: Pull complete
6a234f1e1a45: Pull complete
8d6fda0a3608: Pull complete
75ad68f49e80: Pull complete
d8194c1915a0: Pull complete
c767a04ff090: Pull complete
5ea400208f9f: Pull complete
d732cd9be214: Pull complete
Digest: sha256:94401c03975d7f5dd74f42a7daa23c1b81061050cea017123fd1949ee419870d
Status: Downloaded newer image for docksal/web:1.0-apache2.2
Pulling browser (selenium/standalone-chrome:latest)...
latest: Pulling from selenium/standalone-chrome
6bbedd9b76a4: Pull complete
fc19d60a83f1: Pull complete
de413bb911fd: Pull complete
2879a7ad3144: Pull complete
668604fde02e: Pull complete
6f937cfc60a5: Pull complete
318afcd73c12: Pull complete
8632a4eb4160: Pull complete
6faf0ee13b93: Pull complete
af860db8814e: Pull complete
524e8cc30d75: Pull complete
1e484774c0d6: Pull complete
6621c8b8af82: Pull complete
15de8915984e: Pull complete
448af82067d8: Pull complete
2c2559c84fcd: Pull complete
8f5d44e05621: Pull complete
a46861b4770e: Pull complete
991dc76774b8: Pull complete
6d3ad536d5c8: Pull complete
770aeae44a18: Pull complete
Digest: sha256:efd90f188e95616a34551844741a864999389c0859d63498d3282607a34a08ea
Status: Downloaded newer image for selenium/standalone-chrome:latest
Creating drupal7_db_1
Creating drupal7_browser_1
Creating drupal7_cli_1
Creating drupal7_web_1
Changing user id in cli to 502 to match host user id...
Resetting permissions on /var/www...
Restarting php daemon...
Connected vhost-proxy to "drupal7_default" network.
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
56bec22e3559: Pull complete
Digest: sha256:29f5d56d12684887bdfa50dcd29fc31eea4aaf4ad3bec43daf19026a7ce69912
Status: Downloaded newer image for busybox:latest
Waiting 10s for MySQL to initialize...
 Step 3  Installing site...
bash: cd: docroot: No such file or directory
MotherPhoenix-3:drupal7 stephen$ ls -al
total 16
drwxr-xr-x+  7 stephen  wheel   306 Nov 20 13:43 .
drwxrwxrwx@ 22 user     wheel  1122 Nov 20 14:29 ..
drwxr-xr-x+  4 stephen  wheel   238 Nov 20 13:43 .docksal
drwxr-xr-x+  8 stephen  wheel   442 Nov 20 13:43 .git
-rw-r--r--+  1 stephen  wheel   115 Nov 20 13:43 .gitignore
-rw-r--r--+  1 stephen  wheel  2202 Nov 20 13:43 README.md
drwxr-xr-x+  9 stephen  wheel  1020 Nov 20 13:43 docroot
drwxr-xr-x+  3 stephen  wheel   102 Nov 20 13:43 drush
drwxr-xr-x+  3 stephen  wheel   102 Nov 20 13:43 tests
```

**Comment by lmakarov** [comment]
@DigitalFrontiersMedia 

You've got a conflict in the NFS exports configuration.
```
-----------------
# VAGRANT-BEGIN: 502 2f3e57c5-cace-406c-8178-cab3118a05c2
"/Users/stephen/Projects" 192.168.10.10 -alldirs -mapall=502:20
# VAGRANT-END: 502 2f3e57c5-cace-406c-8178-cab3118a05c2
# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
-----------------
```

That is indeed a left over from the Drude setup.
We have instructions here on how to properly update from Drude to Docksal
https://github.com/docksal/docksal#updating-from-drude-to-docksal
Did you follow them precisely?

**Comment by DigitalFrontiersMedia** [comment]
Okay.  Thanks.  Yeah, since Drude never really ever installed correctly, I didn't think I'd have any issues there.  Will do as advised.  Will report back with results.
Thanks!

**Comment by DigitalFrontiersMedia** [comment]
Okay.  I'm completely lost here.  I follow the instructions as best as I can but I think it's jacked.

> It is very important to use vagrant destroy and not delete the VM manually in VirtualBox.
Vagrant has to clean things up properly and that is what vagrant destroy is for.

While speaking with Dave Kopecek yesterday, we manually deleted the leftover VM from the drude install from inside VirtualBox.  And I deleted the .drude and Projects folders some time ago.

So how do I do a clean install now?

:-(

**Comment by DigitalFrontiersMedia** [comment]
I guess I could add more detail other than the fact that I think we killed the drude uninstall/upgrade by not knowing about the warning (or that drude was still hanging around).

Vagrant shows nothing now:
`MotherPhoenix-3:drupal7 stephen$ vagrant global-status
id       name   provider state  directory
--------------------------------------------------------------------
There are no active Vagrant environments on this computer! Or,
you haven't destroyed and recreated Vagrant environments that were
started with an older version of Vagrant.`

However, before I saw the warning about not deleting it manually, the old vm was still listed (even though it had been manually deleted yesterday).  I tried 'vagrant destroy' on it which resulted in an error complaining about my Projects folder not being present (I think), as well as seemingly removing the VM from the list above as you see it.

Trying to uninstall fin now using the instructions, and re-installing results in the same output as originally posted.

Is it borked beyond help?

**Comment by lmakarov** [comment]
Vagrant VMs generally should be destroyed via `vagrant destroy`.
If you nuke them manually via VirtualBox, then there are leftovers that are not cleaned up properly.
In case of the old Drupal vagrant VM is the NFS export that did not get removed.

You can do a `sudo rm -rf /etc/exports`, then `fin vm start`. This will regenerate the exports file from scratch and should solve your issue.

**Comment by DigitalFrontiersMedia** [comment]
Hmmmm... okay.  removed /etc/exports.  Tried fin vm start but said docksal already running.  Did fin vm stop, then fin init from drupal7 and got the following:

`MotherPhoenix-3:drupal7 stephen$ fin init
 Step 1  Initializing local project configuration...
/Users/stephen/Sites/drupal7/docroot/sites/default/settings.local.php already in place
tests/behat/behat.yml already in place
 Step 2  Creating services...
It looks like 'docksal' docker machine is not running.
Run 'fin vm start' to start it now? [y/n]: y
Starting "docksal"...
(docksal) Check network to re-create if needed...
(docksal) Waiting for an IP...
Machine "docksal" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Configuring NFS shares...
cat: /etc/exports: No such file or directory
cat: /etc/exports: No such file or directory
Writing /etc/exports...
Restarting nfsd...
Mounting NFS shares...
Starting nfs client utilities.
Mounting local /Users to /Users...
Importing ssh keys...
Identity added: id_rsa (id_rsa)
Starting services...
Starting drupal7_db_1
Starting drupal7_cli_1
Starting drupal7_browser_1

ERROR: for db  Cannot start service db: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/Users/stephen/Sites/drupal7/.docksal/etc/mysql/my.cnf\\\\\\\" to rootfs \\\\\\\"/mnt/sda1/var/lib/docker/aufs/mnt/575262c1517080d144efc5832d46a612ac7ae847b96b724fb4d87d60cd0e9829\\\\\\\" at \\\\\\\"/mnt/sda1/var/lib/docker/aufs/mnt/575262c1517080d144efc5832d46a612ac7ae847b96b724fb4d87d60cd0e9829/opt/mysql.conf.d/z_my.cnf\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"

ERROR: for cli  Cannot start service cli: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/Users/stephen/Sites/drupal7/.docksal/etc/php/php-cli.ini\\\\\\\" to rootfs \\\\\\\"/mnt/sda1/var/lib/docker/aufs/mnt/29bafef3d47f405ead81d1dfc4fbff9d5e075e2c2edbb19accccf355a51bf265\\\\\\\" at \\\\\\\"/mnt/sda1/var/lib/docker/aufs/mnt/29bafef3d47f405ead81d1dfc4fbff9d5e075e2c2edbb19accccf355a51bf265/etc/php5/cli/conf.d/z_php.ini\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"
ERROR: Encountered errors while bringing up the project.
`

Going to delete docksal following instructions and try installing again...

**Comment by DigitalFrontiersMedia** [comment]
Huzzah!!!  Working!  Thank you!
