### ISSUE TITLE
mailhog not sending due to name lookup issue

### ISSUE THREAD

**Issue by mf-lit** [docksal/docksal#416]
We're observing that mail is not being sent to mailhog
This can be reproduced at the command-line:
```
docker@cli:/var/www/docroot$ /usr/local/bin/mhsendmail --smtp-addr="mail:1025" <<EOF
> From: App <app@mailhog.local>
> To: Test <test@mailhog.local>
> Subject: Test message
> 
> Some content!
> 
> EOF
error sending mail
2017/12/07 11:04:15 dial tcp 127.0.0.1:1025: getsockopt: connection refused
docker@cli:/var/www/docroot$
```

We see in that output that mhsendmail is resolving `mail` to `127.0.0.1` which is clearly wrong as proven by:

```
docker@cli:/var/www/docroot$ dig mail a +short
172.18.0.6
```

resolv.conf in the cli container looks like this:
```
search mscp.local
nameserver 127.0.0.11
options ndots:0
```

and on the host it looks like this:
```nameserver 192.168.64.100
nameserver 127.0.1.1
search mscp.local
```

At this point I ended up system-tracing the mhsendmail command, I'll spare you the output but basically it showed that mhsendmail wasn't trying to resolve the name `mail` it was trying to resolve `mail.mscp.local`

So let's try and resolve that:
```
docker@cli:/var/www/docroot$ dig mail.mscp.local a +short
127.0.0.1
```

Ah, so there is our problem: mhmailsend is appending the search path when it shouldn't be (perhaps because `options ndots:0` is not being honoured).

I suppose this is a bug in mhmailsend, we're working around it by deleting the search path from resolv.conf on cli after every `fin up` for now, but a more permanent solution would be nice....

FWIW, the mscp.local search path is coming from our office dhcp server.
We're seeing this on both Ubuntu 16.04 & 17.10.

**Comment by drubage** [comment]
We have been seeing the same issue. I also removed the search line in resolv.conf and did a fin up and it starts working.

**Comment by mf-lit** [comment]
PR https://github.com/docksal/service-cli/pull/17

**Comment by lmakarov** [comment]
docksal/service-cli#17 has been merged. Thanks @mf-lit !

Please try one of the edge cli image and report back whether that fixes this issue:

```
$ fin image registry docksal/cli | grep 'edge.*\.'
docksal/cli:edge-php7.2
docksal/cli:edge-php5.6
docksal/cli:edge-php7.1
docksal/cli:edge-php7.0
```

Note, you may have to do fin docker pull if you have previously used any of the edge cli images (e.g. `fin docker pull docksal/cli:edge-php7.1`).

**Comment by drubage** [comment]
I just tried adding this to my docksal.env file:

DOCKSAL_STACK=default
CLI_IMAGE='docksal/cli:edge-php7.1'

I then did a "fin up" and a fresh site install of a Drupal 8 site. I then tried the password reset form and it says "Unable to send email. Contact the site administrator if the problem persists.". Is mailhog supposed to work out of the box now with these edge images and [these instructions](http://docksal.readthedocs.io/en/master/tools/mailhog/)?

**Comment by drubage** [comment]
WAIT! I forgot to do this first:

fin docker pull docksal/cli:edge-php7.1

It seems to be working now!

**Comment by achekulaev** [comment]
"80% of IT issues are caching or cache invalidation issues" © some guy :)

**Comment by lmakarov** [comment]
docksal/cli 2.0 images will be release with Docksal 1.7.0 this month.
