### ISSUE TITLE
is_widows: command not found

### ISSUE THREAD

**Issue by rommaz** [docksal/docksal#424]
fin sysinfo produces an error:
> /usr/local/bin/fin: line 4193: is_widows: command not found

https://github.com/docksal/docksal/blob/6a6118d57164cb81f3a1a80abe7688fdb5a03f17/bin/fin#L4193

**Comment by achekulaev** [comment]
@lmakarov we might need another tiny hotfix this week

**Comment by achekulaev** [comment]
Yeah I initially thought it was fatal but it just break in one line.
