### ISSUE TITLE
Add verification for and document characters allowed in VIRTUAL_HOST 

### ISSUE THREAD

**Issue by frederickjh** [docksal/docksal#430]
**Description**

I am posting this here from gitter.im chat as requested by @lmakarov. See chat text below included for reference.

Currently there is no documentation or validation for allowed characters in VIRTUAL_HOST. Possible tasks to fix this are:
* Add documentation including the Wikipedia link regarding domain names and the allowed characters.
* Add validation to the `fin config show` command that would give an error that the configuration is invalid.
* Add validation when `fin up` is run that would show a warning that the VIRTUAL_HOST is invalid and that Docksal DNS routing will not work.

----

**From [gitter.im/docksal/community-support](https://gitter.im/docksal/community-support)**
#### Chris Zietlow @aczietlow Dec. 01 18:02
I’ve run into a weird issue with the proxy service. I’ve binded the service to 0.0.0.0 so that it handles all incoming requests, and it works as expected. Except when there is an _ in the url
~/.docksal/docksal.env
```
DOCKSAL_VHOST_PROXY_IP=“0.0.0.0”
```
project docksal.env
```
COMPOSE_PROJECT_NAME=Pied_Piper-features-huli-chat
VIRTUAL_HOST=features-huli-chat.Pied_Piper.mg.zietlow.ninja
```
Everything works until an **_** gets added

#### Chris Zietlow @aczietlow Dec. 01 18:08
Is this a given with proxy services, or a bug?
i.e. Is this to be expected, or would it be helpful for me to dig further into it?

#### Leonid Makarov @lmakarov Dec. 05 01:01
> Except when there is an _ in the url

@aczietlow you cannot use underscores in a URL

From https://en.wikipedia.org/wiki/Domain_name

> Domain names may be formed from the set of alphanumeric ASCII characters (a-z, A-Z, 0-9)

also, you cannot have uppercase letters in VIRTUAL_HOST - these won't be routable by the proxy, since browsers force lowercase domain names
It would be helpful to post these issues on Github, so others can easier discover them

**Comment by achekulaev** [comment]
@frederickjh I actually wrote a post about this after that case blog.docksal.io/Virtual-host-value-limitations-4f105725dbf8
But yeah some automation would not hurt

**Comment by lmakarov** [comment]
Let's just make sure VIRTUAL_HOST value is domain name safe. This is already happening in `docksal/ci-agent` - https://github.com/docksal/ci-agent/blob/2d0ccca18fda60d3ef92bfedd679b4eb830b68cb/base/bin/build-env#L28-L34

**Comment by achekulaev** [comment]
Fixed in PR above
