### ISSUE TITLE
fin project create should account for underscores

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#438]
Underscores can not be in the domain name 
https://blog.docksal.io/virtual-host-value-limitations-4f105725dbf8

However, when project is created via `fin project create` if will put underscore in the `VIRTUAL_HOST` if uer enters a name with underscore, e,g, `test_drupal` (try installing drupal7 with that name). 

We should either disallow underscores or remove them and warn user that `VIRTUAL_HOST` will be without it.

**Comment by frederickjh** [comment]
Considering that a user adds an underscore they are wanting a visual separation. Could we possibly replace underscores with hyphens which are allowed to preserver the visual seperation? In this case it would be good to check that `VIRTUAL_HOST` does not start nor end with a hypen as well.

**Comment by achekulaev** [comment]
@frederickjh you are bringing up a more broad issue of gracefully handling unacceptable `VIRTUAL_HOST`. This ticket is more about `project create`. 

I would recommend creating a separate issue for graceful `VIRTUAL_HOST` handling if you feel this is something useful.

For the sake of this issue I am just going to disallow underscores and uppercase letters in `fin project create` name. Dashes are still allowed. Checks for beginning and end applied.
