### ISSUE TITLE
Update dependency versions

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#439]
- docker 17.12.0-ce
- docker-compose 1.18.0
- docker-machine 0.13.0

### docker 17.12.0-ce

- [Full release notes](https://docs.docker.com/release-notes/docker-ce/#17120-ce-2017-12-27)

### boot2docker 17.12.0-ce
 - VirtualBox Guest Additions v5.2.2
 - [Full release notes](https://github.com/boot2docker/boot2docker/releases/tag/v17.12.0-ce)

### Docker for Mac 17.12.0-ce-mac46

> For systems running APFS on SSD on High Sierra, use raw format VM disks by default. This improves disk throughput (from 320MiB/sec to 600MiB/sec in dd on a 2015 MacBook Pro) and disk space handling.
> Existing disks are kept in qcow format, if you want to switch to raw format you need to “Remove all data” or “Reset to factory defaults”. See https://docs.docker.com/docker-for-mac/faqs/#disk-usage

- [Full release notes](https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-17120-ce-mac46-2018-01-09-stable)

**Comment by achekulaev** [comment]
Not until https://github.com/docksal/docksal/issues/442 is resolved

**Comment by achekulaev** [comment]
Updated to 

```
REQUIREMENTS_DOCKER='18.03.1-ce'
REQUIREMENTS_DOCKER_COMPOSE='1.21.1'
REQUIREMENTS_DOCKER_MACHINE='0.14.0'
```
