### ISSUE TITLE
Drupal 8 Installation Profiles?

### ISSUE THREAD

**Issue by jasonglisson** [docksal/docksal#440]
I'm asking because I'd like to use Docksal in a demo for setting up a Drupal 8 site using a profile. As far as I can tell, there isn't a way for Docksal to stop the installation process or start using a profile. 

I'd love to work on this or if anyone else has some ideas of this can be done, I'd love to hear them.

**Comment by lmakarov** [comment]
Docksal provides the stack and ways to automate site provisioning. The actual provisioning, settings, etc. are completely up to the project team.

`fin init` is a **project level** [custom command](https://docs.docksal.io/en/master/fin/custom-commands/). You can anything you want there. Start with [docksal/drupal8](https://github.com/docksal/drupal8) repo and change the [custom command](https://github.com/docksal/drupal8/tree/master/.docksal/commands) there they way you need.

Specifically to your question of custom profiles - change the following [line](https://github.com/docksal/drupal8/blob/master/.docksal/commands/init-site#L64) to include the profile name:

```
    # We disable email sending here so site-install does not return an error
    PHP_OPTIONS="-d sendmail_path=`which true`" drush site-install -y --site-name='My Drupal 8 Site'
```
