### ISSUE TITLE
Warn about deprecation of php-cli.ini with the release of cli:2.0

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#444]
Detect if user has a `.docksal/etc/php/php-cli.ini` and ward that this file is deprecated and `php-fpm.conf` of different format should be used.

Comment: https://github.com/docksal/service-cli/issues/21#issuecomment-357071939

Example of `php-fpm.conf`: https://github.com/docksal/service-cli/blob/develop/tests/.docksal/etc/php/php-fpm.conf

**Comment by achekulaev** [comment]
@lmakarov I have made a commit above but I guess messaging is poor. There should be a documentation that can be referred.

**Comment by lmakarov** [comment]
We decided to not implement this at all. `php.ini` is used for global PHP settings overrides the same way between cli:1.x and cli:2.x. The only difference is PHP-FPM settings, which will only affect a small set of users. We will be adding notes in the release notes and in also updating the docs.
