### ISSUE TITLE
Update MailHog docs

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#446]
There will be no need to edit PHP settings with the new docksal/cli 2.0 images. MailHog will be used by default there:

```
; Mail settings
sendmail_path = '/usr/local/bin/mhsendmail --smtp-addr=mail:1025'
```

Additionally, MailHog can be installed via `fin addon install mailhog` (https://github.com/docksal/addons/issues/6)

**Comment by lmakarov** [comment]
We will need to have two versions of these instructions - for cli 1.x and cli 2.x

**Comment by achekulaev** [comment]
@lmakarov I think we should include `fin addon install mailhog` at the beginning as an easy way to install mailhog

**Comment by lmakarov** [comment]
@achekulaev editing `php.ini` is no loner necessary with the 2.0 cli images, so the mailhog addon will need to be updated to account for that before suggesting it as an option in the docs.
We'll also need a section dedicated to addons in the docs, where we can list all available addons.

**Comment by achekulaev** [comment]
@lmakarov it does not have to be perfect to be a viable solution.
