### ISSUE TITLE
fin cd command

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#447]
Create a `fin cd` command that would cd to the project root.

The main incentive for this command is to use it with an alias to easily cd into that alias/project folder: `fin @projectname cd`.

**Comment by david-hernandez** [comment]
Why not `fin cd @projectname`? In any case, I think having the only use be to get to the project root is fine. I think that is what most people would look for, a simple command to jump from one project to the other.

**Comment by achekulaev** [comment]
Because it's `fin @alias <command>`.

**Comment by frederickjh** [comment]
Can I make a suggestion?  Allow cd deeper by passing extra arguments in so that:
`fin @alias cd docroot` would take one to the docroot folder in ones project or
`fin @alias cd docroot/sites/default/files` would take one to the files directory.

**Comment by achekulaev** [comment]
Sorry guys, as time passed I forgot the real reason why this command was not implemented: there is no technical way to do that. 

One can not chance current directory in a shell. Scripts run in a subshell. What happens in subshell, stays in subshell.

**Comment by frederickjh** [comment]
It is possible to implement **cd**ing so that you stay in the directory you cd to by implementing the script as a function in bash.

https://stackoverflow.com/a/3880051/6079319

This technique is used by [autojump](http://github.com/joelthelion/autojump/wiki).
