### ISSUE TITLE
Additional virtual hosts and default stack

### ISSUE THREAD

**Issue by drubage** [docksal/docksal#449]
How can we use the default stack but have other VIRTUAL_HOST_ALIASES? We tried setting the VIRTUAL_HOST_ALIASES in our docksal.env to be like this:

`VIRTUAL_HOST_ALIASES=domain2.docksal,domain3.docksal,domain4.docksal,domain5.docksal,domain6.docksal`

But all of those domains result in the Docksal page not found page. I don't think that value is being read:

```
Spare-Mac-Book-Pro:domain1 drew.michael$ fin config | grep '^VIRTUAL_HOST'
VIRTUAL_HOST: domain1.docksal
VIRTUAL_HOST_ALIASES: *.domain1.docksal
```

I see here that we can set other virtual hosts in docksal.yml (and we have done it before):

http://docksal.readthedocs.io/en/master/advanced/multiple-projects/#default-virtual-host-domain-name

However, if we define the cli configuration in the docksal.yml file then we can't use "DOCKSAL_STACK=default" in docksal.env, can we?

**Comment by achekulaev** [comment]
Ok that probably was confusing from the fin side, but there is no such variable as "VIRTUAL_HOST_ALIASES". There is only `VIRTUAL_HOST` and you need to override `VIRTUAL_HOST` for your purposes.

**docksal.env**

```
VISTUAL_HOST=domain1.docksal,domain2.docksal,domain3.docksal
```

VISTUAL_HOST_ALIASES is there to show that Docksal adds `*.${VIRTUAL_HOST}` as an additional alias. So wildcard subdomains wull automatically work for the first domain, but not for consequent ones. 

If you need wildcards working for every domain, you need to provide those aliases manually:

```
VISTUAL_HOST=domain1.docksal,domain2.docksal,*.domain2.docksal,domain3.docksal,*.domain3.docksal
```

**Comment by drubage** [comment]
As usual, much appreciated!
