### ISSUE TITLE
Documentation should point to native mode more clearly

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#453]
The documentation link should point to the native mode installation for Docker. The difference between the two is very confusing for most users, so the difference between the two methods of setting up the environment should be explained in a paragraph or so. After that, provide a link to the native mode setup:

http://docksal.readthedocs.io/en/master/getting-started/env-setup-native/

Indeed, we have found Docksal for Drupal pretty much impossible to set up on Windows using the old method due to conflicts between Hyper-V and VirtualBox.

\[ Copy of https://github.com/docksal/drupal7/issues/7 ]

**Comment by loopy3025** [comment]
Agreed. It's really strange how you have to follow the steps up to a certain point in one part of the documentation, then switch to the Docker for Windows/Docker for Mac section at a specific point and the documentation doesn't actually say when that is. Super confusing.

**Comment by lmakarov** [comment]
Note: the install one liner actually supports the following and will set the `DOCKER_NATIVE=1` variable in `$HOME/.docksal/docksal.env`

```
curl -fsSL https://get.docksal.io | DOCKER_NATIVE=1 sh
```

This has never made it into the standard installation docs and is only mentioned in the context of [portable installation](https://docs.docksal.io/en/master/getting-started/portable/)

**Comment by lmakarov** [comment]
We should add [screenshots](https://github.com/docksal/docksal/issues/456#issuecomment-360200709) regarding file sharing configuration for Docker for Mac/Windows. This way the instructions (already there) will be more prominent.

Also, recording videos of the installation process and linking them in the docs would help.

**Comment by achekulaev** [comment]
Closing in favor of https://github.com/docksal/docksal/issues/592
