### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by ssudhak** [docksal/docksal#454]
I am getting following error while running composer install.

[22-Jan-2018 15:15:14 UTC] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 134217728 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php on line 220

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 134217728 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php on line 220

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

fin vm ram gives me the following output.
Total Memory size:     3000MB
Available Memory:	2477 MB
Available Swap:		1621 MB

running  php -r "echo ini_get('memory_limit').PHP_EOL;"
gives me 512M

please help me to fix this.

**Comment by achekulaev** [comment]
https://blog.docksal.io/overriding-php-settings-in-docksal-3ae246c7c588
