### ISSUE TITLE
More "cannot start service" - Windows 10 in Native Mode

### ISSUE THREAD

**Issue by loopy3025** [docksal/docksal#456]
I've followed several issues down multiple rabbit holes here in the documentation regarding the whole "cannot start service" and "no such file or directory" error track and I don't see how any of those pertain to the issue we are having. We are running in Native Mode, so I don't see how it's a VM issue and the errors are totally different from those listed on the SMB troubleshooting page.

I did try adding /c/Users/xlee/.babun/cygwin/home/XLee/Projects/drupal7test as the "DOCKSAL_NFS_PATH" in the ~/.docksal/docksal.env , but I have a feeling it isn't supposed to be the fully qualified path because .babun is an emulated environment. I've also tried starting it after the /home folder, but that didn't seem to work either.

![capture](https://user-images.githubusercontent.com/6729935/35276198-98b04e1e-0010-11e8-879e-132bc4b8274a.png)

**Comment by loopy3025** [comment]
Interestingly, I had to run Babun in administrator mode in order to get cygwin installed. Could that be related to our issues? Could there be some kind of oddness going on with the permissions on this computer?

**Comment by achekulaev** [comment]
> We are running in Native Mode

So Docker for Windows. What version? (`DOCKSAL_NFS_PATH` is not applicable for Windows or Native mode and does nothing)

> I had to run Babun in administrator mode in order to get cygwin installed

Issues you experience are 100% related to this fact. Babun should be installed as a regular user that will use it later on. Otherwise it will not work properly. 
https://docs.docksal.io/en/master/getting-started/env-setup/#windows

You will need to uninstall babun as Administrator and install as a regular user.

**Comment by loopy3025** [comment]
@achekulaev And I take it the resolution for not being able to install cygwin is to simply have my user granted the permissions necessary to perform this task?

**Comment by achekulaev** [comment]
@loopy3025  No special permissions are required to install Babun as a regular user.

**Comment by achekulaev** [comment]
Please note it's exactly http://babun.github.io/. Not just any cygwin

**Comment by loopy3025** [comment]
Hey, @achekulaev I'm sorry. I mislead you. It wasn't babun/cygwin. It was when I tried to install Docksal. Screengrabs incoming.

**Comment by loopy3025** [comment]
Without Run as Administrator:

![docksal_install_without_run_as_administrator](https://user-images.githubusercontent.com/6729935/35296899-758d37ae-004b-11e8-8690-051a8a7f6245.png)

With Run as Administrator:

![docksal_install_with_run_as_administrator](https://user-images.githubusercontent.com/6729935/35296931-85975490-004b-11e8-81de-5463dad62d50.png)

**Comment by loopy3025** [comment]
I'm super curious as to why it tried to download VirtualBox, too. Very strange.

**Comment by achekulaev** [comment]
`fin` thought that your VirtualBox installation is broken hence it tried to reinstall it. 
There is a file `c:\Program files\Oracle\VirtualBox\VBoxManage.exe` which is a command line utility to manage virtual boxes. For some reason you do not have permission to access/execute this file. I guess you need to check permissions for this file specifically and for the whole `c:\Program files\Oracle\VirtualBox` directory. It should be usable by a regular user.

**Comment by loopy3025** [comment]
Great. Thanks. I will do that and report back.

**Comment by achekulaev** [comment]
@loopy3025 also you said `We are running in Native Mode`. It does not look to be the case though. In Native Mode you use Docker for Mac and you do not need VirtualBox. 

Are we talking about the same thing?

**Comment by loopy3025** [comment]
@achekulaev Exactly. That's why it was so weird that it tried to install VirtualBox. I did not run a fin vm start.

**Comment by loopy3025** [comment]
@achekulaev Are you saying that you can't use Native Mode on Windows?

**Comment by achekulaev** [comment]
Sure you can. Please show `fin sysinfo` output.

**Comment by loopy3025** [comment]
fin sysinfo when regular user:
'''
███  OS
 Microsoft Windows [Version 10.0.15063]
CYGWIN_NT-10.0-WOW W8B2ZW52 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
Mode: VirtualBox VM
███  FIN
fin version: 1.43.2
███  ENVIRONMENT
DOCKER_HOST             |
 WARNING:  Non-default DOCKER_HOST
███  DOCKER
EXPECTED VERSION: 17.09.0-ce
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64
Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true
███  DOCKER INFO
Containers: 7
 Running: 3
 Paused: 0
 Stopped: 4
Images: 6
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d4b0100
ID: L5KL:XQJ7:5GMB:6JPU:3UI4:QOMR:2QO6:UAPS:5HT2:7DP2:YBG3:55Y2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 42
 Goroutines: 66
 System Time: 2018-01-24T13:11:47.1382992Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
███  DOCKER COMPOSE
EXPECTED VERSION: 1.17.1
docker-compose version 1.18.0, build 8dd22a96
docker-py version: 2.6.1
CPython version: 2.7.14
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
███  DOCKER MACHINE
EXPECTED VERSION: 0.13.0
docker-machine.exe version 0.13.0, build 9ba6da9
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS
███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
/usr/local/bin/fin: line 4249: /cygdrive/c/Program Files/Oracle/VirtualBox/VBoxManage.exe: Permission denied
███  VIRTUALBOX NETWORK INTERFACES
/usr/local/bin/fin: line 4252: /cygdrive/c/Program Files/Oracle/VirtualBox/VBoxManage.exe: Permission denied
███  HDD Usage
Docker machine docksal is not created. Use 'fin vm start' or 'fin up'.
███  RAM Usage
Docker machine docksal is not created. Use 'fin vm start' or 'fin up'.
███  RAM Usage per container
CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
06b167180bae        docksal-ssh-agent     0.00%               1.262MiB / 1.934GiB   0.06%               5.39kB / 0B         0B / 0B             2
74bd8b7a2ed0        docksal-dns           0.32%               15.49MiB / 1.934GiB   0.78%               1.5MB / 1.79MB      0B / 0B             12
e589a7ce4aa9        docksal-vhost-proxy   0.29%               17.32MiB / 1.934GiB   0.87%               5.51kB / 0B         0B / 0B             14
'''
fin sysinfo when running as admin:
'''
███  OS
 Microsoft Windows [Version 10.0.15063]
CYGWIN_NT-10.0-WOW W8B2ZW52 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
Mode: VirtualBox VM
███  FIN
fin version: 1.43.2
███  ENVIRONMENT
DOCKER_HOST             |
 WARNING:  Non-default DOCKER_HOST
███  DOCKER
EXPECTED VERSION: 17.09.0-ce
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64
Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true
███  DOCKER INFO
Containers: 7
 Running: 3
 Paused: 0
 Stopped: 4
Images: 6
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d4b0100
ID: L5KL:XQJ7:5GMB:6JPU:3UI4:QOMR:2QO6:UAPS:5HT2:7DP2:YBG3:55Y2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 42
 Goroutines: 66
 System Time: 2018-01-24T13:12:57.5505712Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
███  DOCKER COMPOSE
EXPECTED VERSION: 1.17.1
docker-compose version 1.18.0, build 8dd22a96
docker-py version: 2.6.1
CPython version: 2.7.14
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
███  DOCKER MACHINE
EXPECTED VERSION: 0.13.0
docker-machine.exe version 0.13.0, build 9ba6da9
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS
███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.2.0r118431
███  VIRTUALBOX NETWORK INTERFACES
Name:            VirtualBox Host-Only Ethernet Adapter
GUID:            74fe5103-81b6-4c01-a200-4a32155abcaf
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::d4bd:e03f:ae19:7ebd
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:09
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter
███  HDD Usage
Docker machine docksal is not created. Use 'fin vm start' or 'fin up'.
███  RAM Usage
Docker machine docksal is not created. Use 'fin vm start' or 'fin up'.
███  RAM Usage per container
CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
06b167180bae        docksal-ssh-agent     0.00%               1.262MiB / 1.934GiB   0.06%               5.39kB / 0B         0B / 0B             2
74bd8b7a2ed0        docksal-dns           0.36%               15.5MiB / 1.934GiB    0.78%               1.51MB / 1.8MB      0B / 0B             12
e589a7ce4aa9        docksal-vhost-proxy   0.51%               17.3MiB / 1.934GiB    0.87%               5.51kB / 0B         0B / 0B             14
'''

**Comment by loopy3025** [comment]
Here's the results of me changing the permissions. The regular user has full access to that folder now:

![1](https://user-images.githubusercontent.com/6729935/35335697-415221c2-00e4-11e8-8673-f44f2183c80b.png)

For some reason, this user can't be given access. Their access keeps getting reset. After a quick google search, this seems to be not a problem, though I could be wrong.

![2](https://user-images.githubusercontent.com/6729935/35335770-7372f12c-00e4-11e8-8583-8325c72fe301.png)

Initial message when I try to install Docksal...

![3](https://user-images.githubusercontent.com/6729935/35335807-87b866b2-00e4-11e8-87ff-c3141f9fe795.png)

As it makes the attempt...

![4](https://user-images.githubusercontent.com/6729935/35335812-8c3237b8-00e4-11e8-953e-f8023c317de1.png)

**Comment by loopy3025** [comment]
I can't imagine why it is requiring VirtalBox. Is it required for Docker itself to work in the backgroud?

**Comment by achekulaev** [comment]
`Mode: VirtualBox VM`

You do not have Native Mode enabled. Please follow the instruction in documentation
https://docs.docksal.io/en/master/getting-started/env-setup-native/#switching-to-docker-for-macwindows

**Comment by loopy3025** [comment]
@achekulaev there is no .docksal folder if docksal isn't installed yet, right?

**Comment by loopy3025** [comment]
After docksal is installed, we definitely follow those steps.

**Comment by achekulaev** [comment]
@loopy3025 

> there is no .docksal folder if docksal isn't installed yet, right

Yes there is no .docksal folder if docksal isn't installed. You can create a folder with mkdir command.

**Comment by loopy3025** [comment]
So part of the process is to create a ~/docksal/docksal.env file BEFORE installing docksal?

**Comment by achekulaev** [comment]
@loopy3025 I agree that documentation is ambiguous at that spot and should be updated. There are historical reasons for that. 
The ticket to improve documentation is already created https://github.com/docksal/docksal/issues/453

Yes adding `~/docksal/docksal.env` with 1 line will do the job.

**Comment by loopy3025** [comment]
Perfect. Docksal installed without admin mode. I will update our internal documentation to reflect that step. Thank you. I will try to get a site running and report back to see if that worked.

**Comment by loopy3025** [comment]
Looks like the same results.

![image](https://user-images.githubusercontent.com/6729935/35344578-803b4154-00fb-11e8-8e74-4a97758f2b89.png)

**Comment by judy-akers** [comment]
Co-worker of loopy3025 here. 

I was also getting error messages for db and cli issues:  "ERROR: for nyscertified_db_1  Cannot start service db: error while mounting volume '/var/lib/docker/volumes/nyscertified_project_root/_data': error while mounting volume with options: type='none' device='/c/Users/jakers/.babun/cygwin/home/JAkers/projects/nyscertified' o='bind': no such file or direcStarting nyscertified_cli_1 ... error" messages

I did the following:
1. Open Docker for Windows (icon at lower right of task bar)
2. select Settings
3. select Shared Drives
4. make sure C: is checked
5. CLICK ON THE APPLY button

When I reran the fin init - the error messages for db and cli went away. 
 Now to work on the other issues that I've got.

**Comment by loopy3025** [comment]
Ah. We had the subfolder in there before and deleted it. Alrighty. That worked!

Mac:
![image](https://user-images.githubusercontent.com/6729935/35345441-a511947c-00fd-11e8-9bab-29c17ed24ad8.png)

Windows:
![image](https://user-images.githubusercontent.com/6729935/35345448-a8fa2d42-00fd-11e8-8886-4bb37abbd123.png)

**Comment by loopy3025** [comment]
Thanks for all the attention and help so far @achekulaev . You rock!

**Comment by achekulaev** [comment]
@judy-akers thanks for adding comment here. Looks like we really need to improve documentation. The part on the drives is there but is probably not jumping out at user enough.

**Comment by loopy3025** [comment]
We just found out that if you suddenly start getting this error again, that means you probably changed your password or something else happened with your account.

You need to do the following:

1. Go to Docker -> Shared Drives
2. Un-check your shared drive
3. Apply
4. Wait for it to restart
5. Go back to Docker -> Shared Drives
6. Re-check the drive you want to share
7. Click Apply
