### ISSUE TITLE
Error on fin init - Executing: mysql --defaults-extra-file=tmp/drush_...

### ISSUE THREAD

**Issue by judy-akers** [docksal/docksal#458]
Attempting to clone a git project for my state agency, and get it running using Docksal on my workstation.
I get everything set up and then run fin init, and it errors.

I added an ECHO 'site_install function started..'. command and a -v to the drush command in the the ~/nyscertified/.docksal/commands/init file because the error gave no useful information. I reran fin init.

Results of fin init                                      ~/projects/nyscertified 1
 Step 1  Initializing local project configuration...
Making site directory writable...
/c/Users/jakers/.babun/cygwin/home/JAkers/projects/nyscertified/docroot/sites/default/settings.local.php already in place.
 Step 2  Creating services...
Identity added: id_rsa (id_rsa)
Starting services...
Starting nyscertified_db_1 ...
Starting nyscertified_cli_1 ... done
Creating nyscertified_web_1 ... done
Waiting for nyscertified_cli_1 to become ready...
Connected vhost-proxy to "nyscertified_default" network.
Virtual Host: nyscertified.docksal
Waiting 10s for MySQL to initialize...
 Step 3  Installing site...
site_install function started...
Executing: cd /var/www/docroot && git rev-parse --show-toplevel 2> /dev/null
Executing: mysql --defaults-extra-file=/tmp/drush_eKJYz3 --database=nyscertified --host=localhost --
silent  < /tmp/drush_zd8UvJ > /dev/null
You are about to CREATE the 'nyscertified' database. Do you want to continue? (y/n): y
Sites directory /var/www/docroot/sites/default already exists - proceeding.                 [notice]
Executing: mysql --defaults-extra-file=/tmp/drush_uH9ePH --database=nyscertified --host=localhost --
silent  < /tmp/drush_pLqAHn > /dev/null
Executing: mysql --defaults-extra-file=/tmp/drush_eag95l --database=information_schema --host=localh
ost --silent  < /tmp/drush_5OxGX1
                                                                                         [error]

What I hoped would happen is it would install my database and finish setting up the project so that I could access it via http://nyscertified.docksal  (just like what happens when you follow the instructions to clone https://github.com/docksal/drupal7.git.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

 fin config                                    ~/projects/nyscertified 1
---------------------
COMPOSE_PROJECT_NAME_SAFE: nyscertified
COMPOSE_FILE:
C:/Users/jakers/.babun/cygwin/home/JAkers/.docksal/stacks/volumes-bind.yml
C:/Users/jakers/.babun/cygwin/home/JAkers/.docksal/stacks/stack-default.yml
ENV_FILE:
C:/Users/jakers/.babun/cygwin/home/JAkers/projects/nyscertified/.docksal/docksal.env
C:/Users/jakers/.babun/cygwin/home/JAkers/projects/nyscertified/.docksal/docksal-local.env

PROJECT_ROOT: /c/Users/jakers/.babun/cygwin/home/JAkers/projects/nyscertified
DOCROOT: docroot
VIRTUAL_HOST: nyscertified.docksal
VIRTUAL_HOST_ALIASES: *.nyscertified.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32812

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: null
      HOST_UID: null
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /c/Users/jakers/.babun/cygwin/home/JAkers/projects/nyscertified
      io.docksal.virtual-host: nyscertified.docksal,*.nyscertified.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /c/Users/jakers/.babun/cygwin/home/JAkers/projects/nyscertified
      o: bind
      type: none

---------------------

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

 fin sysinfo                                     ~/projects/nyscertified
███  OS
 Microsoft Windows [Version 10.0.16299.192]
CYGWIN_NT-10.0-WOW W8B3TW52 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
Mode: /usr/local/bin/fin: line 4193: is_widows: command not found

███  FIN
fin version: 1.43.2

███  ENVIRONMENT
DOCKER_HOST             |
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true

███  DOCKER INFO
Containers: 9
 Running: 6
 Paused: 0
 Stopped: 3
Images: 7
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.837GiB
Name: linuxkit-00155d4b0106
ID: R7MT:SK6U:HLOS:AGSA:GDJQ:KCQZ:4HCQ:3X7C:JAHL:HW4L:O663:4ZV6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 66
 Goroutines: 87
 System Time: 2018-01-24T16:55:07.6824132Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.17.1
docker-compose version 1.18.0, build 8dd22a96
docker-py version: 2.6.1
CPython version: 2.7.14
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

███  DOCKER MACHINE
EXPECTED VERSION: 0.13.0
docker-machine.exe version 0.13.0, build 9ba6da9

NAME      ACTIVE   DRIVER       STATE   URL   SWARM   DOCKER    ERRORS
docksal   -        virtualbox   Error                 Unknown   machine does not exist
test      -        virtualbox   Error                 Unknown   machine does not exist

███  DOCKER: IMAGES
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
docker4w/nsenter-dockerd   latest              cae870735e91        3 months ago        187kB
docksal/cli                1.3-php5            80248f5ea845        4 months ago        814MB
docksal/web                2.1-apache2.4       32c1d32eba6d        5 months ago        87.5MB
docksal/vhost-proxy        1.1                 898fb21e7f2d        5 months ago        158MB
docksal/db                 1.1-mysql-5.6       6feb79af9597        6 months ago        298MB
docksal/dns                1.0                 20c7a535479d        12 months ago       61.6MB
docksal/ssh-agent          1.0                 148220cc033d        12 months ago       12.2MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
7f664bbfda4d        docksal/web:2.1-apache2.4   "httpd-foreground"       18 minutes ago      Up 18 minutes             80/tcp, 443/tcp                                          nyscertified_web_1
a861214f207a        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      26 minutes ago      Up 26 minutes                                                                      docksal-ssh-agent
552f9294f753        docksal/dns:1.0             "/opt/entrypoint.sh …"   26 minutes ago      Up 26 minutes             192.168.64.100:53->53/udp                                docksal-dns
119d2d3ae31c        docksal/vhost-proxy:1.1     "docker-entrypoint.s…"   26 minutes ago      Up 26 minutes             192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
0ea9bfa14b09        docksal/db:1.1-mysql-5.6    "/entrypoint.sh mysq…"   About an hour ago   Up 18 minutes             0.0.0.0:32812->3306/tcp                                  nyscertified_db_1
a1cc1403026c        docksal/cli:1.3-php5        "/opt/startup.sh sup…"   About an hour ago   Up 18 minutes (healthy)   22/tcp, 9000/tcp                                         nyscertified_cli_1

███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.1.28r117968

███  VIRTUALBOX NETWORK INTERFACES
Name:            VirtualBox Host-Only Ethernet Adapter #3
GUID:            56ff2da6-ca6e-46ee-a42c-b21cc4751e1b
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:09fd:ec37:1620:a251
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:07
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #3

███  HDD Usage
Caption  FreeSpace     Size
C:       153820495872  254859345920
D:       999979794432  1000202039296
E:

███  RAM Usage
find: ‘Available Physical Memory’: No such file or directory

███  RAM Usage per container
CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
7f664bbfda4d        nyscertified_web_1    0.14%               5.723MiB / 3.837GiB   0.15%               1.14kB / 0B         7.97MB / 0B         82
a861214f207a        docksal-ssh-agent     0.00%               1.297MiB / 3.837GiB   0.03%               1.07kB / 0B         0B / 0B             2
552f9294f753        docksal-dns           0.37%               15.2MiB / 3.837GiB    0.39%               48.5kB / 50.6kB     0B / 0B             12
119d2d3ae31c        docksal-vhost-proxy   0.28%               17.41MiB / 3.837GiB   0.44%               2.25kB / 0B         0B / 4.1kB          12
0ea9bfa14b09        nyscertified_db_1     0.07%               492.6MiB / 3.837GiB   12.54%              1.16kB / 0B         31.5MB / 135MB      21
a1cc1403026c        nyscertified_cli_1    0.04%               30.12MiB / 3.837GiB   0.77%               1.32kB / 0B         65.5MB / 32.8kB     6
{ nyscertified } master » 

</details>

**Comment by achekulaev** [comment]
Hi. `init` is a custom command created by users. If you have any questions or issues on Docksal commands I can try to help, but so far I do not understand the question.

**Comment by judy-akers** [comment]
I am trying to clone an existing website from github (along with it's database) and get it running in Babun.

Is there a way to take an existing site, and get it to work locally in Babun?

**Comment by achekulaev** [comment]
Sure, you do a `fin up` and you have your containers running. You can import database with `fin db import --db=nyscertified your_dump_file.sql` etc. 

However `init` is a custom script, we call it custom command (https://docs.docksal.io/en/master/fin/custom-commands/), because for you it looks like a `fin` command, but it's not a built-in. Docksal allows developers to create their own custom commands to make it easier for others in a team to install a site. However we do not control that automation. Whoever creates it does.

Apparently the `init` script in project you are trying to install has some error. However we did not create that file.

**Comment by achekulaev** [comment]
Feel free to update here if you have any further questions.
