### ISSUE TITLE
Documenting commands as part of subfolders

### ISSUE THREAD

**Issue by sean-e-dietrich** [docksal/docksal#460]
**Description**

When writing custom commands whether they are global or project specific you can place the commands in subfolders to organize them but when you try to get a list of those commands they aren't showing up in the list.

Problem/feature description...

**Steps to reproduce the issue:**

1. create folder in `~/.docksal/commands/example`
2. create new command in example folder called `cmdexample`
3. type `fin`
4. Command does not show up in list
5. you can execute this command though using `fin example/cmdexample` though

**Comment by achekulaev** [comment]
Haha that was actually unintentional. You are not supposed to create "namespaces" for commands. If you need a complex command you might want to create an addon.

**Comment by achekulaev** [comment]
Fixed in 
https://github.com/docksal/docksal/pull/526/files
https://github.com/docksal/docksal/pull/527
