### ISSUE TITLE
Document command variable for the cli container

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#464]
There is an ability to configure which command to run upon `cli` start. It should be documented.

**Comment by sean-e-dietrich** [comment]
@achekulaev was this documented as apart of #543 ?

**Comment by achekulaev** [comment]
No, it wasn't. It is not an environment variable, but rather a way to heavily customize compose file.
https://docs.docker.com/compose/compose-file/compose-file-v2/#command

**Comment by lmakarov** [comment]
Here's an example of the approach:
https://github.com/docksal/example-nodejs/blob/master/.docksal/docksal.yml#L10
