### ISSUE TITLE
Non-fatal error during fin sqli

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#465]
I noticed a non-fatal error when I run `fin sqli "../tmp/db.sql"` for a project.

```
Importing DB from dump...
Truncating default database...
bash: syntax error near unexpected token `;'
There were errors during truncation. Continue anyways? [y/n]: y
Importing db.sql...
```

After `Continue anyways? [y/n]: y` everything works just fine (at least I did not notice any further issues).

**Comment by achekulaev** [comment]
Relates to https://github.com/docksal/docksal/commit/dd991170cbb10311f73ca82af0e668a528320aae
