### ISSUE TITLE
How to uninstall on linux ?

### ISSUE THREAD

**Issue by softeg** [docksal/docksal#466]
Hello,

I have windows 7 at my local machine and installed docksal to try it in my VM (virtualbox), it works but sometimes i need to use my older images ( older projetcts that works without docksal), to switch i need to stop three containaire ssh-agent, dns, proxy, but after this i don't have internet on my vm ? 

I think the problem was the dns contanaire. what i need to do to have internet after stopping dns service.

Do you have solution for this ?

Docksal is good solution, but i need to try it with multiple solution befor to adopt it.

Thanks

**Comment by achekulaev** [comment]
> How to uninstall on linux

> I have windows 7 at my local machine

So Linux or Windows?
I don't understand your setup sorry.

**Comment by softeg** [comment]
My base OS is windows 7. i have installed virtualbox on windows with ubuntu.

After i installed docksal on my virtualbox ubuntu.

It's not easy to install docksal on windows7, i need to install virtualbox linux and deploy my code from windows to ubuntu (virtualbox) with sftp with phpstorm.
I hope it's clear for you now ?

**Comment by achekulaev** [comment]
What version of Ubuntu do you have in the box?

**Comment by softeg** [comment]
Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:        8.6
Codename:       jessie

**Comment by achekulaev** [comment]
That's... not Ubuntu...

**Comment by softeg** [comment]
Yes forgive it is debian, is not supported by docksal ?

**Comment by achekulaev** [comment]
It is not officially supported. It will work but might have side issues like the one you are experiencing.

**Comment by lmakarov** [comment]
The steps to uninstall Docksal and Docker entirely are already covered in the docs: https://docs.docksal.io/en/master/getting-started/setup/#uninstallation

The only part missing right now is returning the DNS resolver/network settings back to pre-Docksal state on Linux. That's something we'll need to work on.

Also, in the next Docksal release there will be and new command (`fin system stop`) that can be used to stop/remove Docksal system services if you do not plan to use Docksal, but want to keep Docker, or want to use another Docker based tool and the two do not play nicely together.

**Comment by seyfer** [comment]
duplication of https://github.com/docksal/docksal/issues/234

also, there is a case, when Ubntu was reinstalled, and there is no more `fin` command, but docksal containers are still up and running in Docker desktop in the new system, because `/home` was moved.
In this case, first install `fin` following docs, and then follow the uninstall steps at the bottom of the docs.
