### ISSUE TITLE
What is the best way to install XHProf on Docksal

### ISSUE THREAD

**Issue by paulsheldrake** [docksal/docksal#467]
I would like to do some profiling of my drupal app and I'm wondering if docksal supports xhprof?

Thanks,
Paul

**Comment by lmakarov** [comment]
Looks like [xhprof](https://pecl.php.net/package/xhprof) is no longer maintained and not (officially) supported on PHP 5.6 and above

https://github.com/phacility/xhprof/issues/81
https://github.com/wodby/drupal-php/issues/49#issuecomment-360975377
http://php.net/manual/en/book.xhprof.php#122247

You can try using [Blackfire](https://docs.docksal.io/en/master/tools/blackfire/) instead.

**Comment by nginex** [comment]
@paulsheldrake In case, when you really want to use XHProf you can try to follow this [instruction](https://gist.github.com/nginex/47fa58f9051357cc4de6d79e6d9e96dd)

**Comment by lmakarov** [comment]
Oh wow, thanks for figuring this out @nginex !

I see the setup is quite involved, with a custom image build for xhprof.
We could turn this into an official `docksal/xhprof` image. Would you be willing to contribute / co-maintain it?

**Comment by nginex** [comment]
Hey @lmakarov, thanks

This is a great opportunity to make it available as official image. I think a lot of developers need this. So I say yes, I would like to contribute / co-maintain it.

**Comment by nadavoid** [comment]
For anyone else looking for this, it's ready to go in docksal now. See https://docs.docksal.io/en/develop/tools/blackfire/

Many thanks to @nginex for your work on this.
