### ISSUE TITLE
Setting Up Docksal on Windows 10 - "host-only cidr conflicts"

### ISSUE THREAD

**Issue by gwalliman** [docksal/docksal#474]
**Description**
I have followed the provided instructions for installing Docksal on Windows 10 Pro version 10.0.17 115 Build 17115. After installing Babun and installing Docksal using "curl -fsSL https://get.docksal.io | sh", I have attempted to use "fin vm start" to perform the one-time configurations.

Upon doing so, it runs through installing docker, creating the VM, installing ssh keys, and running a network check, at which point it reports an error. The error is:
"Error creating machine: Error in driver during machine creation: Error setting up host only network on machine start: host-only cidr conflicts with the network address of a host interface"

I have done a thorough search and have not found any software that should cause this conflict. This includes:

1. Running netstat to review all active ports. No application was found using ports 80 or 443, or subnet 192.168.64.x.
2. Reviewing all running services in task manager
3. Closing all active programs from the system tray and toolbar

Despite all this the error still occurs.

**Steps to reproduce the issue:**

1. Follow instructions for installing Docksal on Windows 10 Pro version 10.0.17 115 Build 17115 up to "fin vm start"
2. Run "fin vm start". The error will occur.

**Describe the results you received:**

Result is the following error: "Error creating machine: Error in driver during machine creation: Error setting up host only network on machine start: host-only cidr conflicts with the network address of a host interface". I am also prompted to remove the incomplete container, which I do.

**Describe the results you expected:**

Expected behavior: successful setup.

*Note that in the following output items, several items are missing due to docker apparently being uninstalled after the failure experienced above.*

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>
 ERROR:  Cannot detect project root.
         Please make sure you have .docksal directory in the root of your project.
         To setup a basic Docksal stack in the current directory run fin config generate
</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>
███  OS
 Microsoft Windows [Version 10.0.17115.1]
CYGWIN_NT-10.0-WOW G_WORKSTATION 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
Mode: VirtualBox VM

███  FIN
fin version: 1.43.2

███  ENVIRONMENT
DOCKER_HOST             |
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

███  DOCKER INFO
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
███  DOCKER COMPOSE
EXPECTED VERSION: 1.17.1
docker-compose version 1.17.1, build 6d101fb0
docker-py version: 2.5.1
CPython version: 2.7.14
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

███  DOCKER MACHINE
EXPECTED VERSION: 0.13.0
docker-machine.exe version 0.13.0, build 9ba6da9

NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS

███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.1.28r117968

███  VIRTUALBOX NETWORK INTERFACES
Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            7e79f0e7-4da9-4adb-93e8-53bb00c4111c
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:4cea:5cd2:7aea:07f6
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:0d
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2

███  HDD Usage
Docker machine docksal is not created. Use 'fin vm start' or 'fin up'.

███  RAM Usage
Docker machine docksal is not created. Use 'fin vm start' or 'fin up'.

███  RAM Usage per container
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
</details>

**Comment by achekulaev** [comment]
Do you happen to have 192.168.65.* network?

**Comment by achekulaev** [comment]
Please provide output of `ipconfig`

**Comment by gwalliman** [comment]
Thanks for the follow up @achekulaev. Your question set me down a path that ended up resolving the issue. It turned out there was a Docker virtual adapter from a previous Docker install that did not get removed with the uninstall. Removing this allowed me to get things working again.

Closing issue.
