### ISSUE TITLE
'fin sysinfo' incorrectly reports "Mode" on Linux

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#476]
```
leonid@ubuntu:~$ fin sysinfo
WARNING: No swap limit support
███  OS
Ubuntu 16.04
Linux ubuntu 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Mode: Linux Kernel
VirtualBox VM
...
```

`VirtualBox VM` is reported, since there is a check for `DOCKER_NATIVE=1`, which is not set on Linux by default. No sure if we want to set it automatically or not. Using VirtualBox on Linux is not a use cases we ever considered or supported.

**Comment by frederickjh** [comment]
Related issue #419

**Comment by frederickjh** [comment]
Should the check be looking to see if the OS is Linux and that the variable `DOCKER_NATIVE` is not set first?
