### ISSUE TITLE
Document SECRET_* environment variables for storing project secrets

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#492]
- `SECRET_SSH_PRIVATE_KEY`
- `SECRET_ACAPI_EMAIL`
- `SECRET_ACAPI_KEY`
- `SECRET_TERMINUS_TOKEN`

Relates to https://github.com/docksal/docksal/issues/488

**Comment by lmakarov** [comment]
Covered in https://github.com/docksal/docksal/commit/c0bbd2caa57b6dceaf751b4c162a0cf9202daf7f sans `SECRET_SSH_PRIVATE_KEY ` (which I'm not sure where to put for now).
