### ISSUE TITLE
Documentation request for SASS as provided by tools

### ISSUE THREAD

**Issue by shelane** [docksal/docksal#500]
Reading the docs on http://docksal.readthedocs.io/en/master/tools/sass it is unclear on the setup and technology used. Can you point to documentation that shows file structure expected, options, etc.? My previous experience with SASS is with gulp and I’d like to use what is already available in Docksal.

**Comment by achekulaev** [comment]
gulp is the better way and I would recommend to stick to it. (composer is pre-installed just because it's harder to install it then gulp and because at some point in time it was more widespread than gulp).

**Comment by achekulaev** [comment]
@david-hernandez yes, thanks.

**Comment by achekulaev** [comment]
@shelane can this one be closed?

**Comment by shelane** [comment]
Yes, you can close it.
