### ISSUE TITLE
Install fails on Ubuntu 18.04 LTS (Desktop and server)

### ISSUE THREAD

**Issue by ArturPugacescu** [docksal/docksal#510]
Tried installing on freshly installed Ubuntu 18.04 LTS (both Desktop and server). Getting the following error while installing docker. 
Manual docker installation seems to work.
`sudo apt intall docker.io`

```
root@ubuntu-s-1vcpu-1gb-ams3-01:~# curl -fsSL https://get.docksal.io | sh
/usr/local/bin/fin: line 5000: /root/.docksal/docksal.env: No such file or directory
sed: can't read /root/.docksal/docksal.env: No such file or directory
head: cannot open '/root/.docksal/stacks/services.yml' for reading: No such file or directory
[STEP 1/4] Updating fin... 1.52.0 [OK]
[STEP 2/4] Updating stack files...
overrides-osxfs.yml
services.yml
stack-acquia.yml
stack-default.yml
stack-default-nodb.yml
stack-node.yml
volumes-bind.yml
volumes-nfs.yml
volumes-unison.yml
[STEP 3/4] Updating tools...
WARNING: Installation is running not in a tty mode
Installing Docker...
# Executing docker install script, commit: 36b78b2
+ sh -c apt-get update -qq >/dev/null
+ sh -c apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic edge" > /etc/apt/sources.list.d/docker.list
+ [ ubuntu = debian ]
+ sh -c apt-get update -qq >/dev/null
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
E: Package 'docker-ce' has no installation candidate
sudo: docker: command not found
Docker installation/upgrade has failed.
```

**Comment by frederickjh** [comment]
It seems that the **docker-ce** package is not yet ready for 18.04. See this [issue](https://github.com/docker/for-linux/issues/290) for instructions on how you can install the current release candidate. Expected release date is some time in the first half of June.

**Comment by achekulaev** [comment]
Yup. At this point we can just wait. Or install docker manually.

**Comment by frederickjh** [comment]
This is the risk of using the "latest and greatest".

If you were previously using Ubuntu 17.10 (or an other non-LTS release) you would be prompted that an new release was available about a week after 18.04 came out.

However if you were on a LTS (Long Term Support) release you would not get prompted to upgrade until the 18.04.1 release comes out in June, which is about the same time that the Docker package should come out.

@achekulaev should this get tagged with **upstream**  and **ubuntu** tags?
Should this information go on the Linux installation page, until there is a `docker-ce` package for Ubuntu 18.04? If we did that we could close this issue, otherwise lets leave it open until the package is available.

**Comment by JDJoe** [comment]
docker.io (17.12.1-0ubuntu1) fails 

```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2018-06-06 12:53:30 ; 3ms ago
     Docs: https://docs.docker.com
  Process: 13951 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 13951 (code=exited, status=1/FAILURE)

```

**Comment by frederickjh** [comment]
@JDJoe, are you running Ubuntu 18.04 LTS? Did you install the **docker-ce** package  using the [link above](https://github.com/docker/for-linux/issues/290)  to install the current release candidate?

In any case more details are need. However if you are on Ubuntu 18.04 then this is a **known** upstream issue, as the **docker-ce** package is not yet available for 18.04 and not something that will be fixed in Docksal.

**Comment by achekulaev** [comment]
@JDJoe looks at your output seems like you have `docker` service manually disabled.

```
Loaded: loaded (/lib/systemd/system/docker.service; disabled;
```

**Comment by JDJoe** [comment]
this is what I got and it's default /lib/systemd/system/docker.service  

At least I have not touched it. 

```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target docker.socket firewalld.service
Wants=network-online.target
Requires=docker.socket

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd -H fd://
ExecReload=/bin/kill -s HUP $MAINPID
LimitNOFILE=1048576
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process
# restart the docker process if it exits prematurely
Restart=on-failure
StartLimitBurst=3
StartLimitInterval=60s

[Install]
WantedBy=multi-user.target
```

**Comment by achekulaev** [comment]
Sorry I don't know what is the reason of docker service not working for you, but you need to figure out ho to get your docker service working first. Once docker service is working you can proceed with installing Docksal.

**Comment by lmakarov** [comment]
The 18.05.0 edge release is now available for Ubuntu 18.04:
https://download.docker.com/linux/ubuntu/dists/bionic/pool/edge/amd64/

```
docker-ce_18.05.0~ce~3-0~ubuntu_amd64.deb  2018-06-08 05:59  33M
```

Using a DigitalOcen Ubuntu 18.04 droplet I was able to install Docker manually and then Docksal like this:

```
curl -L get.docker.com | bash
curl -L get.docksal.io | CI=true bash
```

Note: `CI=true` above is used to open Docksal up to the world (bind `vhost-proxy` to `0.0.0.0`).

```
$ docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:16:13 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:14:23 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

The fully automated setup via Docksal on Ubuntu 18.04 will come once Docker 18.06.0 stable branch is released. That should happen prior to the next Docksal release.

**Comment by achekulaev** [comment]
This one it fixed now in develop with universal support for distros, that are supported by get.docker.com.
Will get release with the next stable release.

**Comment by lmakarov** [comment]
Interestingly, Docker decided to publish the 18.03.1 stable release for Ubuntu 18.04 a few weeks ago:
https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/

```
docker-ce_18.03.1~ce~3-0~ubuntu_amd64.deb  2018-06-20 11:28  33M
```

**Comment by aatral-hub** [comment]
Thanks a lot @lmakarov Its working fine now in Ubantu 18.04 LTS version.
