### ISSUE TITLE
Docksal is not working with Docker 18.03.1-ce-win65 

### ISSUE THREAD

**Issue by dealancer** [docksal/docksal#529]
It appears that Docker for Windows has been updated automatically and I can not use Docksal with it. I am seeing an error message when I run `fin up`:

```
{ project} dev » fin up
could not read CA certificate "C:\\Users\\user\\.docker\\machine\\machines\\default\\ca.pem": open C:\Users\user\.docker\machine\machines\default\ca.pem: The system cannot find the path specified.
could not read CA certificate "C:\\Users\\user\\.docker\\machine\\machines\\default\\ca.pem": open C:\Users\user\.docker\machine\machines\default\ca.pem: The system cannot find the path specified.
 ALERT:  Required Docker version is 17.09.0-ce
         Run fin update to update to the required version.

could not read CA certificate "C:\\Users\\user\\.docker\\machine\\machines\\default\\ca.pem": open C:\Users\user\.docker\machine\machines\default\ca.pem: The system cannot find the path specified.
 ERROR:  Your Docker client is unable to talk to the Docker server.
         WHAT TO DO?
         Check that your Docker for Mac/Win app is running.
```

Running `fin update` does not help:

```
{ project } dev » fin update
could not read CA certificate "C:\\Users\\user\\.docker\\machine\\machines\\default\\ca.pem": open C:\Users\user\.docker\machine\machines\default\ca.pem: The system cannot find the path specified.
could not read CA certificate "C:\\Users\\user\\.docker\\machine\\machines\\default\\ca.pem": open C:\Users\user\.docker\machine\machines\default\ca.pem: The system cannot find the path specified.
[STEP 1/4] Updating fin... 1.52.0 [OK]
[STEP 2/4] Updating stack files...
overrides-osxfs.yml
services.yml
stack-acquia.yml
stack-default.yml
stack-default-nodb.yml
stack-node.yml
volumes-bind.yml
volumes-nfs.yml
volumes-unison.yml
[STEP 3/4] Updating tools...
could not read CA certificate "C:\\Users\\user\\.docker\\machine\\machines\\default\\ca.pem": open C:\Users\user\.docker\machine\machines\default\ca.pem: The system cannot find the path specified.
Installing docker client v17.09.0-ce...
Downloading docker-17.09.0-ce.zip...
######################################################################## 100.0%
Archive:  docker-17.09.0-ce.zip
   creating: docker/
  inflating: docker/dockerd.exe
  inflating: docker/docker.exe
Going to optimize Windows network settings for file sharing...
You may see an elevated command prompt - click Yes.
Adjusting git defaults...
git config --global core.autocrlf input
git config --system core.longpaths true
[STEP 4/4] Updating system images...
could not read CA certificate "C:\\Users\\user\\.docker\\machine\\machines\\default\\ca.pem": open C:\Users\user\.docker\machine\machines\default\ca.pem: The system cannot find the path specified.
 ALERT:  Required Docker version is 17.09.0-ce
         Run fin update to update to the required version.

could not read CA certificate "C:\\Users\\user\\.docker\\machine\\machines\\default\\ca.pem": open C:\Users\user\.docker\machine\machines\default\ca.pem: The system cannot find the path specified.
 ERROR:  Your Docker client is unable to talk to the Docker server.
         WHAT TO DO?
         Check that your Docker for Mac/Win app is running.

```

**Comment by dealancer** [comment]
I also noticed there is no `default` machine in `machines` directory, only `docksal` one.

**Comment by achekulaev** [comment]
@dealancer docker machine uses VirtualBox, not Docker for Windows. Updating Docker for Windows does not affect docker machine machines.  

So I don't get the issue.

Looking at your screenshots I see that your Docker Machine is broken. Apparently you accidentally removed it's files. 
I would recommend `fin vm remove`, `fin vm start`.

**Comment by dealancer** [comment]
@achekulaev as far as I know Docksal can use both VirtualBox and Docker for Windows. In my case I am using Docker for Windows and Windows with Hyper-V enabled. See https://docs.docksal.io/en/master/getting-started/env-setup-native/

I don't remember removing any files. I will try to run this commands and see what happens.

**Comment by achekulaev** [comment]
If you are trying to use Docker for Windows then you Docksal installation does not seem to be properly configured to use Docker for Windows. 
Unfortunately I can not tell more since you have not provided `fin sysinfo`

**Comment by achekulaev** [comment]
Take a look at this thread https://github.com/docker/for-win/issues/1746#issuecomment-376280377

**Comment by kyleskrinak** [comment]
I use chocolatey for package management, and DfW was automatically updated on my Win10 system as well. Uninstalling Docker CE for Windows 18.03.1.17513 and installing 18.03.1.17438 has allowed me to resume using Docksal.

**Comment by dealancer** [comment]
@achekulaev, thanks.

Following solution worked:

Go to Control Panel\All Control Panel Items\System Then click Advanced system settings, In System Properties, Go to Advanced Tab and Click Environment Variables. Delete all DOCKER_* from System/User variables.

Remove DOCKER_* from command prompt or PowerShell, i used PowerShell. using following steps

[Environment]::SetEnvironmentVariable("DOCKER_CERT_PATH", $null, "User")
[Environment]::SetEnvironmentVariable("DOCKER_HOST", $null, "User")
[Environment]::SetEnvironmentVariable("DOCKER_MACHINE_NAME", $null, "User")
[Environment]::SetEnvironmentVariable("DOCKER_TLS_VERIFY", $null, "User")
[Environment]::SetEnvironmentVariable("DOCKER_TOOLBOX_INSTALL_PATH", $null, "User")
