### ISSUE TITLE
Drush 8 default path-alias for files fails under fin cli

### ISSUE THREAD

**Issue by tekNorah** [docksal/docksal#534]
When I cd into my docroot and execute: 
`drush rsync @prod:%files @dev:%files`

Drush will automatically point to the **correct** %files location on prod (Cloudways DO App) and dev (local Mac OSX).

BUT…… If I execute:
`fin @d8site drush rsync @prod:%files @dev:%files`

using the docksal cli to locate the project on my machine via an alias, `@dev:%files` resolves to: `/var/www/docroot/%files`

In order to get this to resolve correctly for local (@dev), I have to explicitly add this line to the `path-aliases` in the `$DOCROOT/drush/aliases/aliases.drushrc.php` file:

`'%files' => 'sites/default/files’,`

Any idea why this is happening?

**Comment by lmakarov** [comment]
You may have extra settings in `~/.drush/drushrc.php` on your Mac, which are not available in `cli`. That way, your host's drush will behave differently then the one in `cli`.

What's the output of `drush sa @dev` an `fin drush sa @dev` (run both inside your project's docroot).

**Comment by tekNorah** [comment]
Hi @lmakarov!  Here is the output you are looking for:

I have drush installed on my project. Also, I don't have any global drush aliases defined.

`$ less ~/.drush/drushrc.php: No such file or directory`

But, do have a drushrc.php in my docker vm, but I don't see any mention of %files.

in ~/Sites/[project]/docroot:

```
$ drush sa @dev
$aliases["dev"] = array (
  'uri' => 'http://lovin.docksal',
  'root' => '/var/www/docroot',
  'path-aliases' => 
  array (
    '%files' => 'sites/default/files',
    '%dump-dir' => '/var/www/db',
  ),
);

$ fin drush sa @dev
$aliases["dev"] = array (
  'uri' => 'http://lovin.docksal',
  'root' => '/var/www/docroot',
  'path-aliases' => 
  array (
    '%files' => 'sites/default/files',
    '%dump-dir' => '/var/www/db',
  ),
);

```

**Comment by tekNorah** [comment]
Hmm... wait... I just tried commenting out the files path alias and ran the rsync command again at it is working correctly now.  I cleared out acquia settings from ~/.drush and my project since I orignally posted, might have been something to do with that.
