### ISSUE TITLE
Docker docker-18.03.1-ce binaries for Windows are not available

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#537]
We recently switched to docker-18.03.1-ce (in develop), however we won't be able to release until Windows binaries are available for download.

See: https://github.com/docker/for-win/issues/1460#issuecomment-390045959

As a workaround we could pull the `docker.exe` binary from Docker for Windows and publish it as part of the release.

**Comment by lmakarov** [comment]
Addressed via 8b1fe9ae972b571f65ba7394ddc6e9849633014b

TODO: update download URL when releasing v1.9.0

**Comment by achekulaev** [comment]
I guess we need smth like this so we wouldn't have to update links every time

```bash
DOCKSAL_TAG="${DOCKSAL_TAG:-v1.9.0}"
URL_DOCKER_WIN="https://github.com/docksal/docksal/releases/download/v${DOCKSAL_TAG}/docker-${REQUIREMENTS_DOCKER}.zip"
```

**Comment by lmakarov** [comment]
@achekulaev at some point Docker will release new binaries for Windows 🤞
Updating the `URL_DOCKER_WIN ` is not a big deal and will be a reminder that a binary needs to be pulled out of Docker for Windows and uploaded into the release page on Github.
