### ISSUE TITLE
Symfony Docksal Project Create

### ISSUE THREAD

**Issue by sean-e-dietrich** [docksal/docksal#546]
Add Symfony as an option when setting up a new Docksal Project. This extends into a completely different community of PHP Developers.

## Examples:

https://github.com/sean-e-dietrich/symfony-webapp
https://github.com/sean-e-dietrich/docksal-symfony-skeleton

Built using the following [page](https://symfony.com/download) as a guidance.

**Comment by lmakarov** [comment]
@sean-e-dietrich great idea! What's the difference between your two examples?

**Comment by lmakarov** [comment]
@sean-e-dietrich feel free to move these repos into the Docksal organization as:
- docksal/example-symfony-webapp
- docksal/example-symfony-skeleton

TODOs (similar to other example projects):
- add README.md
- add a basic test case (in `fin test`)
- add .travis.yml

**Comment by lmakarov** [comment]
@sean-e-dietrich I enabled builds in Travis for both repos. Please check the out, as they are currently failing:

https://travis-ci.org/docksal/example-symfony-webapp/builds/383347051
https://travis-ci.org/docksal/example-symfony-skeleton/builds/383347242

**Comment by sean-e-dietrich** [comment]
Thanks @lmakarov I tested this out and looks like I was checking for 200 when by default Symfony gives you a 404

**Comment by lmakarov** [comment]
All good now. Closing.
