### ISSUE TITLE
Blackfire not working with default configuration

### ISSUE THREAD

**Issue by sch4lly** [docksal/docksal#561]
**Description**

When following the instructions from https://docs.docksal.io/en/develop/tools/blackfire/ the profiler does not work. I had to add `blackfire.agent_socket = tcp://blackfire:8707` to my php.ini - the default value for this is `unix:///var/run/blackfire/agent.sock`, which led to the following warning in the logs `Unable to connect probe to socket : No such file or directory`.

**Steps to reproduce the issue:**

1. Follow the instructions on https://docs.docksal.io/en/develop/tools/blackfire/

**Describe the results you received:**

I got the error `Are you authorized to profile this page? Probe not found, invalid signature (HTTP 200)`from the Chrome and Firefox extensions.

**Describe the results you expected:**

Working blackfire

**Comment by lmakarov** [comment]
Thanks for reporting. Blackfire settings got accidentally dropped during the 2.0 cli image upgrade.
I added them back. This will be released in docksal/cli v2.2

**Comment by achekulaev** [comment]
@lmakarov I guess fixes should be included into recipes for 2.0 and 2.1 images as well. Just in case.

**Comment by lmakarov** [comment]
@achekulaev it's not a critical issue and there is a know workaround mentioned in this ticket. I'm reluctant to roll-out hotfix releases for the previous image versions.
