### ISSUE TITLE
Minor errors during installation on a fresh system (from develop)

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#562]
**Description**

There are minor errors during installation on a fresh system (Docksal develop version).
The following condition check is now working correctly: 
https://github.com/docksal/docksal/blob/e02ec2e505ed05d9c902aa47cf10f75773cab10a/bin/fin#L5555

The installation process completes successfully. 

**Steps to reproduce the issue:**

1. Launch a new PWD (Play with Docker) environment
2. Install Docksal with `$ curl -sSL https://get.docksal.io | DOCKSAL_VERSION=develop bash`

**Describe the results you received:**

```
curl -sSL https://get.docksal.io | DOCKSAL_VERSION=develop bash
/usr/local/bin/fin: line 5000: /root/.docksal/docksal.env: No such file or directory
sed: /root/.docksal/docksal.env: No such file or directory
head: /root/.docksal/stacks/services.yml: No such file or directory
...
```

**Describe the results you expected:**

No errors

**Output of `fin config`:**

N/A

</details>

<br>

**Output of `fin sysinfo`:**

N/A

</details>

**Comment by achekulaev** [comment]
Errors appear because get.docksal.io always downloads master. Use test.docksal.io to test dev versions.

<img width="1366" alt="2018-06-01_0004" src="https://user-images.githubusercontent.com/402007/40820594-6f42f19c-652f-11e8-9f08-4329c9180249.png">

**Comment by lmakarov** [comment]
@achekulaev test.docksal.io and get.docksal.io have diverged and need to be manually synced up.

With get.docksal.io the error is still there:

![image](https://user-images.githubusercontent.com/1205005/40863124-a07c550e-65a3-11e8-9a19-26925fd94309.png)

**Comment by achekulaev** [comment]
Related https://github.com/docksal/get.docksal.io/issues/1

**Comment by achekulaev** [comment]
Resolved in the ticket, referenced above.
