### ISSUE TITLE
Document PostreSQL support

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#564]
PostreSQL support was discussed and added in https://github.com/docksal/docksal/issues/193.

See https://github.com/docksal/docksal/issues/193#issuecomment-379113681 (and https://github.com/docksal/docksal/issues/193#issuecomment-376343111) for instructions on using it.

We now needs docs updated/restructured accordingly to cover this use case.

**Comment by achekulaev** [comment]
It is not really added. fin db function do not work for pgsql

**Comment by lmakarov** [comment]
> It is not really added. fin db functions do not work for pgsql

The stack piece is there and can be used.
I created #567 to cover the `fin db` piece. Thanks for pointing that out.
