### ISSUE TITLE
Cloud9 IDE integration

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#568]
The idea comes from https://github.com/BrianGilbert/docksal-core-sprint

Cloud9 provides a web-based IDE environment for editing code and also has a web-base terminal.
We will need a custom `docksal/cloud9` image based on `docksal/cli`.  It can be run either as a separate service or a replacement for the stock `cli` image.

The former option may result in frustrating inconsistencies between the `fin bash` shell (run in `cli`) and the shell in Cloud9 (run in `cloud9` container). E.g., when additional packages are installed in one, they won't be available in the other one. This way, the latter option is preferable.

**Comment by achekulaev** [comment]
Is it done?

**Comment by achekulaev** [comment]
Related 
https://github.com/docksal/service-cli/issues/50
https://github.com/docksal/docksal/issues/595

**Comment by shelane** [comment]
Is this needed anymore with #1194 ?

**Comment by lmakarov** [comment]
Cloud9 was replaced with VS Code Server.
