### ISSUE TITLE
Document CONTAINER_NAME variable for fin exec

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#580]
`fin exec` can execute commands in different containers because it uses `CONTAINER_NAME` environment variable. We need to document it

```bash
19:39:42 ~/Projects/d8test
§ CONTAINER_NAME=web fin exec uname -a
Linux web 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 Linux

19:39:48 ~/Projects/d8test
§ CONTAINER_NAME=cli fin exec uname -a
Linux cli 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 GNU/Linux

19:39:57 ~/Projects/d8test
§ CONTAINER_NAME=unison fin exec uname -a
Linux 4f83e1095edf 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 Linux
```

**Comment by lmakarov** [comment]
IIRC `CONTAINER_NAME ` was mostly an internal workaround in fin.
If we are going to expose it, then I suggest we move this feature into a parameter to `fin exec`, e.g.:

```
fin exec --service=web uname -a
```

**Comment by lmakarov** [comment]
Another option would be to make it a required argument similar to how `docker-compose exec` works:

```
fin exec web uname -a
```

Unfortunately,  this would introduce a breaking change, so we may have to stick with the `--service=` option.

**Comment by achekulaev** [comment]
One of crazy UI ideas I had is to make fin accept `exec-containername`. It's against all standards but so appealing...

**Comment by achekulaev** [comment]
Moving enhancement ideas to https://github.com/docksal/docksal/issues/609
