### ISSUE TITLE
nvm: command not found

### ISSUE THREAD

**Issue by ramns** [docksal/docksal#587]
**Description**

Since fin update to 1.60.0, there is some problem with NVM. While project init it breaks and there is an error message. It says `bash: nvm: command not found`. Does anyone else has the same problem?

**Steps to reproduce the issue:**

You can reproduce this if you are using node and npm packages inside your project.
This is the starting command where it breaks:
`fin exec nvm use node`

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
OS
Linux Ubuntu 16.04
Linux user 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Mode: Linux Kernel

FIN
fin version: 1.60.0

ENVIRONMENT
DOCKER_HOST		| 
 WARNING:  Non-default DOCKER_HOST

DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false

  ```

</details>

Thanks in advance.

**Comment by achekulaev** [comment]
@ramns please share `fin config` output

**Comment by ramns** [comment]
`---------------------
COMPOSE_PROJECT_NAME_SAFE: project
COMPOSE_FILE:
/home/user/.docksal/stacks/volumes-bind.yml
/home/user/.docksal/stacks/stack-default.yml
/home/user/www/project/.docksal/docksal.yml
ENV_FILE:
/home/user/www/project/.docksal/docksal.env
/home/user/www/project/.docksal/docksal-local.env

PROJECT_ROOT: /home/user/www/project
DOCROOT: docroot
VIRTUAL_HOST: project.docksal
VIRTUAL_HOST_ALIASES: *.project.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32771

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      HOST_GID: '1000'
      HOST_UID: '1000'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: project.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:edge-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.0-apache2.4
    labels:
      io.docksal.project-root: /home/user/www/project
      io.docksal.virtual-host: project.docksal,*.project.docksal,project.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/user/www/project
      o: bind
      type: none

---------------------`

**Comment by achekulaev** [comment]
As per output you use `docksal/cli:edge-php7.1` for the `cli` image. That image is a bleeding *edge*, used usually for development purposes or for testing out the latest dev changes. 
It is not stable and can contain errors (but FYI @lmakarov that there might be an issue with it)

@ramns please try using latest stable image which is `docksal/cli:2.2-php7.1`.

```
fin config set CLI_IMAGE="docksal/cli:2.2-php7.1"
fin project start
```

**Comment by ramns** [comment]
@achekulaev Ok, i will try it now.

**Comment by ramns** [comment]
@achekulaev all good now. Thank you very much. :)

**Comment by lmakarov** [comment]
> `fin exec nvm use node`

nvm has been removed in the edge versions of `docksal/cli`. There is now a globally installed nodejs.
This will be a breaking change for those using nvm.
