### ISSUE TITLE
Is there a way to set docroot to current directory?

### ISSUE THREAD

**Issue by goldingdamien** [docksal/docksal#590]
If I have say my_project/.docksal and all the code for my_project starts in my_project say my_project/index.php, can I change the config so that my_project becomes docroot instead, and if so how and are there any side effects?

If not, my desire is to have an easy way to start a LAMP environment without moving any project files such as possible in http-server in npm(node js). Any alternatives would be considered. Regards.
* I am new to docksal so may have missed something.

**Comment by sean-e-dietrich** [comment]
Hi @goldingdamien yes it is possible.

In `.docksal/docksal.env` set the following:

```
DOCROOT=.
```

This will tell Docksal that your current document root is the same as your project root. Once you have done that a `fin restart` should be all that is necessary for Docksal to pick up the changes.

**Comment by goldingdamien** [comment]
Works fine, thanks.
