### ISSUE TITLE
Using xdebug with Cloud9 IDE

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#595]
Figure out how to use xdebug with the Cloud9 IDE integration. Document and blog about it.

This will most likely require changes in the Cloud9 installation (`docksal/cli`)

**Comment by lmakarov** [comment]
This may help: https://medium.com/@kalin.chernev/drupal-8-on-cloud9-ide-1a294328e1aa

**Comment by shelane** [comment]
Is this needed anymore with #1194 ?

**Comment by lmakarov** [comment]
Cloud9 was replaced with VS Code Server.
