### ISSUE TITLE
Adminer / phpmyadmin howto?

### ISSUE THREAD

**Issue by ygerasimov** [docksal/docksal#6]
How to have adminer or phpmyadmin for the local environment?

I would love to be able to investigate my database on the environment.

**Comment by vgrygoryev** [comment]
You can use some visual MySql tool. I use MySQL Workbench -  https://www.mysql.com/products/workbench/
It  is available on Windows, Linux and Mac OS X

Or you can instal phpMyAdmin for Docksal: https://github.com/docksal/phpmyadmin

In both cases you need to bind MySql port from you project container to the host. And using this port you will be able to connect to your DB on localhost. Please see readme here https://github.com/docksal/phpmyadmin

**Comment by ygerasimov** [comment]
thanks for instructions

**Comment by lmakarov** [comment]
@ygerasimov you can also connect to project DBs with any external tool by following these instructions
https://github.com/docksal/docksal/blob/develop/docs/db-access.md

**Comment by frederickjh** [comment]
Last link is now broken. Try this link to the documents instead:
https://docksal.readthedocs.io/en/master/advanced/db-access/

**Comment by AleksandrL** [comment]
frederickjh, vg42, both links are 404.

> "Please see readme here https://github.com/docksal/phpmyadmin"

> "Try this link to the documents instead: https://docksal.readthedocs.io/en/master/advanced/db-access/"

Please explain here how to connect to localhost MySQL server from project container.

**Comment by shelane** [comment]
The updated link for accessing external MySQL tools is
https://docs.docksal.io/service/db/access/

I use the [sequel pro add on](https://github.com/docksal/addons)

This allows me to open sequel pro automatically with the connection information for the current project.
