### ISSUE TITLE
ERROR: unable to remove volume: remove projectname_project_root: volume is in use

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#602]
```
$ fin rm -f
WARNING: No swap limit support
Removing containers...
Removing network emmis-develop_default
WARNING: Network emmis-develop_default not found.
Removing volume emmisdevelop_project_root
ERROR: unable to remove volume: remove emmisdevelop_project_root: volume is in use - [49d925138d9b56e419ad06ea456638b8ea594b3bf73ea6e911ba0f8ab7632449, 4603b6838a85408c31afd4fa14d3f2c8ee51506925478eaa21a61d6ab204ddd4, 2dd3d6d1ba8919c13330aa0f9b00dbb48f0f3b582aadd36f798775fff270e82e]
```

Project root is in `/home/ubuntu/builds/emmis-develop`

This is another breaking change from the Docker Compose 1.19.0 => 1.21.1 update.

Downgrading to 1.19.0 fixes the problem:

```
$ sudo curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose 
```

```
$ fin rm -f
WARNING: No swap limit support
Removing containers...
Removing emmisdevelop_web_1 ... done
Removing emmisdevelop_cli_1 ... done
Removing emmisdevelop_db_1  ... done
Removing network emmisdevelop_default
WARNING: Network emmisdevelop_default not found.
Removing volume emmisdevelop_project_root
Volume docksal_ssh_agent is external, skipping
```

Renaming the folder to remove hyphens in the folder name results in a duplicate project error from Docksal:

```
fin rm -f
WARNING: No swap limit support
 ERROR:  Another project is already using the virtual hostname 'develop.emmis.sb1.us.ffwagency.com'
         Use a different hostname for this project by overriding the VIRTUAL_HOST variable in docksal.env
         or remove the other project's stack by running fin project remove in /home/ubuntu/builds/emmis-develop
```

Related to https://github.com/docksal/docksal/issues/589

**Comment by achekulaev** [comment]
`fin cleanup` should help

**Comment by lmakarov** [comment]
> Restart Docker daemon + fin cleanup should help

Nope. Tested. `fin cleanup` does not (and should never) remove volumes in use.

**Comment by achekulaev** [comment]
Rename folder + fin cleanup. fin will remove containers for non-existent path.

**Comment by lmakarov** [comment]
> Rename folder + fin cleanup

This works :)

Another option is to kill the project directory and run `fin cleanup`.
I ran into this on a sandbox server, so the latter is an easier solution in my case.

Since there is nothing else that can be done, I'm closing this ticket.

**Comment by anisur-rahman** [comment]
Hey Leonid,

Unable to remove a project when I killed the project dir manually  and ran fin cleanup.

$ fin cleanup
Checking for orphaned projects...
Removing dangling images...
Total reclaimed space: 0B
Removing dangling volumes...
Total reclaimed space: 0B

But when I run 
fin pl -a

Here is my out put
project             STATUS                            virtual host                                                   project root
drupal7             Exited (255) About a minute ago   drupal7.docksal,*.drupal7.docksal,drupal7.docksal.*            /Users/anisur/Sites/docksal-d7/drupal7

Could you please explain the follwing command: https://docs.docksal.io/fin/fin-help/
remove [option] [service] Remove all project services, networks and all their volumes, or specified services only
      rm [option] [service] 
    --force (-f)            Do not ask for confirmation when deleting all project services


Thanks



`

**Comment by lmakarov** [comment]
@anisur-rahman I'm not sure why `fin cleanup` would not remove a project stack for which the directory no longer exists. That sounds pretty weird.

What's the output of these commands?

```
fin docker ps -a
fin docker volume ls
fin docker network ls
```

**Comment by anisur-rahman** [comment]
Leonid, thanks for the reply.

I attended your online training class  'What and Why of DevOps with Ray Saltini, FFW and after that I installed  docksal on my machine. Successfully I installed D7 and D8, but unable to remove.

Manually I deleted Sites/docksal-d7/drupal7 folder. 
anisur$ fin pl -a
project             STATUS                    virtual host                                                   project root
docksal-d8          Up About a minute         docksal-d8.docksal,*.docksal-d8.docksal,docksal-d8.docksal.*   /Users/anisur/Sites/docksal-d8
docksal-d7          Exited (255) 3 days ago   docksal-d7.docksal,*.docksal-d7.docksal,docksal-d7.docksal.*   /Users/anisur/Sites/docksal-d7
drupal7             Exited (255) 2 days ago   drupal7.docksal,*.drupal7.docksal,drupal7.docksal.*            /Users/anisur/Sites/docksal-d7/drupal7
Mds-MacBook-Air:Sites anisur$ fin docker ps -a


***_ Here is the output 

anisur$ fin docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                     PORTS                                                    NAMES
d3c3fa97a9ea        docksal/web:2.1-apache2.4   "httpd-foreground"       2 minutes ago       Up 2 minutes               80/tcp, 443/tcp                                          docksal-d8_web_1
633d194f31a6        docksal/cli:2.5-php7.1      "/opt/startup.sh sup…"   2 minutes ago       Up 2 minutes (healthy)     22/tcp, 3000/tcp, 9000/tcp                               docksal-d8_cli_1
8a8915d1f706        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   2 minutes ago       Up 2 minutes               0.0.0.0:32769->3306/tcp                                  docksal-d8_db_1
d36a2aadaf4a        docksal/ssh-agent:1.2       "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes (healthy)                                                              docksal-ssh-agent
d37d1be949ee        docksal/dns:1.1             "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes (healthy)     192.168.64.100:53->53/udp                                docksal-dns
9c39ca012a97        docksal/vhost-proxy:1.4     "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes (healthy)     192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
0a3379f3d4b8        hello-world                 "/hello"                 2 days ago          Exited (0) 2 days ago                                                               quirky_swanson
c7a9118e3992        docksal/web:2.1-apache2.4   "httpd-foreground"       3 days ago          Exited (255) 3 days ago    80/tcp, 443/tcp                                          docksal-d7_web_1
0d60b6fdcaea        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   3 days ago          Exited (255) 3 days ago    0.0.0.0:32773->3306/tcp                                  docksal-d7_db_1
f1b80f11316e        docksal/cli:2.5-php7.1      "/opt/startup.sh sup…"   3 days ago          Exited (255) 3 days ago    22/tcp, 3000/tcp, 9000/tcp                               docksal-d7_cli_1
979b37df527a        docksal/web:2.1-apache2.4   "httpd-foreground"       3 days ago          Exited (255) 2 days ago    80/tcp, 443/tcp                                          drupal7_web_1
4a4ce0d9913d        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   3 days ago          Exited (255) 2 days ago    0.0.0.0:32769->3306/tcp                                  drupal7_db_1
c2ca20b35009        docksal/cli:2.5-php7.1      "/opt/startup.sh sup…"   3 days ago          Exited (255) 2 days ago    22/tcp, 3000/tcp, 9000/tcp                               drupal7_cli_1
3aed3a3b152e        7042885a156a                "nginx -g 'daemon of…"   6 weeks ago         Exited (255) 6 weeks ago   0.0.0.0:80->80/tcp                                       webserver
f9ffc29ad6e1        hello-world                 "/hello"                 6 weeks ago         Exited (0) 6 weeks ago                                                              clever_mestorf
625729f8d0a7        hello-world                 "/hello"                 6 weeks ago         Exited (0) 6 weeks ago                                                              serene_khorana


anisur$ fin docker volume ls
DRIVER              VOLUME NAME
local               docksal-d7_cli_home
local               docksal-d7_db_data
local               docksal-d7_project_root
local               docksal-d8_cli_home
local               docksal-d8_db_data
local               docksal-d8_project_root
local               docksal_projects
local               docksal_ssh_agent
local               drupal7_cli_home
local               drupal7_db_data
local               drupal7_project_root



anisur$ fin docker network ls
NETWORK ID          NAME                 DRIVER              SCOPE
0e9478dbb7a1        _default             bridge              local
19663759bd3f        bridge               bridge              local
ce4f68b6af10        docksal-d7_default   bridge              local
a3e0e197ae9f        docksal-d8_default   bridge              local
0a6bcf3d8afd        drupal7_default      bridge              local
affcceb24d8c        host                 host                local
95ae77006f9b        none                 null                local


Thanks
Anisur

**Comment by lmakarov** [comment]
@anisur-rahman Try this and post the output here:

```
rm -rf /Users/anisur/Sites/docksal-d7
fin cleanup
```

Side note: I fixed the code block formatting in your comment above.
Please use markdown to nicely format code blocks in comments:
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by anisur-rahman** [comment]
Thank you so much, Leonid.

```
$ fin pl -a
project             STATUS                            virtual host                                                   project root
docksal-d8          Exited (255) About a minute ago   docksal-d8.docksal,*.docksal-d8.docksal,docksal-d8.docksal.*   /Users/anisur/Sites/docksal-d8
docksal-d7          Exited (255) 3 days ago           docksal-d7.docksal,*.docksal-d7.docksal,docksal-d7.docksal.*   /Users/anisur/Sites/docksal-d7
drupal7             Exited (255) 3 days ago           drupal7.docksal,*.drupal7.docksal,drupal7.docksal.*            /Users/anisur/Sites/docksal-d7/drupal7


$ rm -rf /Users/anisur/Sites/docksal-d7/drupal7

$ fin cleanup
Checking for orphaned projects...
Directory for project "docksal-d7" does not exist. Removing containers...
c7a9118e3992
0d60b6fdcaea
f1b80f11316e
Directory for project "drupal7" does not exist. Removing containers...
979b37df527a
4a4ce0d9913d
c2ca20b35009
Removing dangling images...
Total reclaimed space: 0B
Removing dangling volumes...
Deleted Volumes:
drupal7_cli_home
drupal7_db_data
docksal-d7_cli_home
docksal-d7_db_data

Total reclaimed space: 871.4MB

$ fin pl -a
project             STATUS                       virtual host                                                   project root
docksal-d8          Exited (255) 2 minutes ago   docksal-d8.docksal,*.docksal-d8.docksal,docksal-d8.docksal.*   /Users/anisur/Sites/docksal-d8
```
