### ISSUE TITLE
Create hooks system

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#606]
Create hooks system for `fin`. 
Placement: `.docksal/hooks/`
Limitations: hooks will ONLY run inside container. `cli` by default. Overridable with `#: exec_target`

Concept: allow hooking to any command.

Hook `.docksal/hooks/post-command` would always run after `fin command`, and hook `post-command-subcommand` would always run after `fin command subcommand`. Only 2 levels are supported.

**Comment by sean-e-dietrich** [comment]
Was thinking of something along the lines of this


```bash
# Execute specific functions if they exist within the hooks directory.
# Examples could be hook_init_pre or hook_db_import.
# Specifically look for hooks to run pre and post actions.
# Checks project and global .docksal/hooks directory for either a single hook file for specific functions
# or checks for individual files that are the hook name.
# $1 - name of the hook to search for
execute_hook ()
{
	local HOOK=$1
	# "Executing Hook: ${HOOK}"

	# Check to see if individual hook file exists.
	local global_hook_individual_file="${CONFIG_DIR}/hooks/${HOOK}"
	if [[ -f "${global_hook_individual_file}" ]] && [[ -x "${global_hook_individual_file}" ]]; then
		# "Executing Global Hook Individual File: ${HOOK}"
		addon_execute "${global_hook_individual_file}"
	fi

	# Check to see if Hooks Exist within the Global Hooks file.
	local global_hook_group_file="${CONFIG_DIR}/hooks/hooks"
	if [[ -f "${global_hook_group_file}" ]] && [[ -x "${global_hook_group_file}" ]]; then
		. ${global_hook_group_file}
		# Check for help function for specific command
		type "hook_${HOOK}" >/dev/null 2>&1
		if [ $? -eq 0 ]; then
			# "Executing Global Hook Function: hook_${HOOK}"
			hook_${HOOK}
		fi
	fi

	# Check to see if individual hook file exists within the project.
	local project_hook_individual_file="${PROJECT_ROOT}/.docksal/hooks/${HOOK}"
	if [[ -f "${project_hook_individual_file}" ]] && [[ -x "${project_hook_individual_file}" ]]; then
		# "Executing Project Hook Individual File: ${HOOK}"
		addon_execute "${project_hook_individual_file}"
	fi

	# Check to see if the global hook file exists within the project.
	local project_hook_group_file="${PROJECT_ROOT}/.docksal/hooks/hooks"
	if [[ -f "${project_hook_group_file}" ]] && [[ -x "${project_hook_group_file}" ]]; then
		. ${project_hook_group_file}
		# Check for help function for specific command
		type "hook_${HOOK}" >/dev/null 2>&1
		if [ $? -eq 0 ]; then
			# "Executing Project Hook Function: hook_${HOOK}"
			hook_${HOOK}
		fi
	fi
}
```

Where before or after a command we would add in `fin`

```bash
execute_hook "db_pre_import"
```

This would then allow for either all hook functions to be in a single file in `$PROJECT_ROOT/.docksal/hooks/hook` or each hook could be it's own file within `$PROJECT_ROOT/.docksal/hooks/hook_[HOOK_NAME]`.

**Comment by achekulaev** [comment]
Hooks are essentially just custom commands that cannot be invoked manually, there is nothing functionally that hooks could do that is not easily achievable with a custom command, and I am arguing that hooks do not bring any value, if they exist next to custom commands. 

The only benefit of hooks I can think of is standardization of a project structure. So it's structural rather than functional. While it's true, there are 2 more items to consider:

1. Standardization helps when it is the only way to do things. When there is more than 1 way to do things it means there is no standard. Benefits of standardization diminish rapidly.
2. Arguably to be consistent hooks should only be able to run inside the project container, however almost every automation I created for a Docksal project had things to be done outside of the container. The most common automation command `init` required to be run outside to start the containers.

Given all the above I do not see any real value hooks would bring and therefore closing this ticket. It is open for discussion. If we collectively can find a reason to implement hooks, it can be reopened.
