### ISSUE TITLE
Create built-in fin init and allow build-in overrides

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#607]
[This is a discussion in progress]
 
Despite it was never documented this way, Docksal messaging to the community and the way we propagate to automate projects might have shaped an expectation, that `fin init` is something default. And users running `fin init` and seeing no results might be puzzled.

It might make sense to create a built-in init command that would do `fin config generate` in case the directory does not have config, and run `fin project reset`.

So this way novice users will have `fin init` to actually do what you would expect something called `init` to do. 

Then they should be able to override it with custom command/addon. For latter to happen we need to allow overriding all built-in commands or maybe just the init one.

**Comment by lmakarov** [comment]
> we need to allow overriding all built-in commands or maybe just the init one

A default overridable `init` is fine and will actually be very helpful for novice users.
I have bad feeling about allowing all built-in commands to be overridden, though.

**Comment by sean-e-dietrich** [comment]
@lmakarov what are the negative impacts you think this could have?

**Comment by lmakarov** [comment]
@sean-e-dietrich Allowing built-in overrides will open up a can of worms in support cases. We no longer will be able to rely on a built-in build what we know it. Even if `fin config` or `fin sysinfo` indicated the overrides are in place, digging into each and all of them to understand the user's issue will be a nightmare.

**Comment by achekulaev** [comment]
Done in develop
