### ISSUE TITLE
Switch to non-persistent network configuration on Linux

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#613]
Non-persistent network configuration was implemented for Alpine Linux in https://github.com/docksal/docksal/pull/542

This approach should be universally applicable to most Linux distributions.
We'll need check implemented to re-apply network settings after restarts networks resets/etc.

**Comment by achekulaev** [comment]
Closed in group of commits ending with https://github.com/docksal/docksal/commit/4f988780b8afacc6a23229a90f2549a45c1a851f

**Comment by frederickjh** [comment]
I want to say that I am not very please with what looks like the decision to drop support for Ubuntu 16.04 before its end of life in April of 2021 by switching to *netplan*. It appears that there is no backport for *netplan* to Ubuntu16.04.

With that in mind is there a way to tell Docksal to only upgrading to a specific version? As it looks like I will need to stop at v1.9.1 for now.

**Comment by lmakarov** [comment]
@frederickjh we did not drop Ubuntu 16.04.

Instead, we removed the code that was tailored for Ubuntu 16.04 only and switched to a network configuration method that is not distro dependent. This in fact opened support for other Linux distros and not only Ubuntu.

**Comment by frederickjh** [comment]
Sorry then @lmakarov. I think read too much into your [comment](https://github.com/docksal/docksal/issues/412#issuecomment-349421999) in the other thread.
