### ISSUE TITLE
Claim support for Debian and Fedora family Linux systems

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#629]
With #613 resolved, we can now claim support a wide range of Linux distributions.

We'll need to have Docksal tested on the following systems:

- [x] Debian
- [x] Ubuntu
- [x] Mint
- [x] Fedora
- [x] CentOS

Automated Docker installation can also be supported on all these systems via the https://get.docker.com/ script.

**Comment by achekulaev** [comment]
Fedora 28

- requires manual sudo configuration (those old school distros!)

[WIP]

**Comment by sean-e-dietrich** [comment]
Checked Centos and seems like every ran ok. 

Oddly when installing docker using the steps and then starting docker it didn't produce a `/var/run/docker.sock` file.

So came across the following which was straight forward to install https://github.com/dpw/selinux-dockersock and I also needed to manually add myself to the `docker` group.

Once I did that ran `fin project create` with out issue
 
![virtualbox_centos_21_06_2018_08_52_57](https://user-images.githubusercontent.com/1564748/41730398-9347753e-7530-11e8-9017-7330bacfc4da.png)

**Comment by achekulaev** [comment]
No, CentOS is not ready. It should support automatic installation.

**Comment by sean-e-dietrich** [comment]
I didn't test the automatic installation piece. How do I go about testing that @achekulaev

**Comment by sean-e-dietrich** [comment]
@lmakarov @achekulaev ran docker install script on Centos 7 then needed to add user to docker group and then run `newgrp docker` for the change to take effect. But then ran docksal install with the develop branch and ran just it had previously if I installed manually.

**Comment by achekulaev** [comment]
CentOS

- added CentOS to `is_fedora` function
- got CentOS image from https://www.osboxes.org/centos-7-image-virtualbox-vmware-available-x86_64/ to avoid manual setup of network, which is not available in minimal setup, and also it has UI which is convenient
- only hit [yum lock by another process issue](https://www.linuxquestions.org/questions/fedora-35/another-app-is-currently-holding-the-yum-lock-603251/) during setup, which is not related to Docksal

<img width="1392" alt="centos 2018-06-21 12-36-58" src="https://user-images.githubusercontent.com/402007/41732728-d59ff22a-754f-11e8-8abf-4bf4a9ef1fb7.png">

https://github.com/docksal/docksal/pull/634

**Comment by lmakarov** [comment]
@achekulaev thanks for testing and making debian and fedora/centos work!

Now we just need docs updated to reflect all of the above :)
