### ISSUE TITLE
git dependency in fin project create

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#635]
`fin project create` has a dependency on git, which may not be installed (WAT!?!).

We should either:

- have a check and a warning instructing user to install git
- drop git as a dependency and use curl/wget instead to pull the project archive from github (though, option this will require `unzip` to be present as well)

**Comment by sean-e-dietrich** [comment]
@lmakarov I believe you can get tarball of the repos. And I believe tar is a standard installation on most machines.

**Comment by sean-e-dietrich** [comment]
Example would be:

```
curl -L https://api.github.com/repos/docksal/docksal/tarball | tar xz
```

**Comment by sean-e-dietrich** [comment]
We would have to change to something like:

```
mkdir project
cd project
curl -L https://api.github.com/repos/docksal/drupal-8/tarball | tar xz --strip=1
fin init
```

**Comment by lmakarov** [comment]
@sean-e-dietrich tarball would mean a lot more download traffic. Though, I like that this option is a 0 extra dependency one.

Since both options I suggested involve installing an extra package (`git` vs `unzip`), it will make sense to just go with option 1. Git is a must for most of web dev use cases and environments anyway.

**Comment by sean-e-dietrich** [comment]
@lmakarov is this a good example where maybe `fin run-cli` may be a good candidate? I believe we have git in the `cli` container

**Comment by lmakarov** [comment]
@sean-e-dietrich 

> is this a good example where maybe fin run-cli may be a good candidate?

Hmm, that may actually be a great idea. It eliminates any possible host dependencies, but will require refactoring `fin project create` to have it somehow run inside cli. We could also just make it part of `cli`, but I'm not sure if that is a good/bad idea. Needs more thought.

Now that I thinking about it, what's preventing is from running anything via a docker container?
No `curl` on the host? Well, there can be a lightweight Alpine based container just for that :D

**Comment by sean-e-dietrich** [comment]
@lmakarov I'm sure you saw this but there is an Alpine Version with GIT installed in already https://hub.docker.com/r/alpine/git/

**Comment by lmakarov** [comment]
@sean-e-dietrich Thats not an official repo, just someone registered the `alpine` namespace on Docker Hub. For something so low level we should use either an official image (which they don't have with the git flavor here https://hub.docker.com/_/alpine/) or maintain our own (which is not a big deal).

**Comment by lmakarov** [comment]
@achekulaev ok, looks like I overcomplicated it in my mind.

What do you think about replacing `curl` with a docker container wrapper?

**Comment by achekulaev** [comment]
@lmakarov I guess overhead of launching run-cli is still pretty big for using it to replace all curl calls.

**Comment by sean-e-dietrich** [comment]
@lmakarov @achekulaev I thought I would try taking a crack at this.

I created the following: https://github.com/docksal/service-runner

It's just an Alpine based Image with GIT and Curl installed. Image is about 66.8MB

But believe that this could do the trick for what we are looking for with taking about the git and curl dependencies. I think I need a little help though because whenever I attempt to run any of the commands it runs as root so the files download as root causing issues when I attempt to access them.

How would you suggest getting around this?

**Comment by achekulaev** [comment]
Pass HOST_UID and GID and use them in the image.

1. Passing https://github.com/docksal/docksal/blob/91350911ee40d6fd0dfd14854208138e0bea4044/bin/fin#L4411
2. Using
2.1. Setting ENV in Dockerfile https://github.com/docksal/service-cli/blob/develop/5.6/Dockerfile#L329
2.2. Overriding UID in startup https://github.com/docksal/service-cli/blob/develop/5.6/startup.sh#L16

**Comment by achekulaev** [comment]
I don't think we really need to create an image with curl and git.
curl is required to install fin. Can be replaced with wget if needed, but one of them is still required tp even install.
git is not required to install, but really if you want to develop something nowadays git is a must-have and in the worst case git is not used that often and is not that tiny, so having `fin run-cli git` is not terrible at all.
