### ISSUE TITLE
Green padlock ssl ?

### ISSUE THREAD

**Issue by acteg** [docksal/docksal#647]
**Description :**

I have configured my drupal 8 to generate HTTPS pages with correct links.

All links on my homepage are on https but i don't see green padlock on the adreess bar. on console i don't have error.

**Problem :**

Docksal generate valid certificat foreach domain or i need to generate one et configure it for myself?

**Comment by lmakarov** [comment]
"Green padlocks" for local development will be possible once #498 is implemented.

For custom domains - https://github.com/docksal/service-vhost-proxy/issues/23
