### ISSUE TITLE
fin run-cli nvm does not work.

### ISSUE THREAD

**Issue by ey-** [docksal/docksal#648]
**Description**

Since the update to fin 1.60.2 nvm does not work for the run-cli command. Using the default cli container 2.2-php7.1. 

**Steps to reproduce the issue:**

1. Execute fin run-cli nvm

**Describe the results you received:**

bash: line 0: exec: nvm: not found

**Describe the results you expected:**

help output of nvm.

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

███  OS
Linux Ubuntu 16.04
Linux vku-runner 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Mode: Linux Kernel

███  FIN
fin version: 1.60.2

███  ENVIRONMENT
DOCKER_HOST		|
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER INFO
Containers: 154
 Running: 76
 Paused: 0
 Stopped: 78
Images: 13
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-127-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 15.4GiB
Name: vku-runner
ID: 4ZSF:I2ND:24TU:PZMD:DIW2:JT3T:C5TY:7335:FBB5:DKGY:TR3E:YV3T
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
WARNING: No swap limit support

███  DOCKER: IMAGES
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
docksal/cli            2.2-php7.1          f8397b8a269f        2 weeks ago         867MB
zenika/alpine-chrome   latest              1d6f2e59d68f        4 weeks ago         645MB
redis                  4.0.9-alpine        494c839f5bb5        5 weeks ago         27.8MB
emgag/varnish          6.0                 efc2866573d8        2 months ago        435MB
docksal/db             1.2-mysql-5.7       514af96ffc68        2 months ago        371MB
docksal/cli            2.1-php7.1          4c7331d4cf77        2 months ago        950MB
docksal/cli            2.0-php7.1          9ba7c35bb83f        3 months ago        914MB
docksal/vhost-proxy    1.2                 a1c980537985        3 months ago        166MB
solr                   6.6.2-alpine        eeb952da4378        5 months ago        270MB
docksal/web            2.1-apache2.4       32c1d32eba6d        10 months ago       87.5MB
mailhog/mailhog        latest              669347153085        14 months ago       19.1MB
docksal/dns            1.0                 20c7a535479d        17 months ago       61.6MB
docksal/ssh-agent      1.0                 148220cc033d        17 months ago       12.2MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                  PORTS                                      NAMES
__sanitized__

███  HDD Usage
Filesystem                        Size  Used Avail Use% Mounted on
udev                              7.7G     0  7.7G   0% /dev
tmpfs                             1.6G   78M  1.5G   5% /run
/dev/mapper/ubuntu16041--vg-root   99G   44G   52G  46% /
tmpfs                             7.8G     0  7.8G   0% /dev/shm
tmpfs                             5.0M     0  5.0M   0% /run/lock
tmpfs                             7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/sda1                         472M  154M  294M  35% /boot
tmpfs                             1.6G     0  1.6G   0% /run/user/1001
tmpfs                             1.6G     0  1.6G   0% /run/user/1000

███  RAM Usage
              total        used        free      shared  buff/cache   available
Mem:       16150140     7944324      439016      607424     7766800     7142116
Swap:        786428       56716      729712

███  RAM Usage per container
CONTAINER ID        NAME                                           CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS
__sanitized__

</details>

**Comment by ey-** [comment]
Same for 
fin run-cli --image=docksal/cli:2.0-php7.1 nvm
So it is definitively fin related, because this worked earlier.
If we only type fin run-cli --image=docksal/cli:2.0-php7.1 and then execute nvm seperately, it works.

**Comment by achekulaev** [comment]
Thanks @ey- 
There was a pesky bug indeed.
