### ISSUE TITLE
Error running fin update

### ISSUE THREAD

**Issue by rootical** [docksal/docksal#66]
Hello, having problems updating. Permission mentioned doesn't help. Tried rerunning install script as well.

```
▶ fin update
[!] Using Docksal develop branch
Updating fin... 0.14.0 [OK]
Updating default configs...
services.yml
curl: (23) Failed writing body (0 != 1914)
 ERROR:  One of the default configs was not downloaded.
         Check your internet connection and file permission on /Users/vadzim/.docksal/stacks
```

Works when running with sudo :(

**Comment by lmakarov** [comment]
@rootical `ls -la /Users/vadzim/.docksal/stacks`

If the files are owned by root, then `sudo rm -rf /Users/vadzim/.docksal/stacks` and run `fin update` again.

**Comment by rootical** [comment]
Thanks, that will help on one host I was experimenting the issue.

Not to create another issue, here is one more from another host:
```
fin update self
[!] Using Docksal develop branch
Downloading...
curl: (22) The requested URL returned error: 404 Not Found
(docksal) default.yml download failed.
```

**Comment by achekulaev** [comment]
>  from another host:
There is no `update self` command
