### ISSUE TITLE
Docksal branded boot2docker.iso required

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#662]
Current boot2docker.iso is unable to mount SMB 2.x shares. Which renders Docksal unable to work in Windows + VirtualBox mode on latest Windows 10 without manually enabling legacy SMB 1.0. There is a pull request https://github.com/boot2docker/boot2docker/pull/1307 pending in boot2docker repo, but it does not look like it is going to be merged any time soon.

I guess the only viable option is to have `docksal/boot2docker` and initialize virtualbox vm from our own fork of boot2docker image.

**Comment by lmakarov** [comment]
It's not required as we have the issue with Windows SMB sharing covered in the troubleshooting docs:
https://docs.docksal.io/en/master/troubleshooting-smb/

I'll poke the maintainers in the boot2docker/boot2docker#1307 PR and suggest others interested in better Windows support in boot2docker to upvote that PR.

**Comment by lmakarov** [comment]
https://github.com/boot2docker/boot2docker/pull/1307 was merged!  🎉 
It will be released later this month with docker/boot2docker 18.06.0 releases.
