### ISSUE TITLE
How to expose the DB via a pretty URL 

### ISSUE THREAD

**Issue by mikecrittenden** [docksal/docksal#664]
I'm probably just missing it in the docs but I can't figure out how to expose the database container externally via a nice subdomain, like http://db.myproject.docksal. Is this supported?

**Comment by sean-e-dietrich** [comment]
@mikecrittenden what are you trying to accomplish?

If you wanted the DB container to be accessible by a web address you could add a label to the db container `io.docksal.virtual-host=db.${VIRTUAL_HOST}` but that will only route TCP web requests won't really route anything else.

**Comment by sean-e-dietrich** [comment]
If you are looking to have a web interface to look at your database specifically you can always use the  [PHPMyAdmin](https://docs.docksal.io/en/master/tools/phpmyadmin/) interface.

**Comment by mikecrittenden** [comment]
I want to be able to connect to it from Sequel Pro on the host without having to use the IP address, and have team members do the same.

**Comment by sean-e-dietrich** [comment]
You can actually use the host name `myproject.docksal`. But also try taking a look at the [SequelPro addon](https://github.com/docksal/addons/tree/master/sequelpro) which simplifies this and allows a person to type `fin sequelpro` within the project and have it open up for them without having to fumble through and find the port that mysql is operating on.

**Comment by mikecrittenden** [comment]
Oh! Amazing! Thank you.

**Comment by shelane** [comment]
I recommend installing the sequelpro addon if Sequel Pro is your preferred db:
`fin addon install sequelpro`
adminer and phpmyadmin are also available as addons.
https://github.com/docksal/addons

If you want to manually configure, [this is what you do](http://docksal.readthedocs.io/en/master/advanced/db-access/).

**Comment by shelane** [comment]
@sean-e-dietrich You beat me to it!
