### ISSUE TITLE
Change overrides-osxfs.yml to using named volume

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#678]
Is it a mistake that it still uses direct mapping via `$PROJECT_ROOT` variable?

```bash
§ cat ~/.docksal/stacks/overrides-osxfs.yml 
# Enabled osxfs:cached mode
# This adjustment makes no difference on non Docker for Mac setups

version: "2.1"

services:
  cli:
    volumes:
      - ${PROJECT_ROOT}:/var/www:rw,cached
```

**Comment by lmakarov** [comment]
@achekulaev see 87b4a10b5089ef3d615c226347b4ecd89585dbb7 - https://github.com/docker/for-mac/issues/1899 is still open.

**Comment by lmakarov** [comment]
Reopening due to #778

**Comment by achekulaev** [comment]
Is it pending for fix in the docker for mac?

**Comment by lmakarov** [comment]
Yes, I posted the details upstream on Aug 16, 2018:
https://github.com/docker/for-mac/issues/1899#issuecomment-413611001

**Comment by lmakarov** [comment]
The upstream issue got closed for inactivity. The problem with `cached` property on named volumes is still valid today, with docker 19.03.04.

**Comment by achekulaev** [comment]
@lmakarov I have created an issue in docker-compose queue since I believe it is a Compose issue

https://github.com/docker/compose/issues/7021

**Comment by lmakarov** [comment]
@achekulaev ok, thanks.

I'm changing all places where we mount the `project_root` volume to include `cached` and avoid mixing cached and non-cached modes on this volume.

**Comment by achekulaev** [comment]
@lmakarov we would also need documentation to state, that `project_root` should always be mounted cached.
