### ISSUE TITLE
Make "fin db import" automatically decompress archived DB dumps

### ISSUE THREAD

**Issue by mikecrittenden** [docksal/docksal#683]
It would be nice if instead of doing this:

```
zcat < dump.sql.gz | fin db import
```

You could instead just do:

```
fin db import dump.sql.gz
``` 

And it would automatically decompress it for you. Thoughts?

As an aside, Drush supports this natively using the `--file` option here: https://drushcommands.com/drush-7x/sql/sql-query/

```
drush sqlq --file=dump.sql.gz
```

**Comment by mikecrittenden** [comment]
Cool, that's fair enough! Just was a random thought I had.

**Comment by mark-casias** [comment]
I created a custom command for this issue. I haven't tested it on paths outside of ./ but I imagine it would be fine.. 

```
#!/usr/bin/env bash

# Import a zipped file
#
# use: fin db-zip $zipped-file-path

zcat < ${1} | fin db import
```
