### ISSUE TITLE
Add documentation for auto-starting stopped projects, and for auto-stopping inactive projects

### ISSUE THREAD

**Issue by mikecrittenden** [docksal/docksal#685]
I found this: https://blog.docksal.io/docksal-will-auto-start-your-existing-projects-1aa53676163c

This is an absolutely KILLER feature for people with lots of projects, but I don't see this feature anywhere in the docs. Am I missing it?

I also found https://blog.docksal.io/docker-reverse-proxy-with-http-2-letsencrypt-and-on-demand-container-start-support-48b275f7d491 which says:

> Inactive project instances (containers) are stopped after a certain period, but can be woken back up simply by visiting the environment’s URL.

So I was wondering what that period is after which they are auto-stopped. That post led me to https://github.com/docksal/service-vhost-proxy which says that `PROJECT_INACTIVITY_TIMEOUT` is inactive by default, which makes me think that by default this doesn't actually happen. Is this true? If so, how can I enable it globally for all projects (for say, a timeout of 7 days)?

Note that I did find http://docksal.readthedocs.io/en/master/advanced/stack-config/#project_inactivity_timeout afterwards, by manually searching the docs for `PROJECT_INACTIVITY_TIMEOUT`.

**Comment by achekulaev** [comment]
A very valid note @mikecrittenden , thanks! It needs documentation indeed.

Yes it is disabled by default on your local. 
You can enable it globally to 7 days by setting `PROJECT_INACTIVITY_TIMEOUT=168h` in `$HOME/.docksal/docksal.env` and run `fin system reset`.

**Comment by lmakarov** [comment]
@mikecrittenden this (hidden) feature is mostly used with Docksal Sandboxes - CI/CD environments (pending documentation and an official announcement).

You can set global variables like this as well:

```
fin config set --global PROJECT_INACTIVITY_TIMEOUT="0.5h"
fin system reset
```

**Comment by mikecrittenden** [comment]
Oh man, this is just a fantastic feature. I just set it to 24h and a couple minutes later my inactive-since-2-days-ago project was stopped. Then loading it in a browser started it back up. Works like a champ, just needs some docs!
