### ISSUE TITLE
Info: Internet connection loss after creation of 16th network/bridge

### ISSUE THREAD

**Issue by Nebel54** [docksal/docksal#700]
**Description**
I had issues on my workstation with the internet connection. The connection worked for a few seconds after logging in, but got unstable/unusable after a few seconds. After that it was not even possible for me to open the router admin UI on the local network. 

The problem seemed to be related to my router, because when I accessed the internet using the hotspot function of my mobile phone i had no problems.

After lots of debugging i saw that i had 16 network bridges up from my docksal projects. After deleting unused networks with `docker network prune` I was able to use the internet again normally.

So this is just a heads-up so you are informed in case your colleagues suddenly face connectivity problems. As this may also be a hardware problem, here are my specs: Notebook: HP EliteBook 840 / Router: UPC Ubee EVW 3226

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>
WARNING: No swap limit support
███  OS
Linux Ubuntu 16.04
Linux hedwig 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Mode: Linux Kernel

███  FIN
fin version: 1.60.2

███  ENVIRONMENT
DOCKER_HOST		| 
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER INFO
Containers: 60
 Running: 6
 Paused: 0
 Stopped: 54
Images: 27
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-45-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.1GiB
Name: hedwig
ID: UXPJ:7B5O:OEUP:VIJE:3PNJ:2IAL:4FH5:OSG2:OUTL:7ZLU:CJXJ:SCOT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
WARNING: No swap limit support

</details>

**Comment by achekulaev** [comment]
Thanks for info!
