### ISSUE TITLE
Move to using Compose file version 2.4

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#701]
Update: Since docker-compose 3.x does not support `extends` (which we widely use today in our docker-compose yamls), we should move to the latest 2.x version - v2.4 at the moment.

---

Considerations, pros and cons of moving to using Compose file version 3. One of the reasons is that it would allow using `docker stack` instead of `docker-compose`, thus removing a dependency.

**Comment by sean-e-dietrich** [comment]
I don't have knowledge of `docker stack` other then what is outlined on the documentation. But, if it removes yet another dependency I'm for it.

Do we lose functionality that we currently have by upgrading?

**Comment by lmakarov** [comment]
We may want to consider moving to 2.4 (brought up in #895) before even thinking about the 3.x jump.

With the exception of hardcoded `version` values in all existing project yamls, the 2.1 => 2.4 upgrade should be pretty straightforward. The 3.x upgrade won't be that easy or even doable for the time being.

Let's brainstorm ideas here around handling the 2.4 upgrade in a way that minimizes a breaking change burned on our users. This same approach can be then applied later on with the 3.x shift.

**Comment by achekulaev** [comment]
Oh!... I did not check that... Well the yeah we should update to the latest 2.x
