### ISSUE TITLE
Global auto-confirm flag

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#707]
Quote from https://github.com/docksal/docksal/pull/706#discussion_r202482908

> I think we should add a global `-y` flag to skip confirmations in `_confirm`.
> Travis is not the only CI system that's using/faking interactive sessions and others may run into the need to skip confirmations.
> Alternatively, commands can be run in a sub-shell in Travis to force a non-interactive environment, e.g. `run (fin init)` (I have not tested this, though).

**Comment by lmakarov** [comment]
@achekulaev ping
