### ISSUE TITLE
Add g++ to CLI container by default, for node-sass

### ISSUE THREAD

**Issue by mikecrittenden** [docksal/docksal#713]
Since node-sass uses libsass which needs g++, it seems logical to include g++ by default in the cli container for anyone who wants to use node-sass.

Until now, I've been apt-get installing `build-essential` which contains g++ to work around this.

**Comment by achekulaev** [comment]
@mikecrittenden not sure I follow.

Using `2.2-php7.1`

```bash
14:33:01 ~/Projects/test
§ fin config | grep image
    image: docksal/cli:2.2-php7.1
    ...
```

Install `node-sass`

```bash
14:32:02 ~/Projects/test
§ fin bash
docker@cli:/var/www$ npm install node-sass

> node-sass@4.9.2 install /var/www/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.2/linux-x64-57_binding.node
Download complete .] - :
Binary saved to /var/www/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /home/docker/.npm/node-sass/4.9.2/linux-x64-57_binding.node

> node-sass@4.9.2 postinstall /var/www/node_modules/node-sass
> node scripts/build.js

Binary found at /var/www/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
npm WARN saveError ENOENT: no such file or directory, open '/var/www/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/var/www/package.json'
npm WARN www No description
npm WARN www No repository field.
npm WARN www No README data
npm WARN www No license field.

+ node-sass@4.9.2
added 199 packages from 134 contributors and audited 531 packages in 16.165s
found 4 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

Use node sass

```nodejs
14:33:07 ~/Projects/test
§ fin exec node
> var sass = require('node-sass');
undefined
> sass.render
[Function]
> 
(To exit, press ^C again or type .exit)
> 

```

**Comment by mikecrittenden** [comment]
@achekulaev Try `npm rebuild node-sass --force` and you should see the error. 

I'm not an expert here, but I believe that certain (more recent) versions of node-sass contain pre-built binaries for certain OS'es, which is what you saw. I think that you run into issues if you need an older version, or if you need to rebuild it for whatever reason, or if some tool you're using forces a rebuild, then you need g++ to make it happen.

**Comment by achekulaev** [comment]
I have been building sass with gulp for quite some time and I am not sure that I have ever had to install g++ to use node-sass. And I guess that if you need to re-compile a module it is ok that you need to install `build-essentials`.

**Comment by mikecrittenden** [comment]
Cool - fair enough. Next time I run into a project that needs me to rebuild node-sass then I'll try and figure out exactly why, and see if it might be something that others would hit. 

Closing this issue. Thanks!

**Comment by achekulaev** [comment]
Thanks @mikecrittenden ! If you stumble upon a scenario when a regular web-developer would need g++ please feel free to comment and we might revision the decision here.

**Comment by mike-potter** [comment]
I know this is closed, but I'd like to chime in and request build-essentials also.  There are several cases where npm needs to rebuild stuff if you don't have the right versions.  I ran into this with node-sass that a project was using (because of gulp-sass 3.x).  Also useful when you upgrade node and new packages haven't been published yet.  I'm not sure this qualifies for "regular web-developer" but I know I have some junior devs who would be lost if npm-install didn't just work on our projects.  Means that I'd likely be distributing my own docksal.yml that extends the cli.

**Comment by lmakarov** [comment]
There is always a balance between image size and convenience. We work hard on keeping our images lean and optimized. Since there have been several requests for `g++`/`build-essentials` and some valid daily use cases for them, we are going to include them in `cli` by default.

**Comment by lmakarov** [comment]
One concern, though. There may be cases when extra libraries will be necessary to build something and you would still need to `apt-get` some mysterious package to be able to compile stuff.

**Comment by lmakarov** [comment]
Well, looks like the build packages are now considered persistent / runtime deps upstream, so we should just stop installing/dropping them :)

https://github.com/docker-library/php/blob/b599d7375c12ff69e4d11ea10c3dea56dd670eb9/7.1/stretch/fpm/Dockerfile#L18-L37
