### ISSUE TITLE
Resizing VM HDD

### ISSUE THREAD

**Issue by sean-e-dietrich** [docksal/docksal#718]
Bringing this back up https://github.com/docksal/docksal/issues/128

Command around resizing the Docksal VM HDD

**Comment by achekulaev** [comment]
@sean-e-dietrich description requires justification around why it was brought up. Did you discover a way to do it?

**Comment by sean-e-dietrich** [comment]
I was creating the issue for now but am following these steps https://www.jeffgeerling.com/blogs/jeff-geerling/resizing-virtualbox-disk-image to confirm that we only need to do step 1

**Comment by sean-e-dietrich** [comment]
and have roughly 10+ projects right now in active dev and need more storage for different docker images

**Comment by achekulaev** [comment]
I am pretty sure you need both steps. I tried it before :D

**Comment by sean-e-dietrich** [comment]
Closing for now seems like the following issue is related though https://github.com/boot2docker/boot2docker/issues/510

Until we can find a way. I ran out of disk space trying to resize.
