### ISSUE TITLE
bash profile unloading and reseting unexpetedly

### ISSUE THREAD

**Issue by ochenk** [docksal/docksal#723]
**Description**

Changes to the bash profile file (~/.profile) are not persistent between bash sessions, and may not even take when reloaded via scripts.

**Steps to reproduce the issue:**

Use the following commands to replicate the issue:
1. mkdir testing
2. cd testing
3. mkdir .docksal
4. fin up
5. fin bash
6. nano ~/.profile
(Scroll to the bottom of the file and add:)
7. alias="echo yes"
(Save and exit. e.g. ctrl-X -> y)
8. testing
(You should get "bash: testing: command not found" because you haven't reloaded the profile file.)
9. source ~/.profile
10. testing
(This time, you should get "yes", verifying that the changes to .profile were saved and loaded.)
11. exit
12. fin bash
13. testing
(You'll get "bash: testing: command not found" again.)
14. source ~/.profile
15. testing
(You should get "yes" again.)

This indicates that the changes to ~/.profile are saved, but aren't being loaded each time you shell in. 

A similar issue happens when you create a custom fin command. If you basically do the same thing as above in a fin command (add an alias to ~/.profile, reload the profile, and then try to run the alias) it won't take.

One real-world application for this (and where I ran into this) is needing to add a path to $PATH via the profile. It doesn't seem like you can currently do this.

**Comment by achekulaev** [comment]
Fixed in https://github.com/docksal/docksal/commit/a14709f10363be792ab7500f77e526f257d9af5e

cc @lmakarov
