### ISSUE TITLE
use DrupalPractice instead of Drupal with PHPCS

### ISSUE THREAD

**Issue by acteg** [docksal/docksal#724]
**Description**

Sometimes when doing contribution we need to check coding standard with standard paramatre like DrupalPractice 

**Steps to reproduce the issue:**

1. Install new command phpcs ( Thanks for this doc ) https://docs.docksal.io/en/master/tools/phpcs/
2. change --standard=Drupal by --standard=DrupalPractice
3. fin phpcs docroot/modules/my_module ( i have nothing on output but with --standard=Drupal  we have a lot of errors  )

We need to add DrupalPractice to codesniffer, how we can do it correctly ?

**Comment by achekulaev** [comment]
@acteg I am not sure I understand your question. `DrupalPractice` is already pre-installed.

```bash
docker@cli:/var/www$ ls /home/docker/.composer/vendor/drupal/coder/coder_sniffer/
Drupal  DrupalPractice
```

**Comment by sean-e-dietrich** [comment]
@achekulaev he's saying that the PHPCS command that is included only has `Drupal` and not `DrupalPractice` also included in the command therefore it can cause false-positives when running `fin phpcs`
