### ISSUE TITLE
PHP Compatibility check for PHP_CodeSniffer

### ISSUE THREAD

**Issue by ssudhak** [docksal/docksal#726]
Need to add following command to composer json to check add new standard to check the php compactibility.

"require-dev": {
    "phpcompatibility/php-compatibility": "*"
},

currently we have /home/docker/.composer  which has the following content
{
    "require": {
        "drupal/coder": "^8.2",
        "hirak/prestissimo": "^0.3.7"
    }
}
can you guide me how to add new library here.

**Comment by achekulaev** [comment]
@ssudhak edit the file with nano editor that is present inside the cli container, or create the file as you need it, pu somewhere in your project and copy over the `/home/docker/.composer/composer.json`, or install the dependency on the project level and use https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-installed-standard-paths to provide path to your standards.

But it is not a Docksal question, frankly speaking, it's just editing files and using phpcs question.

**Comment by ssudhak** [comment]
@achekulaevI was finding it hard to edit the json file. tried with few other editor commands but nano is something that I missed.

Thanks

**Comment by achekulaev** [comment]
@ssudhak it is debian inside cli, you can always install `vim` if you need. `apt install vim`

**Comment by paulsheldrake** [comment]
If you looking for a quick work around, login to your Docksal machine

```
## Install PHP Compat Sniff
cd ~
git clone git@github.com:PHPCompatibility/PHPCompatibility.git
phpcs --config-set installed_paths /home/docker/.composer/vendor/drupal/coder/coder_sniffer,/home/docker/PHPCompatibility
```

Change to you module/theme folder, still within your VM
`phpcs --standard=PHPCompatibility --ignore="*.features.*,*.pages*.inc" ./`
