### ISSUE TITLE
Please include APCu in the cli service

### ISSUE THREAD

**Issue by dearmond** [docksal/docksal#729]
I'm trying to debug APCu issues, and as far as I can tell APCu is not part of the cli service.

I've been able to install APCu myself by simply running:
```
fin exec 'sudo pecl install apcu'
fin restart
```

It's okay, but it would be nice if it was already installed.

Thanks!

**Comment by shelane** [comment]
That sounds like a great use case for [extending the stock images](https://docs.docksal.io/en/master/advanced/extend-images/).

**Comment by dearmond** [comment]
That's cool. Thanks for pointing me there.

I do wish there was a way to silence the output of the Dockerfile output, though. It's kinda verbose.

For the record, and for anyone else wishing to do the same, this is what I used for `.docksal/services/cli/Dockerfile`:
```
# Use a stock Docksal image as the base
FROM docksal/cli:2.2-php7.1

# Install addtional pecl packages
RUN pecl -q install apcu > /dev/null 2>&1
```

**Comment by achekulaev** [comment]
@dearmond there is no way to silence only successful build output.
Silencing all output is not an option too, because Dockerfile can contain errors and you would want to see those errors.

**Comment by lmakarov** [comment]
Since Acquia and Pantheon (not sure about Platform.sh) have APCu installed, we should add it too by default. Create a feature request in `docksal/service-cli` => https://github.com/docksal/service-cli/issues/75
