### ISSUE TITLE
WSL installation Issue

### ISSUE THREAD

**Issue by justinlevi** [docksal/docksal#730]
**Description**

Can't seem to connect the docksal `fin` command running in WSL to docker. 

**Steps to reproduce the issue:**

1. Get WSL up and running with Ubuntu
2. $ ` export DOCKSAL_VERSION=develop && curl -L https://get.docksal.io | sh`

**Describe the results you received:**

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
This is nc from the netcat-openbsd package. An alternative nc is available
in the netcat-traditional package.
usage: nc [-46bCDdhjklnrStUuvZz] [-I length] [-i interval] [-O length]
          [-P proxy_username] [-p source_port] [-q seconds] [-s source]
          [-T toskeyword] [-V rtable] [-w timeout] [-X proxy_protocol]
          [-x proxy_address[:port]] [destination] [port]
```

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
head: cannot open '/home/justinlevi/.docksal/stacks/services.yml' for reading: No such file or directory
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
 ERROR:  Volumes definition not found in /home/justinlevi/.docksal/stacks/volumes-bind.yml.
         Please check that DOCKSAL_VOLUMES is set properly.
         You may need to run fin update to download volume definitions.```

</details>

<br>

$ `fin update`

<details>
head: cannot open '/home/justinlevi/.docksal/stacks/services.yml' for reading: No such file or directory
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
This is nc from the netcat-openbsd package. An alternative nc is available
in the netcat-traditional package.
usage: nc [-46bCDdhjklnrStUuvZz] [-I length] [-i interval] [-O length]
          [-P proxy_username] [-p source_port] [-q seconds] [-s source]
          [-T toskeyword] [-V rtable] [-w timeout] [-X proxy_protocol]
          [-x proxy_address[:port]] [destination] [port]
 ERROR:  Docker for Windows is not running
         Start Docker for Windows, wait for Docker to start and run update again.
</details>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
fin sysinfo
head: cannot open '/home/justinlevi/.docksal/stacks/services.yml' for reading: No such file or directory
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
███  OS
WSL Ubuntu 16.04
Linux W2UA7502F8C 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE :
███  FIN
fin version: 1.65.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
/usr/local/bin/fin: line 364: : command not found

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
███  DOCKER: DOCKER IS NOT RUNNING

███  HDD Usage
/usr/local/bin/fin: line 5193: wmic: command not found
  ```

</details>

**Comment by achekulaev** [comment]
Thanks for addition. It's pretty weird. For WSL fin should use `0.0.0.0:2375` as hostname to connect to. From the output above I see that fin tried to connect via socket and naturally fails. As soon as I get to my Windows, I'll test the latest fin.

**Comment by jdalbeck** [comment]
I think am having a similar issue.  When I run `fin update` I get
```
nc: service "//127.0.0.1:2375" unknown
ERROR:  Docker for Windows is not running
        Start Docker for Windows, wait for Docker to start and run update again.
```
I traced this down to the following lines:
```
			IFS=':' read nc_host nc_port <<< "$DOCKER_HOST"
			nc -w 1 ${nc_host} ${nc_port}
```
My DOCKER_HOST variable is set to `tcp://localhost:2357`.  This is reading in as "tcp" for nc_host and "//localhost:2375" for nc_port.  Therefore the NC command is resolving to `nc -w 1 tcp //localhost:2357` when it should be something like `nc -w 1 localhost 2357`.  It should discard `tcp://` but I'm not sure how many other formats for DOCKER_HOST there could be?

**Comment by achekulaev** [comment]
@jdalbeck your issue is a bit different. 
`fin` does not account for user-set `DOCKER_HOST` that contains `tcp://`, while it is a bug it's not critical, since you can easily overcome it by setting `DOCKER_HOST` to just be `localhost:2357`, since `tcp://` is optional.

**Comment by achekulaev** [comment]
Please try new WSL installation. If issues persist please open new ticket. This one is ancient. A lot has changed since then.
