### ISSUE TITLE
Switching cli container image does not update npm/node

### ISSUE THREAD

**Issue by GMTA** [docksal/docksal#744]
**Description**
Running Docksal v1.60.2. For our projects, we set explicit image tags for the Docksal services so we can expect the same behavior on different machines. However, when upgrading from one image to another, the `node` binary does not seem to be updated.

Example:
1. User 1 has a project up and running with cli image `docksal/cli:2.2-php7.1`
2. User 2 updates the cli image in `docksal.yml` to `docksal/cli:2.3-php7.1`
3. User 1 pulls the latest changes and runs `fin up`
4. Because `/home/docker` is a persistent volume, and `node` exists within that volume, the binary is not updated. Other binaries outside of that folder are updated correctly.

**Suggested fix**
Docker images are powerful because they set a consistent environment for available binaries and configuration. Because node/npm are provided in Docksal's images, they should be part of the image and not a persistent volume. Moving the binaries out of `/home/docker` and into `/usr/local/bin` could be a possible fix.

**Comment by achekulaev** [comment]
@GMTA you should perform `fin reset cli` after switching the image. @lmakarov can elaborate more, but moving node out of home is somewhat problematic.

**Comment by GMTA** [comment]
@achekulaev Thanks, running a `fin reset` indeed helps since that thrashes the persistent volume for `/home/docker`. It would be nice if Docksal provided some sort of hint when that needs to happen but for now, it's a workaround.

Not sure why `node` needs to go into `/home/docker` but couldn't it then be a symlink to somewhere else in the filesystem?

**Comment by lmakarov** [comment]
There are multiple reasons why `/home/docker` is a volume and why `nvm` is installed there:

- `nvm` is a user level tool and is expected to be installed in $HOME. It may be possible to install it globally with some hacks, but that's not the way it was intended to be done.
- `overlay2`, the fs driver used by default for container fs and image layers, is very slow for writes. Any write heavy operations are better happening in a volume (which bind mounts the host's fs instead).
- User level changes are better stored in a volume to avoid losing them when ANY piece of the container configuration defined via docker compose changes. Imagine having a custom node version installed via nvm outside of the `/home/docker` volume, then changing an environment variable on the `cli` service. This will trigger `cli` recreation and drop your previously installed node version.

As @achekulaev mentioned, there is no easy way to know when the `cli` service should be hard reset vs just recreated/updated. For now, I pushed an update to the docs regarding switching PHP versions, mentioning `fin project reset cli` should be used. Besides the docs in https://github.com/docksal/service-cli#nodejs, we do not have a dedicated section on docs.docksal.io on NodeJS use cases. We should probably add one and cover these intricacies.

If not for `nvm`, we would just have a globally installed node and not have these complications. I considered having a mix with a globally installed node + nvm, but then I did not find a good way to control which specific node version is installed globally (and not just 8.x). It was easier to have it installed and loaded via `nvm`.

**Comment by GMTA** [comment]
@achekulaev @lmakarov Thanks! I figure that if we want `docksal/cli` to be more predictable, we should force the node version through a setup script.

> I agree. Do you have any ideas could we do it in a cheap way?

Not really, taking into account @lmakarov's comments. There are too many factors that might result in issues with those binaries. Setting the right version through a project's setup script might be the best approach here.

**Comment by achekulaev** [comment]
@GMTA performing `reset cli` during project init will predictably deliver the same version.

**Comment by achekulaev** [comment]
Related issue #798
