### ISSUE TITLE
Increase VirtualBox disk size

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#747]
The 50GB disk size we set by default may run out pretty quickly when working with multiple projects and image versions. Resizing the disk is a total PIA. Instead, we may be able to set the disk size high enough upfront (e.g. 200GB). Since the disk is dynamic, all this space will not be preallocated on the host.

**Comment by lmakarov** [comment]
An attempt was made to set a 1TB disk size (e178bf3), which worked fine on Mac, but totally failed in a Windows VM (VMWare). Apparently, VirtualBox has some issue with creating large dynamic virtual disks, so that has been rolled back.

See https://github.com/docker/machine/issues/2788

Time to create a VM with a 20GB drive - 3.5min:

```
$ time fin dm create --virtualbox-disk-size=20000 test20
...
3:22.83 total
```

Time to create a VM with a 200GB drive - 16min:

```
$ time fin dm create --virtualbox-disk-size=200000 test200
...
15:56.57 total
```

Space occupied on the host system:

![image](https://user-images.githubusercontent.com/1205005/43494357-4b94ce68-94e7-11e8-9784-c00439cb4f99.png)

**Comment by lmakarov** [comment]
Creating a 200GB disk with VirtualBox (during a manual VM setup) happens immediately.
Looks like `docker-machine` creates the virtual disk on the fly from a tar archive (?) streamed via stdin to `VBoxManage convertfromraw stdin`

https://github.com/docker/machine/blob/19035310d4ba1b58056aae427ea669d1db5fc618/drivers/virtualbox/disk.go#L42-L49

That is where the slowdown happens.

**Comment by achekulaev** [comment]
I don't know if we can really do something about it. Maybe we could ask a user about the desired size of the VM warning about this bug and time they would need to wait.

**Comment by lmakarov** [comment]
I'd say this is not a burning issue, so let's close it for now.
