### ISSUE TITLE
Docksal Hosting Integration project... what do you think?

### ISSUE THREAD

**Issue by croane** [docksal/docksal#756]
Hi!

In a few past issues I linked to several repos that we created that provide some direct integration with Platform.sh using D7 + D8. After creating another repo for Pantheon using WP, and realizing how difficult it was to manage a repo for each use case, I refactored the code to use one repo for everything and made it modular so new hosting providers and cms systems could easily be added to the core code. I also made it a composer project that moves the files to the `.docksal` directory and automates some things that required manual work before (like command file permissions).

This basically becomes almost like one of the "boilerplate" projects you have, with the exception that this is a separate repo managed by composer.

https://bitbucket.org/thebrickfactory/docksal-hosting-integration/src/master/

Most of the code in this repo is dealing with custom commands. This stuff might be too specific to include any of it in the core docksal code, but I figured I would let you know about it. So far I have tested this code with the following combinations on 7 different client sites we are working on:

- Drupal 8 on Platform.sh
- Drupal 7 on Platform.sh
- WP on Pantheon
- Other (just imports the db and user files from compressed files)

The flow with using a project that has the config + files from this repo is simple. This imports the db + user files, gets the frontend tools installed on the CLI container, and everything else. The local site will work 100% after this point:

- fin p start
- fin data

I'll be curious if you have any thoughts on this code or how I am handling this. I want to make sure that you are comfortable with what I am doing here. If you find it useful, and think others might want to use it, it might be something to link to from the official documentation. :)

**Comment by lmakarov** [comment]
Wow, very nice! 👍 Thanks for sharing :)
It's a lot of information in one shot and will take some time to absorb.

We would definitely want to have better/deeper integrations available with major hosting providers in the space. So your work looks very interesting and promising.

One discussion point I can think of right away is using Composer vs the [docksal/addons](https://github.com/docksal/addons) repo.

**Comment by lmakarov** [comment]
Closing as outdated.
See https://docs.docksal.io/fin/fin-pull/ for hosting provider integrations in Docksal.
