### ISSUE TITLE
Add fin config shortcuts as command subsets

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#758]
We should add user-friendly shortcuts for common variables plus maybe some additional logic.
e.g.
- `fin config xdebug enable`/`fin config xdebug disable` would set variable and restart cli
- `fin config native enable`/`fin config native disable` would do required things to enable/disable native

@lmakarov @sean-e-dietrich please add more examples you can think of.

**Comment by shelane** [comment]
Is it very common to switch back and forth on native mode?

**Comment by achekulaev** [comment]
For us, maintainers, it is. Also I wanted to give an example of things this functionality would do as compared to regular `fin config set/rm`.

If you can think of other config related operations that users often do don't hesitate to add proposal here for a shortcut/shorthand.

**Comment by shelane** [comment]
Yes, I can see how that would be useful for you. My need would be for a unison rebuild. I’m still having that issue where inotify stops working and updates don’t get made to the container, so I have to remove and restart it. I have custom command in my projects for that.

**Comment by lmakarov** [comment]
Not sure this brings a lot of value. Typing savings are minimal.

```
fin config xdebug enable
fin config set XDEBUG_ENABLED=1
```

```
fin config native enable
fin config set --global DOCKER_NATIVE=1
```

It would also mix project level and global variables and , thus, may result in confusion among users - one can be run anywhere, but the other one only within a project. Now you'd need to know which one should be run where.

**Comment by achekulaev** [comment]
Closing since there's not enough good usecases
