### ISSUE TITLE
Support request: automatically accepting SSH host keys

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#761]
During our `fin init` process, we use database syncing, and for a new container this will force the classic prompt "do you want to accept this RSA fingerprint... (yes/no)"? You have to manually enter yes to continue the init process.

I looked up how to automatically accept these so as to not block the init script, and came across this post https://askubuntu.com/questions/123072/ssh-automatically-accept-keys. I guess this can be done by setting `StrictHostKeyChecking no` in the SSH config for the host, but I'm wondering if there is a way to make this a global change, and if so how would you do this with Docksal?

Looking for the expert opinion of the Docksal gods⚡.

**Comment by sean-e-dietrich** [comment]
@lpeabody depending on where this is executing you could add the following into your `ssh_config`

```
Host *
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
        LogLevel ERROR
```

This will remove strict host checking. That being said if this is apart of your `init` script and the `init` script is executing in the `cli` container then you could either script so that get's appended to the `~/.ssh/ssh_config` file OR you could add the `ssh_config` file to your project in something like `.docksal/etc/ssh/ssh_config` and then in `docksal.yml` have it will mount so that file is added to the user's `~/.ssh/ssh_config`.

**Comment by lmakarov** [comment]
> During our fin init process, we use database syncing, and for a new container this will force the classic prompt "do you want to accept this RSA fingerprint... (yes/no)"? You have to manually enter yes to continue the init process.

@lpeabody can you please elaborate on what exactly your init script is doing?
`cli` already has host key checking disabled - https://github.com/docksal/service-cli/blob/develop/7.1/config/.ssh/config
Anything you run inside `cli` won't complain about changing host keys.

**Comment by lpeabody** [comment]
It is specifically a BLT sync operation:

```
> drupal:sync:db
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/vendor/bin/drush cache-clear drush --uri=bax_commercial --no-interaction --ansi &&
 /var/www/vendor/bin/drush sql-drop --uri=bax_commercial --no-interaction --ansi &&
 /var/www/vendor/bin/drush sql-sync @baxter.commercialus @local.com --target-dump=/tmp/tmp.target.sql.gz --structure-tables-key=lightweight --create-db --uri=bax_commercial --no-interaction --ansi &&
 /var/www/vendor/bin/drush sql-sanitize --uri=bax_commercial --no-interaction --ansi &&
 /var/www/vendor/bin/drush cr --uri=bax_commercial --no-interaction --ansi &&
 /var/www/vendor/bin/drush sqlq "TRUNCATE cache_entity" --uri=bax_commercial --no-interaction --ansi in /var/www/docroot
```

**Comment by lmakarov** [comment]
@lpeabody can you confirm `drupal:sync:db` is run inside `cli` and not on the host? Do you have `#: exec_target = cli` header in the script (which tells fin to run the custom command inside `cli`).

**Comment by lpeabody** [comment]
The command executed within the init script is `fin exec blt setup`.

**Comment by lmakarov** [comment]
So `cli` it is then. 

> The authenticity of host 'scrubbed' can't be established.
What is this host? I wonder if BLT/drush set their own SSH configuration, which overrides the default one we have in `cli` and does not have `StrictHostKeyChecking no`.

**Comment by lpeabody** [comment]
If you're referring to the URL it's an Acquia web head. Do you need the full specific URL?

**Comment by achekulaev** [comment]
What if you run the command manually in `fin bash`?

```
drush sql-sync @baxter.commercialus @local.com --target-dump=/tmp/tmp.target.sql.gz --structure-tables-key=lightweight --create-db --uri=bax_commercial --no-interaction --ansi
```

**Comment by lpeabody** [comment]
@achekulaev I get the following:

```
[les.peabody@~/Sites/corvette (feature/contributors-cleanup)]
-> fin bash
docker@cli:/var/www$ /var/www/vendor/bin/drush sql-sync @baxter.commercialus @local.com --target-dump=/tmp/tmp.target.sql.gz --structure-tables-key=lightweight --create-db --uri=bax_commercial --no-interaction --ansi
The authenticity of host 'web-1030.enterprise-g1.hosting.acquia.com (52.64.150.244)' can't be established.
RSA key fingerprint is SHA256:MP7McC/lxcUweoXM0RJNdIg6M3RFvUe5FBB9WJ95joM.
Are you sure you want to continue connecting (yes/no)? ^C
docker@cli:/var/www$
```

**Comment by lpeabody** [comment]
Also, if I run `ssh user@acquiahost`, the same user and acquiahost used in the command, I get logged in no problem. However, if I run `drush @sitealias ssh` then I get:

```
docker@cli:/var/www$ drush @baxter.commercialus ssh
The authenticity of host 'web-1030.enterprise-g1.hosting.acquia.com (52.64.150.244)' can't be established.
RSA key fingerprint is SHA256:MP7McC/lxcUweoXM0RJNdIg6M3RFvUe5FBB9WJ95joM.
Are you sure you want to continue connecting (yes/no)? ^C
```

**Comment by lpeabody** [comment]
So:

1) Drush (appropriately) makes it possible to set SSH options.
2) Our codebase is definitely doing that.
3) I fixed it.

Drush alias files can have SSH options specified, and all of our aliases had the following:

```
ssh:
  options: '-F /dev/null'
```

I updated it to say:

```
ssh:
  options: '-F /dev/null -o StrictHostKeyChecking=no'
```

I think the choice to be decided from a Docksal perspective is, if you want to point this out in your SSH documentation somewhere? This mostly comes from a lack of knowledge about this Drush feature, rather than not understanding Docksal since you've already thought about this. If you didn't include this in your documentation, I would totally understand that. Up to you!

**Comment by lmakarov** [comment]
@lpeabody from http://linuxcommand.org/lc3_man_pages/ssh1.html

     -F configfile
             Specifies an alternative per-user configuration file.  If a con‐
             figuration file is given on the command line, the system-wide
             configuration file (/etc/ssh/ssh_config) will be ignored.  The
             default for the per-user configuration file is ~/.ssh/config.

So yes, was not Docksal or Drush, it was rather the config you had in your drush aliases :)
Try removing `options: '-F /dev/null'` and it should also work.

**Comment by lpeabody** [comment]
Interesting! This was a legacy alias file that we inherited and I never gave it a second thought since it works mostly fine. Love learning something new. I'm gonna reach out to the original author and ask why -F /dev/null was added in the first place. For now, I've yanked it out and it works swimmingly. Thank you kindly.
