### ISSUE TITLE
Virtual hosts comply with browser standards in a multi-site multi-domain setup

### ISSUE THREAD

**Issue by maikel-finck** [docksal/docksal#762]
**Description**

There isn't a cooked solution at the docs on how to use a multi-site multi-domain environment with a single code base. A quick workaround was to declare the domains in the virtual_host variable. This may not be an "used as intended" scenario but is one that works with ACSF.

After this pull request this is not working anymore, it seems that virtual_host now expect only a single domain, is that correct?
https://github.com/docksal/docksal/pull/653/files/ae1e447ef25de6f29ea0013fe8cb11e3881ef837

**Steps to reproduce the issue:**

1. Create a new environment, extend Acquia stack.
2. Set up VIRTUAL_HOST with multiple domains, comma separated.
Concept example:
VIRTUAL_HOST="site1.domain1,site2.domain1,site2.domain2,siteN.domainN,tool1.tools,tool2.tools"

3. Override your YML service labels and distribute the domains
Concept example:
service: web
io.docksal.virtual-host="site1.domain1,site2.domain1,site2.domain2,siteN.domainN"
service: tool1
io.docksal.virtual-host="tool1.tools"
service: tool1
io.docksal.virtual-host="tool1.tools"

4. Start your environment

**Describe the results you received:**

WARNING:  The VIRTUAL_HOST has been modified from
site1.domain1,site2.domain1,site2.domain2,siteN.domainN,tool1.tools,tool2.tools
to
site1.domain1site2.domain1site2.domain2siteN.domainNtool1.toolstool2.tools
to comply with browser standards.

**Describe the results you expected:**

The multiple domains would still work as expected before this fix was published.

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
WARNING: No swap limit support
███  OS
Linux Ubuntu 16.04
Linux lnxcit011459 4.8.0-41-generic #44~16.04.1-Ubuntu SMP Fri Mar 3 17:11:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel
DOCKER_HOST : 

███  FIN
fin version: 1.67.2

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
WARNING: No swap limit support

███  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
39f0c917a326        docksal/ssh-agent:1.0      "/run.sh ssh-agent"      4 hours ago         Up 2 hours                                                                   docksal-ssh-agent
4da70467c464        docksal/dns:1.0            "/opt/entrypoint.sh …"   4 hours ago         Up 2 hours          192.168.64.100:53->53/udp                                docksal-dns
9e9b009e015e        docksal/vhost-proxy:1.3    "docker-entrypoint.s…"   4 hours ago         Up 2 hours          192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
13d7caadf614        docksal/db:1.2-mysql-5.6   "/entrypoint.sh mysq…"   45 hours ago        Up 2 hours          0.0.0.0:3308->3306/tcp                                   drupal8_db_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
b94d67f5326e        _default            bridge              local
dd569350c5a1        bridge              bridge              local
94b4230ff2a6        cfn_default         bridge              local
9c937ecd6f34        drupal8_default     bridge              local
9cd5d1cf7270        host                host                local
ca1f32eba0ca        none                null                local

███  HDD Usage
Filesystem      Size  Used Avail Use% Mounted on
udev            3,9G     0  3,9G   0% /dev
tmpfs           789M  9,8M  779M   2% /run
/dev/sda1       103G   53G   45G  55% /
tmpfs           3,9G  263M  3,6G   7% /dev/shm
tmpfs           5,0M  4,0K  5,0M   1% /run/lock
tmpfs           3,9G     0  3,9G   0% /sys/fs/cgroup
/dev/loop0       87M   87M     0 100% /snap/core/4917
/dev/loop1      144M  144M     0 100% /snap/slack/7
tmpfs           789M   80K  789M   1% /run/user/543195382
  ```

</details>

**Comment by sean-e-dietrich** [comment]
@maikel-finck it was actually not our intent to make it so multiple hosts names were not support it was more the case where we wanted to make sure those hostnames were compliant and the `,` delimiter was something that just missed

**Comment by lmakarov** [comment]
`VIRTUAL_HOST` is expected to be a single value domain. Wildcard are automatically applied at the container configuration level in yml:

https://github.com/docksal/docksal/blob/d95bcde6f95fdb3ee9592fcfa12cff2a708a26c6/stacks/services.yml#L15

If you need multiple domains/multisite, then override `io.docksal.virtual-host` in `docksal.yml`

This is covered in docs, but may need to be made more clear around the rules fro the `VIRTUAL_HOST` variable:

- [Overriding the default domain name](https://docs.docksal.io/en/master/advanced/multiple-projects/#overriding-the-default-domain-name)
- [Using arbitrary custom domains](https://docs.docksal.io/en/master/advanced/multiple-projects/#overriding-the-default-domain-name)

**Comment by lmakarov** [comment]
Updated docs. @maikel-finck let me know if you still have questions or concerns around this.

**Comment by maikel-finck** [comment]
Yes, I knew that VIRTUAL_HOST was supposed to hold a single domain and tried to enable the additional domains using the virtual-host label as you said. When I first build my environment this wasn't working and that's why I had to use a workaround with the VIRTUAL_HOST.

I just build a new one from scratch to test it and it seems to work fine now. The only issue I noticed is that I must use ".docksal" as the domain suffix or I will get a DNS_PROBE_FINISHED_NXDOMAIN error.

For instance:
docksal.env
```
VIRTUAL_HOST='site1.docksal'
```

docksal.yml
```
web:
  labels:
    - io.docksal.virtual-host=${VIRTUAL_HOST},*.${VIRTUAL_HOST},site2.acsfsites,site2.docksal,site3.acsfsites,sitex.acsfsites

mail:
  labels:
    - io.docksal.virtual-host=webmail.acsftools,webmail.docksal
```

Any domain listed in the virtual-host label ending with .docksal is working, but all the others cause the DNS issue.

**Comment by lmakarov** [comment]
From https://docs.docksal.io/en/master/advanced/multiple-projects/#using-arbitrary-custom-domains

> Please note, that non .docksal domains (e.g., example.com) will not be resolved automatically. You can use fin hosts command to add and manage additional domain names via the system's hosts file. See fin help hosts.

Based on your example above, do:

```
fin hosts add site2.acsfsites
fin hosts add site3.acsfsites
fin hosts add sitex.acsfsites
```

**Comment by maikel-finck** [comment]
Not sure why I missed that, I did take a quick look at the updated docs.

Thanks for the help!
