### ISSUE TITLE
fin hosts add terminate IPv6 Address

### ISSUE THREAD

**Issue by sean-e-dietrich** [docksal/docksal#766]
When running `fin hosts add` it only adds the IPv4 address but sometimes browsers and routers will attempt to connect to the IPv6 address.

Adding the following to the hosts file should fix this.

```
::1 VIRTUAL_HOST.docksal
```

**Comment by lmakarov** [comment]
@sean-e-dietrich `::1 VIRTUAL_HOST.docksal` would be an equivalent of `127.0.0.1 VIRTUAL_HOST.docksal` for IPv4. What is the benefit of doing that? `docksa-vhost-proxy` only listens on `192.168.64.100` anyway (by default).

**Comment by sean-e-dietrich** [comment]
@lmakarov Right, so my routers try to communicate with IPv6 first. If I try to use a vhost for a live domain (example.com) and run `fin hosts add` it adds the IPv4 address but then I need to go in and attempt to add the IPv6 address. The reason I use a live domain sometimes is that the services we use are domain host name based (example google maps). Because there isn't an IPv6 address for the proxy (yet) this was the next solution I could think of.

**Comment by lmakarov** [comment]
So, let's say you have

```
192.168.64.100 maps.google.com
::1 maps.google.com
```

When attempting a connection to maps.google.com, you machine will resolve it to `::1` (IPv6 localhost). The connection will likely not go through. Does it then try to connect on IPv4 address (`192.168.64.100`), which is where your local Docksal environment would respond? Is that how this all happens to work?

**Comment by sean-e-dietrich** [comment]
Correct

**Comment by lmakarov** [comment]
ok, interesting. Found a confirmation and explanation for this:
https://superuser.com/questions/1199129/how-web-browser-determines-when-to-use-ipv4-or-ipv6-to-connect-to-the-destinatio

Now, `::1:80` may still respond if you have some software binding to `localhost:80`.

Using `::2` instead would guarantee the connection will never work and always fall back to the IPv4 resolved address.

**Comment by sean-e-dietrich** [comment]
@lmakarov thanks for the verification and validation i went ahead and modified the PR to change `::1` to `::2`
