### ISSUE TITLE
Ability to Create Custom 500 Server Error Message?

### ISSUE THREAD

**Issue by CourtneyJordan** [docksal/docksal#768]
Is it possible to create custom error message in docksal that will be displayed via webpage? 

While looking on the docksal documentation site page [Configuration Overrides](https://docksal.readthedocs.io/en/master/advanced/web-configuration-overrides/), the page provides options to override default virtual hosts and was curious if there was an option to override page message errors to display a custom message rather than what is provided by default.

**Comment by achekulaev** [comment]
Hi @CourtneyJordan 

There is no out-of-the box feature to easily override those pages. Your best option at the moment would be to extend our stock images with your custom `Dockerfile` as described here https://docs.docksal.io/en/master/advanced/extend-images/

**Comment by lmakarov** [comment]
This can be handled via [Apache/Nginx Advanced Settings](https://docs.docksal.io/service/web/settings/)

**Comment by achekulaev** [comment]
As a follow-up here is docs on doing that https://httpd.apache.org/docs/2.4/custom-error.html
