### ISSUE TITLE
Create a documentation on how to expose Drush aliases to Docksal

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#77]
Create a documentation on how to expose Drush aliases to Docksal

**Comment by david-hernandez** [comment]
I can add a page. What are the quick steps?

**Comment by achekulaev** [comment]
1. in project root directory (where `.docksal` is) create `drush/aliases` directory
2. put your `*.aliases.drushrc.php` there

Now drush will see them for this project.
