### ISSUE TITLE
Failure to pull system image does not result in failure of Docksal installation

### ISSUE THREAD

**Issue by GMTA** [docksal/docksal#772]
**Description**

We use a custom `IMAGE_DNS` for Docksal which is pulled during the regular Docksal installation. We noticed that if docker is unable to pull this image, Docksal still continues as if nothing bad happened and does not give an exit status that indicates that something failed.

**Steps to reproduce the issue:**

1. Set `IMAGE_DNS` to an image on a Docker registry that is unreachable
2. Install Docksal using `curl -fsSL get.docksal.io | bash`

**Describe the results you received:**

The image pull fails and Docksal returns exit status 0.

**Describe the results you expected:**

Docksal installation fails and provides an exit status != 0.

**Comment by GMTA** [comment]
@achekulaev This is the current purpose: https://github.com/docksal/service-dns/issues/2

But quite possibly there will be new purposes in the future :-)

**Comment by achekulaev** [comment]
@GMTA ah. If you have this change done, dO you want to submit a PR to service-dns maybe then?

**Comment by GMTA** [comment]
@achekulaev The change is that we build a docker image with the `local.conf` file emptied, so it isn't picked up. I can't really offer that as a PR.

But the PR would basically be a revert of this commit:
https://github.com/docksal/service-dns/commit/42b64a71c3850dc019b806120ab716fdbb1a8356#diff-b958f585a04af5ee2087610ea7180f34R15
