### ISSUE TITLE
Add support for shared shell aliases in the cli container

### ISSUE THREAD

**Issue by mikecrittenden** [docksal/docksal#779]
I'm not sure how this could/should work, but it would be nice if I could somehow tell Docksal that every cli container for every project should pull in a specific list of shell aliases for whenever I am working inside the container.

For example, I'm so used to typing `gs` for `git status`, but whenever I type that inside a bash session in the cli container, it kicks me to a GS prompt which is annoying. 

Is there any way to do that? Or could there be?

**Comment by mike-potter** [comment]
+1.  I miss my "ll" alias for "ls -al".  I thinking of using a custom dockerfile that will automatically source a local script but not sure if this is the right way.

**Comment by achekulaev** [comment]
https://docksal.readthedocs.io/en/master/advanced/extend-images/

**Comment by mikecrittenden** [comment]
Suggestion: maybe make the CLI container auto add any aliases that are defined in a global `~/.docksal/services/cli/aliases` file?

**Comment by lmakarov** [comment]
`docksal/cli` has support for running a custom startup script. See:
https://github.com/docksal/service-cli#customizing-startup

That is a lightweight version of extending images, if you don't want to mess with extending an image with a custom Dockerfiles, as pointed to by @achekulaev.

> Suggestion: maybe make the CLI container auto add any aliases that are defined in a global ~/.docksal/services/cli/aliases file?

@mikecrittenden any piece of configuration that is not part of a project's codebase is a potential discrepancy for other developers on you team/project, so I "nay" on that one.

**Comment by mikecrittenden** [comment]
> any piece of configuration that is not part of a project's codebase is a potential discrepancy for other developers on you team/project, so I "nay" on that one.

Cool, that's totally fair. Thanks for the quick response!

**Comment by lmakarov** [comment]
@mikecrittenden, @mike-potter is https://github.com/docksal/service-cli#customizing-startup enough for what you are trying to achieve with aliases?

**Comment by mikecrittenden** [comment]
Assuming `.docksal/services/cli/startup.sh` is only supported within the project directory, and a global one in the home directory is not respected, then that doesn't exactly help in my case since I'm looking for a way to have all projects have them without any work per-project. Or is that not the case, and it does respect a global one?

**Comment by lmakarov** [comment]
@mikecrittenden `.docksal/services/cli/startup.sh` is a project level startup script.

If you are looking for a globally included startup script, then you'd have to take the [Extending stock Docksal images](https://docs.docksal.io/en/master/advanced/extend-images/) path and maintain a forked image. This is the only option that guarantees consistency across the board for anyone working with your project.
