### ISSUE TITLE
Drush 9 path mappings?

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#786]
Version info:

- cli 2.2-7.1
- Drush 9.3.0

I'm running into issues with getting Xdebug to work with Drush 9 and Docksal.

I have the following path mappings:

repo root = /Users/les.peabody/Sites/corvette

- repo root -> /var/www
- repo root/docroot -> /var/www/docroot
- repo root/vendor/bin/drush -> /usr/local/bin/drush

I'm pretty confident I've precisely followed the instructions for setting up Drush debugging https://docksal.readthedocs.io/en/master/tools/xdebug/.

Ultimately, no Drush script or command can be caught with a breakpoint. I checked off "Break at first line of script" and stepped in until I got a path mappings error, and I get the following error:

```
Cannot find a local copy of the file on server /usr/local/bin/drush/bin/drush.php
Local path is /Users/les.peabody/Sites/corvette/vendor/bin/drush/bin/drush.php
```

Maybe it's the end of the day, but for whatever reason I can't figure our how to properly set the path mappings to get everything connected. If you could offer any insight I would be most appreciative. Thanks!

**Comment by sean-e-dietrich** [comment]
@lpeabody I've had success when running the following, and excluding the path mapping.

```
$ fin exec -T vendor/bin/drush ....
```

**Comment by lpeabody** [comment]
That is somewhat helpful. Out of curiosity, is the current documentation completely out of date for Drush 9? Or am I just doing something wrong?

**Comment by sean-e-dietrich** [comment]
I'll confirm and if so we will get that updated.
