### ISSUE TITLE
How to set date/time correctly inside Docksal

### ISSUE THREAD

**Issue by ArtuGit** [docksal/docksal#790]
For a testing reason.

```
docker@cli:/var/www/www$ date --set="2 OCT 2018 18:00:00"
date: cannot set date: Operation not permitted
Tue Oct  2 18:00:00 UTC 2018
```

**Comment by lmakarov** [comment]
There are a few options discussed here:
https://stackoverflow.com/questions/29556879/is-it-possible-change-date-in-docker-container

If you are using VirtualBox, then try `fin vm ssh` and then change the date there.
This should then propagate to all containers then, but not sure how long it is going to persist before the date is synced again from the host machine.

**Comment by lmakarov** [comment]
Closing after a period of inactivity. Please reopen if you still have issues/questions.

**Comment by froboy** [comment]
I wrote up some docs on how I did this: https://gist.github.com/froboy/0fa764ccae683a2a97630f777e694b03
