### ISSUE TITLE
Algolia search integration for new docs

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#809]
https://www.algolia.com

**Comment by lmakarov** [comment]
There is a limit of 10k for a document in Algolia
https://www.algolia.com/doc/faq/basics/is-there-a-size-limit-for-my-index-records/

The following documentation sections are currently larger than 10k:

```
$ find . -size +10k -type f
./fin/fin-help.md
./troubleshooting/common-issues.md
./stack/config.md
```

Not sure whether we can split them into multiple sections. May just have to exclude from indexing with Algolia.

**Comment by shelane** [comment]
Looks like it's free for open source, but you need to apply:
https://www.algolia.com/for-open-source

**Comment by lmakarov** [comment]
I'm goin to apply for the OSS account upgrade, however, I think we should still break those 3 sections over 10k that we currently have into smaller ones. @shelane is this something you could tackle?

**Comment by lmakarov** [comment]
Applied. Once we have Algolia search implemented, we should also leverage this opportunity to cross-promote Docksal :)

![Algolia FAQ](https://api.monosnap.com/rpc/file/download?id=gQBs32A6emfNUf4qa4vCoA5RiLQroh)

**Comment by sean-e-dietrich** [comment]
Looking at the following for helping set this up. https://forestry.io/blog/search-with-algolia-in-hugo/

**Comment by lmakarov** [comment]
@sean-e-dietrich yes, that's where I started from as well. I contacted Algolia to get the OSS subscription approved and they recommended applying for https://community.algolia.com/docsearch/ instead. The application did say it will take them about a week to process, but it has been 2 weeks since then. I've just sent them a followup email.

**Comment by lmakarov** [comment]
Instructions (edited) for setting up DocSearch from Algolia:

> ...
> 
> - Copy the following CSS/JS snippets and add them to your page 
> 
>  
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" /> 
> 
>  
> <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script> 
> <script type="text/javascript"> docsearch({ 
> apiKey: '656714d8c3d5f7138b76633780faf6ba', 
> indexName: 'docksal', 
> inputSelector: '### REPLACE ME ####', 
> debug: false // Set debug to true if you want to inspect the dropdown 
> }); 
> </script> 
> 
> - Add a search input in your page if you don't have any yet. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field. 
> 
> - Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/styling.html) 
> - You can also check your configuration in our github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/docksal.json). 
> ...
> 
> Please open a pull request if want to leverage your configuration! 
> ...

**Comment by shelane** [comment]
Since this needs to go into the header and footer and those are managed in the hugo learn theme, how should it be handled? The forked theme would be updated with the code and then docksal code would be updated to point to the latest commit?

Modifying locally, I see some issues with the autocomplete being unreadable. I'll have to play around with this more later to see it at work.
