### ISSUE TITLE
MacOS 10.13.6 with SIP enabled fails on Raw Partition

### ISSUE THREAD

**Issue by owendelong** [docksal/docksal#814]
**Description**

Cannot start VM using vmdk for raw partition as hard drive -- PERMISSION denied and other errors:

Result Code: | NS_ERROR_FAILURE (0x80004005)
-- | --
Component: | ConsoleWrap
Interface: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

(The following appear in the white box above the previous message which appears in the pink box)
VD: error VERR_NOT_SUPPORTED opening image file '/Users/owen/bootcamp.vmdk' (VERR_NOT_SUPPORTED).
VD: error VERR_ACCESS_DENIED opening image file '/Users/owen/bootcamp.vmdk' (VERR_ACCESS_DENIED).
Failed to open image '/Users/owen/bootcamp.vmdk' in read-write mode (VERR_ACCESS_DENIED).
AHCI: Failed to attach drive to Port0 (VERR_ACCESS_DENIED).

The VirtualBox was run as user owen. The following permissions are n the raw disk partition and .vmdk file:
brw-rw----  1 owen  staff    1,  12 Nov  7 18:24 /dev/disk4s2
-rw-------  1 owen  staff       542 Nov  7 19:07 bootcamp.vmdk

**Steps to reproduce the issue:**

1. Create a raw disk partition vmdk
2. Attach it to the virtual machine storage driver
3. Launch the virtual machine

**Describe the results you received:**

See Description

**Describe the results you expected:**

I expected the VM to launch

**Output of `fin config`:**

<details>

  <summary>fin config output</summary>

```
fin: Command not found.
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
fin: Command not found.
  ```

</details>

**Comment by owendelong** [comment]
This error happens regardless of SIP enabled or not.

**Comment by achekulaev** [comment]
@owendelong you obviously posted the issue to the wrong project. Please repost the the right one.

**Comment by owendelong** [comment]
Seems to apply if setting up the raw partition to point to a slice instead of a whole disk.

Remaking the vmdk file to point to the whole disk worked around the problem.

**Comment by owendelong** [comment]
Not sure how I ended up here, either. Was attempting to post to VirtualBox. Sorry about that.
