### ISSUE TITLE
Add option to perform "project create" from a custom git repo

### ISSUE THREAD

**Issue by jhedstrom** [docksal/docksal#818]
While it is possible to manually setup a docksal project for contributing to Drupal core, it would be nice to be able to just point folks to an existing boilerplate/template.

I've taken a start at what this would look like over at https://github.com/jhedstrom/drupal8-contrib

It essentially does the following:

1. Removes `docroot` from the template repo, and instead clones it from drupal.org
1. Performs a composer install

Things it doesn't yet do, but could:

1. Symlink in a top-level directory for tracking _contrib_ module repos (or themes, etc)
1. Helper commands for patch application and creation

I opened this issue here as I wasn't sure what the process was for creating new boilerplates.

**Comment by sean-e-dietrich** [comment]
Thank you @jhedstrom! I've been thinking about this for sometime after Drupalcon Nashville about how to quickly get a person set up so they can test modules and patches easily. I was thinking that maybe Addons would be the better fit rather then a boilerplate, or rather then just add in a new boilerplate think about what it is a person at a con/camp is looking to do and how can we make it easier for them.

**Comment by jhedstrom** [comment]
@sean-e-dietrich I'd be curious as to how to achieve this with an addon, given that the core repo needs to essentially replace `docroot` in the `drupal8` boilerplate? I'm all for making an addon if there's a way!

**Comment by achekulaev** [comment]
There was already an idea of project create from URL https://github.com/docksal/docksal/pull/436/files

Back then I pushed back for wizard was a guaranteed way to get a project working. Now I think it could be added if messaged properly.

**Comment by lmakarov** [comment]
This was implemented in #1154 and released in [v1.13.0](https://github.com/docksal/docksal/releases/tag/v1.13.0)
