### ISSUE TITLE
Review documentation outline

### ISSUE THREAD

**Issue by david-hernandez** [docksal/docksal#83]
Setting up an issue to go through the docs outline and suggest changes. Input welcome.

Using Read the Docs, [http://docksal.readthedocs.io/en/develop/](http://docksal.readthedocs.io/en/develop/), this is the current outline. 

Docksal 
- intro
- how to install
- describe default stack
- how to update
- tutorial links
- basic troubleshooting
- how to uninstall docksal

Getting started
- system requirements
- env setup
- configure a project, add .docksal directory and run fin start

Advanced config
- multiple projects
- drupal settings
- overriding default php/mysql
- mysql db access
- automatic db import
- extending fin
- exposing docker container ports
- using docker for mac/win
-customize project config

Utilities
- xdebug
- custom ssh keys
- sending and capturing email
- sass and compass
- php code sniffer
- varnish
- memcached
- solr
- blackfire
- behat
- share via ngrok

**Comment by david-hernandez** [comment]
Looking at the list is there anything missing under utilities?

The main thing I want to add is a full list of all fin commands with sample usage.

**Comment by david-hernandez** [comment]
For fin we currently have

vm <command>                  	Docksal's Virtualbox machine commands (fin help vm)

	start (up)                    	Start virtualbox machine and project services
	stop [-a (--all)]             	Stop project services (-a stops all services on all projects)
	restart                       	Restart all current project services
	status (ps) [-a (--all)]      	Show project services status (-a shows all running containers)
	reset [service]               	Recreate project services and containers (fin help reset)
	rm [service]                  	Remove project services (fin help rm)

	bash [service]                	Open shell into container. Defaults to cli
	exec <command> [params]       	Execute a command in cli
	exec-url <url>                	Download script from URL and run it on host (URL should be public)
	logs [service]                	Show Docker logs for service container (e.g. Apache logs)

	create-site                   	Download and install Drupal or Wordpress.
	drush [command]               	Execute Drush command (Drupal)
	drupal [command]              	Execute Drupal Console command (Drupal 8)
	wp [command]                  	Execute WP-CLI command (WordPress)

	sqlc                          	Opens mysql shell to current project database (fin help sqlc)
	sqls                          	Show list of available databases (fin help sqls)
	sqld <database> <file>        	Dump specified database into file (fin help sqld)
	sqli <database> <file>        	Truncate database and import from sql dump (fin help sqli)

	behat [--path=path]           	Run Behat tests from path relative to YML path. Default: tests/behat
	ssh-add [-lD] [key]           	Adds private key identities to the authentication agent (fin help ssh-add)

	alias                         	Create/remove folder aliases (fin help alias)
	config                        	Display/generate project configuration (fin help config)
	cleanup [--hard]              	Remove unused docker images (--hard will also remove stopped containers)
	sysinfo                       	Show diagnostics information for bug reporting
	share                         	Share web server of the current project on the internet using ngrok
	version	(v, -v)               	Print fin version. [v, -v] - prints short version
	update                        	Update Docksal

I'm ok with a page for each. It should be easier to direct link that way.

**Comment by david-hernandez** [comment]
Docksal intro currently does not have a solid overview/explanation of docksal and how it works. That can be its own page with diagram if needed.

**Comment by achekulaev** [comment]
> list of all fin commands with sample usage.

You can use sample usage for some of them via `fin help <command>`

**Comment by lmakarov** [comment]
All docs were reviewed and outline updates for the 1.0.0 release. Closing.
