### ISSUE TITLE
Update fin start to allow starting individual services

### ISSUE THREAD

**Issue by mkochendorfer** [docksal/docksal#830]
Right now if you ever have a scenario where you only want to start one of a projects many services, there is no way to do so.  For example, if you only want to start the cli or web containers.

I would suggested adding an optional parameter to `fin start` that allows you to start a specific service.  For example `fin start cli` would start only the cli service.  `fin start web` would start just the web service.

**Comment by mkochendorfer** [comment]
stop, reset, and remove all already support a similar option

**Comment by achekulaev** [comment]
What happens next is users start service one by one and we would never know when to perform compulsory project things like checking project name is unique, importing new ssh keys, creating project network (if needed), connecting project containers to the network, setting permissions for files in cli, performing unison sync ann some others.

**Comment by lmakarov** [comment]
@mkochendorfer as there are dependencies between services in a stack, you may not be able to start just one without the others.

Try `fin dc start <service>` (`fin docker-compose start <service>`).

Also, @achekulaev is right - there are some assumptions that Docksal makes regarding services and starting stoping the default ones (web, cli and db) independently may produce unexpected and undesired results.

**Comment by mkochendorfer** [comment]
`fin dc start cli` does indeed get me what I needed.  I am curious though what the concern is with adding that same behavior to `fin start cli` if it is already achievable via other means?

**Comment by mkochendorfer** [comment]
`fin stop [service]` also already allows for getting a partial running stack, so I am failing to see the difference here with `fin start [service]`

**Comment by achekulaev** [comment]
> start the project CLI container to do a build of some sort 

To perform some preliminary build using cli before starting a project you can use [run-cli](https://docs.docksal.io/en/master/fin/fin-run-cli/).

**Comment by mkochendorfer** [comment]
@achekulaev I understand how to use `run-cli` for basic tasks.  In my case I have project specific dependencies in the project specific cli container that would not be available in that container, and it would introduce unnecessary complexity and performance overhead to config/install them there in addition to the project cli container.

The cli service example is just one example though.  There are many other cases where your project might define a number of services that you might want to commonly start up all together with `fin start`, but sometimes you might be focused on working on a single portion of the project and only want that single service up.  Like if you have a container with just your design system in it separate from your web container, and you are working on prototyping in the design system (PatternLab, Storybook, etc).  Or if you have a single project that has an API service and a frontend app service in it, you might sometimes want to start up just the API to work only on that part of the project in isolation.  There are countless other potential use cases for this flexibility being available in the system.

**Comment by achekulaev** [comment]
@mkochendorfer I see what you mean. However current workflow is not really suitable for the way of starting a project, when one can start arbitrary project parts in an arbitrary order and in arbitrary combinations. It is a limitation, but it is for global good. When you stop some of the project parts and it still works, it is different. It is like turning off TCS or passenger air bag in your car. You _can_ turn them off and your car will still drive, but you _cannot_ start your car with TCS or passenger air bag off for safety reasons. 

It is the same here. I know for a fact that if we just allow starting arbitrary parts, users will immediately shoot their foot by starting `web` container separately and raising tickets why `project.docksal` is not routing properly now (and it would be because project network is not created and not connected to the docksal-vhost-proxy).

So if you are an experienced user understanding consequences of starting separate services, you have `fin docker-compose ...` to perform any custom operations on your stack that you want. But this is a highly advanced feature and it is harder (but not too cumbersome) to access for a reason, serving a security guard against inexperienced users.

**Comment by lmakarov** [comment]
> `fin stop [service]` also already allows for getting a partial running stack, so I am failing to see the difference here with `fin start [service]`

This is a valid point and we should evaluate the path forward here to keep things consistent. We either allow both `start` and `stop` for individual project level services or none.

In the mean time, `fin dc` (`fin docker-compose`) can be used by advanced users to bypass Docksal's wrappers and checks. We should revise those checks as well.

**Comment by mkochendorfer** [comment]
@achekulaev Thanks for the thoughtful response.  I will move forward with using `fin dc` for my use case.

I wonder if there would be some other alternatives with separating multiple stacks next to each other in the same project easily.  Something like multiple docksal.yml files or something similar.

**Comment by lmakarov** [comment]
> I wonder if there would be some other alternatives with separating multiple stacks next to each other in the same project easily. Something like multiple docksal.yml files or something similar.

@mkochendorfer that's an interesting ask and deserves a separate feature request proposal :)

**Comment by achekulaev** [comment]
@mkochendorfer 

> I wonder if there would be some other alternatives with separating multiple stacks next to each other in the same project easily. 

You can already do it using several stacks that you can switch using [DOCKSAL_ENVIRONMENT](https://docksal.readthedocs.io/en/master/advanced/stack-config/#docksal_environment) variable. 

Create `docksal.yml` containing your minimal setup and `docksal-full.yml` containing your "full" setup, and set `DOCKSAL_ENVIRONMENT=full` in the env file. Whenever you only need your minimal setup, comment out that line.

**Comment by mkochendorfer** [comment]
Ah, perfect!

**Comment by mkochendorfer** [comment]
For anyone else who stumbles across this thread, here is an example custom init command that takes this approach.  Not the right solution for everyone, but it might help some else who has similar dependencies to the project I am working on:
```
#!/usr/bin/env bash

## Initialize the project.

# Start the cli container only so we can run some commands in it before we start the whole project.
fin docker-compose up -d cli

# Install all dependencies.
fin run npm install

# Do an initial build.
fin run npm run build

# Reset containers now that we have all of the dependencies we need.
fin project reset --force
```

**Comment by lmakarov** [comment]
@mkochendorfer for your case, can you please elaborate why `npm install` and `npm build` have to be run before the rest of the stack is up?

**Comment by mkochendorfer** [comment]
It has to do with how local files get mounted into the docker images to override things with things we need for local dev.  In our case we are deploying built docker images to prod, so those images need to have a bunch of dev tooling pushed into them for local development that we don't want in prod.

For example, in prod we are running node with something like `node index.js`, but it local dev we want `nodemon index.js` so we need to get nodemon into the container and override the command in docksal.yml with the nodemon version.  We are also using webpack to build our node app, so we need to get both of those dependencies installed via npm so they are available both for running the service and building `index.js` via `npm run build`.

If you have suggestions on a better approach, I am completely open to other ideas.
