### ISSUE TITLE
Adding a new key is unclear

### ISSUE THREAD

**Issue by paulsheldrake** [docksal/docksal#831]
When adding a new key through the `docksal.env` file it's unclear how to get the new key recognized by the projects.

https://docs.docksal.io/en/master/advanced/ssh-agent/

**Comment by achekulaev** [comment]
[ ] Improve docs to tell when keys are loaded
[ ] Write a blog post about it

**Comment by shelane** [comment]
Blog post: https://blog.docksal.io/loading-ssh-keys-in-docksal-containers-c6a48944ccc8
