### ISSUE TITLE
"/usr/local/bin/fin: line 3258: ip: command not found" on RHEL7

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#835]
Running `fin init` of docksal/drupal7 on RHEL7:

```
...
 Step 2  Recreating services...
/usr/local/bin/fin: line 3258: ip: command not found
 ALERT:  Some Docksal services were not running
         Restarting Docksal system services...
Configuring network settings...
/usr/local/bin/fin: line 3258: ip: command not found
RTNETLINK answers: File exists
Resetting Docksal services...
 ➔ proxy
 ➔ dns
   upstream 10.255.255.10
Enabling automatic *.docksal DNS resolver...
 ➔ ssh-agent
Removing containers...
...
```

**Comment by achekulaev** [comment]
RHEL is not in the support matrix

**Comment by lmakarov** [comment]
RHEL = CentOS.

Just checked CentOS 7 on DO and it does come with `ip`:

```
[root@centos-s-1vcpu-2gb-sfo2-01 ~]# which ip
/usr/sbin/ip
```

I wonder if there are minimal/etc. flavors of RHEL/CentOS or just differences between cloud provider images for the same OS/version.

**Comment by achekulaev** [comment]
```
if (RHEL === CentOS ) then { this ticket would not have existed ;) }
```

**Comment by lmakarov** [comment]
- [Why doesn't centos7 include "ip"?](https://github.com/docker-library/docs/issues/526)
- [Latest centos7 image seems to be missing some packages](https://github.com/CentOS/sig-cloud-instance-images/issues/40)

**Comment by achekulaev** [comment]
Maybe it's flavor dependent then. As I have it in CentOS 7 where I tested Docksal.

**Comment by lmakarov** [comment]
`yum install -y iproute` solves it, but that's a manual step.

Maybe we should not tie our hands and stick with whatever bare minimum there is on the host.
It's a noble move, but I'm not sure that it's really worth trying to come up with workarounds for every possible missing tool. Yes, we should keep it minimal, but tools like `ip` are common even in minimal distributions. There are not that many package manager variations in Linux distros we support, that we couldn't just install the necessary tools if missing.

**Comment by achekulaev** [comment]
Yes `ip` tool is very fundamental for "normal" installations, but is often missing in the bare-bones installations like `docksal/cli` for instance :)

**Comment by lmakarov** [comment]
Just tested on the official AWS CentOS 7 image - `ip` present.

As for `docksal/cli` - it's a container vs VM/server.
There has been no use cases for this package (yet), so yeah, it's not there to minimize the size 😛

**Comment by lmakarov** [comment]
Let's keep this open for visibility. I ran into this issue on a custom provided RHEL7 and assume they used the Minimal flavor of RHEL. This means that any CentOS/RHEL Minimal installation would be affected.

**Comment by achekulaev** [comment]
We should just add `ip` to the list of required software in https://docksal.io/installation#linux-supported and close this ticket IMO

**Comment by lmakarov** [comment]
Won't fix.
