### ISSUE TITLE
SMB share mount failed; SMB v2.1

### ISSUE THREAD

**Issue by kyleskrinak** [docksal/docksal#842]
**Description**

Switched my Win10 environment from Docker Native to using the VBox/SMB 2.1 as per a recent fin update. 

Note SMB2 is enabled:
```
Get-SmbServerConfiguration | Select EnableSMB2Protocol

EnableSMB2Protocol
------------------
              True
```

However, I am seeing the following error message:

```
mount: mounting ///docksal-c on /c failed                                                            
exit status 255                                                                                       
  ERROR:  SMB share mount failed.                                                                              
          Make sure your Windows password is correct and run fin vm restart to try again.                      
          For troubleshooting instructions see https://docs.docksal.io/troubleshooting/windows-smb/

```

I have reviewed the steps here: https://docs.docksal.io/troubleshooting/windows-smb/ I’ve tried all relevant suggestions, including resetting my AD and device password. I haven’t tried re-imaging my device, as that step is non-trivial.

**Steps to reproduce the issue:**

1. Disable Hyper-V environment
2. Edit ~/.docksal/docksal.env so that DOCKER_NATIVE=0
3. Run fin update
4. `fin vm start`

**Describe the results you received:**

```
Starting "docksal"...                                                                                
(docksal) Check network to re-create if needed...                                                    
(docksal) Windows might ask for the permission to configure a dhcp server. Sometimes, such confirmat ion window is minimized in the taskbar.                                                              
(docksal) Waiting for an IP...                                                                       
Machine "docksal" was started.                                                                       
Waiting for SSH to be available...                                                                   
Detecting the provisioner...                                                                         
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command. Enabling automatic *.docksal DNS resolver...                                                         
Clearing DNS cache...                                                                                
Configuring SMB shares...                                                                            
Enter your Windows account password:                                                                 
mount: mounting ///docksal-c on /c failed                                                            
exit status 255                                                                                      
Mount command failed... Trying an alternative method...                                              
mount: mounting ///docksal-c on /c failed                                                            
exit status 255                                                                                       
ERROR:  SMB share mount failed.                                                                              
Make sure your Windows password is correct and run fin vm restart to try again.                      
For troubleshooting instructions see https://docs.docksal.io/troubleshooting/windows-smb/   
{ Projects } master » mount: mounting ///docksal-c on /c failed                                      
mount: mounting ///docksal-c on /c failed                                                            
exit status 255                                                                                       
 ERROR:  SMB share mount failed.                                                                              
          Make sure your Windows password is correct and run fin vm restart to try again.                      
          For troubleshooting instructions see https://docs.docksal.io/troubleshooting/windows-smb/
```

**Describe the results you expected:**

A working VBox docksal environment

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: finupdate
COMPOSE_FILE:
C:/Users/kds38/.babun/cygwin/home/kds38/.docksal/stacks/volumes-bind.yml
C:/Users/kds38/.babun/cygwin/home/kds38/.docksal/stacks/stack-default.yml
C:/Users/kds38/Projects/finupdate/.docksal/docksal.yml
ENV_FILE:
C:/Users/kds38/Projects/finupdate/.docksal/docksal.env

PROJECT_ROOT: /c/Users/kds38/Projects/finupdate
DOCROOT: docroot
VIRTUAL_HOST: finupdate.docksal
VIRTUAL_HOST_ALIASES: *.finupdate.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
---------------------
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Cygwin Windows 10.0.17134

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376

███  FIN
fin version: 1.79.4

███  DOCKER COMPOSE
EXPECTED VERSION: 1.22.0

███  DOCKER
EXPECTED VERSION: 18.06.1-ce


███  DOCKER MACHINE
EXPECTED VERSION: 0.15.0


███  DOCKSAL: PROJECTS

███  DOCKSAL: VIRTUAL HOSTS
No virtual hosts found

███  DOCKER: RUNNING CONTAINERS

███  DOCKER: NETWORKS

███  VIRTUALBOX
EXPECTED VERSION: 5.2.20

███  DOCKSAL MOUNTS
[101m ERROR: [0m [0;91mMounts matching 192.168.64* were not found![0m

███  HDD Usage

  ```

</details>

**Comment by achekulaev** [comment]
@kyleskrinak so does opening `\\192.168.64.1\` in explorer works and you see `docksal-c` share there as pictured?

![](https://d33wubrfki0l68.cloudfront.net/348c6ed95ee522376e473505b3ff100e763406aa/31008/images/troubleshooting-smb-your-shares2.png)

**Comment by kyleskrinak** [comment]
Yes. `\\192.168.64.1` lists the shares “docksal-c” and “c”

**Comment by achekulaev** [comment]
- Do you use Microsoft account?
- Does your password or username contain special characters?

**Comment by achekulaev** [comment]
@kyleskrinak 
Oh I see. `DOCKER_HOST_IP` ends up being empty. I can tell it because this line `mount: mounting ///docksal-c on /c failed` should read `mounting //<ip_address>/docksal-c`.

Please provide outputs of the following commands:

1. 

    /cygdrive/c/Program Files/Oracle/VirtualBox/VBoxManage.exe showvminfo --machinereadable

2.

    /cygdrive/c/Program Files/Oracle/VirtualBox/VBoxManage.exe list hostonlyifs

**Comment by kyleskrinak** [comment]
<details>
<summary>Show VM Info</summary>

```

/cygdrive/c/Program Files/Oracle/VirtualBox/VBoxManage.exe" showvminfo docksal --machinereadable
name="docksal"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="6a229397-5b71-49c8-80de-3293720abb1c"
CfgFile="C:\\Users\\kds38\\.docker\\machine\\machines\\docksal\\docksal\\docksal.vbox"
SnapFldr="C:\\Users\\kds38\\.docker\\machine\\machines\\docksal\\docksal\\Snapshots"
LogFldr="C:\\Users\\kds38\\.docker\\machine\\machines\\docksal\\docksal\\Logs"
hardwareuuid="6a229397-5b71-49c8-80de-3293720abb1c"
memory=2048
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
chipset="piix3"
firmware="BIOS"
cpus=1
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="poweroff"
VMStateChangeTime="2018-11-19T14:02:00.000000000"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="C:\Users\kds38\.docker\machine\machines\docksal\boot2docker.iso"
"SATA-ImageUUID-0-0"="48079c4a-0aec-4b2c-8fec-6628d64c1b41"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="C:\Users\kds38\.docker\machine\machines\docksal\disk.vmdk"
"SATA-ImageUUID-1-0"="3b9c212d-a8d1-49d7-a137-da571a9c982a"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
natnet1="nat"
macaddress1="080027A5B5E7"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,62803,,22"
hostonlyadapter2="VirtualBox Host-Only Ethernet Adapter #2"
macaddress2="080027E362B7"
cableconnected2="on"
nic2="hostonly"
nictype2="82540EM"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="dsound"
audio_in="false"
audio_out="false"
clipboard="disabled"
draganddrop="disabled"
vrde="off"
usb="off"
ehci="off"
xhci="off"
videocap="off"
videocap_audio="off"
videocapscreens=0
videocapfile="C:\Users\kds38\.docker\machine\machines\docksal\docksal\docksal.webm"
videocapres=1024x768
videocaprate=512
videocapfps=25
videocapopts=
GuestMemoryBalloon=0
--

```
</details>

<details>
<summary>Host Only IFS</summary>

```

"/cygdrive/c/Program Files/Oracle/VirtualBox/VBoxManage.exe" list  hostonlyifs   
Name:                        VirtualBox Host-Only Ethernet Adapter #2
GUID:                        1543ef2d-2ad5-49e7-ba84-195d1e5592ca
DHCP:                        Disabled
IPAddress:                   192.168.64.1
NetworkMask:                 255.255.255.0
IPV6Address:                 fe80::6056:7095:d28:c88d
IPV6NetworkMaskPrefixLength: 64
HardwareAddress:             0a:00:27:00:00:06
MediumType:                  Ethernet
Mask:                        255.255.255.0
IPV6Address:                 fe80::a8c0:4314:7763:3ebd
IPV6NetworkMaskPrefixLength: 64
HardwareAddress:             0a:00:27:00:00:16
MediumType:                  Ethernet
Wireless:                    No
Status:                      Up
VBoxNetworkName:             HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter

--
```
</details>

**Comment by kyleskrinak** [comment]
```/cygdrive/c/Program Files/Oracle/VirtualBox/VBoxManage.exe" showvminfo  docksal  --machinereadable                                                                                    name="docksal"                                                                                        groups="/"                                                                                            ostype="Linux 2.6 / 3.x / 4.x (64-bit)"                                                               UUID="6a229397-5b71-49c8-80de-3293720abb1c"                                                           CfgFile="C:\\Users\\kds38\\.docker\\machine\\machines\\docksal\\docksal\\docksal.vbox"                SnapFldr="C:\\Users\\kds38\\.docker\\machine\\machines\\docksal\\docksal\\Snapshots"                  LogFldr="C:\\Users\\kds38\\.docker\\machine\\machines\\docksal\\docksal\\Logs"                        hardwareuuid="6a229397-5b71-49c8-80de-3293720abb1c"                                                   memory=2048                                                                                           pagefusion="off"                                                                                      vram=8                                                                                                cpuexecutioncap=100                                                                                   hpet="on"                                                                                             chipset="piix3"                                                                                       firmware="BIOS"                                                                                       cpus=1                                                                                                pae="on"                                                                                              longmode="on"                                                                                         triplefaultreset="off"                                                                                apic="on"                                                                                             x2apic="off"                                                                                          cpuid-portability-level=0                                                                             bootmenu="disabled"                                                                                   boot1="dvd"                                                                                           boot2="dvd"                                                                                           boot3="disk"                                                                                          boot4="none"                                                                                          acpi="on"                                                                                             ioapic="on"                                                                                           biosapic="apic"                                                                                       biossystemtimeoffset=0                                                                                rtcuseutc="on"                                                                                        hwvirtex="on"                                                                                         nestedpaging="on"                                                                                     largepages="on"                                                                                       vtxvpid="on"                                                                                          vtxux="on"                                                                                            paravirtprovider="default"                                                                            effparavirtprovider="kvm"                                                                             VMState="poweroff"                                                                                    VMStateChangeTime="2018-11-19T14:02:00.000000000"                                                     monitorcount=1                                                                                        accelerate3d="off"                                                                                    accelerate2dvideo="off"                                                                               teleporterenabled="off"                                                                               teleporterport=0                                                                                      teleporteraddress=""                                                                                  teleporterpassword=""                                                                                 tracing-enabled="off"                                                                                 tracing-allow-vm-access="off"                                                                         tracing-config=""                                                                                     autostart-enabled="off"                                                                               autostart-delay=0                                                                                     defaultfrontend=""                                                                                    storagecontrollername0="SATA"                                                                         storagecontrollertype0="IntelAhci"                                                                    storagecontrollerinstance0="0"                                                                        storagecontrollermaxportcount0="30"                                                                   storagecontrollerportcount0="30"                                                                      storagecontrollerbootable0="on"                                                                       "SATA-0-0"="C:\Users\kds38\.docker\machine\machines\docksal\boot2docker.iso"                          "SATA-ImageUUID-0-0"="48079c4a-0aec-4b2c-8fec-6628d64c1b41"                                           "SATA-tempeject"="off"                                                                                "SATA-IsEjected"="off"                                                                                "SATA-1-0"="C:\Users\kds38\.docker\machine\machines\docksal\disk.vmdk"                                "SATA-ImageUUID-1-0"="3b9c212d-a8d1-49d7-a137-da571a9c982a"                                           "SATA-2-0"="none"                                                                                     "SATA-3-0"="none"                                                                                     "SATA-4-0"="none"                                                                                     "SATA-5-0"="none"                                                                                     "SATA-6-0"="none"                                                                                     "SATA-7-0"="none"                                                                                     "SATA-8-0"="none"                                                                                     "SATA-9-0"="none"                                                                                     "SATA-10-0"="none"                                                                                    "SATA-11-0"="none"                                                                                    "SATA-12-0"="none"                                                                                    "SATA-13-0"="none"                                                                                    "SATA-14-0"="none"                                                                                    "SATA-15-0"="none"                                                                                    "SATA-16-0"="none"                                                                                    "SATA-17-0"="none"                                                                                    "SATA-18-0"="none"                                                                                    "SATA-19-0"="none"                                                                                    "SATA-20-0"="none"                                                                                    "SATA-21-0"="none"                                                                                    "SATA-22-0"="none"                                                                                    "SATA-23-0"="none"                                                                                    "SATA-24-0"="none"                                                                                    "SATA-25-0"="none"                                                                                    "SATA-26-0"="none"                                                                                    "SATA-27-0"="none"                                                                                    "SATA-28-0"="none"                                                                                    "SATA-29-0"="none"                                                                                    natnet1="nat"                                                                                         macaddress1="080027A5B5E7"                                                                            cableconnected1="on"                                                                                  nic1="nat"                                                                                            nictype1="82540EM"                                                                                    nicspeed1="0"                                                                                         mtu="0"                                                                                               sockSnd="64"                                                                                          sockRcv="64"                                                                                          tcpWndSnd="64"                                                                                        tcpWndRcv="64"                                                                                        Forwarding(0)="ssh,tcp,127.0.0.1,62803,,22"                                                           hostonlyadapter2="VirtualBox Host-Only Ethernet Adapter #2"                                           macaddress2="080027E362B7"                                                                            cableconnected2="on"                                                                                  nic2="hostonly"                                                                                       nictype2="82540EM"                                                                                    nicspeed2="0"                                                                                         nic3="none"                                                                                           nic4="none"                                                                                           nic5="none"                                                                                           nic6="none"                                                                                           nic7="none"                                                                                           nic8="none"                                                                                           hidpointing="ps2mouse"                                                                                hidkeyboard="ps2kbd"                                                                                  uart1="off"                                                                                           uart2="off"                                                                                           uart3="off"                                                                                           uart4="off"                                                                                           lpt1="off"                                                                                            lpt2="off"                                                                                            audio="dsound"                                                                                        audio_in="false"                                                                                      audio_out="false"                                                                                     clipboard="disabled"                                                                                  draganddrop="disabled"                                                                                vrde="off"                                                                                            usb="off"                                                                                             ehci="off"                                                                                            xhci="off"                                                                                            videocap="off"                                                                                        videocap_audio="off"                                                                                  videocapscreens=0                                                                                     videocapfile="C:\Users\kds38\.docker\machine\machines\docksal\docksal\docksal.webm"                   videocapres=1024x768                                                                                  videocaprate=512                                                                                      videocapfps=25                                                                                        videocapopts=                                                                                         GuestMemoryBalloon=0--```

**Comment by achekulaev** [comment]
@kyleskrinak do you use Babun?

**Comment by kyleskrinak** [comment]
Yes, I use Babun and I ran the commands in Babun.

```
babun version 1.2.0
Created and maintained by Tom Bujok (@tombujok)
Copyright (c) 2014-2015.

```

**Comment by achekulaev** [comment]
Please run these
`docker-compose version`
`docker version`
and `fin sysinfo` again please.

**Comment by kyleskrinak** [comment]
`docker-compose version
zsh: command not found: docker-compose`

`docker version
zsh: command not found: docker
`
<details>
<summary>fin sysinfo</summary>

```
¦¦¦  OS
Cygwin Windows 10.0.17134
CYGWIN_NT-10.0-WOW TTS-170241WL 2.11.2(0.329/5/3) 2018-11-08 14:30 i686 Cygwin

¦¦¦  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376

¦¦¦  FIN
fin version: 1.79.4

¦¦¦  DOCKER COMPOSE
EXPECTED VERSION: 1.22.0
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

¦¦¦  DOCKER
EXPECTED VERSION: 18.06.1-ce

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false

¦¦¦  DOCKER MACHINE
EXPECTED VERSION: 0.15.0
docker-machine.exe version 0.15.0, build b48dc28d

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.06.1-ce

¦¦¦  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

¦¦¦  DOCKSAL: VIRTUAL HOSTS
No virtual hosts found

¦¦¦  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
d0ee0f97c68b        docksal/ssh-agent:1.2     "docker-entrypoint.s…"   42 hours ago        Up 19 minutes (healthy)                                                            docksal-ssh-agent
848db39e9dc0        docksal/dns:1.1           "docker-entrypoint.s…"   42 hours ago        Up 19 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
c53bb3480537        docksal/vhost-proxy:1.4   "docker-entrypoint.s…"   42 hours ago        Up 19 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

¦¦¦  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
63c0f7258232        _default            bridge              local
6e54f471dea6        bridge              bridge              local
137c19bae83a        host                host                local
3f72bef18633        none                null                local

¦¦¦  VIRTUALBOX
EXPECTED VERSION: 5.2.20
5.2.20r125813

¦¦¦  DOCKSAL MOUNTS
 ERROR:  Mounts matching 192.168.64* were not found!

¦¦¦  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G    227.8M     43.5G   1% /mnt/sda1



```
</details>

**Comment by achekulaev** [comment]
Your sysinfo now shows all the information that was missing in the first one and shows different values like this one was launched in a completely different environment. 
I propose you try launching projects now and telling if it works.

**Comment by kyleskrinak** [comment]
Not soup yet:

```

Stopping "docksal"...
Machine "docksal" was stopped.
Starting "docksal"...
(docksal) Check network to re-create if needed...
(docksal) Windows might ask for the permission to configure a dhcp server. Sometimes, such confirmation window is minimized in the taskbar.
(docksal) Waiting for an IP...
Machine "docksal" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
Configuring SMB shares...
Enter your Windows account password:
mount: mounting ///docksal-c on /c failed
exit status 255
Mount command failed... Trying an alternative method...
mount: mounting ///docksal-c on /c failed
exit status 255
 ERROR:  SMB share mount failed.
         Make sure your Windows password is correct and run fin vm restart to try again.
         For troubleshooting instructions see https://docs.docksal.io/troubleshooting/windows-smb/

```

<details>
<summary>fin config</summary>

```

---------------------
COMPOSE_PROJECT_NAME_SAFE: finupdate
COMPOSE_FILE:
C:/Users/kds38/.babun/cygwin/home/kds38/.docksal/stacks/volumes-bind.yml
C:/Users/kds38/.babun/cygwin/home/kds38/.docksal/stacks/stack-default.yml
C:/Users/kds38/Projects/finupdate/.docksal/docksal.yml
ENV_FILE:
C:/Users/kds38/Projects/finupdate/.docksal/docksal.env

PROJECT_ROOT: /c/Users/kds38/Projects/finupdate
DOCROOT: docroot
VIRTUAL_HOST: finupdate.docksal
VIRTUAL_HOST_ALIASES: *.finupdate.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
---------------------

```

</details>

<details>
<summary>fin sysinfo</summary>

```

███  OS
Cygwin Windows 10.0.17134

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376

███  FIN
fin version: 1.79.4

███  DOCKER COMPOSE
EXPECTED VERSION: 1.22.0

███  DOCKER
EXPECTED VERSION: 18.06.1-ce


███  DOCKER MACHINE
EXPECTED VERSION: 0.15.0


███  DOCKSAL: PROJECTS

███  DOCKSAL: VIRTUAL HOSTS
No virtual hosts found

███  DOCKER: RUNNING CONTAINERS

███  DOCKER: NETWORKS

███  VIRTUALBOX
EXPECTED VERSION: 5.2.20

███  DOCKSAL MOUNTS
[101m ERROR: [0m [0;91mMounts matching 192.168.64* were not found![0m

███  HDD Usage

```
</details>

<details>
<summary>Show VM info</summary>

```

name="docksal"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="6a229397-5b71-49c8-80de-3293720abb1c"
CfgFile="C:\\Users\\kds38\\.docker\\machine\\machines\\docksal\\docksal\\docksal.vbox"
SnapFldr="C:\\Users\\kds38\\.docker\\machine\\machines\\docksal\\docksal\\Snapshots"
LogFldr="C:\\Users\\kds38\\.docker\\machine\\machines\\docksal\\docksal\\Logs"
hardwareuuid="6a229397-5b71-49c8-80de-3293720abb1c"
memory=2048
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
chipset="piix3"
firmware="BIOS"
cpus=1
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="running"
VMStateChangeTime="2018-11-20T22:39:26.869000000"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="C:\Users\kds38\.docker\machine\machines\docksal\boot2docker.iso"
"SATA-ImageUUID-0-0"="48079c4a-0aec-4b2c-8fec-6628d64c1b41"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="C:\Users\kds38\.docker\machine\machines\docksal\disk.vmdk"
"SATA-ImageUUID-1-0"="3b9c212d-a8d1-49d7-a137-da571a9c982a"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
natnet1="nat"
macaddress1="080027A5B5E7"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,62803,,22"
hostonlyadapter2="VirtualBox Host-Only Ethernet Adapter #2"
macaddress2="080027E362B7"
cableconnected2="on"
nic2="hostonly"
nictype2="82540EM"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="dsound"
audio_in="false"
audio_out="false"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="720,400,0"@0,0 1
vrde="off"
usb="off"
ehci="off"
xhci="off"
VRDEActiveConnection="off"
VRDEClients=0
videocap="off"
videocap_audio="off"
videocapscreens=0
videocapfile="C:\Users\kds38\.docker\machine\machines\docksal\docksal\docksal.webm"
videocapres=1024x768
videocaprate=512
videocapfps=25
videocapopts=
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="5.2.2 r119230"
GuestAdditionsFacility_VirtualBox Base Driver=50,1542753594503
GuestAdditionsFacility_VirtualBox System Service=50,1542753598219
GuestAdditionsFacility_Seamless Mode=0,1542753594503
GuestAdditionsFacility_Graphics Mode=0,1542753594503



```
</details>

<details>
<summary>Host only IFS</summary>

```
Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            1543ef2d-2ad5-49e7-ba84-195d1e5592ca
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::6056:7095:d28:c88d
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:06
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2

Name:            VirtualBox Host-Only Ethernet Adapter
GUID:            b1154f1b-cf9e-4716-bef7-f9d3a1ab8a69
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::a8c0:4314:7763:3ebd
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:16
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter
```

</details>

**Comment by achekulaev** [comment]
So could you explain how comes that your last sysinfo lacks all the information again?

**Comment by kyleskrinak** [comment]
I cannot. However, I reran fin vm restart, (fail) and the fin sysinfo. I’ve updated the output, above.

**Comment by kyleskrinak** [comment]
FYI: I’ve uninstalled and reinstalled docksal, as per [these instructions.](https://docs.docksal.io/getting-started/setup/#uninstall) After [reinstalling](https://docs.docksal.io/getting-started/setup/#install-windows-babun-virtualbox), my instance works now. Note I didn’t remove and reinstall either babun or virtualbox, only docksal. I’m happy to rerun system output if that helps for others.

**Comment by achekulaev** [comment]
Glad it is fixed for you now. Chances are that it is the the change I made in 1.11.1 to make SMB mounting more robust that helped to solve your case
