### ISSUE TITLE
Misguiding docs on V-Host Proxy

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#845]
Docs on https://docs.docksal.io/core/system-vhost-proxy/ misguide users that they can use `*.${VIRTUAL_HOST}.*` in their configs. 

<img width="478" alt="123123123" src="https://user-images.githubusercontent.com/402007/48798437-a88e8580-ecd2-11e8-8785-1dfa415a17f0.png">

**Comment by shelane** [comment]
stacks/services/yml shows `- io.docksal.virtual-host=${VIRTUAL_HOST},*.${VIRTUAL_HOST},${VIRTUAL_HOST}.*`. So it looks like you should have * at both the beginning and the end. It's one or the other and not both.

**Comment by achekulaev** [comment]
One cannot have asterisk at both beginning and the end. nginx does not accept that. This is just a typo in docs.

**Comment by shelane** [comment]
Fixed with #847
