### ISSUE TITLE
Improve latest available version detection in fin

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#849]
`get_docksal_version_latest` should correctly pick the latest release tag.

Here's what's happening right now:

```
$ fin debug get_docksal_version_latest
master
```
```
$ DOCKSAL_USE_RC=1 fin debug get_docksal_version_latest
v1.11.0-rc4
```

What it should be at the moment for both examples above: `v1.11.0`

When we publish the next RC release (e.g. `v1.12.0-rc1`), the second command should return `v1.12.0-rc1`.

**Comment by sean-e-dietrich** [comment]
@lmakarov I believe this has been taken care of. I won't truly know until we publish the next rc.

```
➜  bin git:(latest_version) ✗ ./fin debug get_docksal_version_latest
v1.11.1
➜  bin git:(latest_version) ✗ DOCKSAL_USE_RC=1 ./fin debug get_docksal_version_latest
v1.11.1
```

**Comment by lmakarov** [comment]
@sean-e-dietrich I think you have `DOCKSAL_USE_RC=1` set in your `~/.docksal/docksal.env`

I'm still getting the following on a clean install (Docksal `develop` branch on PWD):

```
$ fin debug get_docksal_version_latest
master
$ DOCKSAL_USE_RC=1 fin debug get_docksal_version_latest
v1.11.1
```

**Comment by achekulaev** [comment]
@lmakarov 

> What it should be at the moment for both examples above: v1.11.0

I don't see any need in that. Can you explain?

**Comment by sean-e-dietrich** [comment]
@achekulaev then we can return the latest stable version instead of master, no?

**Comment by achekulaev** [comment]
Latest stable version *is* the master.

**Comment by lmakarov** [comment]
The issue here was that the following returned the latest RC tag, when there was a stable release already. So an RC user would never get the latest stable version and be stuck on the latest RC version instead.

```
$ DOCKSAL_USE_RC=1 fin debug get_docksal_version_latest
v1.11.0-rc4
```

In theory, the latest RC version would be identical to the latest release version, but that may not always be the case.

Whether the stable release is referred to as `master` or `v1.11.0` (as in the original example) is irrelevant.

**Comment by lmakarov** [comment]
Looking back at the history of this issue. The original problem is no longer reproducible:

```
$ fin debug get_docksal_version_latest
master
$ DOCKSAL_USE_RC=1 fin debug get_docksal_version_latest
v1.11.1
```

The only question is whether `fin debug get_docksal_version_latest` should return the latest release tag instead of `master`.

Thoughts?

**Comment by achekulaev** [comment]
> The only question is whether fin debug get_docksal_version_latest should return the latest release tag instead of master.

I fully support this sentence:

> Whether the stable release is referred to as master or v1.11.0 (as in the original example) is irrelevant.
