### ISSUE TITLE
CONFIG_CERTS mount causes error during system reset

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#850]
```
$ fin system reset
Restoring network settings...
Resetting Docksal services...
 ➔ proxy
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /Users/leonid/.docksal/certs.
See 'docker run --help'.
 ERROR:  Failed starting the proxy service.
```

This also happens during update/install.

Introduced in Docksal [1.10.0](https://github.com/docksal/docksal/releases/tag/v1.10.0) via https://github.com/docksal/docksal/commit/c9bbadfbd24900e30bcc61a8203366efae9cd357
Specifically: https://github.com/docksal/docksal/blob/develop/bin/fin#L3364-L3366

The issue is the same as in #771 - we cannot rely on the user's home directory to be mounted/available  inside the VirtualBox VM.

**Comment by lmakarov** [comment]
This only happens if the `$HOME/.docksal/certs` directory exists on Mac and will unlikely to affect many users (if any) for now.

**Comment by achekulaev** [comment]
Related issue https://github.com/docksal/docksal/issues/657

**Comment by achekulaev** [comment]
Now that #657 is closed the function `check_docker_path` can be used to check whether certain path is shared with Docksal.
Mind that it's somewhat costly - 1.2s. So not really suitable for things like "check status" but barely noticeable for things like `fin p start`.
