### ISSUE TITLE
SMB3 support for Windows 10

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#851]
Looks like we may be able to use SMB3 with the latest boot2docker (v18.09.0). It switched to a new Tiny Core / Linux kernel version and should now support SMB3.

https://github.com/boot2docker/boot2docker/blob/9ca8f5bce3377787cc20a815f70b497a195a5760/files/kernel-config.d/cifs#L5-L9

**Comment by achekulaev** [comment]
It does work. Tried on WIndows 10

```
docker@docksal:~$ sudo mount -t cifs -o username='user',pass='password',domain='DESKTOP-5QPKO2J',sec='ntlmssp',vers=3,nobrl,mfsymlinks,noperm,actimeo=1,dir_mode=0777,file_mode=0777 //192.168.64.1/docksal-c /c
docker@docksal:~$ ls /c
$Recycle.Bin               Recovery
AppleBcInstaller.log       System Volume Information
Documents and Settings     Users
Intel                      Windows
PerfLogs                   hiberfil.sys
Program Files              pagefile.sys
Program Files (x86)        swapfile.sys
ProgramData
docker@docksal:~$

```

**Comment by achekulaev** [comment]
Included as part of #890

**Comment by lmakarov** [comment]
I ran quick performance tests with Drupal 8 and `drush site-install` and the results are unimpressive.

**VirtualBox: Container FS, SMB 1.0, SMB 2.1 and SMB 3.0**
![image](https://user-images.githubusercontent.com/1205005/53678310-2703a780-3c72-11e9-94a8-bd86d13af4f2.png)

**Docker Desktop: Container FS, SMB 3.02**
![image](https://user-images.githubusercontent.com/1205005/53678269-a3e25180-3c71-11e9-897a-064df9f8b5d0.png)

Something must be terribly wrong with the VirtualBox configuration on Windows. The difference of 5x is just too big to be plausible.

**Comment by achekulaev** [comment]
4 cores will do the trick?

**Comment by lmakarov** [comment]
It is generally not recommended to go above 1/2 of the hosts cores for a VM.
Hyper-V uses 2 cores (1/2 of hosts cores) on the machine I'm testing on.
Going with 4 would make things worse, thought, I've not tested that. I will add this test for completeness.
