### ISSUE TITLE
Use half of available CPUs for new machine during VM creation

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#859]
Currently docker-machine creates VM with only 1 CPU, which is very slow.

**Comment by lmakarov** [comment]
With VirtualBox (as well as Hyper-V), a single virtual CPU produces better results than 1+ on most cases: https://github.com/docker/machine/issues/1062

Unless there are CPU bound tasks/processes that can be efficiently run in parallel across multiple cores, single core will always be more efficient.

I'd like to see solid test cases and comparison for each platform that proves otherwise.

**Comment by achekulaev** [comment]
I remember this test, but first and foremost this test is for Docker for Mac, not VirtualBox (this ticket is about VBox). And secondly the difference here is marginal (in a range of a statistical fluke) which most likely means that this test might be not too representative since it does not use the multi-core advantage. 
I will test using composer install, where I personally seen the most difference, and then page load.

**Comment by lmakarov** [comment]
> I remember this test, but first and foremost this test is for Docker for Mac, not VirtualBox (this ticket is about VBox).

While I don't have a chart handy for VirtualBox, I've done this test and research in the past. All hypervisors (xhyve, VirtualBox, Hyper-V) suffer from the same overhead of virtualizing multiple cores.
Check this links in https://github.com/docker/machine/issues/1062 to see other's mentioning the same observations with VirtualBox.

> the difference here is marginal (in a range of a statistical fluke) which most likely means that this test might be not too representative since it does not use the multi-core advantage.

Unfortunately, Composer may be the only use case where multi-core could be useful in a **local** web stack.

I agreed that a more comprehensive test suite should be in place, which tests `composer install`, `drush si`, as well as page loads (with all caching off).

**Comment by achekulaev** [comment]
@lmakarov I would expect not only composer, but also other compilation tools to have the same benefit as well: npm, grunt etc. For me even composer is pretty significant as it feels forever on a single core, but again I will run tests and see more clearly. 
I don't expect significant change on page load time 4 vs 1.

**Comment by achekulaev** [comment]
`composer create-project` did not turn out any viable results. No difference between 1 and 4 cores.

```time fin run-cli --clean composer create-project drupal-composer/drupal-project:8.x-dev . --stability dev --no-interaction```

Ran 2 tests on each. One with `--clean` and another one without it.

<img width="453" alt="screen shot 2018-11-28 at 11 18 41 pm" src="https://user-images.githubusercontent.com/402007/49199048-0458ae80-f364-11e8-82d8-e40244b78c40.png">

**Comment by achekulaev** [comment]
So me theory is next: since there is an overhead in emulating cores, parallelism shows itself when there are blocking operations. For example in a case of spotty internet `docker pull` should be much faster with several cores. In case of initial Drupal cache on page load build it might or might not show its benefit, depending on "luck", i.e. should there be a process that "stuck" doing something, then single core might stuck there for a long time, while several cores will continue doing other stuff.

**Comment by achekulaev** [comment]
VBox is phasing out anyways
