### ISSUE TITLE
Revise WSL use case on Windows (installation and usage)

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#865]
- [ ] Pin Docker client version (currently installs the latest)
- [ ] Test and make WSL usable with both VirtualBox as well as Docker Desktop
- [ ] Change installation docs (video still points to test.docksal.io)

**Comment by achekulaev** [comment]
The main problem with WSL is running commands as administrator. 

You cannot run another WSL as administrator, that's a limitation. You cannot run 2 WSL sessions, one as an admin and another as non-admin simultaneously.

Therefore the only option is to run some windows script and pass a complex command as a parameter to that script. The script should elevate its privileges asking user and then run your complex command.

The solution I was working on was using PowerShell script. There is a way to run command asking for admin permissions in PowerShell. And PowerShell is already pre-installed.

Unfortunately I was not able to figure out the proper quotes kung-fu. PowerShell, unlike bash, was going nuts after I tried to include escaped quotes inside quotes.

**Comment by achekulaev** [comment]
Did a quick googling for some ready solutions. Here's some sudo for WSL that might work because it builds the object before running. Might be able to overcome the quotes hell.

https://github.com/lukesampson/psutils/blob/master/sudo.ps1#L62-L70

**Comment by achekulaev** [comment]
To use VirtualBox we need to use Windows docker-machine. Linux one tries to work within WSL, but we need it to reach the windows VBox.
It works but has some console quirks.

**Comment by achekulaev** [comment]
Just a side note: I cracked the quotes hell, so not stuck anymore. Moving on with this.

**Comment by achekulaev** [comment]
![capture](https://user-images.githubusercontent.com/402007/49779119-55f32880-fcd6-11e8-9bf0-4985064c0a68.PNG)
