### ISSUE TITLE
Not able to Install Docksal on Ubuntu 16.10 (Yakkety)

### ISSUE THREAD

**Issue by vaza18** [docksal/docksal#88]
When I tried to run `fin update` on Ubuntu 16.10 (Yakkety), it rerurned me a message

```
...
+ sudo -E sh -c sleep 3; apt-get update; apt-get install -y -q docker-engine
...
Get:7 https://apt.dockerproject.org/repo ubuntu-yakkety InRelease [27.5 kB]
...
Fetched 334 kB in 2s (123 kB/s)                               
Reading package lists... Done
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package docker-engine
sudo: docker: command not found
Docker installation/upgrade has failed.

```

A way to workaround this is to use the Xenial sources, they should work fine. Yakkety won't be up until Docker 1.13.

**Comment by achekulaev** [comment]
Thanks for letting know. Not much we can do here though. Have to wait until Docker gets into Yakkety repos.

**Comment by fuzzbomb** [comment]
The `yakkety/main` source are ready now. Docker 1.13.0 is at https://apt.dockerproject.org/repo/dists/ubuntu-yakkety/main/

**Comment by fuzzbomb** [comment]
Watch out, fin is currently capable of breaking itself....

Today when I ran `fin update` it wrote a new apt `docker.list` file with the yakkety/main repo information, and installed docker engine 1.13.0

Later though, I ran foul of the requirement for docker 1.12.6

I'm aware of issue #112 which mentions the problem with docker-engine 1.13.0

I'll try uninstalling docker engine, reverting to the backup `docker.list.save` which still mentions xenial/main, and hopefully get back to the versions required by Docksal.

**Comment by achekulaev** [comment]
I don't fin has something to do with it. Fin tries to lock 0.12.6 version as much as it can. But you're the root on your Linux.

**Comment by achekulaev** [comment]
Also quite possible that they don't have 0.12.6 in yaketti repos. If you could check it that could help.
`apt-cache madison docker-engine`

**Comment by fuzzbomb** [comment]
Yeah, I think it's the mere availability of the yakkety/main repo that did it.

**Comment by achekulaev** [comment]
Should be resolved now
