### ISSUE TITLE
Support Request: Is it possible to disable xdebug in cli? 

### ISSUE THREAD

**Issue by awm086** [docksal/docksal#880]
I have been using docksal for one of my project and it's working well. I love that xdebug works out of the box with just xdebug_enabled=1 in local env file. However, I found a minor issue where If I have xdebug turned on in phpstorm, every time I clear the cache "fin drush cr" or "fin bash" then "drush cr" the xdebug get triggered and it take time to collect data. I know this is a feature and can come in handy in many situation when working with cli but I wonder if it's possible to disable it on demand. 

Thanks

**Comment by achekulaev** [comment]
well disabling it as simple as setting it back to `xdebug_enabled=0` and running `fin project restart`

**Comment by shelane** [comment]
![x-debug_listener](https://user-images.githubusercontent.com/2090502/49540538-334fb280-f885-11e8-9f62-3a1579ca2bc2.png)
You can also turn off the listener in PhpStorm.

**Comment by awm086** [comment]
Thank you, I was just wondering if I could only turn it off to cli because php cli usually have different configs.

**Comment by achekulaev** [comment]
Not sure what you mean "only on cli". Xdebug session is a communication between PhpStorm and `cli`. By default xdebug extension is disabled in `cli`. When you set xdebug_enabled=1 you tell `cli` to enable xdebug extension. When you set xdebug_enabled=0 you tell `cli` to disable xdebug extension back again.

**Comment by lmakarov** [comment]
@awm086 what you are asking for is currently not supported. xdebug can only be enabled/disabled globally - for both `php-cli` and `php-fpm` at the same time.

**Comment by lmakarov** [comment]
This could be done, but it won't be a simple a straightforward implementation. Feel free to create a feature request in https://github.com/docksal/service-cli
