### ISSUE TITLE
Installing Docksal in Ubuntu app on windows

### ISSUE THREAD

**Issue by Opswatch** [docksal/docksal#888]
**Description**

Missing sh file from test.docksal.io

**Steps to reproduce the issue:**

1. Windows 10 system launch ubuntu wsl
2. Run through install steps for 
3. https://www.youtube.com/watch?v=FJBN9-dGhyc

**Describe the results you received:**

sh file not found

**Describe the results you expected:**

Script would launch Docksal install

**Comment by achekulaev** [comment]
@Opswatch re-creating video is pretty hard. You need to use `get.docksal.io` instead. The rest of the steps are the same.
