### ISSUE TITLE
WP-CLI Version Update

### ISSUE THREAD

**Issue by damonsharp** [docksal/docksal#891]
Is updating WP-CLI to version 2.0.1+ on the roadmap? If not, I'd like to put in a request. Seems it's a bit outdated. Thanks.

**Comment by achekulaev** [comment]
Hi. Updating WP-CLI was not on the radar, since we do not have a lot of WordPress folks active in the Docksal community who'd highlight that need. 

Of course feel free to open a Pull Request and we will include it in the next release.

**Comment by sean-e-dietrich** [comment]
Fixed in https://github.com/docksal/service-cli/commit/80c1822db5caf59402f56c15f4a71b8f7bf779f2
