### ISSUE TITLE
Option to prevent stack configs from loading

### ISSUE THREAD

**Issue by mkochendorfer** [docksal/docksal#897]
Right now there is no way to prevent the default stacks from being loaded in addition to docksal.yml even if you are not making use of anything from them.  Preventing this from happening if you are not making use of stacks in docksal.env would allow projects to use docksal in various different ways that were not previously possible.  Such as, using a different docker compose version for their docksal.yml.

More info in https://github.com/docksal/docksal/issues/895

**Comment by lmakarov** [comment]
See https://github.com/docksal/docksal/issues/1425#issuecomment-721245901
