### ISSUE TITLE
Custom commands with exec_target do not execute properly for custom containers

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#898]
Custom commands with an `exec_target` other than `cli` will not even execute, unless you manually specify `PROJECT_ROOT` in `docksal.yml`. https://github.com/docksal/docksal/blob/develop/bin/fin#L6174 is the line that causes it to fail.

(Reported in https://github.com/docksal/docksal/issues/896#issuecomment-447038916)

**Comment by mkochendorfer** [comment]
@achekulaev Correct my if I am wrong here, but doesn't this code change make it so that you have to mount your project at `/var/www` or the custom commands will not function?  Just checking because I have some projects containers that are mounted at different paths currently.
