### ISSUE TITLE
Use Serveo instead of ngrok

### ISSUE THREAD

**Issue by kanduvisla** [docksal/docksal#903]
I want to use [Serveo](https://serveo.net/) instead of ngrok, but I'm not sure how to implement this in my current setup. I can bind Serveo to my local setup with this command:

     ssh -R foobar:80:myproject.docksal:80 serveo.net

This will alias https://foobar.serveo.net to my local development setup. However, I cannot seem to get it forwarded properly in Docksal. At first I get a 404 error.

So I tried editing `.docksal/docksal.env` with the following line:

    VIRTUAL_HOST=myproject.docksal,foobar.serveo.net

I also tried editing `.docksal/docksal.yml` by adding a label to `web`:

    web:
        image: docksal/web:2.1-apache2.4
        labels:
        - io.docksal.virtual-host=myproject.docksal,*.myproject.docksal,myproject.docksal.*,foobar.serveo.net

But this also didn't work (I believe I still got a 404 error at this point, it might have been a 400).

I also tried adding an `.docksal/etc/apache/httpd-vhosts.conf` file to add it manually but I was not sure what to put in it.

`fin logs web` also wasn't very helpful.

So I'm wondering what I'm missing here? Shouldn't this just work?

**Comment by achekulaev** [comment]
Have you tried this? https://github.com/taichunmin/docker-serveo (replace `nginx` with `web` in the `command`)

**Comment by kanduvisla** [comment]
Thanks @achekulaev , adding the following to my `docksal.yml` did the trick:

    serveo:
        image: taichunmin/serveo:latest
        tty: true
        stdin_open: true
        command: "ssh -R myproject:80:web:80 -o ServerAliveInterval=60 -o \"StrictHostKeyChecking no\" serveo.net"

**Comment by namnguyen2091** [comment]
@kanduvisla if i using nginx docker image, how do I config virtual host name (my virtual host name is mymockup.local)

> serveo:
>     image: taichunmin/serveo:latest
>     tty: true
>     stdin_open: true
>     command: "ssh -R mymockup:80:nginx:80 -o ServerAliveInterval=60 -o \"StrictHostKeyChecking no\" serveo.net"
