### ISSUE TITLE
Rename web service declaration into apache

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#905]
`web` should be renamed to `apache` in `services.yml`. The old `web` declaration should remain in `services.yml` until November 2019.

**Comment by shelane** [comment]
Use of the new service name should be changed in the documentation immediately with this new service name so that when it's removed, people won't be scrambling to make changes.

**Comment by lmakarov** [comment]
Similar to https://github.com/docksal/docksal/pull/906#issuecomment-448432430, we will keep using `web` as the service name in the default stacks, but extend the services from the new `apache` service definition in `services.yml`.

I have to admit, that we ARE adding confusion with different service names in `services.yml` vs, e.g., `stack-default.yml`. We will probably need to revise docs and see how this can be explained in a clear way. Also, the fact that the images would still be names `docksal/web` (and `docksal/db`) may add more to the confusion...

**Comment by lmakarov** [comment]
Yes, eventually we will have `nginx` added as a `web` service option.

**Comment by lmakarov** [comment]
For `db` - we already have the `pgsql` option in `service.yml`.
Still need support for `fin db` with pgsql in `fin` (#567) and docs (#564).
