### ISSUE TITLE
Create 'pull' command

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#912]
Should be able to do 3 things: pull db, files and code from Acquia and Pantheon at minimum (+Platform at best).

`fin pull db` - pull db using platform dependent tool(s)
`fin pull files` - pull files using platform dependent tool(s)
`fin pull code` - perform `git pull`
`fin pull` - perform all of the above

Platform to connect to configuration should be read from environment vars.

Push command will follow in the future release.

**Comment by achekulaev** [comment]
I was trying to come up with variable names (and essentially the approach) for this, but I'm not sure what to do with Pantheon. Theoretically we do not need anything besides drush aliases for pantheon as well, since it only hosts Drupal. Or do we? @sean-e-dietrich @lmakarov 

And I don't know what we need for platform.

```bash
# Platform to sync with
SYNC_PLATFORM="<acquia/pantheon/platform>"

# Git branch - uses current is not specified
SYNC_GIT_BRANCH="branch"

# Acquia
ACQUIA_DRUSH_ALIAS="@alias"
ACQUIA_DRUSH_ULI="uli"

# Pantheon
PANTHEON_SITE_NAME="sitename"

# Platform
???
```

**Comment by sean-e-dietrich** [comment]
I was thinking of this to make it generic enough. The purpose for this is because you could technically get Drush to do the majority of the work even with a generic hosting provider like AWS.

```
# Platform to sync with
HOSTING_PLATFORM="<acquia/pantheon/platform>"

# This could be branch name as the branch or it could be an alias
HOSTING_SITE_NAME="<@alias/branch>"
HOSTING_ENV="branch"
```

**Comment by achekulaev** [comment]
@sean-e-dietrich drush is for Drupal only. Pantheon and Platform are not Drupal-only hostings.

**Comment by sean-e-dietrich** [comment]
Correct. But there are commands you can use to make it work for both WordPress and Drupal. I'll push up my WIP so you can see what I was thinking. Additional you can use aliases with WordPress also.
