### ISSUE TITLE
Suppress Alert Messages 

### ISSUE THREAD

**Issue by sean-e-dietrich** [docksal/docksal#917]
When running scripts through the exec command if you are relying on feedback from them, and the alert message shows up to upgrade. This can cause issues in return data. Is there a way we can run this only once?

```
 ALERT:  Required Docker version is 18.09.0
         Run fin update to update to the required version.
```

**Comment by lmakarov** [comment]
We'll make sure this check and message is not triggered in `_exec` (fin exec, drush, etc).

**Comment by achekulaev** [comment]
This was even more annoying 

<img width="185" alt="alerts" src="https://user-images.githubusercontent.com/402007/53211644-f38ca180-360f-11e9-9145-38423f965c8e.png">
