### ISSUE TITLE
Make the internal DNS optional

### ISSUE THREAD

**Issue by erichard** [docksal/docksal#925]
I already have a dnsmasq instance started on port 53 on my machine. So docksal cannot start.
Setting `DOCKSAL_NO_DNS_RESOLVER` to true is no help as the `install_dns_service` function is called.

**Comment by lmakarov** [comment]
@erichard `docksal-dns` service has two basic purposes:

- provide `*.docksal` resolution for the host machine
- provide `*.docksal` resolution for containers

Setting `DOCKSAL_NO_DNS_RESOLVER=1` disables only the first one.
While having the second one disabled as well is possible, it's not a simple change.

`docksal-dns` binds to `192.168.64.100:53`. You should be able to configure you hosts dnsmasq to bind to localhost only and thus play nicely with Docksal.

```
# Listen only on localhost
listen-address=127.0.0.1
```

Will this work for you?

**Comment by erichard** [comment]
@lmakarov Thank for your explanation. I have tried your solution but I still get the same message from docker 

```
/usr/bin/docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-dns (2f45c29d23494a3e893251b5189fa1d5fbde993c46ec435924da71e1dd5e52ae): Error starting userland proxy: listen udp 192.168.64.100:53: bind: address already in use.
```

**Comment by erichard** [comment]
Ok I managed to get this working. dnsmasq config should be 

```
# Listen only on localhost
listen-address=127.0.0.1
bind-interfaces
```

Thanks for your help :+1:

**Comment by erichard** [comment]
Maybe this could go to the documentation in the Troubleshooting section
