### ISSUE TITLE
RVM doesn't install

### ISSUE THREAD

**Issue by paulsheldrake** [docksal/docksal#928]
When using the script provided in the documentation RVM doesn't install the key to validate the download of RVM correctly.

**Comment by achekulaev** [comment]
This is very few information about the issue, I must say

**Comment by paulsheldrake** [comment]
Give me a minute

**Comment by paulsheldrake** [comment]
Sorry, realized the script I was thinking of was actually from a blog post and gist
https://gist.github.com/achekulaev/3bbd65a8265168f1261a70245da0e6e4#gistcomment-2801358

**Comment by achekulaev** [comment]
@paulsheldrake thanks I've updated the script. Anyways rvm will be in `cli` with the next version so the issue should go off the table altogether.
