### ISSUE TITLE
Docksal installation should not quietly replace docker-compose on Linux

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#936]
Currently Docksal installation on Linux puts docker-compose to `/usr/local/bin`, potentially overwriting the version people had. We need to either put it to our own folder as we do on other OS, or at least issue a notification.

**Comment by achekulaev** [comment]
@lmakarov are you aligned with this proposal? I do not quite remember why we decided put `docker-compose` to the system folder on Linux so just double checking in case you remember some details about this.

**Comment by lmakarov** [comment]
@achekulaev I don't recall any specifics regarding the current state.

Let's install our own copy of docker-compose on Linux, the same way we do it on other platforms.
