### ISSUE TITLE
fin share does not respect --host-header

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#945]
Per the documentation https://docs.docksal.io/tools/ngrok/ you should be able to say `fin share --host-header=subdomain.domain.docksal` and ngrok should connect to that host rather than the default of VIRTUAL_HOST.

As far as I can tell, the `--host-header` option is not respected. If I run `fin share --host-header=backstop.edelman.docksal` then it just connects me to `edelman.docksal`.

After reading through the `ngrok_share ()` function in `fin`, the only way I can get it to work is if I prefix the command with `NGROK_HOSTNAME=backstop.edelman.docksal fin share`.

**Comment by sean-e-dietrich** [comment]
@lpeabody ngrok only connects to the web container and shares that. Are you trying to connect to a different container within the project?

**Comment by sean-e-dietrich** [comment]
@lpeabody if you wouldn't mind sharing the `fin config` I could give you a better answer too.

**Comment by lpeabody** [comment]
It's through the web container, it's a multisite Drupal setup where each site is identified by a subdomain. So, site1.project.docksal, for instance. Unfortunately I don't have my work laptop with me at the moment, I can post `fin config` for you later.

**Comment by sean-e-dietrich** [comment]
@lpeabody tried to take a look at this and replicate. Can you take a look and see if there is something I may be missing. I tried to set up just a basic multi-site with Drupal 7. But, I didn't run into any issues when using `fin share --host-header=sample.test-mutli-site.docksal`

![3__sean_dietrich_macbook____desktop_tmp_test_multi_site_docroot_sites__zsh__and_2__sean_dietrich_macbook____desktop_tmp_test_multi_site_docroot_sites__zsh__and_welcome_to_sample_site___sample_site_and_welcome_to_my_drupal_7_site___my_drupal](https://user-images.githubusercontent.com/1564748/52160414-e3655000-2669-11e9-820c-c53fea6e5ace.png)

**Comment by lpeabody** [comment]
So, just opened up my work machine to test with... and it's working as expected now after running some tests again. I have no idea what I was doing to convince myself that it wasn't working, because it works totally fine. Maybe it was just the end of a long work week that was throwing me off...? Very sorry for wasting your time @sean-e-dietrich.

**Comment by sean-e-dietrich** [comment]
@lpeabody not a waste. But glad to hear all is working.
