### ISSUE TITLE
Update docs for windows install. Make WSL main option and Babun a deprecated option.

### ISSUE THREAD

**Issue by snow8gaia** [docksal/docksal#946]
**Description**

These docs need to be updated:-
https://github.com/docksal/docksal/blob/develop/docs/content/getting-started/setup.md#install-windows

**Steps to reproduce the issue:**

1. Go to https://docs.docksal.io/getting-started/setup/#install-windows-babun-virtualbox
2. Follow Step1, i.e., Click on http://babun.github.io/
3. Click on [Download now](http://projects.reficio.org/babun/download)

**Describe the results you received:**

Results: No Babun. No Docksal.

**Describe the results you expected:**

Expected behavior: Install Babun. Install Docksal.

**Comment by snow8gaia** [comment]
As far as I know, there are no duplicate issues and Babun is dead. See https://github.com/babun/babun/issues/868 , https://github.com/babun/babun/issues/854 , https://github.com/babun/babun/issues/810

Can it be swapped out for Cygwin (x86 or x86-64?). Or Msys2 (maybe).

**Comment by snow8gaia** [comment]
Here's the page in the repo: https://github.com/docksal/docksal/blob/develop/docs/content/getting-started/setup.md

And the sections that will need updating:-

- [linux-shell-installation-options](https://github.com/docksal/docksal/blob/develop/docs/content/getting-started/setup.md#windows-linux-shell-installation-options-install-windows)

- [windows-with-babun-docker-installation-options](https://github.com/docksal/docksal/blob/develop/docs/content/getting-started/setup.md#windows-with-babun-docker-installation-options-install-windows-babun)

- [windows-with-babun-and-virtualbox](https://github.com/docksal/docksal/blob/develop/docs/content/getting-started/setup.md#windows-with-babun-and-virtualbox-install-windows-babun-virtualbox)

- [windows-with-babun-and-docker-for-windows](https://github.com/docksal/docksal/blob/develop/docs/content/getting-started/setup.md#windows-with-babun-and-docker-for-windows-install-windows-babun-docker-for-windows)

**Comment by achekulaev** [comment]
I guess the solution here will be to deprecate Babun in favor of WSL. I have a PR pending to finish WSL support

**Comment by tombujok** [comment]
Yep, it's dead. No time to maintain it anymore.  It's a pretty complex project. I was trying to find maintainers but with not luck. Everyone just prefers to grab what's there online for free, but if any involvement is required they are just uninterested and are first to complain about litter.

Good luck with any other tools you may find out there. If you don't contribute to them or pay for them, they will end up like babun pretty soon anyway.

**Comment by claui** [comment]
Hope you folks don’t mind my off-topic comment, but thank you @tombujok for the thousands of hours you put into this. Babun was a great and tremendously useful thing.

**Comment by achekulaev** [comment]
@tombujok yep this is how things go in open source world pretty often, thanks for posting here and thanks for maintaining that tool for a long time.

**Comment by achekulaev** [comment]
This one waits for https://github.com/docksal/docksal/pull/890

**Comment by snow8gaia** [comment]
Thanks.

**Comment by ismailhkose** [comment]
> Yep, it's dead. No time to maintain it anymore. It's a pretty complex project. I was trying to find maintainers but with not luck. Everyone just prefers to grab what's there online for free, but if any involvement is required they are just uninterested and are first to complain about litter.
> 
> Good luck with any other tools you may find out there. If you don't contribute to them or pay for them, they will end up like babun pretty soon anyway.

@tombujok 
As an Owner of the project, Would you mind to send an email to Cygwin, MinGW e-mails list if anyone wants to maintain or merge to Cygwin or MingGW?
