### ISSUE TITLE
fin db create is not workin in non-tty environment

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#947]
```bash
10:24:07 ~/Projects/demo1
§ echo 'fin db create sportbaza' | bash
the input device is not a TTY
 ERROR:  Database 'sportbaza' creation failed

10:24:44 ~/Projects/demo1
§ fin db create sportbaza
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Database sportbaza created
```

**Comment by ivan-berezhnov** [comment]
This is my problem. You can reproduce if use Circle CI + CI Agent 
When run fin init and try to do fin db create sportbaza I had failed

**Comment by ivan-berezhnov** [comment]
I found solution for self:
`echo-yellow "Create dbs..."
fin drush sql-create -y --uri=$URL_SB
sleep 2
fin drush sql-create -y --uri=$URL_TL
sleep 2
fin drush sql-create -y --uri=$URL_WIN
sleep 2
echo ''
fin db ls
echo-green "Done.\n"

echo-yellow "Import dbs..."
fin db import $PROJECT_ROOT/db/default_sportbaza.sql --db=sportbaza --db-user=root --db-password=root
sleep 5
fin db import $PROJECT_ROOT/db/default_tooll.sql --db=tooll --db-user=root --db-password=root
sleep 5
fin db import $PROJECT_ROOT/db/default_winsport.sql --db=winsport --db-user=root --db-password=root
sleep 5
echo-green "\n"`

**Comment by lmakarov** [comment]
This started to happen again with the latest Docksal/fin version:

```
$ echo 'fin db create test' | bash
the input device is not a TTY
 ERROR:  Database 'test' creation failed

$ fin --version
fin version: 1.99.0
```

cc @achekulaev

**Comment by achekulaev** [comment]
Meh... @GMTA I knew [that rewriting](https://github.com/docksal/docksal/pull/1306) would break some edge-case. You broke it you fix it :P

**Comment by GMTA** [comment]
Can't make a beautiful omelette without breaking some eggs I suppose - PR #1394 fixes this issue!
