### ISSUE TITLE
Possible to move project directory to another location in the filesystem?

### ISSUE THREAD

**Issue by mikecrittenden** [docksal/docksal#948]
For example, say I have a Docksal project at `~/sites/abc` and I decide to move it to `~/stuff/abc`, then when I `fin start` in the new location, it complains that project ABC already exists.

Is there a way to move projects from one place to another while keeping the same directory name, without having to `fin rm` first?

**Comment by lmakarov** [comment]
When a project is created, there a a few volumes created for it. One of them is called `project_root`, which is mapped to a specific location on the host. When you move your project to a different place within the host's filesystem, that messes up the `project_root` volume mapping, since the volume now points to a path that no longer exists on the host. Unfortunately, there is no easy (if any) way around this.

**Comment by mikecrittenden** [comment]
Cool, that makes sense and is understandable. Maybe it makes sense to document this? It seems like a common request.

**Comment by achekulaev** [comment]
I should note that this has really nothing to do with Docksal. It is how docker-compose and Docker itself works.

**Comment by achekulaev** [comment]
@shelane if you have a good idea where in docs this might fits, please take the ticket.

**Comment by shelane** [comment]
It can possibly fit in the core/volumes section as it is an explanation of how they work in Docker. Can you think of another place where it might fit better? I would just think a notice of what's needed if a project directory needs to be moved on a user's system.

**Comment by lmakarov** [comment]
@shelane yep, `/core/volumes/` is the place for this.

**Comment by gaelg** [comment]
For the record, I wanted to keep my persisted database while moving my project. This did the trick:
<pre>
# Backup existing db volume data:
sudo cp -R /var/lib/docker/volumes/$MYPROJECT_$MYDBCONTAINER_data /tmp/
# Delete initial docksal containers and volumes:
cd workspace/initial_project_location
fin project rm
#move the project... then:
cd workspace/new_project_location
# Create new docksal containers and volumes:
fin project start
fin project stop
# Restore existing db volume data:
sudo rm -R /var/lib/docker/volumes/$MYPROJECT_$MYDBCONTAINER_data/_data
sudo mv /tmp/$MYPROJECT_$MYDBCONTAINER_data/_data /var/lib/docker/volumes/$MYPROJECT_$MYDBCONTAINER_data/
# Restart the project at the new location, with previous db data:
fin project start
</pre>
