### ISSUE TITLE
Failed to start the proxy servies. 

### ISSUE THREAD

**Issue by chu01** [docksal/docksal#951]
I was able run docksal on this machine Yesterday. Today when i try to fin up -- it gave me an error,  an i tried to reconfigure. 

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (87a8ca758a3aafbd74b03f9c6ff49daa34bcecbe87055e1366de3090b41e57b8): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 ERROR:  Failed starting the proxy service.
```

**Comment by achekulaev** [comment]
It is not known why this happens, it is not related to Docksal. It is something in VBox or Docker. Try restarting your host machine.

**Comment by chu01** [comment]
@achekulaev -- I restarted my mac twice. even reinstalled both VM and Docker. i removed all my images from docker. Still complaining. 

`docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (7c1f9aeed0f35c69221ea913fd339f908b5c8f735033414e527f85e8638e4baa): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 ERROR:  Failed starting the proxy service.`

**Comment by rdehamel** [comment]
I'm having a similar(?) error using Docksal with the  Windows Ubuntu App (WSL).
first path segment in URL cannot contain colon - Failed starting the proxy service.
I have my environment set to recognize /c/ instead of /mnt/c/

**Comment by achekulaev** [comment]
@chu01
> even reinstalled both VM and Docker.

So what do you use VM or Docker?

And you need to provide output of `fin sysinfo`.

**Comment by lmakarov** [comment]
This issue is documented in the troubleshooting section of the docs:
https://docs.docksal.io/troubleshooting/common-issues/#issue-05

**Comment by chu01** [comment]
@achekulaev -- LIke you said the issue was with the VBox. I removed, and reinstall and restarted my host machine. That worked just fine.
I think I should go ahead and close the issue. resolving the issue is in the Virtual Box.

**Comment by rdehamel** [comment]
Hi,

Docker.

Resetting Docksal services...
 ➔ proxy
parse 127.0.0.1:2375: first path segment in URL cannot contain colon
 ERROR:  Failed starting the proxy service.
xxx@xxx:~$ fin sysinfo
parse 127.0.0.1:2375: first path segment in URL cannot contain colon
███  OS
WSL Ubuntu 18.04
Linux xxx 4.4.0-17134-Microsoft #345-Microsoft Wed Sep 19 17:47:00 PST 2018
x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE :
███  FIN
fin version: 1.80.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.1
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

███  DOCKER
EXPECTED VERSION: 18.06.1-ce

parse 127.0.0.1:2375: first path segment in URL cannot contain colon
parse 127.0.0.1:2375: first path segment in URL cannot contain colon
███  DOCKER: DOCKER IS NOT RUNNING


███  HDD Usage
/usr/local/bin/fin: line 5311: wmic: command not found
xxx@xxx:~

**Comment by achekulaev** [comment]
@rdehamel sorry WSL is not really supported yet. It will be soon though. Fallback to Babun for the time being.

**Comment by mwarf** [comment]
> I'm having a similar(?) error using Docksal with the Windows Ubuntu App (WSL).
> first path segment in URL cannot contain colon - Failed starting the proxy service.
> I have my environment set to recognize /c/ instead of /mnt/c/

Hey @rdehamel - I'm using WSL with Docksal and experienced the same issue. Oddly enough if I run "fin system reset" using an elevated CMD prompt, then switching to BASH - it works. If I run "fin system reset" in my WSL terminal it won't reset the proxy, dns or ssh-agent.

So to be clear, I run elevated CMD, then BASH to get a bash prompt - and enter "fin system reset" and it all comes back online for me. 

Worth a try?

**Comment by rdehamel** [comment]
Thanks Michael, I did try it. Unfortunately no luck here.

**Comment by greg-marra** [comment]
With the announcement of Babun going away, I'm having this issue with WSL still:

docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (83970ed4282a90c117d87c3484bb5e49398b3c68d1d7d15a2f8232e2477e8a43): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.

**_SYSINFO BELOW:_**

fin sysinfo
/usr/local/bin/fin: line 117: cmd.exe: command not found
wslpath: Invalid argument
███  OS
WSL Ubuntu 18.04
Linux W8B5VW52 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.85.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:11:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS
Error response from daemon: Container 6c388579c602c8ddd0708763de693a713aec7d2307b5d5db81af917937c4b337 is not running
No virtual hosts found

███  DOCKSAL: DNS
curl: (6) Could not resolve host: dns-test.docksal
ERROR: Requesting http://dns-test.docksal failed!

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                   PORTS               NAMES
d807cb374e2f        050f58033f44        "docker-entrypoint.s…"   2 months ago        Up 8 minutes (healthy)                       docksal-ssh-agent

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
543e84e741ab        _default            bridge              local
e3b1e73f9bb4        bridge              bridge              local
9c4b32d0bfdf        ddev_default        bridge              local
adfae9592555        drupal8_default     bridge              local
ba3ec082ddc5        host                host                local
92fabd6632da        none                null                local
ff2a33986ca2        nysca_default       bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3

Docker Desktop
Version: 2.0.0.3 (31259)
Channel: stable
Sha1: 8858db33c8692b69de9987a5d672798d778735b2
OS Name: Windows 10 Enterprise
Windows Edition: Enterprise
Windows Build Number: 17763

███  HDD Usage
/usr/local/bin/fin: line 5736: wmic.exe: command not found

**Comment by achekulaev** [comment]
@greg-marra something is not very right with your environment at all. 

```
/usr/local/bin/fin: line 117: cmd.exe: command not found
...
/usr/local/bin/fin: line 5736: wmic.exe: command not found
```

`cmd.exe` and `wmic.exe` are basic windows utilities that should be present on the system.

**Comment by greg-marra** [comment]
When I setup my Ubuntu bash_profile, it has a custom $PATH for another machine I use. I wiped it out and it looks better, but I am still getting the vhost-proxy error. I am behind a corporate firewall:

Resetting Docksal system services...
 * proxy
docker: Cannot connect to the Docker daemon at tcp://127.0.0.1:2375. Is the docker daemon running?.
See 'docker run --help'.
 ERROR:  Failed starting the proxy service.

```
[~] $ fin sysinfo
███  OS
WSL Ubuntu 18.04
Linux W8B5VW52 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.85.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:11:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS
Error response from daemon: Container 4180bf0fd136c8b3f4e22da0684b96793c10e8bc46567acc15b2f717daca79c0 is not running
No virtual hosts found

███  DOCKSAL: DNS
curl: (6) Could not resolve host: dns-test.docksal
ERROR: Requesting http://dns-test.docksal failed!

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
4808f35daa3e        bridge              bridge              local
ba3ec082ddc5        host                host                local
92fabd6632da        none                null                local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3

Docker Desktop
Version: 2.0.0.3 (31259)
Channel: stable
Sha1: 8858db33c8692b69de9987a5d672798d778735b2
OS Name: Windows 10 Enterprise
Windows Edition: Enterprise
Windows Build Number: 17763

███  HDD Usage
Caption  FreeSpace      Size
C:       97166884864    254859341824
D:       1000020795392  1000202039296
E:
O:
V:
```
PATH:
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2018.817.0_x64__79rhkp1fndgsc:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/PHP7:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files (x86)/vim/vim80:/mnt/c/ProgramData/ComposerSetup/bin:/mnt/c/tools/php73:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/nodejs:/mnt/c/Program Files (x86)/Yarn/bin:/mnt/c/Users/GMarra/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/GMarra/AppData/Local/atom/bin:/mnt/c/Users/GMarra/AppData/Local/Microsoft/WindowsApps:/mnt/c/usr/local/ssl:/mnt/c/Users/GMarra/.babun:/mnt/c/Users/GMarra/AppData/Roaming/Composer/vendor/bin:/mnt/c/Program Files/ddev:/mnt/c/Users/GMarra/AppData/Roaming/npm:/mnt/c/Users/GMarra/AppData/Local/Yarn/bin:/snap/bin:/Applications/DevDesktop/tools:/Applications/DevDesktop/tools:/Applications/DevDesktop/tools:/Applications/DevDesktop/tools`

**Comment by greg-marra** [comment]
This was part of the issue, I found the other part as part of our local set up here. Thank you!

**Comment by MKorostoff** [comment]
For anyone coming upon this thread in the future: it may be a version compatibility issue.  If you're running mac docker desktop 2.2.0, you need to downgrade to 2.1.0

**Comment by sanger89** [comment]
I use wsl2 Ubuntu 22.04 and have the same problem. I change the .bashrc to disable proxy config and source .bashrc, it didn't work. But when I exit the terminal and enter in again, then it worked. What a strange! isn't it?
