### ISSUE TITLE
Docksal install on ARM server

### ISSUE THREAD

**Issue by acondura** [docksal/docksal#966]
Hello,

I'm using Docksal on an actual server up on scaleway.com (thank you @achekulaev for mentioning scaleway some time ago; AMAZING servers at cheap prices) for development for 2 reasons:

1. whenever I run some fin/docker command (especially composer related commands) my macbook's CPU stays somewhere between 100% and 200% (dual core mac). That heats up quite a bit and it's annoying for a full day (8-10 hours) of work.

2. McAfee Support has not figured out even till today how to allow Docksal's local address 192.168.100.64 to work with their firewall so, I had to constantly disable my Mac's firewall in order to actually get some work done.

Docksal works great on x86 architectures but I'm trying to install Docksal on ARM servers because they're really cheap and they say they can pack a punch! So, I thought I'd give them a try since this will also be a request from my clients at some point as well. When I run the Docksal installation it errors out with this message:

```
Installing Docker Compose...
######################################################################## 100.0%
/usr/local/bin/fin: line 364: /usr/local/bin/docker-compose: cannot execute binary file: Exec format error
Docker Compose installation/upgrade has failed.
```

which obviously means that it can't install Docker Compose for ARM.

Now, since the Docker Composer install page itself gives a solution to this over at https://docs.docker.com/compose/install (the 'Alternative Install Options' tab), could you please update the install sequence to install Docker Composer for ARM architecture when ARM is used?

The options they list there are:
- some PIP install commands
- and install Docker Compose as a container - which come to think of it, doesn't sound bad in the long run.

Thank you,
Andrei

**Comment by acondura** [comment]
The actual solution to use Docksal on an ARM architecture on a Debian based server is to run the following commands before installing Docksal:

- apt-get install python-pip
- pip install docker-compose

After these two, if you run the Docksal install command, it finishes installation successfully.
I just thought this process could be included in the Docksal install processor maybe even use Docker Compose as a container (if it makes sense).

**Comment by lmakarov** [comment]
@acondura glad to hear that you were able to get Docksal running on ARM :)

As you have already figured out, Docksal skips installing dependencies that are already present on the host system.

Please report here with your experience using Docksal on ARM. We may consider adding an official support for that. If installing `docker-compose` via `pip` (which we BTW are already doing for Alpine) is all that's missing to support ARM, then this would be an easy win.

**Comment by acondura** [comment]
Weird, when I issue a 'fin system start' command it returns:

```
Configuring network settings...
Resetting Docksal services...
 ➔ proxy
 ➔ dns
   upstream 10.1.31.38
Enabling automatic *.docksal DNS resolver...
 ➔ ssh-agent
Error response from daemon: Container 9979d3e49a8d62623e2880325c969f4070e3769e5845baaaa6714abee8e3d2e6 is restarting, wait until the container is running
```

However, I am running Docksal as root, I don't know if that might be the issue but I just wanted to test Docksal install on ARM. I'll do a proper install (using a docksal sudo user) a bit later.

**Comment by lmakarov** [comment]
Looks like ARM servers did not get much traction after all and Scaleway dropped the architecture earlier this year
https://www.theregister.com/2020/04/21/scaleway_arm64_cloud_end_of_life/

Moreover, you cannot just run an x86 based docker image on an ARM server instance.
All Docksal images would have to be built for that architecture.
https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/

With that mind, I don't see Docksal supporting ARM any time soon. We'll reconsider when ARM servers become more mainstream.
