### ISSUE TITLE
The `fin` command doesn't exit with status other than 0 even if script fails

### ISSUE THREAD

**Issue by jhedstrom** [docksal/docksal#981]
**Description**
If a script fails, in this case a mis-configured phpunit script:

```
$> fin phpunit
Could not load "/var/www/docroot/core/phpunit.xml".

attributes construct error

Couldn't find end of Start Tag env line 32

/var/www
$> echo $?
0
```
the exit code of `fin` is still 0.

I discovered this in a build that _passed_ on Travis when it should have failed: https://travis-ci.com/docksal/drupal8-contrib/builds/98877656

**Steps to reproduce the issue:**

1. Have a command fail 
2. Test the return value `echo $?`
3. It should be non-zero

**Comment by jhedstrom** [comment]
Sorry for the noise. The `phpunit` addon did not have `set -e` enabled.

**Comment by achekulaev** [comment]
If your script returns 0, fin returns 0. If your script returns 1, fin returns 1.

```
15:27:46 ~/Projects/drupal8
§ cat .docksal/commands/test 
#!/usr/bin/env bash
exit 1

15:27:51 ~/Projects/drupal8
§ fin test; echo $?
1
```
