### ISSUE TITLE
Document adding a custom certificate for a project

### ISSUE THREAD

**Issue by achekulaev** [docksal/docksal#982]
Currently documentation on `VIRTUAL_HOST_CERT_NAME` does not really cover the full process of adding custom certificates.

If I am not mistaken the full process is

1. Put your certificates for your project's virtual host into `$HOME/.docksal/certs`. E.g. if your project's virtual host is `example.com` then put CRT and KEY files as:
```
$HOME/.docksal/certs/example.com.crt
$HOME/.docksal/certs/example.com.key
```
2. If you never had `$HOME/.docksal/certs` directory before you will need to do `fin system reset` for `docksal-vhost-proxy` to find it
3. In your project set environment variable
```
VIRTUAL_HOST_CERT_NAME="example.com"
```
4. Restart the project with `fin project restart`

If I did not mix up anything this should work. Ping @lmakarov

**Comment by lmakarov** [comment]
@achekulaev sounds right, except in step 4 `fin project start` should be used instead of `restart` to update the project stack settings.

See also:
- https://github.com/docksal/service-vhost-proxy#default-and-custom-certs-for-https
- https://github.com/docksal/service-vhost-proxy/issues/34#issuecomment-431637461

**Comment by achekulaev** [comment]
`fin project restart` does `fin project stop && fin project start`, because restarting with `docker-compose restart` was such an edge case that no one actually needed it that way.

**Comment by lmakarov** [comment]
Agreed. `restart` will indeed do the stack update, since it does `start`, which in turn does `docker-compose up` and not `docker-compose start`, thus reloading the stack config. Thanks for a refresher.

**Comment by shelane** [comment]
Advanced Use Cases section?

**Comment by lmakarov** [comment]
@shelane I'd say this belongs to https://docs.docksal.io/core/system-vhost-proxy/
